import type { LibraryStory } from "@/lib/stories/types";

// Original retellings of Aesop's fables (the fables are public domain; this
// wording is our own). Short, wholesome, with a comprehension quiz each.

export const AESOP_STORIES: LibraryStory[] = [
  {
    id: "tortoise-and-hare",
    title: "The Tortoise and the Hare",
    emoji: "🐢",
    illustration: "🐢🏁🐇",
    level: "Easy",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "A speedy hare loved to brag about how fast he was. One day a slow tortoise grew tired of the teasing and challenged him to a race. The hare laughed — but agreed.",
      "When the race began, the hare zoomed far ahead. Looking back and seeing the tortoise so far behind, he decided there was plenty of time for a nap under a shady tree.",
      "The tortoise kept plodding along — slow, steady, never stopping. He passed the sleeping hare and kept right on going.",
      "The hare woke with a jolt and raced to the finish… but too late. The tortoise had already crossed the line.",
    ],
    moral: "Slow and steady wins the race.",
    quiz: [
      { q: "Why did the hare lose the race?", options: ["He stopped for a nap", "He ran the wrong way", "He tripped", "He was slower than the tortoise"], answer: 0, explain: "His overconfidence — and that nap — cost him the race." },
      { q: "What helped the tortoise win?", options: ["Keeping going, slow and steady", "Being the fastest", "Cheating", "Asking for a head start"], answer: 0 },
      { q: "What is the lesson of this story?", options: ["Slow and steady wins the race", "Always nap during a race", "Bragging makes you fast", "Speed is all that matters"], answer: 0 },
    ],
  },
  {
    id: "lion-and-mouse",
    title: "The Lion and the Mouse",
    emoji: "🦁",
    illustration: "🦁🤝🐭",
    level: "Easy",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "A great lion was asleep when a tiny mouse scurried across his paw and woke him. The lion snatched the mouse up, ready to eat him.",
      "“Please let me go,” squeaked the mouse. “One day I might help you.” The lion laughed — how could such a tiny creature ever help him? — but he let the mouse go.",
      "Some time later the lion was caught in a hunter's net. He roared and roared, but could not break free.",
      "The little mouse heard, ran over, and gnawed through the ropes with his sharp teeth. The mighty lion was free — saved by the smallest of friends.",
    ],
    moral: "Even the smallest friend can be a big help, and kindness is repaid.",
    quiz: [
      { q: "Why did the lion let the mouse go?", options: ["The mouse said he might help one day", "He wasn't hungry", "The mouse was too fast", "He felt sick"], answer: 0 },
      { q: "How did the mouse save the lion?", options: ["He chewed through the net", "He roared loudly", "He fetched a hunter", "He ran for help"], answer: 0 },
      { q: "What does the story teach?", options: ["Even small friends can help; kindness comes back", "Lions are weak", "Mice are scary", "Never make friends"], answer: 0 },
    ],
  },
  {
    id: "boy-who-cried-wolf",
    title: "The Boy Who Cried Wolf",
    emoji: "🐺",
    illustration: "👦📣🐺",
    level: "Easy",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "A shepherd boy watched the sheep on a lonely hill. To amuse himself, he shouted, “Wolf! Wolf!” The villagers came running to help — but there was no wolf. The boy laughed at his trick.",
      "He did it again the next day. Again the villagers raced up the hill, and again there was no wolf. They went home grumbling.",
      "Then one day a real wolf came. “Wolf! Wolf!” the boy screamed — but this time no one came. They thought it was just another trick.",
      "The wolf scattered the flock. The boy learned, too late, what happens to those who tell lies.",
    ],
    moral: "Liars aren't believed, even when they tell the truth.",
    quiz: [
      { q: "Why didn't the villagers come the last time?", options: ["They thought he was lying again", "They were asleep", "They had moved away", "They didn't like the sheep"], answer: 0 },
      { q: "What had the boy done on the days before?", options: ["Cried “wolf” when there was none", "Helped the wolf", "Lost the sheep", "Run away"], answer: 0 },
      { q: "What is the lesson?", options: ["Liars aren't believed, even when truthful", "Wolves are friendly", "Shouting is fun", "Sheep are clever"], answer: 0 },
    ],
  },
  {
    id: "ant-and-grasshopper",
    title: "The Ant and the Grasshopper",
    emoji: "🐜",
    illustration: "🐜❄️🦗",
    level: "Easy",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "All summer long the ant worked hard, carrying food to store for the winter. The grasshopper played and sang, laughing at the ant for working on such a sunny day.",
      "“Why not come and play?” said the grasshopper. “Winter is far away.” But the ant kept gathering, day after day.",
      "When the cold winter came, the grasshopper had nothing to eat. The ant, warm and well-fed, had saved plenty.",
      "The grasshopper finally understood: there is a time to work and a time to play.",
    ],
    moral: "Prepare today for what you'll need tomorrow.",
    quiz: [
      { q: "What did the ant do all summer?", options: ["Stored food for winter", "Played and sang", "Slept", "Nothing at all"], answer: 0 },
      { q: "Why was the grasshopper hungry in winter?", options: ["He played instead of preparing", "He gave his food away", "He got lost", "Ants stole his food"], answer: 0 },
      { q: "What is the lesson?", options: ["Prepare today for tomorrow", "Never do any work", "Winter is fun", "Singing fills your tummy"], answer: 0 },
    ],
  },
  {
    id: "crow-and-pitcher",
    title: "The Crow and the Pitcher",
    emoji: "🐦‍⬛",
    illustration: "🐦‍⬛🪨🏺",
    level: "Medium",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "A thirsty crow found a tall pitcher with a little water at the very bottom. She poked her beak in, but the water was too low to reach. She couldn't tip the heavy pitcher over, either.",
      "The crow thought hard. Then she had an idea. One by one, she dropped small pebbles into the pitcher.",
      "With each pebble, the water rose a little higher… and higher… until at last it reached the top.",
      "The clever crow drank her fill. A little thinking had solved a big problem.",
    ],
    moral: "Little by little, cleverness solves big problems.",
    quiz: [
      { q: "How did the crow reach the water?", options: ["She dropped in pebbles to raise it", "She tipped the pitcher over", "She broke it", "She waited for rain"], answer: 0 },
      { q: "What helped the crow the most?", options: ["Thinking cleverly", "Being big and strong", "Being loud", "Pure luck"], answer: 0 },
      { q: "What is the lesson?", options: ["Cleverness solves big problems, bit by bit", "Crows can't drink", "Pitchers are heavy", "Give up when you're stuck"], answer: 0 },
    ],
  },
  {
    id: "fox-and-grapes",
    title: "The Fox and the Grapes",
    emoji: "🦊",
    illustration: "🦊🍇🙄",
    level: "Easy",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "A hungry fox spotted a bunch of juicy grapes hanging high on a vine. They looked delicious, and his mouth watered.",
      "He jumped and jumped, stretching as high as he could — but the grapes were just out of reach.",
      "After many tries, the tired fox gave up and walked away. “Those grapes were probably sour anyway,” he grumbled.",
      "It's easy to look down on what we cannot have.",
    ],
    moral: "Don't pretend to dislike what you simply can't reach.",
    quiz: [
      { q: "Why did the fox say the grapes were sour?", options: ["He couldn't reach them", "He had tasted them", "They were green", "A bird warned him"], answer: 0 },
      { q: "Did the fox actually taste the grapes?", options: ["No — he never reached them", "Yes, and they were sour", "Yes, and they were sweet", "He ate them all"], answer: 0 },
      { q: "What is the lesson?", options: ["Don't pretend to dislike what you can't have", "All grapes are sour", "Foxes can't jump", "Give up early"], answer: 0 },
    ],
  },
  {
    id: "goose-golden-egg",
    title: "The Goose and the Golden Egg",
    emoji: "🪿",
    illustration: "🪿🥚💰",
    level: "Medium",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "A farmer owned a wonderful goose that laid one shining golden egg every single day. Each day he sold the egg and grew a little richer.",
      "But the farmer was greedy. “Why wait for one egg a day?” he thought. “There must be a whole pile of gold inside her.”",
      "So he cut the goose open — but inside there was no gold at all, just an ordinary goose. And now she could lay no more golden eggs.",
      "In his greed, the farmer lost everything.",
    ],
    moral: "Greed can cost you what you already have.",
    quiz: [
      { q: "What did the goose do each day?", options: ["Laid a golden egg", "Flew away", "Ate gold", "Sang a song"], answer: 0 },
      { q: "Why did the farmer lose his treasure?", options: ["He was greedy and wanted it all at once", "He sold the goose", "He lost the eggs", "A fox came"], answer: 0 },
      { q: "What is the lesson?", options: ["Greed can cost what you already have", "Geese are magic", "Eat more eggs", "Sell everything fast"], answer: 0 },
    ],
  },
  {
    id: "wind-and-sun",
    title: "The North Wind and the Sun",
    emoji: "☀️",
    illustration: "🌬️🧥☀️",
    level: "Medium",
    minutes: 2,
    starReward: 3,
    paragraphs: [
      "The North Wind and the Sun argued about who was stronger. They spotted a traveler in a warm coat and agreed: whoever could make him take off his coat would be the winner.",
      "The North Wind blew with all his might, cold and fierce. But the harder he blew, the tighter the traveler wrapped his coat around him.",
      "Then it was the Sun's turn. He shone gently, warm and bright. Soon the traveler felt so warm that he happily took off his coat.",
      "Gentleness had done what force could not.",
    ],
    moral: "Kindness and gentleness are stronger than force.",
    quiz: [
      { q: "Who got the traveler to take off his coat?", options: ["The Sun, with gentle warmth", "The North Wind", "A storm", "Nobody"], answer: 0 },
      { q: "What happened when the wind blew harder?", options: ["The traveler held his coat tighter", "The coat blew off", "He felt warm", "He ran away"], answer: 0 },
      { q: "What is the lesson?", options: ["Gentleness is stronger than force", "The wind always wins", "Coats are warm", "Arguing is good"], answer: 0 },
    ],
  },
];
