import type { LibraryStory } from "@/lib/stories/types";

// Original retellings of Greek myths (public domain) — the same world of gods,
// heroes, and monsters that inspired Percy Jackson. Pitched at ~10–12.

export const GREEK_MYTHS: LibraryStory[] = [
  {
    id: "perseus-medusa",
    collection: "Greek Myths & Heroes",
    title: "Perseus and Medusa",
    emoji: "🗡️",
    illustration: "🗡️🛡️🐍",
    level: "Tricky",
    minutes: 5,
    starReward: 4,
    paragraphs: [
      "Perseus, a young hero, was given a near-impossible task: bring back the head of Medusa — a monster with writhing snakes for hair, whose gaze turned any living thing to solid stone.",
      "The gods lent him gifts: winged sandals to fly, a cap of invisibility, and a shield polished as bright as a mirror. That shield would prove the cleverest weapon of all.",
      "Creeping into Medusa's lair, Perseus never once looked at her directly. Instead he watched her reflection in his gleaming shield, so her deadly stare could not turn him to stone.",
      "With one swift, sure stroke he defeated the monster and flew home a hero — proof that brains and courage together can beat what raw strength cannot.",
    ],
    moral: "Cleverness and courage together can defeat what strength alone cannot.",
    quiz: [
      { q: "Why was Medusa so dangerous?", options: ["Her gaze turned people to stone", "She was enormous", "She breathed fire", "She was invisible"], answer: 0 },
      { q: "How did Perseus avoid her deadly gaze?", options: ["He watched her reflection in his shield", "He shut his eyes and charged", "He attacked from far away", "He wore the magic cap backwards"], answer: 0 },
      { q: "What does the story really show?", options: ["Cleverness plus courage beats brute force", "Always stare a monster down", "Mirrors are magic", "Heroes never need help"], answer: 0, explain: "His mirror-shield trick — not just strength — won the day." },
    ],
  },
  {
    id: "theseus-minotaur",
    collection: "Greek Myths & Heroes",
    title: "Theseus and the Minotaur",
    emoji: "🐂",
    illustration: "🧵🌀🐂",
    level: "Tricky",
    minutes: 5,
    starReward: 4,
    paragraphs: [
      "Beneath the city of Crete lay the Labyrinth — a maze so twisting that no one who entered ever found the way out. At its heart prowled the Minotaur, a fearsome beast, half man and half bull.",
      "Brave Theseus volunteered to enter the maze and end the monster's reign of terror. Princess Ariadne, who believed in him, secretly slipped him a simple ball of thread.",
      "Theseus tied one end at the entrance and unwound the thread behind him as he crept deeper into the dark. Deep inside he found the Minotaur and, after a mighty struggle, defeated it.",
      "Then came the cleverest part: he simply followed the thread all the way back out into the light. Many strong warriors had failed where one good idea succeeded.",
    ],
    moral: "A simple, clever plan can solve a problem that strength alone can't.",
    quiz: [
      { q: "Why was the Labyrinth so deadly?", options: ["It was a maze no one could escape", "It was on fire", "It was flooded", "It was freezing cold"], answer: 0 },
      { q: "How did Theseus find his way back out?", options: ["He followed Ariadne's thread", "He memorised every turn", "He smashed through the walls", "He flew out"], answer: 0 },
      { q: "What was the truly clever part of his plan?", options: ["Using thread to retrace his steps", "Fighting more fiercely", "Running very fast", "Bringing a bright torch"], answer: 0 },
    ],
  },
  {
    id: "heracles-lion",
    collection: "Greek Myths & Heroes",
    title: "Heracles and the Nemean Lion",
    emoji: "🦁",
    illustration: "🦁💪✨",
    level: "Medium",
    minutes: 4,
    starReward: 4,
    paragraphs: [
      "Heracles, the strongest hero who ever lived, was set twelve impossible labours. The very first was to defeat the Nemean Lion, a beast whose golden hide no arrow or blade could pierce.",
      "Heracles fired arrow after arrow — every one bounced off. He swung his mighty club — the lion barely blinked. All his usual weapons were useless.",
      "So Heracles changed his plan entirely. He wrestled the great lion with his bare hands, using his strength in a brand-new way, until at last the beast was beaten.",
      "Afterwards he wore the lion's own unbreakable hide as armour. When one method fails, a true hero finds another.",
    ],
    moral: "When one way fails, find a smarter one.",
    quiz: [
      { q: "Why couldn't Heracles' arrows hurt the lion?", options: ["Its golden hide couldn't be pierced", "He kept missing", "They were broken", "The lion dodged them all"], answer: 0 },
      { q: "What did Heracles do when his weapons failed?", options: ["Wrestled the lion with his bare hands", "Gave up and went home", "Ran away", "Waited for help"], answer: 0 },
      { q: "What's the lesson of the labour?", options: ["When one method fails, try another", "Always rely on arrows", "Lions can't be beaten", "Never accept a challenge"], answer: 0 },
    ],
  },
  {
    id: "daedalus-icarus",
    collection: "Greek Myths & Heroes",
    title: "Daedalus and Icarus",
    emoji: "🪶",
    illustration: "🪶☀️🌊",
    level: "Medium",
    minutes: 4,
    starReward: 4,
    paragraphs: [
      "Daedalus, a brilliant inventor, was trapped on an island with his son Icarus. To escape, he built two pairs of wings out of feathers held together with wax.",
      "Before they flew, Daedalus warned his son carefully: “Don't fly too low, or the sea's damp will clog your wings. And don't fly too high, or the sun's heat will melt the wax.”",
      "They soared into the sky, free at last. But Icarus, dizzy with the joy of flying, forgot the warning. Higher and higher he climbed, closer and closer to the blazing sun.",
      "The wax softened, the feathers loosened, and Icarus tumbled down into the sea. His father flew on, heartbroken — a reminder that excitement is never an excuse to ignore good advice.",
    ],
    moral: "Heed wise warnings, even when you're having the time of your life.",
    quiz: [
      { q: "What were the wings made of?", options: ["Feathers and wax", "Wood and string", "Beaten metal", "Cloth and rope"], answer: 0 },
      { q: "Why did Icarus fall?", options: ["He flew too high and the sun melted the wax", "He flew too low into the waves", "A bird struck him", "The wings broke at takeoff"], answer: 0 },
      { q: "What's the lesson?", options: ["Heed wise warnings, even when excited", "Always fly as high as possible", "Inventors are foolish", "Never go near the sea"], answer: 0 },
    ],
  },
  {
    id: "king-midas",
    collection: "Greek Myths & Heroes",
    title: "King Midas and the Golden Touch",
    emoji: "👑",
    illustration: "👑✨🍎",
    level: "Medium",
    minutes: 4,
    starReward: 4,
    paragraphs: [
      "King Midas loved gold more than anything in the world. So when a god offered him a single wish, he barely paused: “Let everything I touch turn to gold!”",
      "At first it was wonderful. He touched a twig — gold! A stone — gold! He danced through his palace turning everything to glittering treasure.",
      "But then he tried to eat, and his food turned to hard metal in his mouth. His cup of water became solid gold. And when he hugged his beloved daughter… she froze into a cold golden statue.",
      "Midas wept and begged for the wish to be undone. He had learned, almost too late, that the people and things we love are worth more than all the gold in the world.",
    ],
    moral: "The people we love are worth more than any riches.",
    quiz: [
      { q: "What did King Midas wish for?", options: ["Everything he touched would turn to gold", "To be the strongest king", "To live forever", "To be able to fly"], answer: 0 },
      { q: "Why did the golden touch become a curse?", options: ["He couldn't eat, drink, or hug his daughter", "The gold ran out", "Thieves stole it all", "It started to rain"], answer: 0 },
      { q: "What did Midas finally learn?", options: ["Love matters more than riches", "Gold is the best thing of all", "Wishes are useless", "Never trust a god"], answer: 0 },
    ],
  },
  {
    id: "pandoras-box",
    collection: "Greek Myths & Heroes",
    title: "Pandora's Box",
    emoji: "📦",
    illustration: "📦🦋✨",
    level: "Medium",
    minutes: 4,
    starReward: 4,
    paragraphs: [
      "Pandora was given a mysterious box with one strict rule: never, ever open it. But curiosity gnawed at her, day and night, until she could think of nothing else.",
      "At last she couldn't resist. She lifted the lid just a crack — and out swarmed every trouble in the world: worry, sickness, and sadness, escaping into the air before she could slam it shut again.",
      "Horrified, Pandora thought all was lost forever. But then a tiny, gentle glow fluttered up from the very bottom of the box.",
      "It was Hope. And so, even when troubles fill the world, Hope always remains to help people carry on.",
    ],
    moral: "Even when troubles come, hope always remains.",
    quiz: [
      { q: "What was Pandora told NOT to do?", options: ["Open the box", "Hide the box", "Sell the box", "Paint the box"], answer: 0 },
      { q: "What escaped when she opened it?", options: ["All the troubles of the world", "Piles of gold", "A flock of birds", "Nothing at all"], answer: 0 },
      { q: "What remained at the very bottom?", options: ["Hope", "More troubles", "Treasure", "A monster"], answer: 0, explain: "Hope stayed behind to help people through hard times." },
    ],
  },
];
