import type { LibraryStory } from "@/lib/stories/types";

// AUTO-GENERATED by scripts/import-books.mjs — do not edit by hand.
// Populate it (on a machine with internet) by running:  npm run import:books
export const GUTENBERG_BOOKS: LibraryStory[] = [];
