[build]
  command = "npx cross-env NODE_OPTIONS=\"--max-http-header-size=32768\" next build --webpack"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"
