import type { AssetCategory, RealAsset } from "@/lib/domain/types";

export const MIN_TRADE_CENTS = 50;

const about = (
  story: string,
  facts: { label: string; value: string }[],
  whyGreat: { emoji: string; text: string }[],
  didYouKnow: string,
) => ({ story, facts, whyGreat, didYouKnow });

export const REAL_ASSETS: RealAsset[] = [
  { symbol: "AAPL", name: "Apple", ticker: "AAPL", exchange: "NASDAQ", emoji: "🍎", assetType: "stock", categories: ["popular", "tech"], source: "finnhub", sourceId: "AAPL", description: "Makes iPhones, iPads and Macs.", about: about("Apple started in 1976 in a garage. Steve Jobs and Steve Wozniak wanted to make computers anyone could use.", [{ label: "Founded", value: "1976" }, { label: "From", value: "California" }, { label: "Makes", value: "Phones & computers" }], [{ emoji: "📱", text: "The iPhone changed how the world uses phones." }, { emoji: "🎨", text: "Apple is famous for simple designs that feel easy to use." }], "Apple was once nearly out of money; today it is one of the most valuable companies ever.") },
  { symbol: "TSLA", name: "Tesla", ticker: "TSLA", exchange: "NASDAQ", emoji: "⚡", assetType: "stock", categories: ["popular", "tech"], source: "finnhub", sourceId: "TSLA", description: "Builds electric cars and energy products.", about: about("Tesla helped make electric cars feel fast, exciting and normal for everyday drivers.", [{ label: "Founded", value: "2003" }, { label: "From", value: "Texas" }, { label: "Makes", value: "Electric cars" }], [{ emoji: "🔋", text: "It pushed car makers to take batteries seriously." }, { emoji: "🚗", text: "Its cars can receive software updates like phones." }], "The company is named after inventor Nikola Tesla.") },
  { symbol: "DIS", name: "Disney", ticker: "DIS", exchange: "NYSE", emoji: "🏰", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "DIS", description: "Movies, parks and characters families know.", about: about("Disney began as a small animation studio and grew into movies, theme parks, TV and streaming.", [{ label: "Founded", value: "1923" }, { label: "From", value: "California" }, { label: "Makes", value: "Stories & parks" }], [{ emoji: "🎬", text: "Its characters are known across generations." }, { emoji: "🎢", text: "Its parks turn stories into places people can visit." }], "Mickey Mouse first appeared in a short film in 1928.") },
  { symbol: "RBLX", name: "Roblox", ticker: "RBLX", exchange: "NYSE", emoji: "🎮", assetType: "stock", categories: ["popular", "games"], source: "finnhub", sourceId: "RBLX", description: "A platform where people create and play games.", about: about("Roblox is not just one game. It is a huge playground where people can build their own games and share them with friends.", [{ label: "Started", value: "2006" }, { label: "Type", value: "Game platform" }, { label: "Builds", value: "Creator tools" }], [{ emoji: "🛠️", text: "Players can become creators and learn how games are made." }, { emoji: "🌍", text: "Millions of people can visit the same worlds from different places." }], "Some Roblox creators have built games popular enough to become real businesses.") },
  { symbol: "MCD", name: "McDonald's", ticker: "MCD", exchange: "NYSE", emoji: "🍔", assetType: "stock", categories: ["popular", "food"], source: "finnhub", sourceId: "MCD", description: "Fast food restaurants around the world.", about: about("McDonald's grew from one speedy burger restaurant into a global restaurant system.", [{ label: "Founded", value: "1940" }, { label: "From", value: "California" }, { label: "Sells", value: "Burgers & fries" }], [{ emoji: "⏱️", text: "It became famous for quick, repeatable service." }, { emoji: "🌍", text: "Its golden arches are recognised in many countries." }], "Many McDonald's restaurants are owned by local franchise operators.") },
  { symbol: "NKE", name: "Nike", ticker: "NKE", exchange: "NYSE", emoji: "👟", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "NKE", description: "Shoes and sportswear.", about: about("Nike started by selling running shoes and became one of the biggest sports brands in the world.", [{ label: "Founded", value: "1964" }, { label: "From", value: "Oregon" }, { label: "Makes", value: "Shoes & gear" }], [{ emoji: "🏃", text: "It works with famous athletes to test and promote gear." }, { emoji: "✔️", text: "Its swoosh logo is simple and memorable." }], "Nike was originally called Blue Ribbon Sports.") },
  { symbol: "MSFT", name: "Microsoft", ticker: "MSFT", exchange: "NASDAQ", emoji: "💻", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "MSFT", description: "Windows, Xbox, cloud and software." },
  { symbol: "NFLX", name: "Netflix", ticker: "NFLX", exchange: "NASDAQ", emoji: "🎬", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "NFLX", description: "Streaming shows and movies.", about: about("Netflix began by mailing DVDs, then helped make streaming movies at home normal.", [{ label: "Founded", value: "1997" }, { label: "From", value: "California" }, { label: "Makes", value: "Streaming shows" }], [{ emoji: "📺", text: "It changed how families watch shows." }, { emoji: "🌐", text: "It creates stories for audiences around the world." }], "Netflix once sent movies through the post in red envelopes.") },
  { symbol: "AMZN", name: "Amazon", ticker: "AMZN", exchange: "NASDAQ", emoji: "📦", assetType: "stock", categories: ["popular", "tech"], source: "finnhub", sourceId: "AMZN", description: "Online shopping, cloud computing and devices.", about: about("Amazon started as an online bookstore and grew into shopping, deliveries, devices and cloud computing.", [{ label: "Founded", value: "1994" }, { label: "From", value: "Washington" }, { label: "Does", value: "Shopping & cloud" }], [{ emoji: "📚", text: "It proved stores could live on the internet." }, { emoji: "☁️", text: "Its cloud tools power many apps and websites." }], "Amazon's first product category was books.") },
  { symbol: "GOOGL", name: "Alphabet", ticker: "GOOGL", exchange: "NASDAQ", emoji: "🔍", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "GOOGL", description: "Google search, YouTube, Android and cloud." },
  { symbol: "NTDOY", name: "Nintendo", ticker: "NTDOY", exchange: "OTC", emoji: "🎮", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "NTDOY", description: "Mario, Zelda, Switch and family games.", about: about("Nintendo began long before video games, making playing cards in Japan before becoming a game legend.", [{ label: "Founded", value: "1889" }, { label: "From", value: "Kyoto" }, { label: "Makes", value: "Games & consoles" }], [{ emoji: "🍄", text: "Mario and Zelda became some of gaming's most loved worlds." }, { emoji: "🎮", text: "Nintendo often focuses on playful ideas instead of just powerful machines." }], "Nintendo is older than cars, airplanes and television.") },
  { symbol: "SONY", name: "Sony", ticker: "SONY", exchange: "NYSE", emoji: "🎮", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "SONY", description: "PlayStation, music, movies and electronics." },
  { symbol: "KO", name: "Coca-Cola", ticker: "KO", exchange: "NYSE", emoji: "🥤", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "KO", description: "Soft drinks sold around the world." },
  { symbol: "PEP", name: "PepsiCo", ticker: "PEP", exchange: "NASDAQ", emoji: "🥤", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "PEP", description: "Drinks and snack brands." },
  { symbol: "SPOT", name: "Spotify", ticker: "SPOT", exchange: "NYSE", emoji: "🎵", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "SPOT", description: "Music and podcast streaming." },
  { symbol: "META", name: "Meta", ticker: "META", exchange: "NASDAQ", emoji: "📱", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "META", description: "Facebook, Instagram, WhatsApp and VR." },
  { symbol: "NVDA", name: "Nvidia", ticker: "NVDA", exchange: "NASDAQ", emoji: "🖥️", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "NVDA", description: "Computer chips for games and AI." },
  { symbol: "MAT", name: "Mattel", ticker: "MAT", exchange: "NASDAQ", emoji: "🚗", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "MAT", description: "Toys including Barbie and Hot Wheels." },
  { symbol: "HAS", name: "Hasbro", ticker: "HAS", exchange: "NASDAQ", emoji: "🎲", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "HAS", description: "Toys and games like Monopoly and Nerf." },
  { symbol: "SBUX", name: "Starbucks", ticker: "SBUX", exchange: "NASDAQ", emoji: "☕", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "SBUX", description: "Coffee shops around the world." },
  { symbol: "CMG", name: "Chipotle", ticker: "CMG", exchange: "NYSE", emoji: "🌯", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "CMG", description: "Burritos, bowls and quick meals." },
  { symbol: "DPZ", name: "Domino's US", ticker: "DPZ", exchange: "NYSE", emoji: "🍕", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "DPZ", description: "Pizza delivery and stores." },
  { symbol: "HSY", name: "Hershey", ticker: "HSY", exchange: "NYSE", emoji: "🍫", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "HSY", description: "Chocolate and sweets." },
  { symbol: "CROX", name: "Crocs", ticker: "CROX", exchange: "NASDAQ", emoji: "🐊", assetType: "stock", categories: [], source: "finnhub", sourceId: "CROX", description: "Colourful foam clogs and shoes." },
  { symbol: "LULU", name: "Lululemon", ticker: "LULU", exchange: "NASDAQ", emoji: "🧘", assetType: "stock", categories: [], source: "finnhub", sourceId: "LULU", description: "Athletic clothes and yoga gear." },
  { symbol: "RACE", name: "Ferrari", ticker: "RACE", exchange: "NYSE", emoji: "🏎️", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "RACE", description: "Luxury sports cars and racing.", about: about("Ferrari grew from racing into one of the world's most famous sports car brands.", [{ label: "Founded", value: "1947" }, { label: "From", value: "Italy" }, { label: "Makes", value: "Sports cars" }], [{ emoji: "🏁", text: "Racing is part of Ferrari's identity." }, { emoji: "⭐", text: "Its cars are rare, premium and instantly recognisable." }], "Ferrari's prancing horse logo came from an Italian pilot's symbol.") },
  { symbol: "BBW", name: "Build-A-Bear", ticker: "BBW", exchange: "NYSE", emoji: "🧸", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "BBW", description: "Stores where kids make stuffed toys." },
  { symbol: "EA", name: "Electronic Arts", ticker: "EA", exchange: "NASDAQ", emoji: "🎮", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "EA", description: "Video games and sports titles." },
  { symbol: "ABNB", name: "Airbnb", ticker: "ABNB", exchange: "NASDAQ", emoji: "🏠", assetType: "stock", categories: [], source: "finnhub", sourceId: "ABNB", description: "Travel stays hosted by people." },
  { symbol: "UBER", name: "Uber", ticker: "UBER", exchange: "NYSE", emoji: "🚗", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "UBER", description: "Rides, deliveries and transport tech." },
  { symbol: "V", name: "Visa", ticker: "V", exchange: "NYSE", emoji: "💳", assetType: "stock", categories: [], source: "finnhub", sourceId: "V", description: "Payment network used by cards." },
  { symbol: "WMT", name: "Walmart", ticker: "WMT", exchange: "NYSE", emoji: "🛒", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "WMT", description: "Large shops and groceries." },
  { symbol: "TGT", name: "Target", ticker: "TGT", exchange: "NYSE", emoji: "🎯", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "TGT", description: "Retail stores with home, clothes and food." },
  { symbol: "GPRO", name: "GoPro", ticker: "GPRO", exchange: "NASDAQ", emoji: "📷", assetType: "stock", categories: [], source: "finnhub", sourceId: "GPRO", description: "Small cameras for action videos." },
  { symbol: "COST", name: "Costco", ticker: "COST", exchange: "NASDAQ", emoji: "🏬", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "COST", description: "Warehouse shops with memberships." },
  { symbol: "CBA", name: "Commonwealth Bank", ticker: "CBA", exchange: "ASX", emoji: "🏦", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "CBA.AX", description: "One of Australia's biggest banks." },
  { symbol: "BHP", name: "BHP", ticker: "BHP", exchange: "ASX", emoji: "⛏️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "BHP.AX", description: "Australian mining and resources." },
  { symbol: "CSL", name: "CSL", ticker: "CSL", exchange: "ASX", emoji: "💉", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "CSL.AX", description: "Medicines, vaccines and blood products." },
  { symbol: "WOW", name: "Woolworths", ticker: "WOW", exchange: "ASX", emoji: "🛒", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "WOW.AX", description: "Australian supermarkets." },
  { symbol: "WES", name: "Wesfarmers", ticker: "WES", exchange: "ASX", emoji: "🔨", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "WES.AX", description: "Owns businesses including Bunnings and Kmart." },
  { symbol: "TLS", name: "Telstra", ticker: "TLS", exchange: "ASX", emoji: "📡", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "TLS.AX", description: "Phones and internet networks." },
  { symbol: "QAN", name: "Qantas", ticker: "QAN", exchange: "ASX", emoji: "✈️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "QAN.AX", description: "Australia's famous airline." },
  { symbol: "JBH", name: "JB Hi-Fi", ticker: "JBH", exchange: "ASX", emoji: "🎧", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "JBH.AX", description: "Electronics, games and music retail." },
  { symbol: "DMP", name: "Domino's AU", ticker: "DMP", exchange: "ASX", emoji: "🍕", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "DMP.AX", description: "Pizza stores in Australia and beyond." },
  { symbol: "A2M", name: "a2 Milk", ticker: "A2M", exchange: "ASX", emoji: "🥛", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "A2M.AX", description: "Milk and infant nutrition products." },
  { symbol: "COL", name: "Coles", ticker: "COL", exchange: "ASX", emoji: "🛒", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "COL.AX", description: "Australian supermarkets and groceries." },
  { symbol: "RIO", name: "Rio Tinto", ticker: "RIO", exchange: "ASX", emoji: "⛏️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "RIO.AX", description: "Mining and metals company." },
  { symbol: "FMG", name: "Fortescue", ticker: "FMG", exchange: "ASX", emoji: "⛏️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "FMG.AX", description: "Iron ore and green energy projects." },
  { symbol: "XRO", name: "Xero", ticker: "XRO", exchange: "ASX", emoji: "📊", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "XRO.AX", description: "Accounting software for small businesses." },
  { symbol: "COH", name: "Cochlear", ticker: "COH", exchange: "ASX", emoji: "👂", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "COH.AX", description: "Hearing implant technology." },
  { symbol: "BTC", name: "Bitcoin", ticker: "BTC", exchange: "Crypto", emoji: "₿", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "bitcoin", description: "The first and most famous digital money.", about: about("Bitcoin is the world's first digital money. In 2009 an inventor known only as \"Satoshi Nakamoto\" launched it as money no single bank or country controls.", [{ label: "Started", value: "2009" }, { label: "Type", value: "Cryptocurrency" }, { label: "Max ever", value: "21 million" }], [{ emoji: "🌍", text: "Anyone, anywhere can send it directly to anyone else - no bank in the middle." }, { emoji: "🔒", text: "Protected by very hard maths, so it is extremely hard to fake." }, { emoji: "💎", text: "There will only ever be 21 million, so some treat it like digital gold." }], "The very first thing bought with Bitcoin was two pizzas - for 10,000 coins!") },
  { symbol: "ETH", name: "Ethereum", ticker: "ETH", exchange: "Crypto", emoji: "Ξ", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "ethereum", description: "Digital money plus programmable apps.", about: about("Ethereum is a crypto network that can run small programs called smart contracts.", [{ label: "Started", value: "2015" }, { label: "Type", value: "Crypto network" }, { label: "Token", value: "Ether" }], [{ emoji: "🧩", text: "Builders can create apps that run on the network." }, { emoji: "🎨", text: "Many digital collectibles first became popular on Ethereum." }], "Ethereum changed its system in 2022 to use much less energy.") },
  { symbol: "DOGE", name: "Dogecoin", ticker: "DOGE", exchange: "Crypto", emoji: "🐶", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "dogecoin", description: "A joke coin that became famous online.", about: about("Dogecoin began as a funny internet coin and grew because communities loved sharing it.", [{ label: "Started", value: "2013" }, { label: "Type", value: "Meme coin" }, { label: "Mascot", value: "Shiba Inu" }], [{ emoji: "😂", text: "It showed internet communities can move markets." }, { emoji: "💬", text: "People often use it to learn how crypto works." }], "Dogecoin's mascot came from a famous internet meme.") },
  { symbol: "SOL", name: "Solana", ticker: "SOL", exchange: "Crypto", emoji: "◎", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "solana", description: "A fast crypto network for apps.", about: about("Solana is designed to process lots of crypto transactions quickly.", [{ label: "Started", value: "2020" }, { label: "Type", value: "Crypto network" }, { label: "Known for", value: "Speed" }], [{ emoji: "⚡", text: "It aims to make transactions fast and cheap." }, { emoji: "🧱", text: "Developers use it to build games, finance tools and collectibles." }], "Solana's name was inspired by a beach town in California.") },
  { symbol: "ADA", name: "Cardano", ticker: "ADA", exchange: "Crypto", emoji: "🔷", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "cardano", description: "A research-focused crypto network.", about: about("Cardano is a crypto network built with a careful research-first style.", [{ label: "Started", value: "2017" }, { label: "Type", value: "Crypto network" }, { label: "Token", value: "ADA" }], [{ emoji: "📚", text: "Its builders emphasise academic review and planning." }, { emoji: "🌱", text: "It uses a lower-energy proof-of-stake design." }], "ADA is named after Ada Lovelace, an early computing pioneer.") },
];

export const ASSET_CATEGORIES: { key: "all" | AssetCategory; label: string }[] = [
  { key: "all", label: "All" },
  { key: "popular", label: "⭐ Popular" },
  { key: "games", label: "🎮 Games" },
  { key: "tech", label: "💻 Tech" },
  { key: "food", label: "🍔 Food & Shops" },
  { key: "australian", label: "🇦🇺 Australian" },
  { key: "crypto", label: "🪙 Crypto" },
];

export function getAsset(symbol: string): RealAsset | undefined {
  return REAL_ASSETS.find((asset) => asset.symbol === symbol);
}
