import type { AssetCategory, RealAsset } from "@/lib/domain/types";

export const MIN_TRADE_CENTS = 50;

const about = (
  story: string,
  facts: { label: string; value: string }[],
  whyGreat: { emoji: string; text: string }[],
  didYouKnow: string,
) => ({ story, facts, whyGreat, didYouKnow });

export const REAL_ASSETS: RealAsset[] = [
  { symbol: "AAPL", name: "Apple", ticker: "AAPL", exchange: "NASDAQ", emoji: "🍎", assetType: "stock", categories: ["popular", "tech"], source: "finnhub", sourceId: "AAPL", description: "Makes iPhones, iPads and Macs.", about: about("Apple started in 1976 in a garage. Steve Jobs and Steve Wozniak wanted to make computers anyone could use.", [{ label: "Founded", value: "1976" }, { label: "From", value: "California" }, { label: "Makes", value: "Phones & computers" }], [{ emoji: "📱", text: "The iPhone changed how the world uses phones." }, { emoji: "🎨", text: "Apple is famous for simple designs that feel easy to use." }], "Apple was once nearly out of money; today it is one of the most valuable companies ever.") },
  { symbol: "TSLA", name: "Tesla", ticker: "TSLA", exchange: "NASDAQ", emoji: "⚡", assetType: "stock", categories: ["popular", "tech"], source: "finnhub", sourceId: "TSLA", description: "Builds electric cars and energy products.", about: about("Tesla helped make electric cars feel fast, exciting and normal for everyday drivers.", [{ label: "Founded", value: "2003" }, { label: "From", value: "Texas" }, { label: "Makes", value: "Electric cars" }], [{ emoji: "🔋", text: "It pushed car makers to take batteries seriously." }, { emoji: "🚗", text: "Its cars can receive software updates like phones." }], "The company is named after inventor Nikola Tesla.") },
  { symbol: "DIS", name: "Disney", ticker: "DIS", exchange: "NYSE", emoji: "🏰", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "DIS", description: "Movies, parks and characters families know.", about: about("Disney began as a small animation studio and grew into movies, theme parks, TV and streaming.", [{ label: "Founded", value: "1923" }, { label: "From", value: "California" }, { label: "Makes", value: "Stories & parks" }], [{ emoji: "🎬", text: "Its characters are known across generations." }, { emoji: "🎢", text: "Its parks turn stories into places people can visit." }], "Mickey Mouse first appeared in a short film in 1928.") },
  { symbol: "RBLX", name: "Roblox", ticker: "RBLX", exchange: "NYSE", emoji: "🎮", assetType: "stock", categories: ["popular", "games"], source: "finnhub", sourceId: "RBLX", description: "A platform where people create and play games.", about: about("Roblox is not just one game. It is a huge playground where people can build their own games and share them with friends.", [{ label: "Started", value: "2006" }, { label: "Type", value: "Game platform" }, { label: "Builds", value: "Creator tools" }], [{ emoji: "🛠️", text: "Players can become creators and learn how games are made." }, { emoji: "🌍", text: "Millions of people can visit the same worlds from different places." }], "Some Roblox creators have built games popular enough to become real businesses.") },
  { symbol: "MCD", name: "McDonald's", ticker: "MCD", exchange: "NYSE", emoji: "🍔", assetType: "stock", categories: ["popular", "food"], source: "finnhub", sourceId: "MCD", description: "Fast food restaurants around the world.", about: about("McDonald's grew from one speedy burger restaurant into a global restaurant system.", [{ label: "Founded", value: "1940" }, { label: "From", value: "California" }, { label: "Sells", value: "Burgers & fries" }], [{ emoji: "⏱️", text: "It became famous for quick, repeatable service." }, { emoji: "🌍", text: "Its golden arches are recognised in many countries." }], "Many McDonald's restaurants are owned by local franchise operators.") },
  { symbol: "NKE", name: "Nike", ticker: "NKE", exchange: "NYSE", emoji: "👟", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "NKE", description: "Shoes and sportswear.", about: about("Nike started by selling running shoes and became one of the biggest sports brands in the world.", [{ label: "Founded", value: "1964" }, { label: "From", value: "Oregon" }, { label: "Makes", value: "Shoes & gear" }], [{ emoji: "🏃", text: "It works with famous athletes to test and promote gear." }, { emoji: "✔️", text: "Its swoosh logo is simple and memorable." }], "Nike was originally called Blue Ribbon Sports.") },
  { symbol: "MSFT", name: "Microsoft", ticker: "MSFT", exchange: "NASDAQ", emoji: "💻", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "MSFT", description: "Windows, Xbox, cloud and software.", about: about("Microsoft was started in 1975 by Bill Gates and Paul Allen to put software on home computers.", [{ label: "Founded", value: "1975" }, { label: "From", value: "Washington" }, { label: "Makes", value: "Software & Xbox" }], [{ emoji: "🪟", text: "Windows runs on a huge number of computers worldwide." }, { emoji: "🎮", text: "It also makes Xbox and powerful cloud tools." }], "Microsoft began by writing software for one of the very first home computers.") },
  { symbol: "NFLX", name: "Netflix", ticker: "NFLX", exchange: "NASDAQ", emoji: "🎬", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "NFLX", description: "Streaming shows and movies.", about: about("Netflix began by mailing DVDs, then helped make streaming movies at home normal.", [{ label: "Founded", value: "1997" }, { label: "From", value: "California" }, { label: "Makes", value: "Streaming shows" }], [{ emoji: "📺", text: "It changed how families watch shows." }, { emoji: "🌐", text: "It creates stories for audiences around the world." }], "Netflix once sent movies through the post in red envelopes.") },
  { symbol: "AMZN", name: "Amazon", ticker: "AMZN", exchange: "NASDAQ", emoji: "📦", assetType: "stock", categories: ["popular", "tech"], source: "finnhub", sourceId: "AMZN", description: "Online shopping, cloud computing and devices.", about: about("Amazon started as an online bookstore and grew into shopping, deliveries, devices and cloud computing.", [{ label: "Founded", value: "1994" }, { label: "From", value: "Washington" }, { label: "Does", value: "Shopping & cloud" }], [{ emoji: "📚", text: "It proved stores could live on the internet." }, { emoji: "☁️", text: "Its cloud tools power many apps and websites." }], "Amazon's first product category was books.") },
  { symbol: "GOOGL", name: "Alphabet", ticker: "GOOGL", exchange: "NASDAQ", emoji: "🔍", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "GOOGL", description: "Google search, YouTube, Android and cloud.", about: about("Google began in 1998 as a university project to organise the whole web, and grew into search, YouTube and Android.", [{ label: "Founded", value: "1998" }, { label: "From", value: "California" }, { label: "Makes", value: "Search & YouTube" }], [{ emoji: "🔎", text: "Its search helps billions of people find answers." }, { emoji: "📱", text: "Android powers a huge number of phones." }], "The name Google came from googol, a number with one hundred zeros.") },
  { symbol: "NTDOY", name: "Nintendo", ticker: "NTDOY", exchange: "OTC", emoji: "🎮", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "NTDOY", description: "Mario, Zelda, Switch and family games.", about: about("Nintendo began long before video games, making playing cards in Japan before becoming a game legend.", [{ label: "Founded", value: "1889" }, { label: "From", value: "Kyoto" }, { label: "Makes", value: "Games & consoles" }], [{ emoji: "🍄", text: "Mario and Zelda became some of gaming's most loved worlds." }, { emoji: "🎮", text: "Nintendo often focuses on playful ideas instead of just powerful machines." }], "Nintendo is older than cars, airplanes and television.") },
  { symbol: "SONY", name: "Sony", ticker: "SONY", exchange: "NYSE", emoji: "🎮", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "SONY", description: "PlayStation, music, movies and electronics.", about: about("Sony was founded in Japan after World War Two and grew into games, music, movies and electronics.", [{ label: "Founded", value: "1946" }, { label: "From", value: "Tokyo" }, { label: "Makes", value: "PlayStation & gadgets" }], [{ emoji: "🕹️", text: "PlayStation is one of the most popular game consoles ever." }, { emoji: "🎧", text: "Sony also makes cameras, headphones and music." }], "Sony once made one of the first pocket radios people could carry anywhere.") },
  { symbol: "KO", name: "Coca-Cola", ticker: "KO", exchange: "NYSE", emoji: "🥤", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "KO", description: "Soft drinks sold around the world.", about: about("Coca-Cola started in 1886 and became one of the most recognised drink brands on Earth.", [{ label: "Founded", value: "1886" }, { label: "From", value: "Atlanta" }, { label: "Sells", value: "Soft drinks" }], [{ emoji: "🌍", text: "Its drinks are sold in almost every country." }, { emoji: "🔴", text: "Its red logo is famous worldwide." }], "The exact Coca-Cola recipe is kept a closely guarded secret.") },
  { symbol: "PEP", name: "PepsiCo", ticker: "PEP", exchange: "NASDAQ", emoji: "🥤", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "PEP", description: "Drinks and snack brands.", about: about("PepsiCo makes far more than Pepsi; it owns many popular drink and snack brands.", [{ label: "Founded", value: "1965" }, { label: "From", value: "New York" }, { label: "Sells", value: "Drinks & snacks" }], [{ emoji: "🥔", text: "It owns big snack brands like chips and crisps." }, { emoji: "🏃", text: "It also owns sports drinks people know well." }], "PepsiCo owns lots of snack brands, not just fizzy drinks.") },
  { symbol: "SPOT", name: "Spotify", ticker: "SPOT", exchange: "NYSE", emoji: "🎵", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "SPOT", description: "Music and podcast streaming.", about: about("Spotify started in Sweden and helped make streaming music and podcasts a normal everyday thing.", [{ label: "Founded", value: "2006" }, { label: "From", value: "Sweden" }, { label: "Makes", value: "Music streaming" }], [{ emoji: "🎧", text: "It made listening to almost any song instant." }, { emoji: "🎙️", text: "It also became a big home for podcasts." }], "Spotify is known for its personalised playlists that learn what you like.") },
  { symbol: "META", name: "Meta", ticker: "META", exchange: "NASDAQ", emoji: "📱", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "META", description: "Facebook, Instagram, WhatsApp and VR.", about: about("Meta began as Facebook in 2004 and now runs Instagram and WhatsApp too.", [{ label: "Founded", value: "2004" }, { label: "From", value: "California" }, { label: "Makes", value: "Social apps" }], [{ emoji: "🌐", text: "Its apps connect billions of people." }, { emoji: "🕶️", text: "It also builds virtual reality headsets." }], "Facebook was first created in a college dorm room.") },
  { symbol: "NVDA", name: "Nvidia", ticker: "NVDA", exchange: "NASDAQ", emoji: "🖥️", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "NVDA", description: "Computer chips for games and AI.", about: about("Nvidia makes powerful chips that draw game graphics and now also power artificial intelligence.", [{ label: "Founded", value: "1993" }, { label: "From", value: "California" }, { label: "Makes", value: "Computer chips" }], [{ emoji: "🎮", text: "Its chips help games look smooth and detailed." }, { emoji: "🤖", text: "The same chips became very important for AI." }], "Nvidia's founders first planned the company in a roadside diner.") },
  { symbol: "MAT", name: "Mattel", ticker: "MAT", exchange: "NASDAQ", emoji: "🚗", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "MAT", description: "Toys including Barbie and Hot Wheels.", about: about("Mattel is one of the biggest toy makers, known for Barbie and Hot Wheels.", [{ label: "Founded", value: "1945" }, { label: "From", value: "California" }, { label: "Makes", value: "Toys" }], [{ emoji: "👧", text: "Barbie became one of the most famous toys ever." }, { emoji: "🏎️", text: "Hot Wheels cars are collected all over the world." }], "Mattel started out making picture frames before it made toys.") },
  { symbol: "HAS", name: "Hasbro", ticker: "HAS", exchange: "NASDAQ", emoji: "🎲", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "HAS", description: "Toys and games like Monopoly and Nerf.", about: about("Hasbro makes classic toys and board games that families have played for generations.", [{ label: "Founded", value: "1923" }, { label: "From", value: "Rhode Island" }, { label: "Makes", value: "Toys & games" }], [{ emoji: "🎲", text: "It makes games like Monopoly that people know everywhere." }, { emoji: "🔫", text: "Nerf and Transformers are some of its famous toys." }], "Hasbro began by selling fabric scraps before moving into toys.") },
  { symbol: "SBUX", name: "Starbucks", ticker: "SBUX", exchange: "NASDAQ", emoji: "☕", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "SBUX", description: "Coffee shops around the world.", about: about("Starbucks turned the coffee shop into a daily habit for people in many countries.", [{ label: "Founded", value: "1971" }, { label: "From", value: "Seattle" }, { label: "Sells", value: "Coffee & drinks" }], [{ emoji: "🌍", text: "It has thousands of cafes around the world." }, { emoji: "📱", text: "Its app and rewards made ordering easy." }], "The very first Starbucks opened in Seattle's Pike Place Market.") },
  { symbol: "CMG", name: "Chipotle", ticker: "CMG", exchange: "NYSE", emoji: "🌯", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "CMG", description: "Burritos, bowls and quick meals.", about: about("Chipotle made fresh, build-your-own burritos and bowls into popular fast food.", [{ label: "Founded", value: "1993" }, { label: "From", value: "Denver" }, { label: "Sells", value: "Burritos & bowls" }], [{ emoji: "🥗", text: "It became known for fresh ingredients made in front of you." }, { emoji: "⚡", text: "It serves meals quickly without feeling like typical fast food." }], "Chipotle started near a university with just one small restaurant.") },
  { symbol: "DPZ", name: "Domino's US", ticker: "DPZ", exchange: "NYSE", emoji: "🍕", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "DPZ", description: "Pizza delivery and stores.", about: about("Domino's grew from one pizza shop into a worldwide delivery brand known for speed and apps.", [{ label: "Founded", value: "1960" }, { label: "From", value: "Michigan" }, { label: "Sells", value: "Pizza" }], [{ emoji: "🛵", text: "It became famous for fast pizza delivery." }, { emoji: "📲", text: "It uses clever apps and tech to take orders." }], "Domino's once gave away cars to its hardest-working store teams.") },
  { symbol: "HSY", name: "Hershey", ticker: "HSY", exchange: "NYSE", emoji: "🍫", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "HSY", description: "Chocolate and sweets.", about: about("Hershey helped make chocolate affordable for everyday people, not just a treat for the rich.", [{ label: "Founded", value: "1894" }, { label: "From", value: "Pennsylvania" }, { label: "Makes", value: "Chocolate" }], [{ emoji: "🍫", text: "Its chocolate bars became an American classic." }, { emoji: "🏫", text: "Its founder used profits to build schools." }], "Milton Hershey built a whole town for his chocolate factory workers.") },
  { symbol: "CROX", name: "Crocs", ticker: "CROX", exchange: "NASDAQ", emoji: "🐊", assetType: "stock", categories: [], source: "finnhub", sourceId: "CROX", description: "Colourful foam clogs and shoes.", about: about("Crocs turned a comfy foam clog into a fun, collectible fashion item.", [{ label: "Founded", value: "2002" }, { label: "From", value: "Colorado" }, { label: "Makes", value: "Foam shoes" }], [{ emoji: "🌈", text: "People decorate them with little charms called Jibbitz." }, { emoji: "🦶", text: "They became loved for being comfy and easy to clean." }], "Crocs were first designed as a slip-resistant boating shoe.") },
  { symbol: "LULU", name: "Lululemon", ticker: "LULU", exchange: "NASDAQ", emoji: "🧘", assetType: "stock", categories: [], source: "finnhub", sourceId: "LULU", description: "Athletic clothes and yoga gear.", about: about("Lululemon started with yoga clothes and helped make athletic wear into everyday fashion.", [{ label: "Founded", value: "1998" }, { label: "From", value: "Canada" }, { label: "Makes", value: "Activewear" }], [{ emoji: "🧘", text: "It made comfy workout clothes popular for everyday wear." }, { emoji: "🏬", text: "Its stores often host fitness classes." }], "Lululemon began as a single shop that doubled as a yoga studio at night.") },
  { symbol: "RACE", name: "Ferrari", ticker: "RACE", exchange: "NYSE", emoji: "🏎️", assetType: "stock", categories: ["popular"], source: "finnhub", sourceId: "RACE", description: "Luxury sports cars and racing.", about: about("Ferrari grew from racing into one of the world's most famous sports car brands.", [{ label: "Founded", value: "1947" }, { label: "From", value: "Italy" }, { label: "Makes", value: "Sports cars" }], [{ emoji: "🏁", text: "Racing is part of Ferrari's identity." }, { emoji: "⭐", text: "Its cars are rare, premium and instantly recognisable." }], "Ferrari's prancing horse logo came from an Italian pilot's symbol.") },
  { symbol: "BBW", name: "Build-A-Bear", ticker: "BBW", exchange: "NYSE", emoji: "🧸", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "BBW", description: "Stores where kids make stuffed toys.", about: about("Build-A-Bear turned buying a teddy into a fun experience where kids make their own.", [{ label: "Founded", value: "1997" }, { label: "From", value: "Missouri" }, { label: "Makes", value: "Stuffed toys" }], [{ emoji: "🧸", text: "Kids choose, stuff and dress their own bear." }, { emoji: "🎁", text: "It made a toy purchase feel like an event." }], "The idea came to its founder while shopping for toys with a young friend.") },
  { symbol: "EA", name: "Electronic Arts", ticker: "EA", exchange: "NASDAQ", emoji: "🎮", assetType: "stock", categories: ["games"], source: "finnhub", sourceId: "EA", description: "Video games and sports titles.", about: about("Electronic Arts makes huge video games, especially sports and life-simulation titles.", [{ label: "Founded", value: "1982" }, { label: "From", value: "California" }, { label: "Makes", value: "Video games" }], [{ emoji: "⚽", text: "Its sports games are played by millions every year." }, { emoji: "🏠", text: "The Sims let players build and run virtual lives." }], "EA was one of the first to treat game makers like creative stars.") },
  { symbol: "ABNB", name: "Airbnb", ticker: "ABNB", exchange: "NASDAQ", emoji: "🏠", assetType: "stock", categories: [], source: "finnhub", sourceId: "ABNB", description: "Travel stays hosted by people.", about: about("Airbnb let ordinary people rent out their homes to travellers around the world.", [{ label: "Founded", value: "2008" }, { label: "From", value: "California" }, { label: "Does", value: "Travel stays" }], [{ emoji: "🌍", text: "Travellers can stay in real homes instead of only hotels." }, { emoji: "🤝", text: "Anyone with a spare room can become a host." }], "The founders started by renting out air mattresses in their own flat.") },
  { symbol: "UBER", name: "Uber", ticker: "UBER", exchange: "NYSE", emoji: "🚗", assetType: "stock", categories: ["tech"], source: "finnhub", sourceId: "UBER", description: "Rides, deliveries and transport tech.", about: about("Uber made it possible to tap a phone and get a ride or a meal delivered.", [{ label: "Founded", value: "2009" }, { label: "From", value: "California" }, { label: "Does", value: "Rides & delivery" }], [{ emoji: "📱", text: "It turned getting a ride into a few taps." }, { emoji: "🍔", text: "It also delivers food through Uber Eats." }], "The idea came from struggling to find a taxi on a snowy night.") },
  { symbol: "V", name: "Visa", ticker: "V", exchange: "NYSE", emoji: "💳", assetType: "stock", categories: [], source: "finnhub", sourceId: "V", description: "Payment network used by cards.", about: about("Visa runs a giant network that lets cards pay shops almost anywhere in the world.", [{ label: "Founded", value: "1958" }, { label: "From", value: "California" }, { label: "Does", value: "Card payments" }], [{ emoji: "🌐", text: "It connects banks, shops and shoppers in seconds." }, { emoji: "⚡", text: "Payments move safely and very fast." }], "Visa does not lend you money itself; it moves the payment between banks.") },
  { symbol: "WMT", name: "Walmart", ticker: "WMT", exchange: "NYSE", emoji: "🛒", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "WMT", description: "Large shops and groceries.", about: about("Walmart grew from one discount store into one of the biggest shop chains in the world.", [{ label: "Founded", value: "1962" }, { label: "From", value: "Arkansas" }, { label: "Sells", value: "Almost everything" }], [{ emoji: "🏷️", text: "It became famous for low everyday prices." }, { emoji: "👷", text: "It is one of the largest employers anywhere." }], "Walmart started as a single small-town discount store.") },
  { symbol: "TGT", name: "Target", ticker: "TGT", exchange: "NYSE", emoji: "🎯", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "TGT", description: "Retail stores with home, clothes and food.", about: about("Target became known for mixing low prices with a more stylish shopping feel.", [{ label: "Founded", value: "1962" }, { label: "From", value: "Minnesota" }, { label: "Sells", value: "Home, clothes, food" }], [{ emoji: "🎯", text: "Its bullseye logo is easy to recognise." }, { emoji: "🛍️", text: "It blends value with design-led products." }], "Target grew out of an older department store company.") },
  { symbol: "GPRO", name: "GoPro", ticker: "GPRO", exchange: "NASDAQ", emoji: "📷", assetType: "stock", categories: [], source: "finnhub", sourceId: "GPRO", description: "Small cameras for action videos.", about: about("GoPro made tough little cameras that capture adventures like surfing, biking and skiing.", [{ label: "Founded", value: "2002" }, { label: "From", value: "California" }, { label: "Makes", value: "Action cameras" }], [{ emoji: "🏄", text: "Its cameras can film in places normal cameras cannot." }, { emoji: "🎥", text: "It helped start a wave of action videos online." }], "The founder invented it to film himself surfing.") },
  { symbol: "COST", name: "Costco", ticker: "COST", exchange: "NASDAQ", emoji: "🏬", assetType: "stock", categories: ["food"], source: "finnhub", sourceId: "COST", description: "Warehouse shops with memberships.", about: about("Costco sells goods in bulk at low prices to members who pay to shop there.", [{ label: "Founded", value: "1983" }, { label: "From", value: "Washington" }, { label: "Sells", value: "Bulk goods" }], [{ emoji: "📦", text: "Buying in bulk keeps prices low." }, { emoji: "🎫", text: "Shoppers pay a yearly membership to get in." }], "Costco is famous for a cheap hot-dog combo whose price has barely changed in decades.") },
  { symbol: "CBA", name: "Commonwealth Bank", ticker: "CBA", exchange: "ASX", emoji: "🏦", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "CBA.AX", description: "One of Australia's biggest banks.", about: about("Commonwealth Bank is one of Australia's largest banks, used by millions of people.", [{ label: "Founded", value: "1911" }, { label: "From", value: "Australia" }, { label: "Does", value: "Banking" }], [{ emoji: "🏦", text: "It looks after savings, loans and payments for many Australians." }, { emoji: "📱", text: "Its banking app is one of the most used in Australia." }], "It was once run by the government before becoming a public company.") },
  { symbol: "BHP", name: "BHP", ticker: "BHP", exchange: "ASX", emoji: "⛏️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "BHP.AX", description: "Australian mining and resources.", about: about("BHP is one of the world's biggest mining companies, digging up metals and minerals.", [{ label: "Founded", value: "1885" }, { label: "From", value: "Australia" }, { label: "Does", value: "Mining" }], [{ emoji: "⛏️", text: "It mines materials used to build almost everything." }, { emoji: "🌏", text: "It sells resources to factories around the world." }], "BHP started at an Australian place called Broken Hill.") },
  { symbol: "CSL", name: "CSL", ticker: "CSL", exchange: "ASX", emoji: "💉", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "CSL.AX", description: "Medicines, vaccines and blood products.", about: about("CSL makes important medicines and vaccines, including treatments made from blood plasma.", [{ label: "Founded", value: "1916" }, { label: "From", value: "Melbourne" }, { label: "Makes", value: "Medicines" }], [{ emoji: "💉", text: "Its products help treat serious illnesses." }, { emoji: "🔬", text: "It does a lot of medical research and science." }], "CSL began as an Australian government laboratory.") },
  { symbol: "WOW", name: "Woolworths", ticker: "WOW", exchange: "ASX", emoji: "🛒", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "WOW.AX", description: "Australian supermarkets.", about: about("Woolworths is one of Australia's biggest supermarket chains, selling groceries everywhere.", [{ label: "Founded", value: "1924" }, { label: "From", value: "Australia" }, { label: "Sells", value: "Groceries" }], [{ emoji: "🛒", text: "Most Australians shop at its stores." }, { emoji: "🚚", text: "It runs a huge delivery and supply network." }], "The Australian Woolworths is a separate company from the old overseas ones.") },
  { symbol: "WES", name: "Wesfarmers", ticker: "WES", exchange: "ASX", emoji: "🔨", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "WES.AX", description: "Owns businesses including Bunnings and Kmart.", about: about("Wesfarmers owns many everyday Australian stores, including Bunnings and Kmart.", [{ label: "Founded", value: "1914" }, { label: "From", value: "Australia" }, { label: "Does", value: "Owns retailers" }], [{ emoji: "🔨", text: "Bunnings is a favourite for tools and home projects." }, { emoji: "🛍️", text: "It owns several big shops people visit weekly." }], "Wesfarmers began as a cooperative to help farmers.") },
  { symbol: "TLS", name: "Telstra", ticker: "TLS", exchange: "ASX", emoji: "📡", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "TLS.AX", description: "Phones and internet networks.", about: about("Telstra runs one of Australia's biggest phone and internet networks.", [{ label: "Founded", value: "1975" }, { label: "From", value: "Australia" }, { label: "Does", value: "Phone & internet" }], [{ emoji: "📶", text: "Its network reaches across a very large country." }, { emoji: "📱", text: "It connects homes, phones and businesses." }], "Telstra was once part of Australia's postal and telegraph service.") },
  { symbol: "QAN", name: "Qantas", ticker: "QAN", exchange: "ASX", emoji: "✈️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "QAN.AX", description: "Australia's famous airline.", about: about("Qantas is one of the oldest airlines in the world and a symbol of Australia.", [{ label: "Founded", value: "1920" }, { label: "From", value: "Australia" }, { label: "Does", value: "Flying" }], [{ emoji: "✈️", text: "It flies people across Australia and around the globe." }, { emoji: "🦘", text: "Its kangaroo logo is known worldwide." }], "The name Qantas comes from the first letters of Queensland and Northern Territory Aerial Services.") },
  { symbol: "JBH", name: "JB Hi-Fi", ticker: "JBH", exchange: "ASX", emoji: "🎧", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "JBH.AX", description: "Electronics, games and music retail.", about: about("JB Hi-Fi is a popular Australian shop for gadgets, games, music and devices.", [{ label: "Founded", value: "1974" }, { label: "From", value: "Australia" }, { label: "Sells", value: "Electronics" }], [{ emoji: "🎮", text: "It is a go-to store for games and tech." }, { emoji: "🎧", text: "It started with music and grew into all electronics." }], "JB Hi-Fi began as a single hi-fi and record store.") },
  { symbol: "DMP", name: "Domino's AU", ticker: "DMP", exchange: "ASX", emoji: "🍕", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "DMP.AX", description: "Pizza stores in Australia and beyond.", about: about("This Australian company runs Domino's pizza stores across Australia and several other countries.", [{ label: "Founded", value: "1983" }, { label: "From", value: "Australia" }, { label: "Sells", value: "Pizza" }], [{ emoji: "🍕", text: "It runs hundreds of pizza stores overseas." }, { emoji: "📲", text: "It is known for clever online ordering and tech." }], "It is a separate company that runs the Domino's brand outside the United States.") },
  { symbol: "A2M", name: "a2 Milk", ticker: "A2M", exchange: "ASX", emoji: "🥛", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "A2M.AX", description: "Milk and infant nutrition products.", about: about("The a2 Milk Company sells milk and baby formula built around a particular milk protein.", [{ label: "Founded", value: "2000" }, { label: "From", value: "New Zealand" }, { label: "Sells", value: "Milk products" }], [{ emoji: "🥛", text: "It focuses on a specific type of milk protein." }, { emoji: "🍼", text: "Its baby formula became very popular in Asia." }], "The whole company was built around one special kind of milk.") },
  { symbol: "COL", name: "Coles", ticker: "COL", exchange: "ASX", emoji: "🛒", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "COL.AX", description: "Australian supermarkets and groceries.", about: about("Coles is one of Australia's two biggest supermarket chains.", [{ label: "Founded", value: "1914" }, { label: "From", value: "Australia" }, { label: "Sells", value: "Groceries" }], [{ emoji: "🛒", text: "Millions of Australians shop there each week." }, { emoji: "🚚", text: "It runs a big network of stores and deliveries." }], "Coles began as a single store in Melbourne.") },
  { symbol: "RIO", name: "Rio Tinto", ticker: "RIO", exchange: "ASX", emoji: "⛏️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "RIO.AX", description: "Mining and metals company.", about: about("Rio Tinto is one of the world's largest mining companies, digging up metals and minerals.", [{ label: "Founded", value: "1873" }, { label: "From", value: "Australia & UK" }, { label: "Does", value: "Mining" }], [{ emoji: "⛏️", text: "It mines materials used to make cars, buildings and gadgets." }, { emoji: "🌏", text: "It ships resources all over the world." }], "Rio Tinto is named after a river in Spain where it first mined.") },
  { symbol: "FMG", name: "Fortescue", ticker: "FMG", exchange: "ASX", emoji: "⛏️", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "FMG.AX", description: "Iron ore and green energy projects.", about: about("Fortescue grew quickly into a major iron ore miner and is now investing in green energy.", [{ label: "Founded", value: "2003" }, { label: "From", value: "Australia" }, { label: "Does", value: "Mining & energy" }], [{ emoji: "⛏️", text: "It became a big iron ore exporter in a short time." }, { emoji: "🌱", text: "It is working on cleaner, greener energy." }], "Fortescue grew from a small start-up into a giant miner in only a couple of decades.") },
  { symbol: "XRO", name: "Xero", ticker: "XRO", exchange: "ASX", emoji: "📊", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "XRO.AX", description: "Accounting software for small businesses.", about: about("Xero makes cloud accounting software that helps small businesses manage their money.", [{ label: "Founded", value: "2006" }, { label: "From", value: "New Zealand" }, { label: "Makes", value: "Accounting apps" }], [{ emoji: "📊", text: "It moved business bookkeeping onto the cloud." }, { emoji: "💼", text: "Lots of small businesses use it every day." }], "Xero started in New Zealand and grew across many countries.") },
  { symbol: "COH", name: "Cochlear", ticker: "COH", exchange: "ASX", emoji: "👂", assetType: "stock", categories: ["australian"], source: "yahoo", sourceId: "COH.AX", description: "Hearing implant technology.", about: about("Cochlear makes implants that help people who are deaf or hard of hearing to hear sounds.", [{ label: "Founded", value: "1981" }, { label: "From", value: "Australia" }, { label: "Makes", value: "Hearing implants" }], [{ emoji: "👂", text: "Its implants have helped people hear for the first time." }, { emoji: "🔬", text: "It grew from Australian medical research." }], "Cochlear's technology is often called the bionic ear.") },
  { symbol: "BTC", name: "Bitcoin", ticker: "BTC", exchange: "Crypto", emoji: "₿", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "bitcoin", description: "The first and most famous digital money.", about: about("Bitcoin is the world's first digital money. In 2009 an inventor known only as \"Satoshi Nakamoto\" launched it as money no single bank or country controls.", [{ label: "Started", value: "2009" }, { label: "Type", value: "Cryptocurrency" }, { label: "Max ever", value: "21 million" }], [{ emoji: "🌍", text: "Anyone, anywhere can send it directly to anyone else - no bank in the middle." }, { emoji: "🔒", text: "Protected by very hard maths, so it is extremely hard to fake." }, { emoji: "💎", text: "There will only ever be 21 million, so some treat it like digital gold." }], "The very first thing bought with Bitcoin was two pizzas - for 10,000 coins!") },
  { symbol: "ETH", name: "Ethereum", ticker: "ETH", exchange: "Crypto", emoji: "Ξ", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "ethereum", description: "Digital money plus programmable apps.", about: about("Ethereum is a crypto network that can run small programs called smart contracts.", [{ label: "Started", value: "2015" }, { label: "Type", value: "Crypto network" }, { label: "Token", value: "Ether" }], [{ emoji: "🧩", text: "Builders can create apps that run on the network." }, { emoji: "🎨", text: "Many digital collectibles first became popular on Ethereum." }], "Ethereum changed its system in 2022 to use much less energy.") },
  { symbol: "DOGE", name: "Dogecoin", ticker: "DOGE", exchange: "Crypto", emoji: "🐶", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "dogecoin", description: "A joke coin that became famous online.", about: about("Dogecoin began as a funny internet coin and grew because communities loved sharing it.", [{ label: "Started", value: "2013" }, { label: "Type", value: "Meme coin" }, { label: "Mascot", value: "Shiba Inu" }], [{ emoji: "😂", text: "It showed internet communities can move markets." }, { emoji: "💬", text: "People often use it to learn how crypto works." }], "Dogecoin's mascot came from a famous internet meme.") },
  { symbol: "SOL", name: "Solana", ticker: "SOL", exchange: "Crypto", emoji: "◎", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "solana", description: "A fast crypto network for apps.", about: about("Solana is designed to process lots of crypto transactions quickly.", [{ label: "Started", value: "2020" }, { label: "Type", value: "Crypto network" }, { label: "Known for", value: "Speed" }], [{ emoji: "⚡", text: "It aims to make transactions fast and cheap." }, { emoji: "🧱", text: "Developers use it to build games, finance tools and collectibles." }], "Solana's name was inspired by a beach town in California.") },
  { symbol: "ADA", name: "Cardano", ticker: "ADA", exchange: "Crypto", emoji: "🔷", assetType: "crypto", categories: ["crypto"], source: "coingecko", sourceId: "cardano", description: "A research-focused crypto network.", about: about("Cardano is a crypto network built with a careful research-first style.", [{ label: "Started", value: "2017" }, { label: "Type", value: "Crypto network" }, { label: "Token", value: "ADA" }], [{ emoji: "📚", text: "Its builders emphasise academic review and planning." }, { emoji: "🌱", text: "It uses a lower-energy proof-of-stake design." }], "ADA is named after Ada Lovelace, an early computing pioneer.") },
];

export const ASSET_CATEGORIES: { key: "all" | AssetCategory; label: string }[] = [
  { key: "all", label: "All" },
  { key: "popular", label: "⭐ Popular" },
  { key: "games", label: "🎮 Games" },
  { key: "tech", label: "💻 Tech" },
  { key: "food", label: "🍔 Food & Shops" },
  { key: "australian", label: "🇦🇺 Australian" },
  { key: "crypto", label: "🪙 Crypto" },
];

export function getAsset(symbol: string): RealAsset | undefined {
  return REAL_ASSETS.find((asset) => asset.symbol === symbol);
}
