import type { InvestQuizQuestion, Lesson } from "@/lib/domain/types";

export const LICENCE_PASS_THRESHOLD = 4;
export const SMART_INVESTOR_SPARKS = 50;

export const LESSONS: Lesson[] = [
  {
    id: "what-is-investing",
    section: "basics",
    required: true,
    order: 1,
    title: "What is investing?",
    emoji: "💡",
    minutes: 2,
    blurb: "Use money today to try to grow it for the future.",
    body: [
      { kind: "para", text: "Investing means choosing something that might become worth more over time. You are not buying a toy to use today; you are buying a tiny piece of value that can move up or down." },
      { kind: "illustration", emoji: "🌱", caption: "Like planting a seed, investing needs time and care." },
      { kind: "keyIdea", text: "Investing is for money you can leave alone, not money you need straight away." },
      { kind: "example", emoji: "📦", text: "If you invest $2 in a company, your $2 follows that company's real price. It might grow, shrink, or stay almost the same." },
      { kind: "didYouKnow", text: "Adults often invest slowly over years, not because every day is exciting, but because time can help good choices grow." },
    ],
    check: { question: "What is investing mostly about?", options: ["Trying to grow money over time", "Spending money as fast as possible", "Guessing a secret code"], correctIndex: 0, correctNote: "Right. Investing is about giving money time to work, while accepting risk." },
  },
  {
    id: "what-is-a-stock",
    section: "basics",
    required: true,
    order: 2,
    title: "What is a stock?",
    emoji: "🍕",
    minutes: 3,
    blurb: "A stock is a tiny slice of a real company.",
    body: [
      { kind: "para", text: "Imagine a giant pizza. If the pizza is a company, one tiny slice is like one stock share." },
      { kind: "para", text: "When you own stock, you own a tiny piece of that company. If people think the company is doing well, the price of that tiny piece can go up. If people worry, it can go down." },
      { kind: "illustration", emoji: "🍕", caption: "A share is a small slice of the company pizza." },
      { kind: "keyIdea", text: "Buying a stock means buying a small piece of a real business, not just a number on a screen." },
      { kind: "example", emoji: "🍎", text: "If you buy Apple stock, your investment follows how investors value Apple as a business." },
      { kind: "didYouKnow", text: "Some companies have millions or billions of shares, so even a tiny investor can own a tiny piece." },
    ],
    check: { question: "A stock is most like...", options: ["A tiny piece of a company", "A password", "A shop receipt"], correctIndex: 0, correctNote: "Exactly. It is a tiny ownership slice." },
  },
  {
    id: "what-is-crypto",
    section: "basics",
    required: true,
    order: 3,
    title: "What is crypto?",
    emoji: "🔐",
    minutes: 3,
    blurb: "Digital assets protected by computer networks.",
    body: [
      { kind: "para", text: "Crypto is a kind of digital asset. Instead of one company or bank keeping the list, many computers help check the records." },
      { kind: "para", text: "Some crypto is used like digital money. Some is used to power apps. Crypto prices can move very fast, so it is extra risky." },
      { kind: "illustration", emoji: "🧮", caption: "Lots of computers agree on the same record book." },
      { kind: "keyIdea", text: "Crypto can be interesting technology, but it can also be much bumpier than many stocks." },
      { kind: "example", emoji: "₿", text: "Bitcoin is the oldest famous crypto. Ethereum is a network where builders can make apps." },
      { kind: "didYouKnow", text: "Crypto markets trade all day and all night, even on weekends." },
    ],
    check: { question: "Why should crypto be treated carefully?", options: ["Prices can change very quickly", "It never changes price", "It is always safer than cash"], correctIndex: 0, correctNote: "Correct. Big moves are possible in both directions." },
  },
  {
    id: "why-prices-move",
    section: "basics",
    required: true,
    order: 4,
    title: "Why prices go up & down",
    emoji: "📈",
    minutes: 3,
    blurb: "Prices move when buyers and sellers change their minds.",
    body: [
      { kind: "para", text: "A price is what buyers and sellers agree on right now. If more people want to buy than sell, the price often rises. If more people want to sell than buy, it often falls." },
      { kind: "illustration", emoji: "⚖️", caption: "Price is a balance between demand and supply." },
      { kind: "keyIdea", text: "A good company can still have a bad day in the market, and a risky asset can still jump up for a while." },
      { kind: "example", emoji: "🎮", text: "If a game company releases a hit game, more investors may want the stock. If the game disappoints, some may sell." },
      { kind: "didYouKnow", text: "News, earnings, interest rates, trends and feelings can all affect prices." },
    ],
    check: { question: "If lots more people want to buy an asset, what often happens?", options: ["The price can go up", "The price must become zero", "The market closes forever"], correctIndex: 0, correctNote: "Yes. More demand can push prices higher." },
  },
  {
    id: "diversify",
    section: "deeper",
    required: false,
    order: 5,
    title: "Don't put all eggs in one basket",
    emoji: "🧺",
    minutes: 2,
    blurb: "Spread risk instead of betting everything on one idea.",
    body: [
      { kind: "para", text: "Diversifying means owning more than one kind of investment. If one has a bad day, another might be steadier." },
      { kind: "keyIdea", text: "Spreading money around can make surprises less painful." },
      { kind: "example", emoji: "🍎", text: "A mix of a tech company, a food company and a small amount of crypto is less all-or-nothing than only one coin." },
      { kind: "didYouKnow", text: "Big investors often use baskets of many companies because nobody can predict every winner." },
    ],
  },
  {
    id: "slow-and-steady",
    section: "deeper",
    required: false,
    order: 6,
    title: "Slow and steady wins",
    emoji: "🐢",
    minutes: 2,
    blurb: "Small, patient choices can beat wild guessing.",
    body: [
      { kind: "para", text: "Investing does not need to be a race. Many people invest small amounts regularly and let time do the heavy lifting." },
      { kind: "keyIdea", text: "Patience is a skill. Checking prices every minute can make normal bumps feel scary." },
      { kind: "example", emoji: "📅", text: "Putting in $1 every week teaches a different habit from trying to guess the perfect day." },
      { kind: "didYouKnow", text: "Markets have had many scary drops, but patient long-term investors focus on plans, not panic." },
    ],
  },
  {
    id: "you-can-lose",
    section: "safe",
    required: false,
    order: 7,
    title: "You can lose money too",
    emoji: "⚠️",
    minutes: 2,
    blurb: "Real investing has real ups and downs.",
    body: [
      { kind: "para", text: "In Invest, your cash follows real prices. If you buy something and the price falls, your investment is worth less." },
      { kind: "keyIdea", text: "Never invest money you need for something important soon." },
      { kind: "example", emoji: "💵", text: "If you invest $5 and the price falls 20%, it may be worth about $4 before it recovers, if it recovers." },
      { kind: "didYouKnow", text: "Losing a small amount while learning can teach a useful lesson before the amounts become bigger." },
    ],
  },
  {
    id: "think-before-buying",
    section: "safe",
    required: false,
    order: 8,
    title: "Think before you buy",
    emoji: "🧠",
    minutes: 2,
    blurb: "Have a reason, not just a feeling.",
    body: [
      { kind: "para", text: "Before buying, ask: What does this company or coin do? Why do I think it could do well? What could go wrong?" },
      { kind: "keyIdea", text: "A cool logo, a friend talking about it, or a sudden jump is not enough by itself." },
      { kind: "example", emoji: "🔎", text: "Read the About section, check the price move, and decide whether the risk fits your plan." },
      { kind: "didYouKnow", text: "Some of the best investing decisions are the ones where you choose to wait." },
    ],
  },
];

export const REQUIRED_LESSON_IDS = LESSONS.filter((lesson) => lesson.required).map((lesson) => lesson.id);

export const LICENCE_QUIZ: InvestQuizQuestion[] = [
  { id: "demand-price", question: "Lots of people suddenly want to buy the same stock. What can happen to its price?", options: ["It can go up", "It must disappear", "It can never change", "It turns into cash"], correctIndex: 0, explainer: "Why? When demand is higher than supply, buyers may offer more, so the price can rise." },
  { id: "stock-slice", question: "What do you own when you buy a stock?", options: ["A tiny piece of a company", "A guaranteed prize", "A bank password", "A toy version of the company"], correctIndex: 0, explainer: "A stock is a small ownership slice of a real business." },
  { id: "crypto-risk", question: "Why should you be extra careful with crypto?", options: ["It can move up and down very quickly", "It is always the safest asset", "It only opens on Mondays", "It never loses value"], correctIndex: 0, explainer: "Crypto can be exciting technology, but the prices can be very bumpy." },
  { id: "diversify-meaning", question: "What does diversifying mean?", options: ["Spreading money across different investments", "Putting every cent in one idea", "Buying only the asset with the funniest emoji", "Selling everything every day"], correctIndex: 0, explainer: "Diversifying spreads risk so one bad result hurts less." },
  { id: "need-soon", question: "What should you do with money you need very soon?", options: ["Keep it safe instead of investing it", "Put it all in the riskiest thing", "Hide the price from yourself", "Only buy after a big jump"], correctIndex: 0, explainer: "Investing is for money that can handle ups and downs over time." },
];

export const GLOSSARY: { term: string; definition: string }[] = [
  { term: "Asset", definition: "Something with value, like a stock, crypto coin or cash." },
  { term: "Share", definition: "A tiny ownership piece of a company." },
  { term: "Portfolio", definition: "All your investments added together." },
  { term: "Diversify", definition: "Spread money across different investments." },
  { term: "Profit", definition: "Money gained after selling for more than you paid." },
  { term: "Loss", definition: "Money lost after selling for less than you paid." },
  { term: "Risk", definition: "The chance that an investment does worse than you hoped." },
];
