import type { Lesson, LessonDraft } from "../types";

// Coral, the Sea Wizard. Calm, wavy, gentle as a lapping tide.
const drafts: LessonDraft[] = [
  {
    id: "coral-glowing-jellyfish",
    title: "Glowing Jellyfish",
    emoji: "🪼",
    lines: [
      "Mmm, little wave... some jellyfish can glow in the dark sea, like floating lanterns.",
      "Making your own light is called bioluminescence. Lots of deep-sea creatures can do it.",
      "Jellyfish have no brain, no heart and no bones. They're mostly water!",
    ],
    quiz: {
      q: "What's it called when an animal makes its own light?",
      options: ["Bioluminescence", "Sunburn", "Reflection"],
      answer: 0,
      explain: "Bioluminescence! A big word for a beautiful glow.",
    },
  },
  {
    id: "coral-octopus-disguise",
    title: "The Octopus Disguise",
    emoji: "🐙",
    lines: [
      "The octopus is the ocean's best hider.",
      "In a blink, it can change the colour of its skin, and even make it bumpy like a rock or smooth like sand.",
      "If a hungry fish still finds it, the octopus squirts a cloud of ink and zooms away.",
    ],
    tryIt: "Play octopus hide-and-seek: hide a toy where it blends in. Can someone find it?",
    quiz: {
      q: "What does an octopus squirt to escape?",
      options: ["A cloud of ink", "Bubblegum", "Hot water"],
      answer: 0,
      explain: "A cloud of ink! Then it slips away.",
    },
  },
  {
    id: "coral-humpback-songs",
    title: "The Humpback Highway",
    emoji: "🐋",
    lines: [
      "Every year, humpback whales swim along Australia's coasts. People call it the humpback highway.",
      "They travel north to warm waters in winter to have their babies, then swim back south to feed.",
      "Male humpbacks sing long, beautiful songs that can travel a long way underwater. Listen...",
    ],
    funFact: "From about May to November, you might see humpbacks from the shore on Australia's east and west coasts.",
    quiz: {
      q: "Why do humpbacks swim north in winter?",
      options: ["To have their babies in warm water", "To go shopping", "To find snow"],
      answer: 0,
      explain: "Warm water is a cosy place for baby whales.",
    },
  },
  {
    id: "coral-whale-blowhole",
    title: "Whales Breathe Air",
    emoji: "💨",
    lines: [
      "Whales live in the sea, but they aren't fish. They're mammals, like us!",
      "They breathe air through a blowhole on top of their head, so they have to swim up to breathe.",
      "When a whale breathes out, it sends up a big misty spout. Whoooosh!",
    ],
    tryIt: "Take a big breath, hold it for three seconds, then blow it out like a whale spout!",
    quiz: {
      q: "How do whales breathe?",
      options: ["Through a blowhole", "Through gills", "They don't breathe"],
      answer: 0,
      explain: "Through a blowhole on top of their head!",
    },
  },
  {
    id: "coral-shark-skeleton",
    title: "Sharks Have No Bones",
    emoji: "🦈",
    lines: [
      "Sharks don't have bones at all!",
      "Their skeleton is made of cartilage. That's the bendy stuff in your ears and the tip of your nose.",
      "Sharks have been swimming in the oceans for more than 400 million years, since long before dinosaurs.",
    ],
    tryIt: "Gently wiggle the tip of your nose. That's cartilage, like a shark's skeleton!",
    quiz: {
      q: "What is a shark's skeleton made of?",
      options: ["Cartilage", "Wood", "Metal"],
      answer: 0,
      explain: "Cartilage! Bendy, like your ears.",
    },
  },
  {
    id: "coral-shark-teeth",
    title: "Endless Shark Teeth",
    emoji: "🦷",
    lines: [
      "When you lose a tooth, a new one grows once. But sharks keep growing new teeth their whole lives!",
      "They have rows of teeth waiting behind the front ones, ready to move forward like a conveyor belt.",
      "Some sharks lose thousands of teeth in their lifetime. Imagine the tooth fairy's job!",
    ],
    quiz: {
      q: "What happens when a shark loses a tooth?",
      options: ["A new one moves forward", "It has a gap forever", "It gets a gold tooth"],
      answer: 0,
      explain: "A new tooth moves up from the row behind!",
    },
  },
  {
    id: "coral-turtle-homecoming",
    title: "Turtles Come Home",
    emoji: "🐢",
    lines: [
      "Six of the world's seven kinds of sea turtles can be found in Australian waters.",
      "When a mother turtle is ready to lay eggs, she often swims all the way back to the beach where she hatched.",
      "Baby turtles head for the sea at night. Bright lights on the beach can confuse them, so we keep beaches dark.",
    ],
    quiz: {
      q: "Where does a mother sea turtle often lay her eggs?",
      options: ["On the beach where she hatched", "In a tree", "On a boat"],
      answer: 0,
      explain: "She often swims back to the very beach where she hatched!",
    },
  },
  {
    id: "coral-turtles-and-plastic",
    title: "Bags Look Like Jellyfish",
    emoji: "🛍️",
    lines: [
      "Sea turtles love to eat jellyfish.",
      "But a floating plastic bag looks a lot like a jellyfish, and turtles can eat it by mistake. That makes them very sick.",
      "Using reusable bags and putting rubbish in the bin helps keep turtles safe.",
    ],
    tryIt: "Remind your grown-up to bring reusable bags to the shops.",
    quiz: {
      q: "Why are plastic bags dangerous for turtles?",
      options: ["They look like jellyfish", "They're too heavy", "They're scary"],
      answer: 0,
      explain: "Turtles can mistake them for jellyfish and eat them.",
    },
  },
  {
    id: "coral-coral-is-alive",
    title: "Coral Is Alive!",
    emoji: "🪸",
    lines: [
      "Coral might look like colourful rocks or plants. But it's actually made of tiny animals!",
      "Each little animal is called a polyp. They're related to jellyfish.",
      "Millions of polyps build hard skeletons together, and over many years they make a coral reef.",
    ],
    quiz: {
      q: "What is coral made of?",
      options: ["Tiny animals called polyps", "Plastic", "Seaweed"],
      answer: 0,
      explain: "Polyps! Tiny animals that build reefs together.",
    },
  },
  {
    id: "coral-great-barrier-reef",
    title: "The Great Barrier Reef",
    emoji: "🐠",
    lines: [
      "Off the coast of Queensland lies the Great Barrier Reef, the biggest coral reef system in the world!",
      "It stretches more than 2,300 kilometres, and it's made of thousands of separate reefs.",
      "It's so big that astronauts can see it from space. And it's home to thousands of kinds of sea life.",
    ],
    tryIt: "Find the Great Barrier Reef on a map of Australia. Trace how long it is!",
    quiz: {
      q: "Which Australian state is the Great Barrier Reef next to?",
      options: ["Queensland", "Tasmania", "Victoria"],
      answer: 0,
      explain: "Queensland! It stretches along much of the coast.",
    },
  },
  {
    id: "coral-bleaching",
    title: "Why Coral Turns White",
    emoji: "🤍",
    lines: [
      "Coral gets its bright colours from tiny algae that live inside it and help feed it.",
      "When the sea gets too warm for too long, coral pushes the algae out and turns white. This is called bleaching.",
      "Bleached coral is stressed and hungry. If the water cools down in time, it can recover.",
    ],
    age: "8+",
    quiz: {
      q: "What can cause coral bleaching?",
      options: ["Water that's too warm for too long", "Too many fish", "Moonlight"],
      answer: 0,
      explain: "Warm water stresses coral, and it loses its colourful algae.",
    },
  },
  {
    id: "coral-clownfish",
    title: "Clownfish and Anemones",
    emoji: "🐡",
    lines: [
      "Clownfish live among the waving arms of sea anemones.",
      "Anemones sting most fish, but clownfish have a special slimy coat that protects them.",
      "The anemone keeps the clownfish safe, and the clownfish helps keep the anemone clean. Good friends!",
    ],
    funFact: "Clownfish are all born male. The biggest one in a group can change to become the female!",
    quiz: {
      q: "Why don't anemones sting clownfish?",
      options: ["Clownfish have a special slimy coat", "Anemones are asleep", "Clownfish are too fast"],
      answer: 0,
      explain: "Their slimy coat protects them from stings!",
    },
  },
  {
    id: "coral-tides",
    title: "The Moon Pulls the Tides",
    emoji: "🌊",
    lines: [
      "Have you noticed the sea creeps up the beach, then slides back down, during the day?",
      "That's the tide! The Moon's gravity gently tugs on the oceans, making them bulge.",
      "Most beaches have two high tides and two low tides each day.",
    ],
    age: "8+",
    quiz: {
      q: "What mostly causes the tides?",
      options: ["The Moon's gravity", "Wind", "Big fish"],
      answer: 0,
      explain: "The Moon's gravity tugs on the sea!",
    },
  },
  {
    id: "coral-swim-between-flags",
    title: "Swim Between the Flags",
    emoji: "🚩",
    lines: [
      "At Aussie beaches, lifesavers put up red and yellow flags.",
      "The flags mark the safest place to swim, where lifesavers are watching.",
      "Always swim between the flags, with a grown-up. If there are no flags, stay out of the water.",
    ],
    tryIt: "On your next beach trip, spot the red and yellow flags before anyone swims.",
    quiz: {
      q: "Where is the safest place to swim at the beach?",
      options: ["Between the red and yellow flags", "Far from everyone", "Near the rocks"],
      answer: 0,
      explain: "Between the flags, where lifesavers are watching.",
    },
  },
  {
    id: "coral-rip-currents",
    title: "Rips and What to Do",
    emoji: "🏊",
    lines: [
      "A rip is a strong current that pulls water, and swimmers, away from the beach. It can look like a calm, dark gap between waves.",
      "If you get caught in a rip, stay calm and float. Don't fight it.",
      "Raise one arm high and wave for help. Lifesavers are trained to come and get you.",
    ],
    quiz: {
      q: "If you're caught in a rip, what should you do?",
      options: ["Stay calm, float and raise an arm", "Swim hard against it", "Dive to the bottom"],
      answer: 0,
      explain: "Float, raise an arm and signal for help.",
    },
  },
  {
    id: "coral-bluebottles",
    title: "Beware the Bluebottle",
    emoji: "🔵",
    lines: [
      "Bluebottles look like pretty little blue balloons washed up on the sand.",
      "But their long blue tentacles can sting, even when they're lying on the beach!",
      "Never touch them. If you get stung, tell a lifesaver or a grown-up. They know the right first aid.",
    ],
    quiz: {
      q: "Is it safe to touch a bluebottle on the sand?",
      options: ["No, it can still sting", "Yes, it's asleep", "Yes, if you're quick"],
      answer: 0,
      explain: "No! Even washed-up bluebottles can sting.",
    },
  },
  {
    id: "coral-rock-pools",
    title: "Rock Pool Rules",
    emoji: "🦀",
    lines: [
      "Rock pools are tiny worlds full of crabs, snails and sea stars. Look closely, but gently.",
      "Never touch an octopus. The tiny blue-ringed octopus lives in Aussie rock pools and is very venomous.",
      "Don't pick up shells with animals inside. If you lift a rock, put it back just how you found it.",
    ],
    tryIt: "On your next beach trip, count how many creatures you can spot in a rock pool, hands off.",
    quiz: {
      q: "Which rock pool creature should you never touch?",
      options: ["The blue-ringed octopus", "A piece of seaweed you see", "The water"],
      answer: 0,
      explain: "Never touch any octopus, especially the blue-ringed one.",
    },
  },
  {
    id: "coral-seahorse-dads",
    title: "Seahorse Dads",
    emoji: "🐴",
    lines: [
      "Seahorses have a very special family secret.",
      "The mum puts her eggs into a pouch on the dad's tummy, and the dad carries them!",
      "When they're ready, the dad gives birth to lots of tiny baby seahorses. What a dad!",
    ],
    quiz: {
      q: "Which seahorse parent carries the babies?",
      options: ["The dad", "The mum", "A crab"],
      answer: 0,
      explain: "The dad! In a pouch on his tummy.",
    },
  },
  {
    id: "coral-sea-stars",
    title: "Sea Stars Aren't Fish",
    emoji: "⭐",
    lines: [
      "People call them starfish, but they aren't fish at all! Scientists call them sea stars.",
      "They have no brain and no blood. Instead, seawater flows through their bodies.",
      "And many can grow back a lost arm. Slowly, slowly... a new one appears.",
    ],
    funFact: "Many sea stars have a tiny eye at the tip of each arm!",
    quiz: {
      q: "Are starfish really fish?",
      options: ["No, they're sea stars", "Yes", "They're birds"],
      answer: 0,
      explain: "Not fish at all! That's why we say sea stars.",
    },
  },
  {
    id: "coral-dolphin-sleep",
    title: "How Dolphins Sleep",
    emoji: "🐬",
    lines: [
      "Dolphins breathe air, so they can't fall fast asleep underwater like we do in bed.",
      "Instead, they rest one half of their brain at a time!",
      "The awake half helps them swim up to breathe and watch for danger. Clever and sleepy!",
    ],
    quiz: {
      q: "How do dolphins sleep?",
      options: ["One half of the brain at a time", "Upside down on the sand", "They never rest"],
      answer: 0,
      explain: "Half a brain at a time, so they can still breathe.",
    },
  },
  {
    id: "coral-plankton",
    title: "Tiny Plankton, Big Job",
    emoji: "🦠",
    lines: [
      "The sea is full of plankton: tiny living things that drift along with the water.",
      "Many are so small you need a microscope to see them. Yet they're food for fish, and even for giant whales!",
      "Tiny plant-like plankton also make about half of the oxygen we breathe. Thank you, plankton!",
    ],
    age: "8+",
    quiz: {
      q: "What do tiny plant-like plankton make that we breathe?",
      options: ["Oxygen", "Smoke", "Salt"],
      answer: 0,
      explain: "Oxygen! About half of it.",
    },
  },
  {
    id: "coral-salty-sea",
    title: "Why the Sea Is Salty",
    emoji: "🧂",
    lines: [
      "Rain washes tiny bits of salt out of rocks and soil, and rivers carry them to the sea.",
      "The Sun warms the sea and water floats up into the sky, but the salt stays behind.",
      "Over a very long time, the salt has built up. That's why the sea tastes salty!",
    ],
    age: "8+",
    quiz: {
      q: "Where does the sea's salt come from?",
      options: ["Rocks and soil, carried by rivers", "Fish sprinkle it", "Chips"],
      answer: 0,
      explain: "From rocks and soil, washed down by rivers over ages.",
    },
  },
  {
    id: "coral-deepest-place",
    title: "The Deepest Place",
    emoji: "⬇️",
    lines: [
      "The deepest part of the ocean is in the Mariana Trench, in the Pacific Ocean.",
      "It's about 11 kilometres deep. If you dropped Mount Everest in, its top would still be under water!",
      "Down there, it's pitch black and freezing cold, yet small creatures still live there.",
    ],
    quiz: {
      q: "What's the deepest part of the ocean called?",
      options: ["The Mariana Trench", "The Sandy Shallows", "The Kiddie Pool"],
      answer: 0,
      explain: "The Mariana Trench, about 11 kilometres deep!",
    },
  },
  {
    id: "coral-anglerfish",
    title: "The Anglerfish's Lantern",
    emoji: "🎣",
    lines: [
      "In the dark deep sea lives the anglerfish.",
      "It has a glowing lure dangling in front of its face, like a fishing rod with a light on the end!",
      "Little fish swim towards the glow, and... gulp! Dinner is served.",
    ],
    quiz: {
      q: "What does the anglerfish use to catch food?",
      options: ["A glowing lure", "A net", "A spoon"],
      answer: 0,
      explain: "A glowing lure, like a light on a fishing rod!",
    },
  },
  {
    id: "coral-dugongs",
    title: "Gentle Dugongs",
    emoji: "🌱",
    lines: [
      "Dugongs are gentle sea mammals, sometimes called sea cows.",
      "They graze on seagrass meadows on the sea floor, just like cows munch grass.",
      "Their closest living relatives are elephants! Many dugongs live in the warm waters of northern Australia.",
    ],
    quiz: {
      q: "What do dugongs eat?",
      options: ["Seagrass", "Sharks", "Pizza"],
      answer: 0,
      explain: "Seagrass! They're gentle grazers.",
    },
  },
  {
    id: "coral-mangroves",
    title: "Magic Mangroves",
    emoji: "🌳",
    lines: [
      "Mangroves are special trees that grow in salty water along the coast.",
      "Their tangled roots are like a nursery, where baby fish and crabs hide and grow.",
      "Mangroves also protect the coast from big waves and storms.",
    ],
    quiz: {
      q: "What do mangrove roots do for baby fish?",
      options: ["Give them a safe place to hide and grow", "Eat them", "Nothing"],
      answer: 0,
      explain: "They're a safe nursery for baby sea creatures!",
    },
  },
  {
    id: "coral-hermit-crabs",
    title: "Hermit Crab House Swap",
    emoji: "🐚",
    lines: [
      "Hermit crabs have a soft, squishy tail, so they live inside empty shells for protection.",
      "When a hermit crab grows too big for its shell, it goes looking for a bigger one.",
      "It checks the new shell carefully, then quickly moves house. Snug!",
    ],
    funFact: "Sometimes hermit crabs line up biggest to smallest and all swap shells at once!",
    quiz: {
      q: "What does a hermit crab do when it outgrows its shell?",
      options: ["Finds a bigger shell", "Stays squished", "Grows a new one"],
      answer: 0,
      explain: "It moves house into a bigger shell!",
    },
  },
  {
    id: "coral-sea-lions",
    title: "Sea Lion or Seal?",
    emoji: "🦭",
    lines: [
      "Sea lions and seals look similar, but here's how to tell them apart.",
      "Sea lions have little ear flaps and can walk on their flippers. Seals have just ear holes and wriggle on their tummies.",
      "The Australian sea lion is found only in Australia, along our southern and western coasts.",
    ],
    age: "8+",
    quiz: {
      q: "Which one has little ear flaps?",
      options: ["Sea lions", "Seals", "Sea stars"],
      answer: 0,
      explain: "Sea lions! Seals only have small ear holes.",
    },
  },
  {
    id: "coral-seadragons",
    title: "Secret Seadragons",
    emoji: "🐉",
    lines: [
      "Weedy and leafy seadragons are relatives of seahorses.",
      "They're covered in leafy frills, so they look just like floating seaweed. Can you spot one?",
      "They live only in the cool waters of southern Australia, and nowhere else in the world!",
    ],
    quiz: {
      q: "Why do leafy seadragons look like seaweed?",
      options: ["To hide from danger", "They're made of seaweed", "They're sick"],
      answer: 0,
      explain: "Their leafy frills help them hide. Clever camouflage!",
    },
  },
  {
    id: "coral-take-three",
    title: "Take Three for the Sea",
    emoji: "🗑️",
    lines: [
      "Rubbish on beaches can wash into the sea and hurt animals.",
      "Here's a simple habit: whenever you visit the beach, a river or a park, pick up three pieces of rubbish.",
      "Only pick up safe things like wrappers, never glass or sharp things. And wash your hands afterwards!",
    ],
    tryIt: "Next time you're at the park or beach, take three pieces of rubbish to the bin.",
    quiz: {
      q: "How many bits of rubbish do you pick up in 'Take Three'?",
      options: ["Three", "None", "A hundred"],
      answer: 0,
      explain: "Three! Small habits make a big splash.",
    },
  },
  {
    id: "coral-drains-to-sea",
    title: "Drains Lead to the Sea",
    emoji: "🕳️",
    lines: [
      "Did you know the drains in the street usually lead straight to creeks, rivers and the sea?",
      "Anything that goes down them, like litter or dirty water, can end up where fish and turtles live.",
      "So remember: only rain down the drain!",
    ],
    tryIt: "On your next walk, count how many street drains you can spot.",
    quiz: {
      q: "What should go down street drains?",
      options: ["Only rain", "Rubbish", "Old paint"],
      answer: 0,
      explain: "Only rain! Everything else can reach the sea.",
    },
  },
  {
    id: "coral-daintree",
    title: "Where Rainforest Meets Reef",
    emoji: "🌴",
    lines: [
      "In far north Queensland, there's the Daintree Rainforest, one of the oldest rainforests in the world.",
      "In some places, it grows right down to the beach, next to the Great Barrier Reef.",
      "Two amazing natural wonders, side by side! Cassowaries, tall flightless birds, live there too.",
    ],
    quiz: {
      q: "Which old rainforest grows right next to the Great Barrier Reef?",
      options: ["The Daintree", "The Sahara", "The Arctic"],
      answer: 0,
      explain: "The Daintree, in far north Queensland!",
    },
  },
  {
    id: "coral-cyclones",
    title: "Swirling Cyclones",
    emoji: "🌀",
    lines: [
      "A cyclone is a giant spinning storm that forms over warm ocean water.",
      "In northern Australia, cyclone season is usually from about November to April.",
      "The same kind of storm is called a hurricane or a typhoon in other parts of the world. Ours spin clockwise!",
    ],
    age: "8+",
    quiz: {
      q: "Where do cyclones form?",
      options: ["Over warm ocean water", "In deserts", "Inside volcanoes"],
      answer: 0,
      explain: "Over warm ocean water!",
    },
  },
  {
    id: "coral-waves",
    title: "Where Waves Come From",
    emoji: "🏄",
    lines: [
      "Most waves are made by the wind!",
      "As wind blows across the sea, it pushes the water into ripples, which can grow into big waves.",
      "Some waves travel across a whole ocean before they splash onto a beach.",
    ],
    tryIt: "Blow gently across a bowl of water. Can you make tiny waves?",
    quiz: {
      q: "What makes most ocean waves?",
      options: ["Wind", "Whales splashing", "Boats"],
      answer: 0,
      explain: "Wind! It pushes water into ripples and waves.",
    },
  },
  {
    id: "coral-plants-and-fire",
    title: "Plants That Bounce Back",
    emoji: "🌿",
    lines: [
      "Some Australian plants have clever ways to survive bushfires.",
      "Many gum trees can sprout new green shoots from buds hidden under their bark after a fire.",
      "And many banksia seed pods stay shut until heat from a fire helps them open and drop their seeds.",
    ],
    age: "8+",
    quiz: {
      q: "Where can gum trees sprout new shoots after a fire?",
      options: ["From buds under their bark", "From their shadows", "They can't"],
      answer: 0,
      explain: "From hidden buds under the bark. Nature is tough!",
    },
  },
  {
    id: "coral-kookaburra",
    title: "The Laughing Kookaburra",
    emoji: "🐦",
    lines: [
      "Koo-koo-koo-ka-ka-ka! That's the laughing kookaburra.",
      "Kookaburras aren't really laughing at a joke. Their call tells other birds, 'This is our home!'",
      "Often the whole family joins in together, especially at dawn and dusk.",
    ],
    tryIt: "Listen outside early in the morning. Can you hear a kookaburra?",
    quiz: {
      q: "Why do kookaburras 'laugh'?",
      options: ["To say 'this is our home'", "They heard a joke", "They're sneezing"],
      answer: 0,
      explain: "Their laugh tells other birds this is their territory.",
    },
  },
  {
    id: "coral-frogs",
    title: "Frogs Drink Through Skin",
    emoji: "🐸",
    lines: [
      "Frogs don't drink water with their mouths like we do.",
      "Instead, they soak it up through their skin! They can take in air through their skin too.",
      "Because of their special skin, frogs need clean water. Lots of happy frogs means a healthy place.",
    ],
    tryIt: "After rain, listen at dusk for frogs calling.",
    quiz: {
      q: "How do most frogs drink?",
      options: ["Through their skin", "With a straw", "They never need water"],
      answer: 0,
      explain: "Through their skin! That's why they need clean water.",
    },
  },
  {
    id: "coral-whale-shark",
    title: "The Biggest Fish",
    emoji: "🦈",
    lines: [
      "The whale shark is the biggest fish in the sea. It can grow longer than a bus!",
      "But don't worry, this gentle giant only eats tiny plankton and little fish.",
      "Every year, whale sharks visit Ningaloo Reef in Western Australia.",
    ],
    quiz: {
      q: "What does the giant whale shark eat?",
      options: ["Tiny plankton and little fish", "Boats", "People"],
      answer: 0,
      explain: "Tiny plankton! It's a gentle giant.",
    },
  },
  {
    id: "coral-sponges",
    title: "Sponges Are Animals",
    emoji: "🧽",
    lines: [
      "Sea sponges look like plants, but they're animals!",
      "They have no brain, no heart and no mouth. They stay in one spot for their whole lives.",
      "Water flows through their tiny holes, and they catch little bits of food from it.",
    ],
    quiz: {
      q: "Are sea sponges plants or animals?",
      options: ["Animals", "Plants", "Rocks"],
      answer: 0,
      explain: "Animals! Very still, very simple ones.",
    },
  },
  {
    id: "coral-blue-planet",
    title: "Our Blue Planet",
    emoji: "🌏",
    lines: [
      "From space, Earth looks mostly blue. That's because oceans cover about 70% of it!",
      "Almost all of Earth's water is in the oceans, and it's salty.",
      "Only a tiny bit is fresh water we can drink. That's why we look after it so carefully.",
    ],
    tryIt: "Look at a globe or world map. Is there more blue or more land?",
    quiz: {
      q: "About how much of Earth is covered by ocean?",
      options: ["About 70%", "About 5%", "None"],
      answer: 0,
      explain: "About 70%! We live on a blue planet.",
    },
  },
  {
    id: "coral-deep-mysteries",
    title: "Mysteries of the Deep",
    emoji: "🔦",
    lines: [
      "The deep ocean is dark, cold and very hard to reach.",
      "Most of it has never been seen by people. Scientists find new kinds of sea creatures every year!",
      "Maybe one day, you'll be an ocean explorer who discovers something new.",
    ],
    quiz: {
      q: "Have people seen most of the deep ocean?",
      options: ["No, most is still unexplored", "Yes, every bit", "There is no deep ocean"],
      answer: 0,
      explain: "No! There's still so much to discover.",
    },
  },
  {
    id: "coral-manta-rays",
    title: "Majestic Manta Rays",
    emoji: "🪽",
    lines: [
      "Manta rays glide through the water like giant underwater birds.",
      "The biggest kind can be about 7 metres from wingtip to wingtip!",
      "They're gentle, and unlike some rays they don't have a stinging barb. They eat plankton.",
    ],
    quiz: {
      q: "How do manta rays move through the water?",
      options: ["They glide like giant birds", "They hop", "They roll"],
      answer: 0,
      explain: "They glide, flapping their huge fins like wings!",
    },
  },
  {
    id: "coral-be-crocwise",
    title: "Be Crocwise",
    emoji: "🐊",
    lines: [
      "In northern Australia, crocodiles can live in rivers, creeks, beaches and even billabongs.",
      "Always obey crocodile warning signs, and never swim where crocs might be.",
      "Stay well back from the water's edge, and listen to your grown-ups and park rangers.",
    ],
    quiz: {
      q: "What should you do when you see a crocodile warning sign?",
      options: ["Obey it and stay out of the water", "Go for a swim", "Look for the croc up close"],
      answer: 0,
      explain: "Obey it! Crocs are very dangerous.",
    },
  },
  {
    id: "coral-stingray-shuffle",
    title: "The Stingray Shuffle",
    emoji: "🩴",
    lines: [
      "Stingrays like to rest on sandy sea floors, sometimes hidden under the sand.",
      "When you walk in shallow sandy water, shuffle your feet along instead of stomping.",
      "The shuffle gently warns rays you're coming, so they glide away.",
    ],
    quiz: {
      q: "How should you walk in shallow sandy water?",
      options: ["Shuffle your feet", "Stomp hard", "Jump with both feet"],
      answer: 0,
      explain: "Shuffle! It lets the stingrays know you're coming.",
    },
  },
  {
    id: "coral-pufferfish",
    title: "Puffed-Up Pufferfish",
    emoji: "🐡",
    lines: [
      "When a pufferfish is scared, it gulps water and puffs up into a big spiky ball!",
      "Many pufferfish are also poisonous, so predators leave them alone.",
      "In Australia, toadfish are a kind of pufferfish. Never touch or eat them, and keep dogs away too.",
    ],
    quiz: {
      q: "What does a scared pufferfish do?",
      options: ["Puffs up into a ball", "Changes into a bird", "Sings"],
      answer: 0,
      explain: "It puffs up big so it's hard to eat!",
    },
  },
];

export const LESSONS_CORAL: Lesson[] = drafts.map((d) => ({ ...d, wizard: "coral" }));
