import type { Lesson, LessonDraft } from "../types";

// Marigold, the Kitchen & Home Wizard. Cosy, practical, safety-first.
const drafts: LessonDraft[] = [
  {
    id: "marigold-handwashing",
    title: "Washing Hands Properly",
    emoji: "🧼",
    lines: [
      "Germs are too tiny to see, poppet, but soap and water wash them away.",
      "Wet your hands, add soap, and rub your palms, the backs, between your fingers, your thumbs and your nails.",
      "Scrub for about 20 seconds, like singing 'Happy Birthday' twice. Then rinse and dry.",
    ],
    tryIt: "Sing 'Happy Birthday' twice while you wash your hands before your next meal.",
    quiz: {
      q: "About how long should you scrub your hands with soap?",
      options: ["About 20 seconds", "One second", "Ten minutes"],
      answer: 0,
      explain: "About 20 seconds, like two rounds of 'Happy Birthday'.",
    },
  },
  {
    id: "marigold-make-your-bed",
    title: "Make Your Bed",
    emoji: "🛏️",
    lines: [
      "A made bed makes the whole room look tidy, sweet pea.",
      "Pull the sheet and doona up to the top, and smooth out the lumps with your hands.",
      "Pop your pillow at the top and your teddy on top. Done in one minute!",
    ],
    tryIt: "Make your bed as soon as you get up tomorrow.",
    quiz: {
      q: "What do you do with the lumps in your doona?",
      options: ["Smooth them out with your hands", "Jump on them", "Leave them"],
      answer: 0,
      explain: "Smooth them out! Nice and neat.",
    },
  },
  {
    id: "marigold-sort-laundry",
    title: "Sorting the Washing",
    emoji: "🧺",
    lines: [
      "Before clothes go in the washing machine, we sort them into piles.",
      "Whites and light colours go in one pile. Darks, like navy and black, go in another.",
      "Why? Dark or bright clothes can let colour run out and turn your whites a funny colour!",
    ],
    tryIt: "Help sort the washing basket into a light pile and a dark pile.",
    quiz: {
      q: "Why do we keep dark clothes away from whites in the wash?",
      options: ["The colour can run onto the whites", "Dark clothes are grumpy", "No reason"],
      answer: 0,
      explain: "Colour can run! Nobody wants pink school shirts by accident.",
    },
  },
  {
    id: "marigold-set-the-table",
    title: "Setting the Table",
    emoji: "🍽️",
    lines: [
      "Put a plate in the middle of each place. The fork goes on the left side.",
      "The knife goes on the right, with its blade facing the plate. The spoon sits beside the knife.",
      "The cup goes at the top right. Let a grown-up carry any sharp knives to the table.",
    ],
    tryIt: "Set the table for your family's next dinner.",
    quiz: {
      q: "Which side does the fork go on?",
      options: ["The left", "The right", "On the chair"],
      answer: 0,
      explain: "The left! Fork and left both have four letters.",
    },
  },
  {
    id: "marigold-knife-safety",
    title: "Knife Safety Basics",
    emoji: "🔪",
    lines: [
      "Knives are for grown-ups to teach and watch over, dearie. Never use one on your own.",
      "With a grown-up, you might start by using a butter knife to cut soft things like banana, on a chopping board.",
      "Keep your fingers curled away from the blade, and if a knife falls, step back. Never try to catch it.",
    ],
    quiz: {
      q: "Who should be with you when you use a knife?",
      options: ["A grown-up", "Nobody", "Your pet"],
      answer: 0,
      explain: "Always a grown-up, to teach you and keep you safe.",
    },
  },
  {
    id: "marigold-measuring",
    title: "Measuring Cups and Spoons",
    emoji: "🥄",
    lines: [
      "Baking needs careful measuring, poppet. Too much or too little can change the whole recipe!",
      "In Australia, one cup holds 250 millilitres. A teaspoon is 5 millilitres, and a tablespoon is 20.",
      "For flour, fill the cup and level off the top with something flat, like the back of a spoon handle.",
    ],
    age: "8+",
    funFact: "An Australian tablespoon is 20 mL, but in many other countries it's about 15 mL!",
    quiz: {
      q: "In Australia, how much does one measuring cup hold?",
      options: ["250 millilitres", "5 millilitres", "10 litres"],
      answer: 0,
      explain: "250 millilitres. That's a quarter of a litre.",
    },
  },
  {
    id: "marigold-three-jars",
    title: "Spend, Save, Share Jars",
    emoji: "🫙",
    lines: [
      "Here's a clever way to look after your money: use three jars.",
      "Label them Spend, Save and Share. When you get money, split it between the jars.",
      "Spend is for small treats, Save is for something bigger, and Share is for helping others.",
    ],
    tryIt: "Decorate three jars or boxes and label them Spend, Save and Share.",
    quiz: {
      q: "What's the Share jar for?",
      options: ["Helping others", "Buying lollies", "Hiding socks"],
      answer: 0,
      explain: "Helping others, like a donation or a gift.",
    },
  },
  {
    id: "marigold-pocket-money-plan",
    title: "Planning Pocket Money",
    emoji: "💰",
    lines: [
      "A budget is a plan for your money, sweet pea.",
      "Say you get $5 a week and want a $20 book. Save it all, and in four weeks you'll have enough!",
      "Writing down your plan helps you stick to it and reach your goal.",
    ],
    age: "8+",
    quiz: {
      q: "If you save $5 a week, how long until you have $20?",
      options: ["4 weeks", "1 week", "20 weeks"],
      answer: 0,
      explain: "4 weeks! 5, 10, 15, 20.",
    },
  },
  {
    id: "marigold-needs-and-wants",
    title: "Needs and Wants",
    emoji: "🛒",
    lines: [
      "Needs are things we must have, like food, water, clothes and a home.",
      "Wants are things that are nice to have, like toys and treats.",
      "Wants are lovely, but needs come first. Knowing the difference is very grown-up of you!",
    ],
    quiz: {
      q: "Which one is a need?",
      options: ["Food", "A new toy car", "A lolly"],
      answer: 0,
      explain: "Food! We all need it to live.",
    },
  },
  {
    id: "marigold-plant-care",
    title: "Caring for Plants",
    emoji: "🪴",
    lines: [
      "Plants need water, light and good soil to grow happy and green.",
      "Before watering, poke your finger gently into the soil. If it's dry, give it a drink.",
      "If it's still damp, wait a day or two. Too much water can make roots sick too!",
    ],
    tryIt: "Do the finger test on a plant at home and water it only if the soil is dry.",
    quiz: {
      q: "How can you tell if a plant needs water?",
      options: ["Feel if the soil is dry", "Ask it", "Water it every hour"],
      answer: 0,
      explain: "The finger test! Dry soil means drink time.",
    },
  },
  {
    id: "marigold-pet-care",
    title: "Looking After Pets",
    emoji: "🐕",
    lines: [
      "Pets are family, and they need us every single day.",
      "They need fresh water, the right food, a clean bed, and gentle love.",
      "Always wash your hands after touching pets or cleaning up after them.",
    ],
    tryIt: "Check your pet's water bowl and fill it with fresh water.",
    quiz: {
      q: "What should you do after cleaning up after a pet?",
      options: ["Wash your hands", "Lick your fingers", "Nothing"],
      answer: 0,
      explain: "Wash your hands! It keeps germs away.",
    },
  },
  {
    id: "marigold-slip-slop-slap",
    title: "Slip, Slop, Slap, Seek, Slide",
    emoji: "🧴",
    lines: [
      "The Aussie sun is strong, poppet! Remember five words.",
      "Slip on a shirt. Slop on SPF 50+ sunscreen. Slap on a hat.",
      "Seek shade. Slide on sunglasses. And put sunscreen on again every two hours!",
    ],
    tryIt: "Before you play outside today, do all five: slip, slop, slap, seek, slide.",
    quiz: {
      q: "What does 'Slap' mean in Slip, Slop, Slap?",
      options: ["Slap on a hat", "Slap your friend", "Slap the water"],
      answer: 0,
      explain: "Slap on a hat! Wide brims are best.",
    },
  },
  {
    id: "marigold-uv-index",
    title: "Check the UV Level",
    emoji: "☀️",
    lines: [
      "UV is invisible sunshine that can burn your skin, even on cool or cloudy days.",
      "Weather apps and websites show a UV number each day.",
      "When the UV is 3 or higher, it's time to be SunSmart and use all your sun protection.",
    ],
    age: "8+",
    quiz: {
      q: "Can you get sunburnt on a cloudy day?",
      options: ["Yes", "No, never", "Only at night"],
      answer: 0,
      explain: "Yes! UV can get through clouds, so protect your skin.",
    },
  },
  {
    id: "marigold-road-safety",
    title: "Stop, Look, Listen, Think",
    emoji: "🚸",
    lines: [
      "Roads are for cars, dearie, so we must be very careful near them.",
      "Before crossing, hold a grown-up's hand, stop at the kerb, then look and listen for traffic both ways.",
      "Think: is it safe? Cross at crossings when you can, and keep looking as you walk.",
    ],
    quiz: {
      q: "What do you do at the kerb before crossing?",
      options: ["Stop, look and listen", "Run straight across", "Close your eyes"],
      answer: 0,
      explain: "Stop, look, listen and think, holding a grown-up's hand.",
    },
  },
  {
    id: "marigold-buckle-up",
    title: "Buckle Up Every Trip",
    emoji: "🚗",
    lines: [
      "Even a short trip to the shops needs a seatbelt, sweet pea.",
      "Sit in your car seat or booster, with the belt flat across your shoulder and low across your hips.",
      "Kids ride in the back seat, and your grown-up will check the belt is done up tight.",
    ],
    quiz: {
      q: "When should you wear your seatbelt?",
      options: ["Every single trip", "Only on long trips", "Never"],
      answer: 0,
      explain: "Every trip! Even short ones.",
    },
  },
  {
    id: "marigold-if-you-get-lost",
    title: "If You Get Lost",
    emoji: "🧭",
    lines: [
      "If you can't find your grown-up in a shop or park, stop and stay where you are. They'll be looking for you.",
      "If you need help, ask a safe helper: a police officer, a worker at the shop counter, or a mum or dad with kids.",
      "Never leave the place with anyone. Knowing your grown-up's phone number helps a lot!",
    ],
    quiz: {
      q: "Who is a safe helper if you get lost in a shop?",
      options: ["A worker at the shop counter", "Someone asking you to leave with them", "Nobody"],
      answer: 0,
      explain: "A shop worker is a safe helper. Stay inside the shop.",
    },
  },
  {
    id: "marigold-call-000",
    title: "Calling Triple Zero",
    emoji: "☎️",
    lines: [
      "In Australia, the emergency number is 000, triple zero. It's for when someone is badly hurt, there's a fire, or danger.",
      "The person who answers will ask: police, fire or ambulance? Then tell them what happened and where you are.",
      "Stay on the phone until they say you can hang up. And never call 000 as a joke.",
    ],
    quiz: {
      q: "What's the emergency number in Australia?",
      options: ["000", "123", "999"],
      answer: 0,
      explain: "000, triple zero. Only for real emergencies.",
    },
  },
  {
    id: "marigold-burns-cool-water",
    title: "Cool Water for Burns",
    emoji: "🚰",
    lines: [
      "If someone gets a burn, tell a grown-up straight away, dearie.",
      "The best first aid is cool running water on the burn for 20 minutes. Not ice, and never butter!",
      "For a big burn, a grown-up should call 000.",
    ],
    quiz: {
      q: "How long should a burn be cooled under running water?",
      options: ["20 minutes", "5 seconds", "Put butter on it instead"],
      answer: 0,
      explain: "20 minutes of cool running water. And tell a grown-up!",
    },
  },
  {
    id: "marigold-cuts-and-scrapes",
    title: "Cuts and Scrapes",
    emoji: "🩹",
    lines: [
      "Ouch! If you get a cut, tell a grown-up.",
      "Pressing firmly on the cut with a clean cloth helps it stop bleeding.",
      "Then a grown-up can clean it and pop on a bandaid.",
    ],
    quiz: {
      q: "What helps a cut stop bleeding?",
      options: ["Pressing on it with a clean cloth", "Shaking it", "Blowing on it"],
      answer: 0,
      explain: "Firm pressure with a clean cloth, then tell a grown-up.",
    },
  },
  {
    id: "marigold-nosebleed",
    title: "Nosebleed Know-How",
    emoji: "👃",
    lines: [
      "Nosebleeds are common, sweet pea, and usually not serious.",
      "Sit down, lean forward (not back!), and pinch the soft part of your nose for about 10 minutes.",
      "Breathe through your mouth, and tell a grown-up. Leaning back just makes you swallow blood. Yuck!",
    ],
    quiz: {
      q: "During a nosebleed, which way should you lean?",
      options: ["Forward", "Backward", "Upside down"],
      answer: 0,
      explain: "Forward! And pinch the soft part of your nose.",
    },
  },
  {
    id: "marigold-recycle-right",
    title: "Recycling Right",
    emoji: "♻️",
    lines: [
      "In lots of Aussie towns, the yellow-lid bin is for recycling. Check what your council says.",
      "Clean paper, cardboard, glass bottles, tins and hard plastic containers can usually go in.",
      "Put them in loose, never in a plastic bag, so the recycling machines can sort them.",
    ],
    tryIt: "Help sort this week's recycling and squash the cardboard boxes flat.",
    quiz: {
      q: "How should recycling go into the bin?",
      options: ["Loose, not in a plastic bag", "Tied up in plastic bags", "Wrapped in wrapping paper"],
      answer: 0,
      explain: "Loose! Plastic bags jam the sorting machines.",
    },
  },
  {
    id: "marigold-compost-scraps",
    title: "Food Scraps Into Soil",
    emoji: "🪱",
    lines: [
      "Fruit and veggie peels don't have to be rubbish!",
      "In a compost bin or worm farm, they break down into rich soil that helps gardens grow.",
      "Worms munch the scraps and leave behind 'worm castings', which is fancy for worm poo. Plants love it!",
    ],
    quiz: {
      q: "What can fruit and veggie scraps turn into?",
      options: ["Rich soil for gardens", "Plastic", "Rocks"],
      answer: 0,
      explain: "Rich soil! The worms do the hard work.",
    },
  },
  {
    id: "marigold-table-manners",
    title: "Tidy Table Manners",
    emoji: "🍴",
    lines: [
      "Good manners make mealtimes nice for everyone, poppet.",
      "Chew with your mouth closed, and wait until you've swallowed before you talk.",
      "If you want something, say 'Please pass the peas' instead of reaching across.",
    ],
    quiz: {
      q: "What's a polite way to get the salad bowl?",
      options: ["Ask someone to please pass it", "Climb on the table", "Shout 'GIVE!'"],
      answer: 0,
      explain: "Ask nicely! 'Please pass the salad.'",
    },
  },
  {
    id: "marigold-welcome-guests",
    title: "Welcoming Guests",
    emoji: "🚪",
    lines: [
      "When visitors come to your home, you can be a wonderful host.",
      "Look at them, smile and say 'Hello, welcome!'",
      "Offer them a seat or a glass of water. They'll feel so welcome!",
    ],
    quiz: {
      q: "What can you offer a guest?",
      options: ["A seat or a glass of water", "Your dirty socks", "Nothing, ignore them"],
      answer: 0,
      explain: "A seat or a drink. Lovely hosting!",
    },
  },
  {
    id: "marigold-phone-manners",
    title: "Answering the Phone",
    emoji: "📱",
    lines: [
      "If a grown-up says you can answer the phone, say 'Hello, this is Mia speaking,' using your own name.",
      "If the call is for someone else, say 'Just a moment, please,' and go and get them.",
      "Never tell a caller you're home alone or give out your address. Get a grown-up instead.",
    ],
    quiz: {
      q: "What should you never tell a caller?",
      options: ["That you're home alone", "Hello", "Just a moment, please"],
      answer: 0,
      explain: "Right. Keep that private and get a grown-up.",
    },
  },
  {
    id: "marigold-clear-your-plate",
    title: "Clearing Your Plate",
    emoji: "🧽",
    lines: [
      "When you've finished eating, you can clear your own plate, sweet pea.",
      "Carry it carefully to the kitchen, and scrape the leftovers into the bin or compost.",
      "Then pop it in the sink or dishwasher. The cook will be so pleased!",
    ],
    tryIt: "Clear your plate after dinner tonight without being asked.",
    quiz: {
      q: "Where do leftover scraps go?",
      options: ["The bin or compost", "Under the table", "Back in the pot"],
      answer: 0,
      explain: "The bin or compost, before the plate goes to the sink.",
    },
  },
  {
    id: "marigold-washing-up",
    title: "Doing the Washing Up",
    emoji: "🫧",
    lines: [
      "Washing up is a great job to help with. Ask a grown-up to fill the sink and check the water isn't too hot.",
      "Wash the cleanest things first, like cups, and the greasy pans last.",
      "Leave sharp things for your grown-up. Then rinse, and stack them to dry.",
    ],
    quiz: {
      q: "Which should you wash first?",
      options: ["The cleanest things, like cups", "The greasiest pan", "Your shoes"],
      answer: 0,
      explain: "Cleanest first, so your water stays cleaner for longer.",
    },
  },
  {
    id: "marigold-hang-the-washing",
    title: "Hanging Out the Washing",
    emoji: "👚",
    lines: [
      "Sunshine and breeze dry clothes for free, poppet!",
      "Give each piece a good shake first so it dries with fewer wrinkles, then peg it on the line.",
      "Turn dark clothes inside out. That helps stop the strong sun fading their colour.",
    ],
    quiz: {
      q: "Why turn dark clothes inside out on the line?",
      options: ["To stop the sun fading them", "To confuse the birds", "So they dry wet"],
      answer: 0,
      explain: "Strong sunshine can fade colours. Inside out protects them.",
    },
  },
  {
    id: "marigold-save-water",
    title: "Saving Water",
    emoji: "🚿",
    lines: [
      "Water is precious, especially in a dry country like Australia.",
      "Turn the tap off while you brush your teeth. Only turn it on to rinse!",
      "Try a short shower, about four minutes. A song or a timer can help.",
    ],
    tryIt: "Turn off the tap while you brush your teeth tonight.",
    quiz: {
      q: "What should the tap be doing while you brush your teeth?",
      options: ["Turned off", "Running the whole time", "Filling the bath"],
      answer: 0,
      explain: "Off! Only turn it on when you need to rinse.",
    },
  },
  {
    id: "marigold-lights-off",
    title: "Lights Off, Please",
    emoji: "💡",
    lines: [
      "Leaving a room? Switch off the light, sweet pea!",
      "Lights and screens left on use energy, even when nobody's there.",
      "Saving energy is good for the planet and saves your family money too.",
    ],
    tryIt: "Be the family Light Detective today and switch off lights in empty rooms.",
    quiz: {
      q: "What should you do when you leave an empty room?",
      options: ["Switch off the light", "Turn on more lights", "Leave the TV on"],
      answer: 0,
      explain: "Lights off! Good for the planet and the power bill.",
    },
  },
  {
    id: "marigold-cough-in-elbow",
    title: "Cough Into Your Elbow",
    emoji: "🤧",
    lines: [
      "Coughs and sneezes spray germs out very fast, poppet!",
      "Cover your cough or sneeze with a tissue, or your elbow if there's no tissue.",
      "Put the tissue in the bin and wash your hands. That keeps germs off your hands, and off everyone else.",
    ],
    quiz: {
      q: "If there's no tissue, what should you sneeze into?",
      options: ["Your elbow", "Your hands", "The air near someone"],
      answer: 0,
      explain: "Your elbow! Hands touch everything, elbows don't.",
    },
  },
  {
    id: "marigold-eat-a-rainbow",
    title: "Eat a Rainbow",
    emoji: "🥕",
    lines: [
      "Different coloured fruit and veggies give your body different good things.",
      "Try to eat lots of colours: red tomatoes, orange carrots, green peas, purple plums!",
      "And water is the best drink to have every day.",
    ],
    tryIt: "Count how many colours of fruit and veggies you eat today.",
    quiz: {
      q: "What's the best everyday drink?",
      options: ["Water", "Soft drink", "Syrup"],
      answer: 0,
      explain: "Water! Your body loves it.",
    },
  },
  {
    id: "marigold-pack-a-lunch",
    title: "Packing a Healthy Lunch",
    emoji: "🥪",
    lines: [
      "A good lunchbox has something filling, like a sandwich or wrap, plus fruit and veggies.",
      "Add a small snack, like cheese or yoghurt, and a water bottle.",
      "An ice brick keeps it all cool and fresh until lunchtime.",
    ],
    tryIt: "Help pack your own lunchbox for tomorrow.",
    quiz: {
      q: "What keeps a lunchbox cool?",
      options: ["An ice brick", "A sock", "Sunshine"],
      answer: 0,
      explain: "An ice brick! Cool food stays fresh and safe.",
    },
  },
  {
    id: "marigold-shopping-smart",
    title: "Smart Shopping",
    emoji: "🏷️",
    lines: [
      "Writing a shopping list before you go helps you buy only what you need.",
      "At the supermarket, shelf labels often show a 'unit price', like the price per 100 grams.",
      "Comparing unit prices shows which choice really gives you more for your money.",
    ],
    age: "8+",
    quiz: {
      q: "Why write a shopping list?",
      options: ["To buy only what you need", "To make the trip longer", "For fun only"],
      answer: 0,
      explain: "A list keeps you on track and saves money.",
    },
  },
  {
    id: "marigold-hot-things",
    title: "Hot Things Are Grown-Up Jobs",
    emoji: "🔥",
    lines: [
      "Ovens, stoves, kettles and hot pots can burn very badly, dearie.",
      "Stay a big step back when a grown-up is cooking, and never run in the kitchen.",
      "Pot handles should always point inwards, so nobody knocks them. Only cook with a grown-up.",
    ],
    quiz: {
      q: "Which way should pot handles point on the stove?",
      options: ["Inwards", "Out over the edge", "At the dog"],
      answer: 0,
      explain: "Inwards, so they can't be bumped. Cooking is a grown-up job.",
    },
  },
  {
    id: "marigold-pool-safety",
    title: "Pool Safety",
    emoji: "🏊",
    lines: [
      "Water is fun, but it can be dangerous very quickly, sweet pea.",
      "Only swim when a grown-up is watching you, and never swim alone.",
      "Pool gates must always be kept shut. Never prop them open.",
    ],
    quiz: {
      q: "When can you swim in a pool?",
      options: ["When a grown-up is watching", "Whenever, alone", "At night by yourself"],
      answer: 0,
      explain: "Only with a grown-up watching. Every time.",
    },
  },
  {
    id: "marigold-medicine-not-lollies",
    title: "Medicine Isn't Lollies",
    emoji: "💊",
    lines: [
      "Some medicines look like lollies, and some cleaning bottles look like drinks. But they can make you very sick.",
      "Only take medicine when a grown-up gives it to you. Never touch cleaning stuff.",
      "If someone swallows something they shouldn't, tell a grown-up fast. The Poisons Information Centre is on 13 11 26.",
    ],
    quiz: {
      q: "When should you take medicine?",
      options: ["Only when a grown-up gives it to you", "Whenever you find some", "When it looks yummy"],
      answer: 0,
      explain: "Only from a grown-up. Medicine isn't a treat.",
    },
  },
  {
    id: "marigold-safety-hand",
    title: "Your Safety Hand",
    emoji: "✋",
    lines: [
      "Trace around your hand. On each finger, write a grown-up you trust and could talk to.",
      "Maybe mum, dad, a grandparent, a teacher or an aunty.",
      "If anything ever worries you, talk to someone on your hand. If they don't help, keep telling until someone does.",
    ],
    tryIt: "Draw your safety hand with a grown-up and stick it on the fridge.",
    quiz: {
      q: "Who goes on your safety hand?",
      options: ["Grown-ups you trust", "Cartoon characters", "Strangers"],
      answer: 0,
      explain: "Grown-ups you trust and can always talk to.",
    },
  },
  {
    id: "marigold-know-your-address",
    title: "Know Your Address",
    emoji: "🏡",
    lines: [
      "Your address is the special name for where your home is.",
      "It has a number, a street name, a suburb or town, and a state.",
      "Learning it by heart is very handy if you ever need help, like when calling 000.",
    ],
    tryIt: "Practise saying your address with a grown-up until you know it by heart.",
    quiz: {
      q: "Why is it good to know your address?",
      options: ["So you can tell helpers where you live", "To impress the cat", "It isn't"],
      answer: 0,
      explain: "In an emergency, helpers need to know where to come.",
    },
  },
  {
    id: "marigold-fire-escape",
    title: "Get Down Low and Go",
    emoji: "🚒",
    lines: [
      "If the smoke alarm beeps, get down low and go, go, go! Smoke rises, so the cleaner air is near the floor.",
      "Get out, stay out, and meet your family at your safe meeting spot, like the letterbox. Then call 000.",
      "Never hide from fire. And matches and lighters are tools only grown-ups should touch.",
    ],
    tryIt: "Ask your grown-up to plan your family's fire escape and choose a meeting spot.",
    quiz: {
      q: "Where is the cleaner air in a smoky room?",
      options: ["Down low, near the floor", "Up high near the ceiling", "Under the bed"],
      answer: 0,
      explain: "Down low! Smoke rises, so crawl low and go.",
    },
  },
  {
    id: "marigold-stop-drop-roll",
    title: "Stop, Drop and Roll",
    emoji: "🧯",
    lines: [
      "If your clothes ever catch fire, don't run. Running makes the flames bigger.",
      "Stop, drop to the ground, cover your face with your hands, and roll over and over.",
      "Then cool any burns under running water and get a grown-up to call 000.",
    ],
    quiz: {
      q: "If your clothes catch fire, what should you NOT do?",
      options: ["Run", "Stop", "Roll"],
      answer: 0,
      explain: "Don't run! Stop, drop and roll puts the fire out.",
    },
  },
  {
    id: "marigold-bike-helmet",
    title: "Helmets On!",
    emoji: "🚲",
    lines: [
      "In Australia, it's the law to wear a helmet when you ride a bike. It protects your precious brain!",
      "Your helmet should sit level, about two fingers above your eyebrows.",
      "Do up the strap so only about two fingers fit between it and your chin.",
    ],
    tryIt: "Check your helmet fit with the two-finger test.",
    quiz: {
      q: "Where should your helmet sit?",
      options: ["About two fingers above your eyebrows", "On the back of your head", "In your bag"],
      answer: 0,
      explain: "Level and low, two fingers above your eyebrows.",
    },
  },
  {
    id: "marigold-snake-safety",
    title: "If You See a Snake",
    emoji: "🐍",
    lines: [
      "Australia has lots of snakes, and some are very venomous. Most just want to be left alone.",
      "If you see one, stop, stay calm, and slowly back away. Never poke it or try to catch it.",
      "Tell a grown-up straight away. If anyone is bitten, keep them still and call 000.",
    ],
    quiz: {
      q: "What should you do if you see a snake?",
      options: ["Slowly back away and tell a grown-up", "Poke it with a stick", "Try to pick it up"],
      answer: 0,
      explain: "Back away slowly and tell a grown-up.",
    },
  },
  {
    id: "marigold-spill-cleanup",
    title: "Cleaning Up Spills",
    emoji: "🧻",
    lines: [
      "Oops, spilled your drink? Don't worry, poppet, it happens to everyone.",
      "Grab a cloth or paper towel and press it onto the spill to soak it up. Rubbing can spread it around.",
      "If something glass broke, stay back and call a grown-up. Never pick up broken glass.",
    ],
    quiz: {
      q: "What should you do if a glass breaks?",
      options: ["Stay back and call a grown-up", "Pick up the pieces", "Walk through it"],
      answer: 0,
      explain: "Stay back! Broken glass is a grown-up job.",
    },
  },
  {
    id: "marigold-crack-an-egg",
    title: "Cracking an Egg",
    emoji: "🥚",
    lines: [
      "With a grown-up helping, cracking eggs is a fun baking job!",
      "Tap the egg firmly on the flat bench, not the bowl's edge. Put your thumbs in the crack and pull it open over the bowl.",
      "Raw egg can have germs, so wash your hands afterwards, and don't eat raw cake batter.",
    ],
    tryIt: "Ask a grown-up if you can crack the eggs next time you bake together.",
    quiz: {
      q: "What should you do after touching raw egg?",
      options: ["Wash your hands", "Lick your fingers", "Nothing"],
      answer: 0,
      explain: "Wash your hands! Raw egg can carry germs.",
    },
  },
];

export const LESSONS_MARIGOLD: Lesson[] = drafts.map((d) => ({ ...d, wizard: "marigold" }));
