import type { Lesson, LessonDraft } from "../types";

// Nova, the Star Wizard. Curious, wondering, loves asking "why?".
const drafts: LessonDraft[] = [
  {
    id: "nova-why-sky-blue",
    title: "Why Is the Sky Blue?",
    emoji: "🌤️",
    lines: [
      "Hmm, have you ever wondered why the sky is blue? Sunlight looks white, but it's really all the colours mixed together.",
      "When sunlight zooms into the air, the air scatters the blue light all over the sky much more than the other colours.",
      "So wherever you look up, blue light is bouncing towards your eyes!",
    ],
    quiz: {
      q: "What colours are mixed together in sunlight?",
      options: ["All the colours", "Only yellow", "Only blue"],
      answer: 0,
      explain: "All the colours! The air scatters the blue part the most.",
    },
  },
  {
    id: "nova-sunset-colours",
    title: "Why Sunsets Glow",
    emoji: "🌇",
    lines: [
      "At sunset, the Sun is low in the sky, so its light has to travel through much more air to reach you.",
      "On that long trip, most of the blue light gets scattered away.",
      "The reds, oranges and pinks are left behind to paint the sky. Beautiful science!",
    ],
    age: "8+",
    quiz: {
      q: "Why are sunsets orange and red?",
      options: ["Light travels through more air, and the blue gets scattered away", "The Sun catches fire", "Clouds are painted"],
      answer: 0,
      explain: "Yes! The long trip through the air leaves the warm colours.",
    },
  },
  {
    id: "nova-rainbows",
    title: "How Rainbows Are Made",
    emoji: "🌈",
    lines: [
      "Rainbows appear when sunlight shines through raindrops.",
      "Each drop bends the light and splits it into all its colours, like a tiny prism.",
      "To see a rainbow, stand with the Sun behind you and the rain in front of you.",
    ],
    tryIt: "On a sunny day, ask a grown-up to spray a fine mist from the hose with the Sun behind you.",
    quiz: {
      q: "Where should the Sun be when you look for a rainbow?",
      options: ["Behind you", "Right in front of you", "Hidden at night"],
      answer: 0,
      explain: "Behind you, with the rain in front!",
    },
  },
  {
    id: "nova-magnets",
    title: "Marvellous Magnets",
    emoji: "🧲",
    lines: [
      "Magnets pull on things made of iron or steel, like paperclips.",
      "But they don't pull on everything metal! Aluminium foil, plastic and wood aren't attracted at all.",
      "Every magnet has a north and a south end. Opposite ends pull together, and matching ends push apart.",
    ],
    tryIt: "Use a fridge magnet to test five things around the house. Which ones stick?",
    quiz: {
      q: "Which of these will a magnet pick up?",
      options: ["A steel paperclip", "A wooden block", "A plastic spoon"],
      answer: 0,
      explain: "The steel paperclip! Magnets like iron and steel.",
    },
  },
  {
    id: "nova-earth-magnet",
    title: "Earth Is a Giant Magnet",
    emoji: "🧭",
    lines: [
      "Hmm, how does a compass know which way is north?",
      "Deep inside, the Earth acts like a giant magnet!",
      "A compass needle is a tiny magnet, and Earth's magnetism turns it to point north.",
    ],
    quiz: {
      q: "What makes a compass needle point north?",
      options: ["Earth's magnetism", "The wind", "Luck"],
      answer: 0,
      explain: "Earth's magnetism! The whole planet acts like a magnet.",
    },
  },
  {
    id: "nova-volcanoes",
    title: "Inside a Volcano",
    emoji: "🌋",
    lines: [
      "Deep underground, it's so hot that rock can melt! This melted rock is called magma.",
      "When magma pushes up and bursts out of a volcano, we call it lava.",
      "Lava cools and hardens into new rock. Volcanoes can even build new islands!",
    ],
    funFact: "Mainland Australia has no active volcanoes, but old ones left us the Blue Lake at Mount Gambier.",
    quiz: {
      q: "What is magma called once it comes out of a volcano?",
      options: ["Lava", "Ice", "Sand"],
      answer: 0,
      explain: "Lava! Magma underground, lava above ground.",
    },
  },
  {
    id: "nova-fizzy-volcano",
    title: "Make a Fizzy Volcano",
    emoji: "🧪",
    lines: [
      "Here's a safe experiment to do with a grown-up. Put a spoonful of bicarb soda in a cup on a tray.",
      "Then pour in a little vinegar and watch it fizz up and overflow!",
      "The two mix and make a gas called carbon dioxide. Those bubbles are the gas escaping!",
    ],
    tryIt: "With a grown-up, add a drop of food colouring to the vinegar before pouring.",
    quiz: {
      q: "What gas makes the fizzy bubbles?",
      options: ["Carbon dioxide", "Steam", "Helium"],
      answer: 0,
      explain: "Carbon dioxide! The same gas that makes drinks fizzy.",
    },
  },
  {
    id: "nova-water-cycle",
    title: "The Water Cycle",
    emoji: "💧",
    lines: [
      "The Sun warms water in oceans and puddles, and it floats up into the sky as invisible vapour. That's evaporation.",
      "High up, the vapour cools and turns into tiny droplets that make clouds. That's condensation.",
      "When the droplets get heavy, they fall as rain. Then it all starts again!",
    ],
    age: "8+",
    quiz: {
      q: "What do we call it when water falls from clouds?",
      options: ["Rain", "Evaporation", "Magnetism"],
      answer: 0,
      explain: "Rain! Scientists also call it precipitation.",
    },
  },
  {
    id: "nova-clouds",
    title: "What Are Clouds?",
    emoji: "☁️",
    lines: [
      "Clouds look like fluffy cotton wool, but they're really made of water!",
      "A cloud is billions of teeny water droplets, or tiny bits of ice, floating together.",
      "Dark grey clouds are thick with water. They might be getting ready to rain!",
    ],
    tryIt: "Look at the clouds today. Can you find one shaped like an animal?",
    quiz: {
      q: "What are clouds made of?",
      options: ["Tiny water droplets or ice", "Cotton wool", "Marshmallows"],
      answer: 0,
      explain: "Water droplets or tiny bits of ice!",
    },
  },
  {
    id: "nova-gravity",
    title: "Gravity Pulls Us Down",
    emoji: "🍎",
    lines: [
      "Why do things fall down, not up? Hmm... it's gravity!",
      "Gravity is a pull that keeps our feet on the ground and keeps the Moon going around Earth.",
      "On the Moon, where there's no air, an astronaut dropped a hammer and a feather. They landed at the same time!",
    ],
    quiz: {
      q: "What keeps your feet on the ground?",
      options: ["Gravity", "Glue", "Magnets in your shoes"],
      answer: 0,
      explain: "Gravity! It pulls everything towards Earth.",
    },
  },
  {
    id: "nova-moon-phases",
    title: "The Changing Moon",
    emoji: "🌙",
    lines: [
      "The Moon doesn't make its own light. It shines because sunlight bounces off it.",
      "As the Moon travels around Earth, we see different amounts of its sunny side. That's why it seems to change shape.",
      "It's not Earth's shadow! The whole cycle, from full moon to full moon, takes about a month.",
    ],
    age: "8+",
    tryIt: "Look at the Moon each night this week and draw its shape.",
    quiz: {
      q: "Why does the Moon shine?",
      options: ["Sunlight bounces off it", "It has lights inside", "It's on fire"],
      answer: 0,
      explain: "Sunlight bounces off it, like a giant mirror ball.",
    },
  },
  {
    id: "nova-seasons",
    title: "Why We Have Seasons",
    emoji: "🍂",
    lines: [
      "Many people think summer happens when Earth is closer to the Sun. Nope, that's a myth!",
      "Earth is tilted. When our half of Earth leans towards the Sun, we get more direct sunshine: that's summer.",
      "When our half leans away, we get winter. That's why Australia has summer at Christmas!",
    ],
    age: "8+",
    funFact: "Earth is actually closest to the Sun in early January, during Australia's summer holidays!",
    quiz: {
      q: "What causes the seasons?",
      options: ["Earth's tilt", "Earth getting closer to the Sun", "The Moon"],
      answer: 0,
      explain: "Earth's tilt! Leaning towards the Sun makes summer.",
    },
  },
  {
    id: "nova-day-and-night",
    title: "Day and Night",
    emoji: "🌓",
    lines: [
      "The Sun looks like it moves across the sky. But really, it's the Earth that's spinning!",
      "Earth spins around once about every 24 hours.",
      "When your side faces the Sun, it's day. When it spins away, it's night.",
    ],
    tryIt: "Shine a torch on a ball in a dark room and slowly spin the ball. Watch day and night!",
    quiz: {
      q: "Why do we have day and night?",
      options: ["Earth spins around", "The Sun switches off", "Clouds cover the Sun"],
      answer: 0,
      explain: "Earth spins! Your side faces the Sun, then away.",
    },
  },
  {
    id: "nova-sound-vibrations",
    title: "Sound Is Wiggles",
    emoji: "🔊",
    lines: [
      "Every sound you hear is made by something wiggling back and forth really fast. We call it vibration.",
      "The vibrations travel through the air to your ears.",
      "Gently touch your throat while you hum. Can you feel the buzz? That's your voice vibrating!",
    ],
    tryIt: "Stretch a rubber band over an open box and pluck it. Watch it wiggle and hear it twang!",
    quiz: {
      q: "What makes sound?",
      options: ["Vibrations", "Colours", "Shadows"],
      answer: 0,
      explain: "Vibrations! Wiggles that travel to your ears.",
    },
  },
  {
    id: "nova-silent-space",
    title: "Space Is Silent",
    emoji: "🌌",
    lines: [
      "Sound needs something to travel through, like air or water.",
      "Space has almost no air at all. So sound can't travel there!",
      "That's why astronauts outside their ship talk to each other using radios.",
    ],
    quiz: {
      q: "Why is space silent?",
      options: ["There's no air to carry sound", "Everyone's asleep", "Stars are shy"],
      answer: 0,
      explain: "No air, no sound! Radios help astronauts talk.",
    },
  },
  {
    id: "nova-shadows",
    title: "Shadow Science",
    emoji: "👤",
    lines: [
      "A shadow forms when something blocks the light.",
      "Outside, your shadow is longest in the early morning and late afternoon, when the Sun is low.",
      "Around the middle of the day, when the Sun is high, your shadow is short and stubby!",
    ],
    tryIt: "Stand in the same spot in the morning and afternoon. How does your shadow change?",
    quiz: {
      q: "When is your shadow shortest?",
      options: ["Around the middle of the day", "Early morning", "At night"],
      answer: 0,
      explain: "Around midday, when the Sun is high in the sky!",
    },
  },
  {
    id: "nova-thunder-counting",
    title: "Counting to the Storm",
    emoji: "⛈️",
    lines: [
      "Lightning and thunder happen at the same time, but light travels much faster than sound.",
      "So you see the flash first. Count the seconds until the thunder, then divide by three. That's about how many kilometres away it is!",
      "Remember: when thunder roars, go indoors.",
    ],
    age: "8+",
    quiz: {
      q: "Why do we see lightning before we hear thunder?",
      options: ["Light travels faster than sound", "Thunder is lazy", "Our ears are slow"],
      answer: 0,
      explain: "Light is much faster than sound!",
    },
  },
  {
    id: "nova-plants-make-food",
    title: "Plants Make Their Own Food",
    emoji: "🌿",
    lines: [
      "Plants can't go to the shops. So they make their own food, using sunlight!",
      "They take in water from their roots and a gas called carbon dioxide from the air.",
      "With sunlight, their leaves turn these into sugary food, and they breathe out oxygen for us!",
    ],
    age: "8+",
    quiz: {
      q: "What do plants give off that we breathe?",
      options: ["Oxygen", "Smoke", "Glitter"],
      answer: 0,
      explain: "Oxygen! Thank you, plants.",
    },
  },
  {
    id: "nova-bean-in-a-jar",
    title: "Grow a Bean in a Jar",
    emoji: "🫘",
    lines: [
      "Want to watch a seed wake up? Put a damp paper towel inside a clear jar.",
      "Tuck a dried bean between the towel and the glass, and keep the towel damp.",
      "In a few days, a root pokes down and a shoot reaches up. You're a plant scientist!",
    ],
    tryIt: "Start a bean jar today and check it every morning.",
    quiz: {
      q: "Which way does the root grow?",
      options: ["Down", "Up", "Sideways out of the jar"],
      answer: 0,
      explain: "Down! The shoot goes up towards the light.",
    },
  },
  {
    id: "nova-solid-liquid-gas",
    title: "Solid, Liquid, Gas",
    emoji: "🧊",
    lines: [
      "Water can be three different things! Frozen, it's solid ice.",
      "Melted, it's runny liquid water. Heated up a lot, it turns into a gas called water vapour.",
      "Hot steam from a kettle can burn, so only watch that part from a safe distance with a grown-up.",
    ],
    quiz: {
      q: "What is ice?",
      options: ["Solid water", "A gas", "A kind of rock"],
      answer: 0,
      explain: "Solid water! Melt it and it's liquid again.",
    },
  },
  {
    id: "nova-float-or-sink",
    title: "Float or Sink?",
    emoji: "🛁",
    lines: [
      "Some things float and some sink. It's not just about how big they are!",
      "It depends on how heavy something is for its size, and its shape.",
      "A big log can float, but a tiny pebble sinks!",
    ],
    tryIt: "Fill a tub with water and guess: will a spoon, a leaf, a cork and a coin float or sink?",
    quiz: {
      q: "Do all big things sink?",
      options: ["No, a big log can float", "Yes, always", "Only on Mondays"],
      answer: 0,
      explain: "No! It's about how heavy it is for its size.",
    },
  },
  {
    id: "nova-friction",
    title: "Friction Slows Things Down",
    emoji: "🛝",
    lines: [
      "When two things rub together, they grip a little. That grip is called friction.",
      "Friction helps your shoes grip the ground, and it slows down a sliding toy car.",
      "Rub your hands together fast. Feel them get warm? That's friction too!",
    ],
    tryIt: "Roll a toy car on carpet, then on a smooth floor. Where does it go further?",
    quiz: {
      q: "What happens when you rub your hands together fast?",
      options: ["They get warm", "They get wet", "They glow"],
      answer: 0,
      explain: "They warm up, thanks to friction!",
    },
  },
  {
    id: "nova-static-balloon",
    title: "The Sticky Balloon",
    emoji: "🎈",
    lines: [
      "Rub a balloon on your hair or a woolly jumper for a few seconds.",
      "Now hold it against a wall. Hmm... it sticks!",
      "Rubbing moves tiny bits called electrons. This makes static electricity, which gives the balloon a pull.",
    ],
    tryIt: "Rub a balloon on your hair and see if it can lift your hair up too!",
    quiz: {
      q: "What makes the balloon stick to the wall?",
      options: ["Static electricity", "Glue", "Magic dust"],
      answer: 0,
      explain: "Static electricity from rubbing!",
    },
  },
  {
    id: "nova-ramps",
    title: "Ramps Make Work Easier",
    emoji: "📐",
    lines: [
      "Lifting something heavy straight up is hard work.",
      "Pushing it up a ramp takes less force. You go a longer way, but each push is easier!",
      "That's why there are ramps for wheelchairs, prams and delivery trolleys.",
    ],
    age: "8+",
    quiz: {
      q: "Why is a ramp helpful?",
      options: ["You need less force to push things up", "It's shorter", "It makes things vanish"],
      answer: 0,
      explain: "Less force for each push. Clever science!",
    },
  },
  {
    id: "nova-air-takes-space",
    title: "The Dry Tissue Trick",
    emoji: "🥤",
    lines: [
      "Scrunch a tissue into the bottom of a clear cup so it stays put.",
      "Turn the cup upside down and push it straight down into a bowl of water. Then lift it straight out.",
      "The tissue stays dry! The air trapped in the cup takes up space, so the water can't get in.",
    ],
    tryIt: "Try the dry tissue trick. What happens if you tilt the cup underwater?",
    quiz: {
      q: "What keeps the tissue dry?",
      options: ["Air trapped in the cup", "The tissue is waterproof", "Magic"],
      answer: 0,
      explain: "Air takes up space, even though we can't see it!",
    },
  },
  {
    id: "nova-disappearing-puddles",
    title: "Where Do Puddles Go?",
    emoji: "☀️",
    lines: [
      "After rain there are puddles everywhere. Then, hmm... they vanish! Where did they go?",
      "The Sun and wind turn the water into invisible water vapour, which floats into the air.",
      "This is called evaporation. It happens faster on hot, windy days.",
    ],
    tryIt: "Paint a water picture on warm concrete and watch how fast it evaporates.",
    quiz: {
      q: "What's it called when water turns into vapour and disappears into the air?",
      options: ["Evaporation", "Freezing", "Melting"],
      answer: 0,
      explain: "Evaporation! The water is still there, just invisible.",
    },
  },
  {
    id: "nova-rust",
    title: "Why Things Rust",
    emoji: "🔩",
    lines: [
      "Have you seen orange-brown crusty stuff on an old bike or gate? That's rust!",
      "Rust forms when iron or steel meets water and oxygen from the air for a long time.",
      "Paint and oil help protect metal from rusting by keeping the water out.",
    ],
    age: "8+",
    quiz: {
      q: "What does iron need to rust?",
      options: ["Water and oxygen", "Sunlight only", "Music"],
      answer: 0,
      explain: "Water and oxygen! That's why wet things rust.",
    },
  },
  {
    id: "nova-dissolving",
    title: "Disappearing Sugar",
    emoji: "🥄",
    lines: [
      "Stir some sugar into water. Where did it go? It dissolved!",
      "The sugar breaks into pieces too tiny to see, and spreads all through the water. Taste it, and it's still sweet!",
      "Sugar dissolves faster in warm water than cold. Ask a grown-up for warm tap water to test it.",
    ],
    tryIt: "With a grown-up, stir sugar into cold water and warm water. Which dissolves first?",
    quiz: {
      q: "Where does sugar go when it dissolves?",
      options: ["It spreads through the water in tiny pieces", "It vanishes forever", "It sinks and hides"],
      answer: 0,
      explain: "It's still there, just in pieces too tiny to see!",
    },
  },
  {
    id: "nova-how-we-see",
    title: "How Your Eyes See",
    emoji: "👀",
    lines: [
      "You can only see things when there's light. Light bounces off things and into your eyes!",
      "Your eyes send a message to your brain, and your brain works out what you're looking at.",
      "Never look straight at the Sun, not even with sunglasses. It can hurt your eyes forever.",
    ],
    quiz: {
      q: "Is it ever okay to stare straight at the Sun?",
      options: ["No, never", "Yes, with sunglasses", "Yes, for a minute"],
      answer: 0,
      explain: "Never! It can damage your eyes.",
    },
  },
  {
    id: "nova-sun-is-a-star",
    title: "Our Sun Is a Star",
    emoji: "⭐",
    lines: [
      "Guess what? The Sun is a star, just like the twinkly ones at night!",
      "It looks much bigger and brighter because it's so much closer to us.",
      "Stars seem to twinkle because the air above us is always moving and wobbling their light.",
    ],
    quiz: {
      q: "What is the Sun?",
      options: ["A star", "A planet", "A giant lamp"],
      answer: 0,
      explain: "A star! The closest one to Earth.",
    },
  },
  {
    id: "nova-southern-cross",
    title: "The Southern Cross",
    emoji: "🌠",
    lines: [
      "Look up on a clear night in Australia, and you might spot the Southern Cross!",
      "It's a group of bright stars shaped like a kite or a cross.",
      "It's on the Australian flag. And two bright stars nearby, called the Pointers, point right to it!",
    ],
    tryIt: "On a clear night, look up with a grown-up and try to find the Southern Cross.",
    quiz: {
      q: "Which flag has the Southern Cross on it?",
      options: ["The Australian flag", "No flag", "A pirate flag"],
      answer: 0,
      explain: "The Australian flag! It's our starry signpost.",
    },
  },
  {
    id: "nova-earths-orbit",
    title: "Our Trip Around the Sun",
    emoji: "🌍",
    lines: [
      "Earth travels around the Sun in a big loop called an orbit.",
      "One whole trip takes about 365 days. That's one year!",
      "Actually it's about 365 and a quarter days. So every four years, we usually add an extra day: 29 February!",
    ],
    age: "8+",
    quiz: {
      q: "How long does Earth take to go around the Sun?",
      options: ["About a year", "One day", "One week"],
      answer: 0,
      explain: "About 365 days. Happy trip-around-the-Sun day on your birthday!",
    },
  },
  {
    id: "nova-mirrors",
    title: "Mirror, Mirror",
    emoji: "🪞",
    lines: [
      "Smooth, shiny things like mirrors bounce light back neatly, so you see a reflection.",
      "Wave your right hand at a mirror. Your reflection seems to wave its left!",
      "That's why 'AMBULANCE' is often written backwards on the front, so drivers read it the right way in their mirrors.",
    ],
    tryIt: "Write your name on paper and hold it up to a mirror. What does it look like?",
    quiz: {
      q: "Why is 'AMBULANCE' written backwards on the front?",
      options: ["So drivers can read it in their mirrors", "It's a spelling mistake", "For decoration"],
      answer: 0,
      explain: "So drivers ahead read it the right way in their mirror!",
    },
  },
  {
    id: "nova-mixing-colours",
    title: "Mixing Paint Colours",
    emoji: "🎨",
    lines: [
      "With just three paint colours, red, yellow and blue, you can make lots more!",
      "Red and yellow make orange. Yellow and blue make green. Blue and red make purple.",
      "Mixing paint is like doing a little experiment every time you paint!",
    ],
    tryIt: "Mix yellow and blue paint and see what colour appears.",
    quiz: {
      q: "What do yellow and blue paint make?",
      options: ["Green", "Pink", "Orange"],
      answer: 0,
      explain: "Green! Like a frog.",
    },
  },
  {
    id: "nova-round-bubbles",
    title: "Why Bubbles Are Round",
    emoji: "🫧",
    lines: [
      "Even if you blow through a square wand, bubbles come out round! Hmm, why?",
      "A bubble's soapy skin is stretchy, and it pulls itself in as tightly as it can.",
      "A ball shape is the tightest way to wrap up the air inside. So bubbles are always round!",
    ],
    tryIt: "Bend a pipe cleaner into a star shape and blow bubbles. What shape are they?",
    quiz: {
      q: "What shape are free-floating bubbles?",
      options: ["Round", "Square", "Star-shaped"],
      answer: 0,
      explain: "Round! Their stretchy skin pulls into a ball.",
    },
  },
  {
    id: "nova-pepper-scatter",
    title: "The Scared Pepper Trick",
    emoji: "🧂",
    lines: [
      "Sprinkle ground pepper onto a plate of water. It floats on top.",
      "The water's surface is like a thin stretchy skin. Now touch the middle with a soapy finger.",
      "Whoosh! The pepper races to the edges, because the soap breaks the skin in the middle.",
    ],
    tryIt: "Try the pepper trick with a grown-up, then wash your hands.",
    quiz: {
      q: "What makes the pepper rush to the edges?",
      options: ["Soap breaks the water's skin", "The pepper is scared", "Wind"],
      answer: 0,
      explain: "Soap breaks the surface skin, and the pepper gets pulled outwards!",
    },
  },
  {
    id: "nova-earthquakes",
    title: "Why the Ground Shakes",
    emoji: "🌏",
    lines: [
      "Earth's outside is broken into giant pieces called plates, like a cracked eggshell.",
      "They move very slowly, and sometimes they get stuck, then slip suddenly. That shakes the ground: an earthquake!",
      "If you feel one, drop down, take cover under a sturdy table, and hold on.",
    ],
    age: "8+",
    funFact: "The whole continent of Australia creeps north by about 7 centimetres every year!",
    quiz: {
      q: "What should you do in an earthquake?",
      options: ["Drop, take cover and hold on", "Run outside past windows", "Jump up and down"],
      answer: 0,
      explain: "Drop, cover and hold on until the shaking stops.",
    },
  },
  {
    id: "nova-fossils",
    title: "Fossil Detectives",
    emoji: "🦕",
    lines: [
      "Long, long ago, when some plants and animals died, they were buried in mud or sand.",
      "Over millions of years, the mud turned into rock, and their shapes were saved in stone. These are fossils!",
      "Fossils help scientists learn about dinosaurs and creatures from long ago.",
    ],
    funFact: "Lots of dinosaur fossils have been found in outback Queensland, near a town called Winton.",
    quiz: {
      q: "How long do fossils take to form?",
      options: ["Millions of years", "One night", "About a week"],
      answer: 0,
      explain: "Millions of years! Very patient rocks.",
    },
  },
  {
    id: "nova-hot-air-rises",
    title: "Warm Air Rises",
    emoji: "🎈",
    lines: [
      "When air warms up, it spreads out, so it weighs less than the same amount of cool air. So warm air rises!",
      "That's how hot air balloons fly. A burner warms the air inside, and up they float.",
      "It's also why upstairs rooms often feel warmer than downstairs.",
    ],
    quiz: {
      q: "Which way does warm air move?",
      options: ["Up", "Down", "It doesn't move"],
      answer: 0,
      explain: "Up! That's how hot air balloons rise.",
    },
  },
  {
    id: "nova-cosy-jumper",
    title: "How Jumpers Keep You Warm",
    emoji: "🧶",
    lines: [
      "Does a jumper make heat? Hmm, surprise: no, it doesn't!",
      "Your body makes the heat. A jumper traps a layer of warm air next to you, so the heat can't escape as fast.",
      "Wrap an ice cube in a sock, and it melts slower, because the sock keeps the warm air away!",
    ],
    tryIt: "Put one ice cube in a sock and one on a plate. Which melts first?",
    quiz: {
      q: "Where does the warmth inside a jumper come from?",
      options: ["Your body", "The jumper makes it", "Tiny heaters"],
      answer: 0,
      explain: "Your body! The jumper just traps it in.",
    },
  },
  {
    id: "nova-circuits",
    title: "Electricity Loves a Loop",
    emoji: "🔋",
    lines: [
      "Electricity only flows when it has a complete loop to travel around. We call that loop a circuit.",
      "A torch works because the battery, wires and bulb make a full loop when you switch it on.",
      "Power points are dangerous, so never poke anything in them. Only do battery experiments with a grown-up.",
    ],
    age: "8+",
    funFact: "Tiny button batteries are dangerous if swallowed. If that ever happens, tell a grown-up straight away.",
    quiz: {
      q: "What does electricity need to flow?",
      options: ["A complete loop", "A broken wire", "A cup of water"],
      answer: 0,
      explain: "A complete loop, called a circuit!",
    },
  },
  {
    id: "nova-think-like-a-scientist",
    title: "Think Like a Scientist",
    emoji: "🔬",
    lines: [
      "Scientists find things out in steps. First, ask a question: which paper plane flies furthest?",
      "Next, make a guess. Then test it fairly, changing only one thing at a time.",
      "Finally, look at what happened. Was your guess right? Either way, you learned something!",
    ],
    tryIt: "Make two paper planes with different wings and test which flies further.",
    quiz: {
      q: "What's the first step of thinking like a scientist?",
      options: ["Ask a question", "Give up", "Pick the answer you like"],
      answer: 0,
      explain: "Ask a question! Then guess, test and look.",
    },
  },
  {
    id: "nova-cells",
    title: "Tiny Building Blocks",
    emoji: "🧫",
    lines: [
      "Every living thing is made of tiny building blocks called cells.",
      "Your body has trillions of them! Most are far too small to see without a microscope.",
      "There are skin cells, bone cells, blood cells, and many more, each with its own job.",
    ],
    age: "8+",
    quiz: {
      q: "What are living things made of?",
      options: ["Cells", "Lego", "Sand"],
      answer: 0,
      explain: "Cells! Tiny building blocks of life.",
    },
  },
  {
    id: "nova-echoes",
    title: "Echo, Echo, Echo",
    emoji: "🦇",
    lines: [
      "When you shout in a big empty hall or a canyon, you might hear an echo!",
      "An echo is your sound bouncing off a hard surface and coming back to your ears.",
      "Bats use echoes to find their way in the dark. They make squeaks and listen for them bouncing back!",
    ],
    quiz: {
      q: "What is an echo?",
      options: ["Sound bouncing back", "A kind of bird", "A rainbow"],
      answer: 0,
      explain: "Sound bouncing back to your ears!",
    },
  },
  {
    id: "nova-ice-floats",
    title: "Why Ice Floats",
    emoji: "🧊",
    lines: [
      "Most things shrink and get heavier for their size when they freeze solid. But water is different!",
      "When water freezes, it spreads out a little, so ice weighs less than the same amount of water. So ice floats!",
      "Because of this, lakes freeze from the top down, and fish can keep swimming in the water underneath.",
    ],
    age: "8+",
    tryIt: "Drop an ice cube into a glass of water. Does it float or sink?",
    quiz: {
      q: "What happens to water when it freezes?",
      options: ["It spreads out a little", "It shrinks to nothing", "It turns into sand"],
      answer: 0,
      explain: "It spreads out, which makes ice float!",
    },
  },
];

export const LESSONS_NOVA: Lesson[] = drafts.map((d) => ({ ...d, wizard: "nova" }));
