import type { Lesson, LessonDraft } from "../types";

// Sage Oakbeard, the Wizard of Wisdom. Gentle, slow, warm.
const drafts: LessonDraft[] = [
  {
    id: "sage-kind-words",
    title: "Kind Words Are Magic",
    emoji: "💬",
    lines: [
      "Words are a little like seeds, little one.",
      "Kind words grow happy feelings in other people. Unkind words can grow sad ones.",
      "Before you speak, you can ask yourself: is it kind?",
    ],
    tryIt: "Say one kind thing to three different people today.",
    quiz: {
      q: "What can you ask yourself before you speak?",
      options: ["Is it loud?", "Is it kind?", "Is it long?"],
      answer: 1,
      explain: "Yes! Asking 'is it kind?' helps your words grow happy feelings.",
    },
  },
  {
    id: "sage-balloon-breath",
    title: "Balloon Breathing",
    emoji: "🎈",
    lines: [
      "When big feelings bubble up, try balloon breathing with me.",
      "Breathe in slowly through your nose and fill your tummy like a balloon.",
      "Then let the air out slowly through your mouth... sssss. Do it three times.",
    ],
    tryIt: "Do three slow balloon breaths before bed tonight.",
    quiz: {
      q: "In balloon breathing, what fills up like a balloon?",
      options: ["Your tummy", "Your shoes", "Your hat"],
      answer: 0,
      explain: "That's it! Slow breaths into your tummy help your body feel calm.",
    },
  },
  {
    id: "sage-power-of-yet",
    title: "The Power of Yet",
    emoji: "🌱",
    lines: [
      "Hmm... have you ever said 'I can't do it'?",
      "Try adding one tiny word to the end: 'I can't do it YET.'",
      "'Yet' reminds your brain that you are still learning, and practice helps you grow.",
    ],
    tryIt: "Next time something is tricky, say 'I can't do it... yet!'",
    quiz: {
      q: "Which little word reminds you that you're still learning?",
      options: ["Never", "Yet", "Stop"],
      answer: 1,
      explain: "Yes! 'Yet' means you haven't got it so far, but you're on your way.",
    },
  },
  {
    id: "sage-mistakes-help",
    title: "Mistakes Help Us Grow",
    emoji: "🧩",
    lines: [
      "Everybody makes mistakes. Even very old wizards like me.",
      "A mistake is not a bad thing. It shows you what to try differently next time.",
      "So when you make one, take a breath and ask: what did I learn?",
    ],
    quiz: {
      q: "What's a good question to ask after a mistake?",
      options: ["Who can I blame?", "Why am I so bad?", "What did I learn?"],
      answer: 2,
      explain: "Well done! Every mistake has a little lesson hiding inside it.",
    },
  },
  {
    id: "sage-name-your-feeling",
    title: "Name That Feeling",
    emoji: "🌈",
    lines: [
      "Feelings have names, like happy, sad, cross, worried, excited or proud.",
      "When you can name a feeling, it often gets a little easier to handle.",
      "You can say, 'I feel worried,' to a grown-up you trust. That is very brave.",
    ],
    tryIt: "At dinner, share one feeling you had today and what made you feel it.",
    quiz: {
      q: "What can help a big feeling get a little easier?",
      options: ["Giving it a name", "Hiding it in a box", "Shouting at it"],
      answer: 0,
      explain: "Yes! Naming your feeling helps you and others understand it.",
    },
  },
  {
    id: "sage-three-good-things",
    title: "Three Good Things",
    emoji: "🙏",
    lines: [
      "Here is an old wizard habit. Each night, think of three good things from your day.",
      "They can be small, like a warm bath, a funny joke or a yummy apple.",
      "Noticing good things helps your heart feel thankful and happy.",
    ],
    tryIt: "Tonight in bed, whisper three good things that happened today.",
    quiz: {
      q: "Do your three good things need to be big and special?",
      options: ["Yes, only huge things count", "No, small things count too", "Only presents count"],
      answer: 1,
      explain: "Right! Little good things are some of the best ones to notice.",
    },
  },
  {
    id: "sage-saying-sorry",
    title: "Saying Sorry Well",
    emoji: "💛",
    lines: [
      "A good sorry has three parts, little one.",
      "Say what you did, say sorry, and say how you will make it better.",
      "Like: 'I bumped your tower. I'm sorry. Can I help you build it again?'",
    ],
    quiz: {
      q: "What's part of a really good sorry?",
      options: ["Saying it very fast", "Saying how you'll make it better", "Saying it was their fault"],
      answer: 1,
      explain: "Yes! Offering to fix things shows you really mean your sorry.",
    },
  },
  {
    id: "sage-truth-courage",
    title: "Telling the Truth",
    emoji: "🦁",
    lines: [
      "Telling the truth can feel scary, especially if you did something wrong.",
      "But the truth helps people trust you, and trust is a precious treasure.",
      "Being honest when it's hard is one of the bravest things you can do.",
    ],
    quiz: {
      q: "Why is telling the truth so important?",
      options: ["It helps people trust you", "It makes you taller", "It's never important"],
      answer: 0,
      explain: "That's right. Honesty builds trust, and trust keeps friendships strong.",
    },
  },
  {
    id: "sage-good-listener",
    title: "Be a Great Listener",
    emoji: "👂",
    lines: [
      "Listening is a gift you can give anyone.",
      "Look at the person, keep your body still, and wait until they finish.",
      "Then you can ask a question about what they said. That shows you really care.",
    ],
    tryIt: "Ask someone about their day and listen all the way to the end.",
    quiz: {
      q: "What does a great listener do?",
      options: ["Talks over people", "Waits until the person finishes", "Walks away"],
      answer: 1,
      explain: "Yes! Waiting and looking at someone shows them they matter.",
    },
  },
  {
    id: "sage-taking-turns",
    title: "Taking Turns",
    emoji: "🔄",
    lines: [
      "Games are more fun when everyone gets a go.",
      "Taking turns means sometimes you wait, and then it's your turn to shine.",
      "If waiting feels hard, you can count slowly or cheer for your friend.",
    ],
    quiz: {
      q: "What can you do while you wait for your turn?",
      options: ["Grab the toy", "Cheer for your friend", "Go home"],
      answer: 1,
      explain: "Lovely! Cheering makes waiting fun and makes your friend feel good.",
    },
  },
  {
    id: "sage-feelings-clouds",
    title: "Feelings Are Like Clouds",
    emoji: "☁️",
    lines: [
      "Feelings are like clouds drifting across the sky.",
      "Even a big grey storm cloud floats away in time.",
      "So when you feel sad or cross, remember: this feeling will pass.",
    ],
    quiz: {
      q: "What happens to big feelings, like storm clouds?",
      options: ["They stay forever", "They pass in time", "They turn into rocks"],
      answer: 1,
      explain: "Yes. Feelings come and go, and you'll feel calm again soon.",
    },
  },
  {
    id: "sage-brave-and-scared",
    title: "Brave Doesn't Mean Not Scared",
    emoji: "🛡️",
    lines: [
      "Did you know brave people still feel scared sometimes?",
      "Being brave means feeling a little scared, and trying anyway.",
      "Brave also means knowing when to say no and ask a grown-up for help.",
    ],
    quiz: {
      q: "What does being brave mean?",
      options: ["Never feeling scared", "Feeling scared and still trying", "Being the loudest"],
      answer: 1,
      explain: "Exactly! Courage is doing something even when you feel a bit wobbly.",
    },
  },
  {
    id: "sage-room-for-one-more",
    title: "Room for One More",
    emoji: "🪑",
    lines: [
      "Hmm... have you ever seen someone playing all alone?",
      "You can walk over and say, 'Do you want to play with us?'",
      "Those few words can turn someone's whole day around.",
    ],
    tryIt: "Invite someone new to join your game.",
    quiz: {
      q: "What can you say to someone playing alone?",
      options: ["Go away", "Do you want to play with us?", "Nothing, ever"],
      answer: 1,
      explain: "Yes! Including others is one of the kindest things you can do.",
    },
  },
  {
    id: "sage-count-to-ten",
    title: "Count to Ten",
    emoji: "🔟",
    lines: [
      "When you feel very cross, your body can get hot and your hands can get tight.",
      "Before you say or do anything, count slowly to ten in your head.",
      "Counting gives your wise brain time to catch up with your cross feelings.",
    ],
    quiz: {
      q: "Why is counting to ten helpful when you're cross?",
      options: ["It gives your brain time to calm down", "It makes you hungry", "It's a race"],
      answer: 0,
      explain: "Right! A little pause helps you choose what to do next.",
    },
  },
  {
    id: "sage-helping-unasked",
    title: "Helping Without Being Asked",
    emoji: "🤲",
    lines: [
      "Here is a secret: the best helpers look around and notice what needs doing.",
      "Maybe the shoes need lining up, or someone's hands are full.",
      "When you help without being asked, people feel so cared for.",
    ],
    tryIt: "Find one job to help with at home before anyone asks.",
    quiz: {
      q: "What do the best helpers do?",
      options: ["Wait to be told ten times", "Notice what needs doing", "Hide"],
      answer: 1,
      explain: "Yes! Noticing and helping is a real wizard skill.",
    },
  },
  {
    id: "sage-patience-power",
    title: "Patience Is a Superpower",
    emoji: "⏳",
    lines: [
      "An oak tree grows from a tiny acorn. It takes years and years.",
      "Some good things take time, like learning to read or growing a garden.",
      "Patience means waiting calmly and keeping going. It is a quiet superpower.",
    ],
    funFact: "Oak trees can live for hundreds of years, and some for over a thousand.",
    quiz: {
      q: "What does patience mean?",
      options: ["Giving up quickly", "Waiting calmly and keeping going", "Rushing everything"],
      answer: 1,
      explain: "That's right. Patient people keep going, just like a growing oak.",
    },
  },
  {
    id: "sage-real-compliment",
    title: "Give a Real Compliment",
    emoji: "🌟",
    lines: [
      "A compliment is saying something nice about someone.",
      "The best ones are about what people DO, like 'You were so patient with your sister.'",
      "A real compliment can stay in someone's heart all day.",
    ],
    tryIt: "Give someone a compliment about something they did, not what they wear.",
    quiz: {
      q: "Which is a compliment about something someone did?",
      options: ["You helped me so kindly", "You're in my way", "I'm bored"],
      answer: 0,
      explain: "Yes! Noticing kind actions makes people feel really seen.",
    },
  },
  {
    id: "sage-in-their-shoes",
    title: "In Someone Else's Shoes",
    emoji: "👟",
    lines: [
      "Here's a wise trick. Imagine you are standing in someone else's shoes.",
      "How would you feel if you were them right now?",
      "Understanding how others feel is called empathy, and it makes you a wonderful friend.",
    ],
    quiz: {
      q: "What is empathy?",
      options: ["Understanding how others feel", "A type of shoe", "Running fast"],
      answer: 0,
      explain: "Right! Empathy means imagining how someone else feels.",
    },
  },
  {
    id: "sage-ask-for-help",
    title: "Asking for Help Is Smart",
    emoji: "🙋",
    lines: [
      "Some people think asking for help means you're not clever. That isn't true!",
      "Even the wisest wizards ask for help. It's how we learn new things.",
      "You can say, 'Can you help me, please? I'm stuck on this part.'",
    ],
    quiz: {
      q: "Is asking for help a smart thing to do?",
      options: ["No, never ask", "Yes, it helps you learn", "Only on Tuesdays"],
      answer: 1,
      explain: "Yes! Smart people ask for help when they're stuck.",
    },
  },
  {
    id: "sage-body-clues",
    title: "Your Body Gives Clues",
    emoji: "💓",
    lines: [
      "Your body often tells you how you feel, before your words do.",
      "A racing heart, hot cheeks or a wobbly tummy can be clues of worry or anger.",
      "When you notice a clue, stop and ask yourself: how am I feeling?",
    ],
    quiz: {
      q: "Which could be a body clue that you feel worried?",
      options: ["A wobbly tummy", "Growing taller", "Your hair turning blue"],
      answer: 0,
      explain: "Yes. A wobbly tummy can be your body's way of saying 'I'm worried'.",
    },
  },
  {
    id: "sage-calm-corner",
    title: "Make a Calm Corner",
    emoji: "🧸",
    lines: [
      "Everyone needs a cosy place to settle big feelings.",
      "A calm corner might have a soft cushion, a teddy and a favourite book.",
      "You can go there to breathe and rest until you feel ready again.",
    ],
    tryIt: "Ask a grown-up to help you set up a little calm corner at home.",
    quiz: {
      q: "What is a calm corner for?",
      options: ["Settling big feelings", "Hiding vegetables", "Jumping on"],
      answer: 0,
      explain: "Right. It's a cosy spot to rest and breathe when feelings are big.",
    },
  },
  {
    id: "sage-five-senses-calm",
    title: "The 5-4-3-2-1 Calm Trick",
    emoji: "🖐️",
    lines: [
      "When worries swirl, try this: find 5 things you can see and 4 you can touch.",
      "Then 3 things you can hear, 2 you can smell, and 1 you can taste.",
      "Using your senses brings your busy mind back to right here, right now.",
    ],
    quiz: {
      q: "In the 5-4-3-2-1 trick, what do you use?",
      options: ["Your senses", "A calculator", "A ball"],
      answer: 0,
      explain: "Yes! Seeing, touching, hearing, smelling and tasting help you feel calm.",
    },
  },
  {
    id: "sage-sharing",
    title: "Sharing Makes More Fun",
    emoji: "🍪",
    lines: [
      "When you share, a funny thing happens. The fun gets bigger, not smaller!",
      "Sharing toys, snacks or turns shows your friends you care about them.",
      "And it's okay to have a special thing you keep safe. Just share what you can.",
    ],
    quiz: {
      q: "What often happens to fun when you share?",
      options: ["It disappears", "It gets bigger", "It turns sour"],
      answer: 1,
      explain: "Right! Playing together is usually more fun than playing alone.",
    },
  },
  {
    id: "sage-good-sport",
    title: "Being a Good Sport",
    emoji: "🏅",
    lines: [
      "Winning feels nice. Losing can feel yucky. Both are part of playing games.",
      "A good sport says 'good game' whether they win or lose.",
      "Good sports are the people everyone wants to play with again.",
    ],
    quiz: {
      q: "What does a good sport say after a game?",
      options: ["That's not fair!", "Good game!", "I quit!"],
      answer: 1,
      explain: "Yes! 'Good game' shows you care about the fun, not just winning.",
    },
  },
  {
    id: "sage-thank-you-note",
    title: "The Magic of Thank You",
    emoji: "✉️",
    lines: [
      "Saying thank you tells people you noticed what they did for you.",
      "You can say it, draw it, or write a little thank-you note.",
      "A thank-you note can make someone smile for days.",
    ],
    tryIt: "Draw a thank-you picture for someone who helped you this week.",
    quiz: {
      q: "What does saying thank you show?",
      options: ["You noticed what they did", "You want more", "Nothing at all"],
      answer: 0,
      explain: "That's right. Thank you shows you noticed their kindness.",
    },
  },
  {
    id: "sage-kind-self-talk",
    title: "Talk to Yourself Kindly",
    emoji: "🗣️",
    lines: [
      "You have a little voice inside your head. It talks to you all day.",
      "Try to make it a kind voice, like a friend: 'You can do this. Keep going.'",
      "Be as kind to yourself as you would be to your best friend.",
    ],
    quiz: {
      q: "How should your inside voice talk to you?",
      options: ["Kindly, like a good friend", "Grumpily", "In a scary way"],
      answer: 0,
      explain: "Yes! A kind inside voice helps you feel strong and brave.",
    },
  },
  {
    id: "sage-friends-disagree",
    title: "When Friends Disagree",
    emoji: "🤝",
    lines: [
      "Even the best of friends disagree sometimes. That's normal.",
      "Take turns to say what you want, and really listen to each other.",
      "Then look for an idea you both like, like taking turns or playing both games.",
    ],
    quiz: {
      q: "What can friends do when they disagree?",
      options: ["Never talk again", "Listen and find an idea they both like", "Shout louder"],
      answer: 1,
      explain: "Lovely. Listening and sharing ideas helps fix most disagreements.",
    },
  },
  {
    id: "sage-i-feel-words",
    title: "Using 'I Feel' Words",
    emoji: "💭",
    lines: [
      "When someone upsets you, try starting with 'I feel...' instead of 'You always...'",
      "For example: 'I feel sad when I'm left out. Can I join in next time?'",
      "'I feel' words help people listen, instead of feeling blamed.",
    ],
    age: "8+",
    quiz: {
      q: "Which is an 'I feel' sentence?",
      options: ["You always ruin it!", "I feel sad when I'm left out.", "Go away!"],
      answer: 1,
      explain: "Yes! Sharing your feeling calmly helps others understand you.",
    },
  },
  {
    id: "sage-small-steps",
    title: "Big Jobs, Small Steps",
    emoji: "🪜",
    lines: [
      "Hmm... a big job can feel like a mountain.",
      "But every mountain is climbed one small step at a time.",
      "Break your big job into little pieces, and do just the first piece.",
    ],
    tryIt: "Pick a big job and write or draw its three small steps.",
    quiz: {
      q: "How do you climb a big job 'mountain'?",
      options: ["One small step at a time", "All in one giant jump", "You don't"],
      answer: 0,
      explain: "That's it. Small steps add up to big things.",
    },
  },
  {
    id: "sage-try-something-new",
    title: "Try Something New",
    emoji: "🍓",
    lines: [
      "New things can feel a bit strange at first, like a new food or a new game.",
      "But if you never try, you'll never know if it could be your new favourite!",
      "Try a tiny bit first. That is how brave explorers start.",
    ],
    tryIt: "Try one small bite of a food you haven't tried before.",
    quiz: {
      q: "How can you start trying something new?",
      options: ["Try a tiny bit first", "Refuse forever", "Cry right away"],
      answer: 0,
      explain: "Yes! A tiny try is a big brave step.",
    },
  },
  {
    id: "sage-gentle-creatures",
    title: "Gentle With Little Creatures",
    emoji: "🐞",
    lines: [
      "Ladybirds, snails and ants are small, but their lives matter too.",
      "Watch them gently, and let them go on their way.",
      "Being kind to little creatures is a sign of a big, kind heart.",
    ],
    quiz: {
      q: "How should you treat little creatures?",
      options: ["Gently", "Roughly", "Squish them"],
      answer: 0,
      explain: "Yes. Watching gently keeps both you and the creature happy.",
    },
  },
  {
    id: "sage-stand-up-for-others",
    title: "Standing Up for Others",
    emoji: "🙌",
    lines: [
      "If you see someone being teased or left out, you can help.",
      "You can stand with them, say 'That's not kind,' or invite them to play.",
      "And always tell a grown-up you trust. Telling is not dobbing when someone is hurt.",
    ],
    quiz: {
      q: "If someone is being teased, what's a good thing to do?",
      options: ["Join in", "Tell a grown-up you trust", "Pretend you didn't see"],
      answer: 1,
      explain: "Right. Telling a trusted grown-up helps keep everyone safe.",
    },
  },
  {
    id: "sage-keep-promises",
    title: "Keep Your Promises",
    emoji: "🤞",
    lines: [
      "A promise is when you tell someone you will surely do something.",
      "When you keep your promises, people know they can count on you.",
      "So only promise what you truly can do.",
    ],
    quiz: {
      q: "What should you promise?",
      options: ["Only what you can really do", "Everything, always", "Impossible things"],
      answer: 0,
      explain: "Yes! Careful promises are promises you can keep.",
    },
  },
  {
    id: "sage-jealous-feelings",
    title: "When You Feel Jealous",
    emoji: "💚",
    lines: [
      "Sometimes when a friend gets something we want, we feel jealous.",
      "That feeling is normal. Everyone feels it sometimes.",
      "Try saying 'Well done!' to your friend, and think of something good in your own life.",
    ],
    age: "8+",
    quiz: {
      q: "Is feeling jealous sometimes normal?",
      options: ["Yes, everyone feels it", "No, only baddies do", "Only wizards feel it"],
      answer: 0,
      explain: "That's right. What matters is how kindly we act with the feeling.",
    },
  },
  {
    id: "sage-worry-box",
    title: "The Worry Box",
    emoji: "📦",
    lines: [
      "Worries can feel heavy when we carry them around all day.",
      "Try drawing or writing your worry and popping it into a special box.",
      "Then later, open the box with a grown-up you trust and talk about it together.",
    ],
    tryIt: "Decorate a small box to be your worry box.",
    quiz: {
      q: "What do you do with the worries in your worry box?",
      options: ["Talk about them with a trusted grown-up", "Throw the box at someone", "Eat them"],
      answer: 0,
      explain: "Yes. Sharing worries with a trusted grown-up makes them feel smaller.",
    },
  },
  {
    id: "sage-cheer-for-others",
    title: "Cheer for Others",
    emoji: "🎉",
    lines: [
      "When a friend does something great, it's lovely to cheer for them.",
      "Their happiness doesn't take away from yours. There's plenty to go around.",
      "People who cheer for others often find lots of people cheering for them too.",
    ],
    quiz: {
      q: "Does a friend's success take away from yours?",
      options: ["No, there's plenty to go around", "Yes, always", "Only if they're taller"],
      answer: 0,
      explain: "Right! You can be happy for others and happy for yourself too.",
    },
  },
  {
    id: "sage-forgiving",
    title: "Forgiving Frees Your Heart",
    emoji: "🕊️",
    lines: [
      "When someone says sorry, you can choose to forgive them.",
      "Forgiving means letting go of the cross feeling, so it stops weighing on your heart.",
      "It doesn't mean what they did was okay. It means you're ready to move on.",
    ],
    age: "8+",
    quiz: {
      q: "What does forgiving someone mean?",
      options: ["Letting go of the cross feeling", "Pretending nothing happened", "Getting even"],
      answer: 0,
      explain: "Yes. Forgiving helps your own heart feel free and peaceful.",
    },
  },
  {
    id: "sage-different-is-wonderful",
    title: "Different Is Wonderful",
    emoji: "🌍",
    lines: [
      "People come from different places, speak different languages and look different.",
      "Imagine a garden with only one kind of flower. Wouldn't that be a bit boring?",
      "Our differences make the world more colourful and interesting.",
    ],
    quiz: {
      q: "What do our differences make the world?",
      options: ["More colourful and interesting", "Boring", "Grey"],
      answer: 0,
      explain: "Yes! Just like a garden full of different flowers.",
    },
  },
  {
    id: "sage-bubble-space",
    title: "Your Bubble Space",
    emoji: "🫧",
    lines: [
      "Everyone has an invisible bubble of space around their body.",
      "Some people like hugs, and some like a bit more space. Both are okay.",
      "Asking 'Can I have a hug?' shows you respect someone's bubble.",
    ],
    quiz: {
      q: "What's a kind thing to do before hugging someone?",
      options: ["Ask first", "Run at them", "Squeeze really hard"],
      answer: 0,
      explain: "Right. Asking first respects their bubble space.",
    },
  },
  {
    id: "sage-surprises-not-secrets",
    title: "Surprises, Not Secrets",
    emoji: "🎁",
    lines: [
      "A surprise, like a birthday present, is fun to keep because everyone finds out soon.",
      "But a secret that makes you feel worried, scared or confused should never be kept.",
      "Always tell a grown-up you trust. You will never be in trouble for telling.",
    ],
    quiz: {
      q: "What should you do with a secret that makes you feel worried?",
      options: ["Keep it forever", "Tell a grown-up you trust", "Forget about it"],
      answer: 1,
      explain: "Yes. Worried-feeling secrets should always be shared with a trusted grown-up.",
    },
  },
  {
    id: "sage-quiet-in-nature",
    title: "Quiet Time in Nature",
    emoji: "🍃",
    lines: [
      "When your mind feels busy, step outside for a few quiet minutes.",
      "Listen for birds, feel the breeze, and watch the leaves move.",
      "Nature is very good at helping busy minds feel calm.",
    ],
    tryIt: "Sit outside quietly for two minutes and count the sounds you hear.",
    quiz: {
      q: "What can quiet time in nature help with?",
      options: ["Calming a busy mind", "Making you grumpy", "Nothing"],
      answer: 0,
      explain: "Yes. Birds, breeze and trees help us feel peaceful.",
    },
  },
  {
    id: "sage-proud-of-effort",
    title: "Be Proud of Your Effort",
    emoji: "💪",
    lines: [
      "Hmm... it's nice to get things right. But trying hard matters even more.",
      "When you practise and keep going, your brain grows stronger, like a muscle.",
      "So be proud of your hard work, not just the result.",
    ],
    quiz: {
      q: "What should you feel proud of?",
      options: ["Only winning", "Your hard work and effort", "Nothing"],
      answer: 1,
      explain: "Yes! Effort is how you grow, whatever the result.",
    },
  },
  {
    id: "sage-its-ok-to-say-no",
    title: "It's Okay to Say No",
    emoji: "🚦",
    lines: [
      "Your body belongs to you. If a touch or game doesn't feel okay, you can say 'No!' or 'Stop!'",
      "You can say it loudly and clearly, and move away.",
      "Then tell a grown-up you trust. Your feelings about your body matter.",
    ],
    quiz: {
      q: "If a game or touch doesn't feel okay, what can you say?",
      options: ["Nothing, just put up with it", "No! or Stop!", "Do it more"],
      answer: 1,
      explain: "Yes. You can always say no, and tell a grown-up you trust.",
    },
  },
  {
    id: "sage-thoughts-not-facts",
    title: "Thoughts Aren't Always True",
    emoji: "🔍",
    lines: [
      "Sometimes our minds tell us things like 'Nobody likes me' or 'I'm bad at everything.'",
      "Be a detective! Ask: what is the real evidence? Is it really true?",
      "Usually you'll find the thought was a worry, not a fact.",
    ],
    age: "8+",
    quiz: {
      q: "What can you do with a gloomy thought?",
      options: ["Check the evidence like a detective", "Believe it straight away", "Shout it out"],
      answer: 0,
      explain: "Great! Checking the evidence helps you see what's really true.",
    },
  },
  {
    id: "sage-family-team",
    title: "Family Is a Team",
    emoji: "🏡",
    lines: [
      "A family is a bit like a team. Everyone helps so home runs smoothly.",
      "When you do your jobs, like feeding the pet or packing away toys, you help the whole team.",
      "Teams that help each other have more time for fun together.",
    ],
    tryIt: "Ask your family, 'What can I help with today?'",
    quiz: {
      q: "Why are chores like being on a team?",
      options: ["Everyone helps so home runs smoothly", "Only one person does everything", "Teams don't help"],
      answer: 0,
      explain: "Yes! When everyone helps, there's more time for fun.",
    },
  },
];

export const LESSONS_SAGE: Lesson[] = drafts.map((d) => ({ ...d, wizard: "sage" }));
