import type { Lesson, LessonDraft } from "../types";

// Tinker Wren, the Wizard of Clever Tricks. Mischievous, loves a secret shortcut.
const drafts: LessonDraft[] = [
  {
    id: "tinker-knuckle-months",
    title: "Months on Your Knuckles",
    emoji: "✊",
    lines: [
      "Psst! Your fist is secretly a calendar. Make a fist and touch your first knuckle: January!",
      "Then the dip: February. Next knuckle: March. After July, start again on the first knuckle for August.",
      "Knuckle months have 31 days. Dip months have 30, except sneaky February with 28 or 29!",
    ],
    tryIt: "Use your knuckles to find out how many days are in your birthday month.",
    funFact: "July and August are both knuckle months, so they both have 31 days.",
    quiz: {
      q: "If a month lands on a knuckle, how many days does it have?",
      options: ["31", "30", "28"],
      answer: 0,
      explain: "31! Knuckles are the long months.",
    },
  },
  {
    id: "tinker-left-hand-l",
    title: "The Left-Hand L",
    emoji: "🤚",
    lines: [
      "Can't remember which side is left? Hehe, here's my trick.",
      "Hold both hands out in front of you, palms facing away. Stick your pointer fingers and thumbs out.",
      "One hand makes a proper letter L. That's your Left hand!",
    ],
    tryIt: "Try the L trick, then point left and right five times, super fast.",
    quiz: {
      q: "Which hand makes the letter L?",
      options: ["Your left hand", "Your right hand", "Your foot"],
      answer: 0,
      explain: "Your left! L for Left.",
    },
  },
  {
    id: "tinker-compass-weetbix",
    title: "Never Eat Soggy Weet-Bix",
    emoji: "🧭",
    lines: [
      "Here's how clever explorers remember a compass: Never Eat Soggy Weet-Bix!",
      "Start at the top and go around like a clock: North, East, South, West.",
      "Soggy Weet-Bix... yuck! That's exactly why you won't forget it.",
    ],
    quiz: {
      q: "What does the E in 'Never Eat Soggy Weet-Bix' stand for?",
      options: ["Everywhere", "East", "Elephant"],
      answer: 1,
      explain: "East! North, East, South, West.",
    },
  },
  {
    id: "tinker-bunny-ears",
    title: "Bunny Ears Shoelaces",
    emoji: "🐰",
    lines: [
      "Tying shoelaces is easier with bunny ears! First, cross the laces and tuck one under to make a knot.",
      "Now make each lace into a loop. Those are the bunny's ears!",
      "Cross the ears, tuck one under through the hole, and pull both ears tight. Ta-da!",
    ],
    tryIt: "Practise bunny ears on a shoe sitting on the table, where you can see it easily.",
    quiz: {
      q: "In the bunny ears trick, what do you make each lace into?",
      options: ["A loop", "A ball", "A knot in the middle of your hair"],
      answer: 0,
      explain: "A loop! Two loops make two bunny ears.",
    },
  },
  {
    id: "tinker-tshirt-fold",
    title: "Speedy T-Shirt Fold",
    emoji: "👕",
    lines: [
      "Lay your t-shirt flat on the bed, face down, and smooth it out.",
      "Fold one side and its sleeve into the middle. Then fold the other side in too.",
      "Now fold it in half from the bottom up. Neat as a shop!",
    ],
    tryIt: "Fold three t-shirts the speedy way and stack them in your drawer.",
    quiz: {
      q: "What's the last step of the speedy fold?",
      options: ["Fold it in half from the bottom up", "Throw it in the air", "Scrunch it up"],
      answer: 0,
      explain: "Yes! Bottom up, and you've got a neat little rectangle.",
    },
  },
  {
    id: "tinker-five-minute-tidy",
    title: "The Five-Minute Tidy",
    emoji: "⏱️",
    lines: [
      "Hehe, here's my secret: messy rooms get tidy fast when you race a timer!",
      "Ask a grown-up to set a timer for five minutes.",
      "Do one kind of thing at a time: first all the books, then all the clothes, then all the toys.",
    ],
    tryIt: "Do a five-minute tidy race today. How much can you put away?",
    quiz: {
      q: "What's the trick to tidying fast?",
      options: ["Do one kind of thing at a time", "Hide it under the bed", "Wait for it to tidy itself"],
      answer: 0,
      explain: "Yes! Books, then clothes, then toys. Zoom!",
    },
  },
  {
    id: "tinker-bag-night-before",
    title: "Pack Your Bag Tonight",
    emoji: "🎒",
    lines: [
      "Mornings can be a mad rush. Here's a sneaky way to beat it.",
      "Pack your school bag the night before: hat, reader, homework and drink bottle.",
      "Pop it by the door. Morning you will say, 'Thanks, night-time me!'",
    ],
    tryIt: "Before bed, pack your bag and leave it by the front door.",
    quiz: {
      q: "When is the sneaky time to pack your school bag?",
      options: ["The night before", "When you're already late", "Never"],
      answer: 0,
      explain: "The night before! Calm mornings, happy you.",
    },
  },
  {
    id: "tinker-nines-finger-trick",
    title: "The Nines Finger Trick",
    emoji: "🖐️",
    lines: [
      "Hold up all ten fingers. Want to know 9 times 3? Fold down your third finger from the left.",
      "Count the fingers before the folded one: 2. Count the fingers after it: 7.",
      "Put them together: 27! It works for 9 times 1 up to 9 times 10.",
    ],
    age: "8+",
    tryIt: "Use your fingers to work out 9 times 7. Then check it with a grown-up.",
    quiz: {
      q: "For 9 times 4, which finger do you fold down?",
      options: ["The fourth finger", "The ninth finger", "Your thumb, always"],
      answer: 0,
      explain: "The fourth! Then you see 3 and 6: 36.",
    },
  },
  {
    id: "tinker-spell-because",
    title: "Spelling 'Because'",
    emoji: "🐘",
    lines: [
      "'Because' is a tricky word. But I have a silly sentence for it.",
      "Big Elephants Can Always Understand Small Elephants.",
      "Take the first letter of each word: B-E-C-A-U-S-E. Because!",
    ],
    quiz: {
      q: "What's the silly sentence for 'because'?",
      options: ["Big Elephants Can Always Understand Small Elephants", "Bananas Eat Cake", "Bees Can't Swim"],
      answer: 0,
      explain: "Big Elephants Can Always Understand Small Elephants!",
    },
  },
  {
    id: "tinker-remember-names",
    title: "Never Forget a Name",
    emoji: "📛",
    lines: [
      "When you meet someone new, say their name back straight away: 'Hi, Maya!'",
      "Then link it to something, like 'Maya likes mangoes.' M and M!",
      "Use their name once more when you say goodbye. Now it's stuck in your brain!",
    ],
    quiz: {
      q: "What should you do right after hearing someone's name?",
      options: ["Say it back to them", "Forget it", "Change it"],
      answer: 0,
      explain: "Say it back! Saying it helps your brain keep it.",
    },
  },
  {
    id: "tinker-sleepy-body-trick",
    title: "The Sleepy Body Trick",
    emoji: "😴",
    lines: [
      "Can't fall asleep? Lie still and pretend your body is slowly melting like an ice cream.",
      "Start with your toes. Let them go floppy. Then your legs, your tummy, your arms, your face.",
      "Breathe slowly the whole time. Many people are asleep before they reach their head!",
    ],
    tryIt: "Tonight in bed, try melting from your toes all the way to your nose.",
    quiz: {
      q: "Where does the sleepy body trick start?",
      options: ["Your toes", "Your ears", "Your pillow"],
      answer: 0,
      explain: "Your toes! Then melt upwards, nice and slowly.",
    },
  },
  {
    id: "tinker-banana-bottom",
    title: "Peel a Banana Upside Down",
    emoji: "🍌",
    lines: [
      "Is your banana stem too tough to snap? Hehe, flip it over!",
      "Gently pinch the little dark tip at the bottom until the skin splits.",
      "Then peel it down from there. No squashed banana!",
    ],
    tryIt: "Peel your next banana from the bottom.",
    quiz: {
      q: "Where do you pinch to peel a banana the sneaky way?",
      options: ["The little tip at the bottom", "The middle", "You bite it"],
      answer: 0,
      explain: "The bottom tip! Pinch, split, peel.",
    },
  },
  {
    id: "tinker-rainbow-order",
    title: "Remember the Rainbow",
    emoji: "🌈",
    lines: [
      "Want to remember the colours of a rainbow in order? Meet my friend Roy G. Biv!",
      "R-O-Y G B-I-V: red, orange, yellow, green, blue, indigo, violet.",
      "Say 'Roy G. Biv' like it's someone's name, and you'll always know it.",
    ],
    quiz: {
      q: "What colour does the G in Roy G. Biv stand for?",
      options: ["Grey", "Green", "Gold"],
      answer: 1,
      explain: "Green! Right in the middle of the rainbow.",
    },
  },
  {
    id: "tinker-planet-sentence",
    title: "The Planet Sentence",
    emoji: "🪐",
    lines: [
      "Eight planets in order? Easy peasy with this sentence:",
      "My Very Easy Method Just Speeds Up Naming.",
      "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune!",
    ],
    age: "8+",
    quiz: {
      q: "In 'My Very Easy Method', which planet is 'Easy'?",
      options: ["Earth", "Mars", "Neptune"],
      answer: 0,
      explain: "Earth! The third planet from the Sun.",
    },
  },
  {
    id: "tinker-elevens",
    title: "The Easy Elevens",
    emoji: "🎯",
    lines: [
      "Here's a cheeky one. For 11 times any number from 1 to 9, just write the number twice!",
      "11 times 3? Write 3 twice: 33. 11 times 7? 77!",
      "It's the easiest times table there is. Shhh, don't tell!",
    ],
    quiz: {
      q: "What's 11 times 5?",
      options: ["55", "15", "5"],
      answer: 0,
      explain: "55! Just write the 5 twice.",
    },
  },
  {
    id: "tinker-double-double",
    title: "Double Double for Fours",
    emoji: "✌️",
    lines: [
      "Times by 4 feels tricky? Just double the number, then double it again!",
      "4 times 6: double 6 is 12, double 12 is 24.",
      "Double, double, done! Hehe.",
    ],
    age: "8+",
    quiz: {
      q: "What's 4 times 5 using double double?",
      options: ["20", "10", "45"],
      answer: 0,
      explain: "Double 5 is 10, double 10 is 20!",
    },
  },
  {
    id: "tinker-clock-fives",
    title: "Fives on the Clock",
    emoji: "🕒",
    lines: [
      "Look at a clock with hands. Each number is worth 5 minutes for the long hand!",
      "When the long hand points at 3, it's 15 minutes past. That's 3 times 5!",
      "So a clock is really a secret five times table, hiding on the wall.",
    ],
    quiz: {
      q: "The long hand points at 2. How many minutes past is it?",
      options: ["2 minutes", "10 minutes", "20 minutes"],
      answer: 1,
      explain: "10 minutes! 2 times 5 is 10.",
    },
  },
  {
    id: "tinker-times-ten",
    title: "Tens Get a Zero",
    emoji: "🔟",
    lines: [
      "To times a whole number by 10, just stick a zero on the end!",
      "4 times 10 is 40. 12 times 10 is 120.",
      "It's like the number gets a shiny new zero hat.",
    ],
    quiz: {
      q: "What's 7 times 10?",
      options: ["17", "70", "700"],
      answer: 1,
      explain: "70! Put a zero on the end of the 7.",
    },
  },
  {
    id: "tinker-spell-necessary",
    title: "Spelling 'Necessary'",
    emoji: "👔",
    lines: [
      "'Necessary' trips everyone up. Here's my trick: a shirt has one collar and two sleeves.",
      "So 'necessary' has one C and two S's!",
      "N-E-C-E-S-S-A-R-Y. Now you're spelling like a wizard.",
    ],
    age: "8+",
    quiz: {
      q: "How many S's are in 'necessary'?",
      options: ["One", "Two", "Three"],
      answer: 1,
      explain: "Two! Like two sleeves on a shirt.",
    },
  },
  {
    id: "tinker-dessert-desert",
    title: "Dessert or Desert?",
    emoji: "🍨",
    lines: [
      "Dessert is the yummy treat after dinner. Desert is a dry, sandy place.",
      "Here's the trick: dessert has two S's, because you always want seconds!",
      "Desert has just one S, for all that sand.",
    ],
    quiz: {
      q: "Which word means the yummy treat?",
      options: ["Desert", "Dessert", "Dissert"],
      answer: 1,
      explain: "Dessert! Two S's, for seconds.",
    },
  },
  {
    id: "tinker-b-d-bed",
    title: "The b and d Bed",
    emoji: "🛏️",
    lines: [
      "Do b and d get mixed up? Try this. Make two fists with thumbs up, palms facing each other.",
      "Your left hand looks like a b, and your right hand looks like a d.",
      "Together they make a bed! b comes first, just like in 'bed'.",
    ],
    tryIt: "Make the bed with your hands, then write b and d three times each.",
    quiz: {
      q: "In the bed trick, which letter does your left hand make?",
      options: ["b", "d", "q"],
      answer: 0,
      explain: "b! Left hand b, right hand d, together: bed.",
    },
  },
  {
    id: "tinker-sock-bundles",
    title: "Sock Buddies",
    emoji: "🧦",
    lines: [
      "Lost socks drive grown-ups bonkers. Here's how to keep sock buddies together.",
      "Lay two socks of a pair on top of each other and roll them up from the toe.",
      "Then tuck the roll into the top of one sock. A sock ball that can't escape!",
    ],
    tryIt: "Find five pairs of socks and roll them into sock balls.",
    quiz: {
      q: "How do you keep a pair of socks together?",
      options: ["Roll them into a sock ball", "Throw one away", "Wear them on your hands"],
      answer: 0,
      explain: "Sock ball! No more lonely socks.",
    },
  },
  {
    id: "tinker-morning-checklist",
    title: "The Morning Checklist",
    emoji: "📋",
    lines: [
      "Do you forget things in the morning? Make a checklist!",
      "Draw little pictures: brush teeth, get dressed, breakfast, shoes, bag.",
      "Stick it on your door and tick each one. Your brain gets a holiday!",
    ],
    tryIt: "Draw a picture checklist for your morning and stick it up.",
    quiz: {
      q: "Where's a good place to stick your morning checklist?",
      options: ["On your door", "Inside the fridge", "Under the carpet"],
      answer: 0,
      explain: "On your door, where you'll see it every morning.",
    },
  },
  {
    id: "tinker-work-and-wiggle",
    title: "Work, Then Wiggle",
    emoji: "🕺",
    lines: [
      "Brains focus best in little bursts. Here's my trick: work, then wiggle!",
      "Do your homework or practice for 10 minutes. Then have a 2-minute wiggle break.",
      "Then back to work. Your brain stays fresh, like a just-baked cookie.",
    ],
    tryIt: "Try one round of 10 minutes of work and a 2-minute wiggle break.",
    quiz: {
      q: "What comes after 10 minutes of work?",
      options: ["A short wiggle break", "A three-hour nap", "More work, forever"],
      answer: 0,
      explain: "A wiggle break! Then your brain is ready again.",
    },
  },
  {
    id: "tinker-chunk-numbers",
    title: "Chunk Your Numbers",
    emoji: "📞",
    lines: [
      "Long numbers are hard to remember in one go. So chop them into chunks!",
      "Instead of ten numbers in a row, remember three little groups, like 0412, 345, 678.",
      "It's a great way to learn a grown-up's phone number off by heart.",
    ],
    age: "8+",
    tryIt: "Learn your grown-up's phone number in chunks. Say it to them to check.",
    quiz: {
      q: "What makes a long number easier to remember?",
      options: ["Chopping it into chunks", "Saying it backwards", "Whispering it once"],
      answer: 0,
      explain: "Chunks! Small groups are easier for your brain.",
    },
  },
  {
    id: "tinker-silly-story",
    title: "The Silly Story Trick",
    emoji: "🤪",
    lines: [
      "Need to remember a list? Turn it into a silly story!",
      "Milk, bread, apples? Picture a cow in a bread boat, throwing apples at seagulls!",
      "The sillier the story, the better your brain remembers it. Hehe!",
    ],
    tryIt: "Next shopping trip, remember three things with a silly story.",
    quiz: {
      q: "What kind of story helps you remember best?",
      options: ["A really silly one", "A boring one", "No story at all"],
      answer: 0,
      explain: "Silly ones! Brains love funny pictures.",
    },
  },
  {
    id: "tinker-carry-a-cup",
    title: "Carry a Cup Without Spilling",
    emoji: "🥛",
    lines: [
      "Here's a sneaky spill-stopper. Don't fill your cup right to the top.",
      "Hold it with two hands, and walk slowly.",
      "And look where you're going, so you don't trip over a toy on the floor!",
    ],
    quiz: {
      q: "How full should you fill a cup you need to carry?",
      options: ["Right to the very top", "Not all the way to the top", "Overflowing"],
      answer: 1,
      explain: "Not to the top! A little space means fewer spills.",
    },
  },
  {
    id: "tinker-coat-flip",
    title: "The Magic Coat Flip",
    emoji: "🧥",
    lines: [
      "Can't get your jacket on? Try the magic flip!",
      "Lay your jacket on the floor, inside facing up, with the hood by your toes.",
      "Push your arms into the sleeves, then flip it up over your head. Whoosh, it's on!",
    ],
    tryIt: "Try the coat flip three times. Can you do it faster each time?",
    quiz: {
      q: "Where should the hood be before you flip?",
      options: ["By your toes", "Far away from you", "On your head already"],
      answer: 0,
      explain: "By your toes! Then arms in and flip.",
    },
  },
  {
    id: "tinker-shoe-sticker",
    title: "The Shoe Sticker Trick",
    emoji: "👟",
    lines: [
      "Shoes on the wrong feet again? Hehe, here's a fix.",
      "Ask a grown-up to cut a sticker in half, and put one half inside each shoe.",
      "Put your shoes side by side. When the picture joins up, they're the right way round!",
    ],
    quiz: {
      q: "How do you know your shoes are the right way round?",
      options: ["The sticker picture joins up", "They feel funny", "They're different colours"],
      answer: 0,
      explain: "The sticker joins up! Easy peasy.",
    },
  },
  {
    id: "tinker-two-minute-teeth",
    title: "Two-Minute Teeth",
    emoji: "🪥",
    lines: [
      "Dentists say to brush your teeth for two minutes, twice a day.",
      "Two minutes feels long, so here's a trick: brush while you hum a favourite song.",
      "Or split your mouth into four parts and brush each part while you count to 30.",
    ],
    tryIt: "Brush for a whole song tonight. Top, bottom, front and back!",
    quiz: {
      q: "How long should you brush your teeth?",
      options: ["About two minutes", "Two seconds", "Two hours"],
      answer: 0,
      explain: "About two minutes, morning and night.",
    },
  },
  {
    id: "tinker-hungry-crocodile",
    title: "The Hungry Crocodile",
    emoji: "🐊",
    lines: [
      "The signs < and > look confusing. But pretend they're a hungry crocodile's mouth!",
      "The crocodile always opens its mouth towards the bigger number, because it's greedy.",
      "So 8 > 3 means 8 is bigger than 3. Chomp!",
    ],
    quiz: {
      q: "Which way does the crocodile mouth open?",
      options: ["Towards the bigger number", "Towards the smaller number", "Upwards"],
      answer: 0,
      explain: "Towards the bigger number, because it's greedy!",
    },
  },
  {
    id: "tinker-righty-tighty",
    title: "Righty Tighty, Lefty Loosey",
    emoji: "🔩",
    lines: [
      "Can't open a jar lid or bottle cap? Remember: righty tighty, lefty loosey!",
      "Turn it to the right to make it tighter. Turn it to the left to loosen it.",
      "It works for most lids and screws. If it's really stuck, ask a grown-up.",
    ],
    quiz: {
      q: "Which way do you turn a lid to loosen it?",
      options: ["Left", "Right", "Upside down"],
      answer: 0,
      explain: "Lefty loosey!",
    },
  },
  {
    id: "tinker-there-their-theyre",
    title: "There, Their or They're?",
    emoji: "📍",
    lines: [
      "Three words that sound the same! Here's the trick.",
      "'There' has the word 'here' hiding inside it. It's about places: over there!",
      "'Their' means it belongs to them. 'They're' is a squished-up 'they are'.",
    ],
    age: "8+",
    quiz: {
      q: "Which word means 'they are'?",
      options: ["There", "Their", "They're"],
      answer: 2,
      explain: "They're! The little mark shows letters were squished out.",
    },
  },
  {
    id: "tinker-stationery-e",
    title: "Stationery Has an E",
    emoji: "✉️",
    lines: [
      "Stationery with an E means paper, pens and envelopes. E for envelopes!",
      "Stationary with an A means standing still, like a parked car. A for 'at a stop'.",
      "Now you know which one to write on your shopping list!",
    ],
    age: "8+",
    quiz: {
      q: "Which spelling means pens and paper?",
      options: ["Stationary", "Stationery", "Stayshunery"],
      answer: 1,
      explain: "Stationery, with an E for envelopes!",
    },
  },
  {
    id: "tinker-check-by-adding",
    title: "Check Your Take-Aways",
    emoji: "✅",
    lines: [
      "Here's a sneaky way to check a take-away sum: add it back up!",
      "If 12 take away 5 is 7, then 7 add 5 should make 12. It does!",
      "If it doesn't, you know to have another look.",
    ],
    age: "8+",
    quiz: {
      q: "How can you check 10 take away 4 equals 6?",
      options: ["Add 6 and 4 to see if you get 10", "Guess", "Take away again"],
      answer: 0,
      explain: "6 add 4 is 10, so you got it right!",
    },
  },
  {
    id: "tinker-best-friends-of-ten",
    title: "Best Friends of Ten",
    emoji: "👯",
    lines: [
      "Some numbers are best friends because they add up to 10!",
      "1 and 9, 2 and 8, 3 and 7, 4 and 6, and 5 and 5.",
      "Learn these buddies and adding gets super speedy.",
    ],
    tryIt: "Hold up some fingers. How many are folded down? Together they make 10!",
    quiz: {
      q: "Which number is 3's best friend to make 10?",
      options: ["7", "5", "3"],
      answer: 0,
      explain: "7! 3 and 7 make 10.",
    },
  },
  {
    id: "tinker-count-on",
    title: "Count On From the Big One",
    emoji: "➕",
    lines: [
      "Adding 2 plus 8? Don't start counting from 2. That's the slow way!",
      "Start from the bigger number, 8, and count on: 9, 10.",
      "The answer is 10. Always start from the big one. Hehe, sneaky!",
    ],
    quiz: {
      q: "For 3 plus 9, which number should you start counting from?",
      options: ["9", "3", "1"],
      answer: 0,
      explain: "9! Then count on: 10, 11, 12.",
    },
  },
  {
    id: "tinker-soggy-shoes",
    title: "Drying Soggy Shoes",
    emoji: "🥾",
    lines: [
      "Stomped in a puddle? Hehe, me too. Here's how to dry soggy shoes.",
      "Take out the laces and scrunch old newspaper up inside them. It soaks up the water.",
      "Swap in fresh paper later, and leave the shoes somewhere airy, away from heaters.",
    ],
    quiz: {
      q: "What can you stuff inside wet shoes to dry them?",
      options: ["Scrunched-up newspaper", "Wet socks", "Jelly"],
      answer: 0,
      explain: "Newspaper! It soaks up the water.",
    },
  },
  {
    id: "tinker-drip-catcher",
    title: "The Ice Block Drip Catcher",
    emoji: "🍦",
    lines: [
      "Ice blocks drip down your hand on hot days. Sticky!",
      "Poke the stick through the middle of a paper cupcake case.",
      "The case catches the drips, and your fingers stay clean. Genius!",
    ],
    tryIt: "Next time you have an ice block, add a cupcake case drip catcher.",
    quiz: {
      q: "What catches the drips in this trick?",
      options: ["A paper cupcake case", "Your sleeve", "A sponge on your head"],
      answer: 0,
      explain: "A cupcake case! Poke the stick through the middle.",
    },
  },
  {
    id: "tinker-teach-it",
    title: "Teach It to Learn It",
    emoji: "🧑‍🏫",
    lines: [
      "Want to remember something you learned? Hehe, teach it to someone else!",
      "Explain it to a family member, a friend or even your teddy.",
      "When you explain things, your brain works out the tricky parts and holds on tight.",
    ],
    tryIt: "Teach one of today's tricks to someone in your family.",
    quiz: {
      q: "What's a great way to remember something you learned?",
      options: ["Teach it to someone else", "Never think about it again", "Hide the book"],
      answer: 0,
      explain: "Teach it! Even teddy counts as a student.",
    },
  },
  {
    id: "tinker-sleep-on-it",
    title: "Sleep Helps You Learn",
    emoji: "🌙",
    lines: [
      "Here's a sneaky secret: your brain keeps working while you sleep!",
      "At night, it sorts through what you learned and helps store it away.",
      "So practising before bed, then a good night's sleep, is a super learning trick.",
    ],
    quiz: {
      q: "What does your brain do while you sleep?",
      options: ["Helps store what you learned", "Switches off completely", "Forgets everything"],
      answer: 0,
      explain: "It helps store your learning. Sleep is brain magic!",
    },
  },
  {
    id: "tinker-hand-ruler",
    title: "Your Hand Is a Ruler",
    emoji: "📏",
    lines: [
      "Spread your hand out wide. The distance from thumb tip to little finger tip is your hand span.",
      "Measure it once with a ruler. Then you can use your hand to guess how long things are!",
      "No ruler? No problem. You carry one on the end of your arm. Hehe.",
    ],
    tryIt: "Measure your hand span with a ruler, then measure your bed in hand spans.",
    quiz: {
      q: "What is a hand span?",
      options: ["Thumb tip to little finger tip, spread wide", "How long you can clap", "A kind of pan"],
      answer: 0,
      explain: "Right! Spread wide, thumb to little finger.",
    },
  },
  {
    id: "tinker-reef-knot",
    title: "The Reef Knot",
    emoji: "🪢",
    lines: [
      "Sailors use the reef knot to tie two ends together. Here's the rhyme:",
      "Right over left and under. Then left over right and under.",
      "Pull it tight, and you'll see a neat, flat knot. If it looks twisted, try again!",
    ],
    age: "8+",
    tryIt: "Practise a reef knot with two pieces of string or two scarves.",
    quiz: {
      q: "What's the second step of the reef knot?",
      options: ["Left over right and under", "Right over right", "Cut the string"],
      answer: 0,
      explain: "Left over right and under! Then pull tight.",
    },
  },
  {
    id: "tinker-home-for-everything",
    title: "A Home for Everything",
    emoji: "🏠",
    lines: [
      "Things get lost when they don't have a home. So give everything a home!",
      "Shoes live by the door. Hats live on a hook. Pencils live in a cup.",
      "When you finish with something, send it home. You'll never hunt for it again!",
    ],
    tryIt: "Choose a home for three things you often lose.",
    quiz: {
      q: "Why do things get lost?",
      options: ["They don't have a home", "They run away at night", "Goblins"],
      answer: 0,
      explain: "No home! Give them one, and they'll always be there.",
    },
  },
  {
    id: "tinker-clock-hands",
    title: "Short Hand, Long Hand",
    emoji: "🕰️",
    lines: [
      "A clock with hands has a short hand and a long hand.",
      "The short hand shows the hour. It's short, like the word 'hour' is short!",
      "The long hand shows the minutes. When it points straight up at 12, it's 'o'clock'.",
    ],
    quiz: {
      q: "Which clock hand shows the hour?",
      options: ["The short hand", "The long hand", "The second hand"],
      answer: 0,
      explain: "The short hand! The long one does the minutes.",
    },
  },
];

export const LESSONS_TINKER: Lesson[] = drafts.map((d) => ({ ...d, wizard: "tinker" }));
