import type { Lesson, LessonDraft } from "../types";

// Professor Twinkle, the Trivia Wizard. Excitable, amazed by everything.
const drafts: LessonDraft[] = [
  {
    id: "twinkle-octopus-hearts",
    title: "Three Hearts, Blue Blood!",
    emoji: "🐙",
    lines: [
      "Great galaxies! An octopus has THREE hearts!",
      "Two hearts pump blood to its gills, and one pumps blood around its body.",
      "And its blood is blue, not red! Isn't that wonderfully weird?",
    ],
    funFact: "An octopus has eight arms, and each arm is covered in suckers that can taste and feel.",
    quiz: {
      q: "How many hearts does an octopus have?",
      options: ["One", "Three", "Ten"],
      answer: 1,
      explain: "Three! Two for the gills and one for the body.",
    },
  },
  {
    id: "twinkle-sun-size",
    title: "The Super-Sized Sun",
    emoji: "☀️",
    lines: [
      "Sparkling stars! The Sun is SO big that about 1.3 million Earths could fit inside it.",
      "It only looks small because it's very, very far away.",
      "The Sun is a star, and it's the closest star to Earth.",
    ],
    quiz: {
      q: "About how many Earths could fit inside the Sun?",
      options: ["About 10", "About 1.3 million", "Only 1"],
      answer: 1,
      explain: "About 1.3 million! The Sun is enormous.",
    },
  },
  {
    id: "twinkle-blue-whale",
    title: "The Biggest Animal Alive",
    emoji: "🐋",
    lines: [
      "Great galaxies! The blue whale is the biggest animal alive today.",
      "It can grow up to about 30 metres long. That's longer than two buses!",
      "And this giant eats some of the tiniest food in the sea: little shrimp-like krill.",
    ],
    tryIt: "Ask a grown-up to take 30 big steps outside. That's about how long a blue whale can be!",
    quiz: {
      q: "What's the biggest animal alive today?",
      options: ["The elephant", "The blue whale", "The giraffe"],
      answer: 1,
      explain: "The blue whale! It's even bigger than an elephant, by a lot.",
    },
  },
  {
    id: "twinkle-baby-bones",
    title: "Babies Have More Bones",
    emoji: "🦴",
    lines: [
      "Here's a wowzer: babies are born with around 300 bones!",
      "Grown-ups only have 206. So where do the others go?",
      "As you grow, some small bones join together to make bigger, stronger bones.",
    ],
    age: "8+",
    quiz: {
      q: "Why do grown-ups have fewer bones than babies?",
      options: ["Some bones join together", "They lose them in the wash", "Bones melt"],
      answer: 0,
      explain: "Right! Little bones fuse together as you grow.",
    },
  },
  {
    id: "twinkle-wombat-cubes",
    title: "Wombats Do Cube Poo",
    emoji: "🟫",
    lines: [
      "Hold onto your hat! Wombats do poo shaped like little cubes!",
      "They leave them on rocks and logs to tell other wombats, 'This is my spot!'",
      "Scientists think the cube shape helps the poo stay put instead of rolling away.",
    ],
    quiz: {
      q: "What shape is wombat poo?",
      options: ["Round like a ball", "Cube-shaped", "Star-shaped"],
      answer: 1,
      explain: "Cubes! Wombats are the only animals known to do it.",
    },
  },
  {
    id: "twinkle-platypus",
    title: "The Platypus Puzzle",
    emoji: "🦆",
    lines: [
      "The platypus is a mammal, but it lays eggs! Great galaxies!",
      "When it hunts underwater, it closes its eyes and ears.",
      "Its bill can sense the tiny electric signals made by little creatures moving.",
    ],
    funFact: "Only two kinds of mammals lay eggs: the platypus and the echidna. Both live in Australia.",
    quiz: {
      q: "What's surprising about the platypus?",
      options: ["It's a mammal that lays eggs", "It can fly", "It lives in the desert"],
      answer: 0,
      explain: "Yes! Mammals that lay eggs are very rare.",
    },
  },
  {
    id: "twinkle-venus-day",
    title: "A Day Longer Than a Year",
    emoji: "🪐",
    lines: [
      "Brain-boggler alert! On Venus, one day is longer than one year!",
      "Venus spins very slowly. One spin takes about 243 Earth days.",
      "But it goes all the way around the Sun in only about 225 Earth days.",
    ],
    age: "8+",
    funFact: "Venus is the hottest planet, even hotter than Mercury, which is closer to the Sun.",
    quiz: {
      q: "On Venus, which is longer?",
      options: ["A day", "A year", "They're the same"],
      answer: 0,
      explain: "A day! Venus spins so slowly that one day beats one year.",
    },
  },
  {
    id: "twinkle-honey",
    title: "Honey Keeps for Ages",
    emoji: "🍯",
    lines: [
      "Bees make honey from the sweet nectar inside flowers.",
      "Sealed-up honey can last for an incredibly long time without going bad.",
      "That's because germs find it very hard to grow in thick, sugary honey!",
    ],
    quiz: {
      q: "What do bees make honey from?",
      options: ["Flower nectar", "Leaves", "Rain"],
      answer: 0,
      explain: "Yes! Bees collect sweet nectar from flowers.",
    },
  },
  {
    id: "twinkle-great-wall-myth",
    title: "The Great Wall Myth",
    emoji: "🧱",
    lines: [
      "The Great Wall of China is super long, more than 20,000 kilometres with all its parts!",
      "Some people say you can see it from the Moon. Myth-busted! You can't.",
      "It's very long, but it's thin, and it's a similar colour to the land around it.",
    ],
    quiz: {
      q: "Can you see the Great Wall of China from the Moon?",
      options: ["Yes, easily", "No, that's a myth", "Only at night"],
      answer: 1,
      explain: "It's a myth! The wall is too thin to see from that far away.",
    },
  },
  {
    id: "twinkle-heartbeats",
    title: "Your Busy Heart",
    emoji: "❤️",
    lines: [
      "Your heart is about the size of your fist.",
      "It beats about 100,000 times every single day, even while you sleep!",
      "Running and playing makes it beat faster, and that helps keep it strong.",
    ],
    tryIt: "Put your hand on your chest. Feel your heartbeat, then jump 10 times and feel again!",
    quiz: {
      q: "About how big is your heart?",
      options: ["The size of your fist", "The size of a car", "The size of a pea"],
      answer: 0,
      explain: "Yes! Make a fist. That's about how big your heart is.",
    },
  },
  {
    id: "twinkle-joey-jellybean",
    title: "A Jellybean Joey",
    emoji: "🦘",
    lines: [
      "When a baby kangaroo is born, it's only about the size of a jellybean!",
      "The tiny joey crawls all by itself into its mum's pouch.",
      "It stays snug in there for months, drinking milk and growing big.",
    ],
    tryIt: "Hold a jellybean in your hand and imagine a baby kangaroo that tiny!",
    quiz: {
      q: "How big is a newborn kangaroo?",
      options: ["About the size of a jellybean", "As big as a dog", "As big as its mum"],
      answer: 0,
      explain: "Teeny tiny! About the size of a jellybean.",
    },
  },
  {
    id: "twinkle-everest",
    title: "The Tallest Mountain",
    emoji: "🏔️",
    lines: [
      "Mount Everest is the tallest mountain above sea level on Earth.",
      "It's about 8,849 metres tall. That's nearly nine kilometres up!",
      "At the top, the air is so thin that most climbers carry bottles of oxygen.",
    ],
    quiz: {
      q: "What's the tallest mountain above sea level?",
      options: ["Mount Everest", "Uluru", "Mount Kosciuszko"],
      answer: 0,
      explain: "Everest! It's nearly nine kilometres high.",
    },
  },
  {
    id: "twinkle-cheetah",
    title: "The Speedy Cheetah",
    emoji: "🐆",
    lines: [
      "Zoom! The cheetah is the fastest land animal in the world.",
      "In short bursts it can run around 100 kilometres an hour, like a car on a highway!",
      "But it gets tired quickly, so it can only sprint for a short time.",
    ],
    quiz: {
      q: "What's the fastest land animal?",
      options: ["The cheetah", "The snail", "The koala"],
      answer: 0,
      explain: "The cheetah! Zoom zoom!",
    },
  },
  {
    id: "twinkle-antarctica-desert",
    title: "The Biggest Desert Is Icy",
    emoji: "🧊",
    lines: [
      "What's the biggest desert in the world? Not a sandy one... it's Antarctica!",
      "A desert is a place that gets very little rain or snow. Antarctica gets very little.",
      "It's also the coldest place on Earth. Brrr!",
    ],
    age: "8+",
    quiz: {
      q: "What makes a place a desert?",
      options: ["It gets very little rain or snow", "It must be hot", "It must have camels"],
      answer: 0,
      explain: "Yes! Deserts are dry, and they can be hot or icy cold.",
    },
  },
  {
    id: "twinkle-koala-sleep",
    title: "Sleepy Koalas",
    emoji: "🐨",
    lines: [
      "Koalas can sleep for about 18 to 20 hours a day! What sleepyheads!",
      "They eat gum leaves, which don't give them much energy, so they rest a lot.",
      "And koalas are not bears. They're marsupials, like kangaroos.",
    ],
    tryIt: "Count how many hours you sleep tonight. Koalas sleep almost twice as long!",
    quiz: {
      q: "Are koalas bears?",
      options: ["Yes", "No, they're marsupials", "They're birds"],
      answer: 1,
      explain: "Right! Koalas are marsupials. Mums carry babies in a pouch.",
    },
  },
  {
    id: "twinkle-saturn-float",
    title: "Saturn Could Float!",
    emoji: "🪐",
    lines: [
      "Saturn is a giant planet made mostly of gas.",
      "It's so light for its size that, if you had a bathtub big enough, it would float!",
      "Its beautiful rings are made of chunks of ice and rock.",
    ],
    quiz: {
      q: "What are Saturn's rings made of?",
      options: ["Ice and rock", "Jelly", "String"],
      answer: 0,
      explain: "Ice and rock! Billions of pieces spin around Saturn.",
    },
  },
  {
    id: "twinkle-mars-red",
    title: "Why Mars Is Red",
    emoji: "🔴",
    lines: [
      "Mars is called the Red Planet. But why is it red?",
      "Its ground is covered in dust with rusty iron in it. Rust is reddish!",
      "So Mars is a bit like a giant rusty ball in space.",
    ],
    funFact: "Mars has the tallest volcano in the solar system, called Olympus Mons.",
    quiz: {
      q: "Why does Mars look red?",
      options: ["It's covered in rusty dust", "It's on fire", "It's painted"],
      answer: 0,
      explain: "Rusty dust! That's what gives Mars its colour.",
    },
  },
  {
    id: "twinkle-tongue-map-myth",
    title: "The Tongue Map Myth",
    emoji: "👅",
    lines: [
      "Some old books showed a 'tongue map', with sweet only at the tip and bitter at the back.",
      "Myth-busted! All the parts of your tongue with taste buds can taste all the tastes.",
      "Sweet, salty, sour, bitter and savoury: your whole tongue joins in!",
    ],
    tryIt: "Put a tiny bit of honey on different parts of your tongue. Can you taste it everywhere?",
    quiz: {
      q: "Which part of your tongue can taste sweet things?",
      options: ["Only the tip", "Only the back", "All the parts with taste buds"],
      answer: 2,
      explain: "Right! The tongue map was a myth.",
    },
  },
  {
    id: "twinkle-goldfish-memory",
    title: "Goldfish Remember!",
    emoji: "🐠",
    lines: [
      "Have you heard goldfish only remember things for three seconds? Myth-busted!",
      "Scientists have trained goldfish to remember things for months.",
      "Some even learn when feeding time is and swim over to wait!",
    ],
    quiz: {
      q: "Do goldfish really forget everything after three seconds?",
      options: ["Yes", "No, they can remember for months", "They can't remember at all"],
      answer: 1,
      explain: "It's a myth! Goldfish are smarter than people think.",
    },
  },
  {
    id: "twinkle-bulls-red-myth",
    title: "Bulls and the Red Cape",
    emoji: "🐂",
    lines: [
      "People say bulls get angry when they see red. Myth-busted!",
      "Bulls can't see red the way we do.",
      "It's the waving and moving of a cape that gets their attention, not its colour.",
    ],
    quiz: {
      q: "What really catches a bull's attention?",
      options: ["The colour red", "Movement", "Singing"],
      answer: 1,
      explain: "Movement! The colour doesn't matter to a bull.",
    },
  },
  {
    id: "twinkle-pyramids",
    title: "The Great Pyramid",
    emoji: "🔺",
    lines: [
      "The Great Pyramid in Egypt was built about 4,500 years ago!",
      "It's made of more than two million huge stone blocks.",
      "For about 3,800 years it was the tallest thing people had ever built.",
    ],
    age: "8+",
    quiz: {
      q: "Where is the Great Pyramid?",
      options: ["Egypt", "Antarctica", "The Moon"],
      answer: 0,
      explain: "Egypt! It's one of the oldest wonders in the world.",
    },
  },
  {
    id: "twinkle-uluru",
    title: "Magnificent Uluru",
    emoji: "🪨",
    lines: [
      "In the middle of Australia stands Uluru, a giant rock about 348 metres tall.",
      "It's a very special, sacred place for the Anangu people, its Traditional Owners.",
      "At sunset it seems to glow bright orange and red. Breathtaking!",
    ],
    tryIt: "Find Uluru on a map of Australia. Look near the middle!",
    quiz: {
      q: "Who are the Traditional Owners of Uluru?",
      options: ["The Anangu people", "The penguins", "Nobody"],
      answer: 0,
      explain: "The Anangu people have cared for Uluru for a very long time.",
    },
  },
  {
    id: "twinkle-coathanger",
    title: "The Coathanger Bridge",
    emoji: "🌉",
    lines: [
      "The Sydney Harbour Bridge opened way back in 1932!",
      "Its big curved arch gave it a funny nickname: 'the Coathanger'.",
      "Trains, cars, bikes and people walking all cross it every day.",
    ],
    quiz: {
      q: "What's the Sydney Harbour Bridge's nickname?",
      options: ["The Coathanger", "The Spoon", "The Noodle"],
      answer: 0,
      explain: "The Coathanger! Because of its curved arch shape.",
    },
  },
  {
    id: "twinkle-emu-dads",
    title: "Super Emu Dads",
    emoji: "🥚",
    lines: [
      "Emus can't fly, but they can run up to about 50 kilometres an hour!",
      "Here's the amazing part: emu dads sit on the eggs to keep them warm.",
      "They sit for about eight weeks and hardly eat or drink the whole time!",
    ],
    quiz: {
      q: "Who sits on emu eggs to keep them warm?",
      options: ["The mum", "The dad", "A kangaroo"],
      answer: 1,
      explain: "The dad! Emu dads are egg-cellent.",
    },
  },
  {
    id: "twinkle-sunlight-trip",
    title: "Sunlight's Long Trip",
    emoji: "🌅",
    lines: [
      "Light is the fastest thing there is. But the Sun is very far away.",
      "So sunlight takes about 8 minutes to travel from the Sun to Earth!",
      "That means the sunshine on your face left the Sun about 8 minutes ago.",
    ],
    quiz: {
      q: "How long does sunlight take to reach Earth?",
      options: ["About 8 minutes", "About 8 years", "No time at all"],
      answer: 0,
      explain: "About 8 minutes! Speedy, but it's a long way.",
    },
  },
  {
    id: "twinkle-moon-footprints",
    title: "Footprints on the Moon",
    emoji: "👣",
    lines: [
      "In 1969, astronaut Neil Armstrong became the first person to walk on the Moon.",
      "The Moon has no wind or rain to wash footprints away.",
      "So the astronauts' footprints could stay there for a very, very long time!",
    ],
    quiz: {
      q: "Who was the first person to walk on the Moon?",
      options: ["Neil Armstrong", "Captain Cook", "Professor Twinkle"],
      answer: 0,
      explain: "Neil Armstrong, in 1969! (Sadly, I wasn't invited.)",
    },
  },
  {
    id: "twinkle-hummingbird",
    title: "Birds That Fly Backwards",
    emoji: "🐦",
    lines: [
      "Hummingbirds are one of the only birds that can fly backwards!",
      "Their wings flap so fast they make a humming sound. That's how they got their name.",
      "They live in the Americas, so you won't see one flying wild in Australia.",
    ],
    quiz: {
      q: "How did hummingbirds get their name?",
      options: ["Their fast wings make a humming sound", "They sing songs", "They love hummus"],
      answer: 0,
      explain: "Their super-fast wings hum as they flap!",
    },
  },
  {
    id: "twinkle-fingerprints",
    title: "Your One-of-a-Kind Fingerprints",
    emoji: "☝️",
    lines: [
      "Look closely at your fingertip. See the swirly lines? Those are your fingerprints.",
      "Nobody else in the world has fingerprints exactly like yours, not even an identical twin!",
      "Police sometimes use fingerprints to work out who touched something.",
    ],
    funFact: "Koalas have fingerprints that look amazingly like human ones!",
    tryIt: "Press your finger on a pencil smudge, then onto paper, and look at your swirls.",
    quiz: {
      q: "Do identical twins have the same fingerprints?",
      options: ["Yes, exactly the same", "No, everyone's are different", "They don't have any"],
      answer: 1,
      explain: "Everyone's fingerprints are different, even twins!",
    },
  },
  {
    id: "twinkle-elephant-trunk",
    title: "The Terrific Trunk",
    emoji: "🐘",
    lines: [
      "An elephant's trunk is its nose and top lip joined together!",
      "It uses it to smell, breathe, grab food, and even say hello to friends.",
      "To drink, it sucks water into its trunk, then squirts it into its mouth. Splash!",
    ],
    funFact: "When elephants swim, they can hold their trunk up high like a snorkel.",
    quiz: {
      q: "What is an elephant's trunk?",
      options: ["Its nose and top lip", "Its tail", "A kind of suitcase"],
      answer: 0,
      explain: "Its nose and top lip, joined together into one amazing tool!",
    },
  },
  {
    id: "twinkle-jupiter-storm",
    title: "Jupiter's Giant Storm",
    emoji: "🌪️",
    lines: [
      "Jupiter is the biggest planet in our solar system.",
      "It has a giant storm called the Great Red Spot.",
      "That storm is wider than the whole Earth, and it has been swirling for more than 150 years!",
    ],
    quiz: {
      q: "Which is the biggest planet in our solar system?",
      options: ["Earth", "Jupiter", "Mars"],
      answer: 1,
      explain: "Jupiter! It's a true giant.",
    },
  },
  {
    id: "twinkle-body-water",
    title: "You're Mostly Water!",
    emoji: "💧",
    lines: [
      "More than half of your body is made of water! Great galaxies!",
      "Water helps carry food around your body and keeps you cool.",
      "That's why drinking water every day is so important.",
    ],
    tryIt: "Have a big glass of water with your next meal.",
    quiz: {
      q: "About how much of your body is water?",
      options: ["None of it", "More than half", "Just your tears"],
      answer: 1,
      explain: "More than half! You're a walking water bottle.",
    },
  },
  {
    id: "twinkle-bee-dance",
    title: "The Bee Waggle Dance",
    emoji: "🐝",
    lines: [
      "When a honeybee finds lots of flowers, it flies home and does a dance!",
      "It's called the waggle dance. The bee wiggles its body in a special pattern.",
      "The dance tells the other bees which way to fly and how far to go. Clever!",
    ],
    tryIt: "Make up a waggle dance to show your family where the fruit bowl is.",
    quiz: {
      q: "Why do honeybees do the waggle dance?",
      options: ["To show where flowers are", "Because they're bored", "To scare birds"],
      answer: 0,
      explain: "Yes! The dance is a map for the other bees.",
    },
  },
  {
    id: "twinkle-little-penguins",
    title: "Little Aussie Penguins",
    emoji: "🐧",
    lines: [
      "Almost all penguins live in the southern half of the world, like us!",
      "The smallest penguin of all is the little penguin, and it lives in Australia.",
      "It's only about 30 centimetres tall, about as tall as a ruler.",
    ],
    funFact: "At Phillip Island in Victoria, little penguins waddle up the beach at sunset.",
    tryIt: "Waddle like a penguin across the room with your arms by your sides.",
    quiz: {
      q: "Which is the smallest penguin?",
      options: ["The emperor penguin", "The little penguin", "The giant penguin"],
      answer: 1,
      explain: "The little penguin! It's small and lives right here in Australia.",
    },
  },
  {
    id: "twinkle-pacific",
    title: "The Enormous Pacific",
    emoji: "🌊",
    lines: [
      "The Pacific Ocean is the biggest ocean on Earth.",
      "It's so big that all the land in the world could fit inside it, with room to spare!",
      "Australia's east coast looks out over the Pacific.",
    ],
    tryIt: "Find the Pacific Ocean on a map or globe. Can you see Australia next to it?",
    quiz: {
      q: "What's the biggest ocean on Earth?",
      options: ["The Pacific Ocean", "The bathtub", "The Indian Ocean"],
      answer: 0,
      explain: "The Pacific! It's bigger than all the land put together.",
    },
  },
  {
    id: "twinkle-lyrebird",
    title: "The Copycat Lyrebird",
    emoji: "🪶",
    lines: [
      "The lyrebird is an Aussie bird that's a champion copycat!",
      "It can copy the songs of lots of other birds.",
      "Some have even copied sounds like camera clicks, car alarms and chainsaws!",
    ],
    funFact: "There's a lyrebird on the Australian 10-cent coin.",
    tryIt: "Listen outside and try copying three different bird calls you hear.",
    quiz: {
      q: "What is the lyrebird famous for?",
      options: ["Copying sounds", "Swimming", "Digging tunnels"],
      answer: 0,
      explain: "Copying sounds! It's one of the best mimics in the world.",
    },
  },
  {
    id: "twinkle-dinosaur-birds",
    title: "Birds Are Dinosaurs!",
    emoji: "🦖",
    lines: [
      "Scientists have found that birds come from a group of dinosaurs.",
      "Some dinosaurs even had feathers, just like birds!",
      "So the next time you see a magpie, you're looking at a distant dinosaur cousin.",
    ],
    age: "8+",
    quiz: {
      q: "Which animals come from dinosaurs?",
      options: ["Birds", "Cats", "Fish"],
      answer: 0,
      explain: "Birds! Some dinosaurs even had feathers.",
    },
  },
  {
    id: "twinkle-olympics",
    title: "The Olympics Are Ancient",
    emoji: "🏃",
    lines: [
      "The first Olympic Games were held in ancient Greece nearly 3,000 years ago!",
      "Sydney hosted the Olympics in the year 2000.",
      "And Brisbane is set to host them in 2032. Go, go, go!",
    ],
    quiz: {
      q: "Where were the first Olympic Games held?",
      options: ["Ancient Greece", "Brisbane", "The North Pole"],
      answer: 0,
      explain: "Ancient Greece, nearly 3,000 years ago!",
    },
  },
  {
    id: "twinkle-mountain-ash",
    title: "Australia's Giant Tree",
    emoji: "🌳",
    lines: [
      "The mountain ash is a kind of gum tree that grows in Victoria and Tasmania.",
      "It's the tallest flowering plant in the whole world!",
      "Some are about 100 metres tall. That's as tall as a 30-storey building!",
    ],
    age: "8+",
    quiz: {
      q: "What kind of tree is the mountain ash?",
      options: ["A gum tree", "A palm tree", "A pine tree"],
      answer: 0,
      explain: "A gum tree! A super-tall one.",
    },
  },
  {
    id: "twinkle-saltie",
    title: "The Mighty Saltie",
    emoji: "🐊",
    lines: [
      "The saltwater crocodile is the biggest reptile alive today!",
      "Big males can grow more than 6 metres long.",
      "They live in northern Australia, so always obey croc warning signs up north.",
    ],
    quiz: {
      q: "What's the biggest reptile alive today?",
      options: ["The saltwater crocodile", "The gecko", "The turtle"],
      answer: 0,
      explain: "The saltie! Give it lots and lots of space.",
    },
  },
  {
    id: "twinkle-butterfly-feet",
    title: "Tasting With Feet",
    emoji: "🦋",
    lines: [
      "Guess what? Butterflies taste with their feet!",
      "When a butterfly lands on a leaf, its feet can tell what kind of plant it is.",
      "That helps mum butterflies choose the right leaf to lay their eggs on.",
    ],
    quiz: {
      q: "What do butterflies use to taste?",
      options: ["Their wings", "Their feet", "Their antennae only"],
      answer: 1,
      explain: "Their feet! Imagine tasting your socks. Yuck!",
    },
  },
  {
    id: "twinkle-blinking",
    title: "Blink, Blink, Blink",
    emoji: "👁️",
    lines: [
      "You blink about 15 to 20 times every minute without even thinking about it!",
      "That's thousands and thousands of blinks every day.",
      "Each blink spreads tears over your eyes to keep them clean and wet.",
    ],
    tryIt: "Have a staring contest with someone. Who blinks first?",
    quiz: {
      q: "Why do we blink?",
      options: ["To keep our eyes clean and wet", "To say hello", "To make wind"],
      answer: 0,
      explain: "Blinking keeps your eyes clean, wet and happy.",
    },
  },
  {
    id: "twinkle-quokka",
    title: "The Quokka's Island",
    emoji: "🏝️",
    lines: [
      "Quokkas are small, smiley-looking marsupials. Many live on Rottnest Island in WA.",
      "Long ago, a Dutch explorer thought they were big rats!",
      "So he named the island 'rat nest'. Please don't touch or feed quokkas. Just smile back!",
    ],
    quiz: {
      q: "What did the explorer think quokkas were?",
      options: ["Big rats", "Small dogs", "Fish"],
      answer: 0,
      explain: "Big rats! That's how Rottnest got its name.",
    },
  },
  {
    id: "twinkle-space-station",
    title: "Sixteen Sunrises a Day",
    emoji: "🛰️",
    lines: [
      "The International Space Station zooms around Earth about every 90 minutes!",
      "That means the astronauts inside see about 16 sunrises every day.",
      "Sometimes you can spot it at night. It looks like a bright star moving fast across the sky.",
    ],
    tryIt: "Ask a grown-up to check when the Space Station flies over your town, then look up!",
    quiz: {
      q: "About how many sunrises do astronauts on the Space Station see each day?",
      options: ["One", "About 16", "None"],
      answer: 1,
      explain: "About 16! Their days are very sparkly.",
    },
  },
  {
    id: "twinkle-tassie-devil",
    title: "The Tasmanian Devil",
    emoji: "😈",
    lines: [
      "Tasmanian devils live on the island of Tasmania.",
      "They make spooky screeches and growls, which is how they got their name!",
      "They're marsupials with very strong jaws that can crunch through bones.",
    ],
    quiz: {
      q: "Where do Tasmanian devils live?",
      options: ["Tasmania", "Antarctica", "Under the sea"],
      answer: 0,
      explain: "Tasmania! It's right there in their name.",
    },
  },
  {
    id: "twinkle-first-writing",
    title: "The First Writing",
    emoji: "📜",
    lines: [
      "People first started writing about 5,000 years ago, in a place called Mesopotamia.",
      "They pressed wedge-shaped marks into soft clay tablets.",
      "Before writing, everything had to be remembered or told as stories.",
    ],
    age: "8+",
    quiz: {
      q: "What did early writers press marks into?",
      options: ["Clay tablets", "Computers", "Clouds"],
      answer: 0,
      explain: "Clay tablets! No paper or screens back then.",
    },
  },
];

export const LESSONS_TWINKLE: Lesson[] = drafts.map((d) => ({ ...d, wizard: "twinkle" }));
