import type { Course } from "@/lib/courses/types";

// Original kid-friendly lessons in the spirit of "Big Life Journal" — growth
// mindset, resilience, gratitude, kindness, and confidence. Wording is our own.
// Each lesson follows the learning loop: hook → story → big idea → why →
// real examples → reflect → retrieval-practice quiz.

export const BIG_LIFE_SKILLS: Course = {
  id: "big-life-skills",
  title: "Big Life Skills",
  subtitle: "Grow your heart and mind",
  emoji: "🌈",
  about:
    "Six lessons on growth mindset, bouncing back, gratitude, kindness, and believing in yourself — each with a story and a quiz to earn ⭐ stars!",
  passPct: 0.75,
  finalReward: 15,
  finalCount: 10,
  lessons: [
    {
      id: "power-of-yet",
      title: "The Power of Yet",
      emoji: "🌱",
      summary: "Turn “I can't” into “I can't… yet.”",
      starReward: 5,
      hook: "Have you ever said “I can't do this”? What if you added one tiny word to the end?",
      story: {
        title: "Lina and the Cartwheel",
        illustration: "🤸🌱✨",
        paragraphs: [
          "Lina watched her friends do cartwheels and sighed, “I can't do a cartwheel.” She flopped on the grass, sure she never would.",
          "Her coach smiled. “You can't do a cartwheel… YET.” That one little word made Lina sit up.",
          "She practiced a little each day — hands down, legs up, wobble, fall, try again. Her cartwheels were messy for weeks.",
          "Then one sunny afternoon she flipped right over and landed on her feet. “I knew it was just a YET!” she laughed.",
        ],
        moral: "Adding “yet” turns “I can't” into “I'm still learning.”",
      },
      bigIdea: "A growth mindset means believing you can get better with practice. “I can't” becomes “I can't… yet.”",
      reading: [
        { heading: "Why it works", body: "Your brain grows stronger every time you practice something hard, like a muscle. “Yet” reminds you that not-knowing is the start, not the end." },
        { heading: "Watch out", body: "A “fixed mindset” says “I'm just bad at this” and gives up — which stops your brain from growing." },
      ],
      realExamples: [
        "Saying “I can't ride a bike yet” instead of “I can't ride a bike.”",
        "Thinking “I haven't learned this maths yet.”",
        "Practicing a song that's too hard — for now.",
      ],
      tryIt: "Catch yourself saying “I can't” today and add the word “yet.”",
      reflect: "What's something you can't do YET that you'd love to learn?",
      quiz: [
        { q: "What word did the coach add to change Lina's thinking?", options: ["“Yet”", "“Never”", "“No”", "“Maybe”"], answer: 0, explain: "“Yet” turned “I can't” into “I'm still learning.”" },
        { q: "A growth mindset means believing you can…", options: ["Get better with practice", "Never change", "Only do easy things", "Give up quickly"], answer: 0 },
        { q: "Practicing hard things makes your brain…", options: ["Grow stronger, like a muscle", "Shrink", "Stay exactly the same", "Stop working"], answer: 0 },
        { q: "You're stuck on a tricky puzzle. Growth-mindset thinking is…", options: ["“I haven't solved it YET.”", "“I'm just not smart.”", "“I'll never get it.”", "“Puzzles are dumb.”"], answer: 0 },
        { q: "Which is a FIXED mindset (the kind to avoid)?", options: ["“I'm just bad at this, why try.”", "“I can improve with practice.”", "“Mistakes help me learn.”", "“I can't do it yet.”"], answer: 0 },
      ],
    },
    {
      id: "mistakes-grow",
      title: "Mistakes Help You Grow",
      emoji: "🛠️",
      summary: "Flops are how your brain learns.",
      starReward: 5,
      hook: "When you make a mistake, is it proof you failed — or proof you're learning?",
      story: {
        title: "The Spaghetti Sauce",
        illustration: "🍝🧪💡",
        paragraphs: [
          "A famous food company tried to make the perfect spaghetti sauce. They got it smooth and tasty — but people only kind of liked it.",
          "So they made dozens of different sauces — chunky, spicy, plain — and let people taste them all. Lots of “wrong” batches, lots of mess.",
          "It turned out there was no ONE perfect sauce. Different people loved different ones! The “mistakes” taught them what people really wanted.",
          "By trying, failing, and learning, they made sauces everyone loved — and sold millions of jars.",
        ],
        moral: "Mistakes aren't the opposite of success — they're the path to it.",
      },
      bigIdea: "Mistakes are how your brain learns. Every flop teaches you something for next time.",
      reading: [
        { heading: "Why it works", body: "When something goes wrong, your brain notices and adjusts. People who try, fail, and adjust end up far ahead of people who never try." },
        { heading: "Watch out", body: "Being scared of mistakes makes you stop trying. The only real mistake is giving up — or not learning from it." },
      ],
      realExamples: [
        "Falling off a bike and learning to balance better.",
        "Getting a spelling word wrong, then remembering it for good.",
        "A wobbly first drawing that teaches you for the next one.",
      ],
      tryIt: "Today, when you make a mistake, ask: “What can this teach me?”",
      reflect: "Think of a mistake that ended up teaching you something useful.",
      quiz: [
        { q: "What did the sauce company learn from all their “wrong” batches?", options: ["Different people love different sauces", "One perfect sauce exists", "Cooking is pointless", "Mistakes are always bad"], answer: 0 },
        { q: "Mistakes are…", options: ["A normal part of learning", "Proof you're hopeless", "Something to hide", "Always the end"], answer: 0 },
        { q: "When you make a mistake, your brain…", options: ["Notices and adjusts for next time", "Stops working", "Forgets everything", "Gets weaker"], answer: 0 },
        { q: "You got a maths problem wrong. The growth move is…", options: ["Find out why and learn from it", "Hide the paper", "Decide you're bad at maths", "Never try again"], answer: 0 },
        { q: "What's the only REAL mistake?", options: ["Giving up or not learning from it", "Trying and missing", "Asking for help", "Practicing"], answer: 0 },
      ],
    },
    {
      id: "bounce-back",
      title: "Bounce Back",
      emoji: "🏀",
      summary: "Get back up after a setback.",
      starReward: 5,
      hook: "When something knocks you down, what helps you get back up?",
      story: {
        title: "The Basketball and the Bad Day",
        illustration: "🏀💧💪",
        paragraphs: [
          "Marcus missed the winning shot at the buzzer. His team lost, and he felt terrible. He wanted to quit basketball forever.",
          "At home, his grandpa asked, “Did you give up, or did you try your best?” “I tried my best,” Marcus mumbled.",
          "“Then you didn't fail — you're just bouncing,” Grandpa said. “A basketball only goes UP after it hits the ground.”",
          "Marcus practiced his shots all week. He didn't make every one. But he kept bouncing back — and slowly got better and braver.",
        ],
        moral: "Bouncing back after a setback is what makes you stronger.",
      },
      bigIdea: "Resilience means getting back up after things go wrong, instead of staying down.",
      reading: [
        { heading: "Why it works", body: "Everyone faces setbacks. The difference between people who succeed and people who don't is usually who keeps bouncing back." },
        { heading: "How to bounce", body: "Feel your feelings, take a breath, remember it's not the end, and try again — maybe a new way." },
      ],
      realExamples: [
        "Trying out again after not making the team.",
        "Redoing a project that didn't work the first time.",
        "Saying sorry and trying again after a fight with a friend.",
      ],
      tryIt: "Next time something goes wrong today, take a breath and say, “I can bounce back.”",
      reflect: "What's something hard you bounced back from before?",
      quiz: [
        { q: "What did Grandpa mean by “a basketball only goes up after it hits the ground”?", options: ["Setbacks can lead to bouncing back stronger", "Basketball is too hard", "You should quit", "Grandpas are funny"], answer: 0 },
        { q: "Resilience means…", options: ["Getting back up after setbacks", "Never feeling sad", "Always winning", "Giving up calmly"], answer: 0 },
        { q: "What often separates people who succeed from those who don't?", options: ["They keep bouncing back", "They never fail", "They're just luckier", "They're born better"], answer: 0 },
        { q: "You didn't make the team. A resilient response is…", options: ["Practice and try again next time", "Quit the sport forever", "Decide you're useless", "Blame everyone else"], answer: 0 },
        { q: "A good way to bounce back is to…", options: ["Take a breath and try again, maybe a new way", "Pretend you don't care", "Give up quietly", "Stay upset all week"], answer: 0 },
      ],
    },
    {
      id: "gratitude",
      title: "An Attitude of Gratitude",
      emoji: "🙏",
      summary: "Notice the good things, big and small.",
      starReward: 5,
      hook: "What's one small thing that went RIGHT for you today?",
      story: {
        title: "The Gratitude Jar",
        illustration: "🫙💌😊",
        paragraphs: [
          "The Ortega family was having a grumpy month. Everyone noticed what was going wrong, but never what was going right.",
          "So Mum put an empty jar on the table. “Every night,” she said, “write one good thing that happened, and drop it in.”",
          "At first it felt silly. “Found a cool rock.” “Pizza for dinner.” “My sister helped me.” Tiny things. But the jar slowly filled.",
          "On New Year's Eve they read every note out loud. The “grumpy” year had been full of good moments — they'd just forgotten to notice.",
        ],
        moral: "Noticing the good things makes you happier — they were there all along.",
      },
      bigIdea: "Gratitude means noticing and being thankful for the good things, big and small. It trains your brain to spot the good.",
      reading: [
        { heading: "Why it works", body: "Our brains naturally notice problems. Practicing gratitude balances that out, so we feel happier and luckier." },
        { heading: "Watch out", body: "Gratitude isn't pretending nothing is wrong. It's choosing to ALSO see the good that's really there." },
      ],
      realExamples: [
        "Thanking someone who helped you.",
        "Noticing a sunny sky or a tasty snack.",
        "Sharing one good thing from your day at dinner.",
      ],
      tryIt: "Write or say three things you're grateful for today.",
      reflect: "Who is someone you're thankful for — and have you told them?",
      quiz: [
        { q: "What did the Ortega family discover when they read the jar?", options: ["Their “grumpy” year had lots of good moments", "Nothing good had happened", "Jars are useless", "They needed a bigger jar"], answer: 0 },
        { q: "Gratitude means…", options: ["Noticing and being thankful for good things", "Ignoring everything", "Only ever wanting more", "Complaining a lot"], answer: 0 },
        { q: "Practicing gratitude helps because our brains…", options: ["Naturally notice problems, so it balances us out", "Only think happy thoughts", "Never notice anything", "Forget good things on purpose"], answer: 0 },
        { q: "You had a hard day but lunch was great. Gratitude is…", options: ["Noticing the good lunch too", "Pretending nothing was hard", "Only thinking about the bad", "Skipping dinner"], answer: 0 },
        { q: "Which is a grateful habit?", options: ["Sharing one good thing at dinner", "Listing only complaints", "Ignoring kind acts", "Always wanting more"], answer: 0 },
      ],
    },
    {
      id: "kindness",
      title: "Sprinkle Kindness",
      emoji: "💛",
      summary: "Small kind acts ripple far.",
      starReward: 5,
      hook: "Has one small kind act ever made your whole day better?",
      story: {
        title: "The Ripple",
        illustration: "💧💛🌊",
        paragraphs: [
          "On a cold morning, Sofia noticed her classmate Ben shivering with no jacket. She lent him her spare scarf.",
          "Ben felt warm and happy. At lunch, he helped a younger kid who'd dropped their tray.",
          "That kid, feeling good, later cheered up his sad little sister at home. The sister shared her cookies with a neighbour.",
          "Sofia's one small kindness rippled out to people she never even met — like a stone dropped in a pond.",
        ],
        moral: "One act of kindness can ripple out much farther than you think.",
      },
      bigIdea: "Kindness is doing good things for others. It makes them happier — and it spreads.",
      reading: [
        { heading: "Why it works", body: "Kindness feels good for the giver AND the receiver, and it often passes from person to person, creating a ripple." },
        { heading: "How to do it", body: "Look for small chances: share, help, include someone, or say something nice. Small kindnesses count a lot." },
      ],
      realExamples: [
        "Including someone who's being left out.",
        "Helping carry something heavy.",
        "Saying a genuine “thank you” or “are you okay?”",
      ],
      tryIt: "Do one kind thing for someone today without being asked.",
      reflect: "Who around you could use a little kindness this week?",
      quiz: [
        { q: "What happened after Sofia lent Ben her scarf?", options: ["Kindness rippled to people she never met", "Nothing changed", "Ben kept the scarf and left", "Everyone got cold"], answer: 0 },
        { q: "Kindness means…", options: ["Doing good things for others", "Only helping yourself", "Waiting to be paid", "Being nice only to friends"], answer: 0 },
        { q: "Kindness often spreads because…", options: ["It passes from person to person", "It's the law", "People are forced to", "It's pure magic"], answer: 0 },
        { q: "A new kid is sitting alone. A kind act is…", options: ["Inviting them to join you", "Ignoring them", "Pointing and laughing", "Walking away"], answer: 0 },
        { q: "Small kindnesses…", options: ["Count a lot and can ripple far", "Don't really matter", "Only count if they're huge", "Are a waste of time"], answer: 0 },
      ],
    },
    {
      id: "believe-in-yourself",
      title: "Believe in Yourself",
      emoji: "🦁",
      summary: "The worried voice is a feeling, not a fact.",
      starReward: 5,
      hook: "What could you try if you weren't afraid of looking silly?",
      story: {
        title: "The Voice in the Audition",
        illustration: "🎤🦁🌟",
        paragraphs: [
          "Priya wanted to try out for the school choir, but a little voice in her head said, “What if you're not good enough?”",
          "She almost stayed home. But she remembered: that worried voice isn't the boss — it's just a feeling, not a fact.",
          "Hands shaking, she walked up and sang. Her voice wobbled at first, then grew strong and clear.",
          "She didn't get every note perfect — but she made the choir. The biggest win was believing in herself enough to try.",
        ],
        moral: "Believing in yourself enough to TRY is already a victory.",
      },
      bigIdea: "Confidence is believing you're worth a try. The worried voice in your head is a feeling, not a fact.",
      reading: [
        { heading: "Why it works", body: "Confidence grows by doing brave things, not by waiting to feel ready. Each time you try, the worried voice gets a little quieter." },
        { heading: "Watch out", body: "Confidence isn't thinking you're perfect. It's being kind to yourself and willing to try and learn." },
      ],
      realExamples: [
        "Raising your hand even when you're unsure.",
        "Trying a new activity that looks a bit scary.",
        "Speaking up for what you think is right.",
      ],
      tryIt: "Do one small brave thing today, even if the worried voice complains.",
      reflect: "What brave thing would “confident you” try this week?",
      quiz: [
        { q: "What was Priya's biggest win?", options: ["Believing in herself enough to try", "Singing every note perfectly", "Staying home where it's safe", "Being the loudest"], answer: 0 },
        { q: "The worried voice in your head is…", options: ["A feeling, not a fact", "Always right", "The boss of you", "Never there"], answer: 0 },
        { q: "Confidence grows by…", options: ["Doing brave things, not waiting to feel ready", "Waiting until you feel perfect", "Avoiding everything hard", "Never trying"], answer: 0 },
        { q: "You're nervous to raise your hand. The confident move is…", options: ["Try it anyway, even nervous", "Never speak up", "Wait until you feel zero fear", "Decide you're not smart"], answer: 0 },
        { q: "Real confidence is…", options: ["Being willing to try and learn", "Thinking you're perfect", "Never making mistakes", "Showing off"], answer: 0 },
      ],
    },
  ],
};
