import type { Course } from "@/lib/courses/types";

// Original, kid-friendly lessons inspired by the people-skills ideas in
// "How to Win Friends and Influence People" (Dale Carnegie). Wording is our own.
// Each lesson follows a learning loop: hook → story → big idea → why →
// real examples → reflect → retrieval-practice quiz.

export const HOW_TO_WIN_FRIENDS: Course = {
  id: "how-to-win-friends",
  title: "How to Win Friends",
  subtitle: "Be a kind, friendly superstar",
  emoji: "🤝",
  about:
    "Six short lessons on making friends and being someone people love to be around. Read the story, learn the idea, then pass the quiz to earn stars!",
  passPct: 0.75,
  finalReward: 15,
  finalCount: 10,
  lessons: [
    {
      id: "smile",
      title: "Start With a Smile",
      emoji: "🙂",
      summary: "A smile is the friendliest hello.",
      starReward: 5,
      hook: "When you walk into a room, what do people notice about you before you even speak?",
      story: {
        title: "The New Kid at Table 4",
        illustration: "🏫🍱🙂",
        paragraphs: [
          "On Maya's first day at her new school, she stood holding her lunch tray, not knowing where to sit. Every table looked full of kids who already knew each other.",
          "At table 4, a boy named Theo looked up, caught her eye, and gave her a big, warm smile. He waved at the empty seat beside him.",
          "Maya's nervous tummy relaxed. She sat down, and soon they were laughing about their favourite games.",
          "Theo didn't do anything fancy. He just smiled — and that smile said, “You're welcome here.”",
        ],
        moral: "A smile can make someone feel safe before you say a single word.",
      },
      bigIdea: "A genuine smile is the fastest, easiest way to show kindness and make people feel welcome.",
      reading: [
        { heading: "Why it works", body: "Our brains copy the faces we see. When someone notices your warm smile, they relax and often smile back — so good feelings bounce both ways." },
        { heading: "Watch out", body: "People can tell a fake smile from a real one. A smile works best with kind eyes and honest feelings — not when you're secretly annoyed or want something." },
      ],
      realExamples: [
        "Smiling at a new classmate who looks lonely.",
        "Greeting a grandparent with a big smile when they arrive.",
        "Smiling at the bus driver and saying good morning.",
      ],
      tryIt: "Give a real, warm smile to three people today and notice how they react.",
      reflect: "Who is someone that could really use a friendly smile from you tomorrow?",
      quiz: [
        { q: "In the story, how did Theo help Maya feel welcome?", options: ["He smiled warmly and waved her over", "He told her the school rules", "He ignored her so she'd settle in", "He gave her his lunch"], answer: 0, explain: "His warm smile said “you belong here” before any words." },
        { q: "A new kid looks nervous at the classroom door. What's the kindest first move?", options: ["Give a warm smile and a little wave", "Stare to size them up", "Wait and see if they talk first", "Point out where NOT to sit"], answer: 0, explain: "A smile quickly signals they're safe and welcome." },
        { q: "Why do people often smile back when you smile at them?", options: ["Our brains copy the faces we see", "It's a strict rule", "It scares them into it", "Pure luck"], answer: 0 },
        { q: "Sam grins at customers but rolls his eyes the moment they turn around. What's the problem?", options: ["His smile isn't genuine, so people won't trust it", "Nothing — looks are all that matter", "He smiles too much", "He should never smile"], answer: 0, explain: "A fake smile breaks trust; real warmth matters." },
        { q: "A genuine smile works best when it comes with…", options: ["Kind eyes and honest feelings", "A secret plan to get something", "Crossed arms", "A bored face"], answer: 0 },
      ],
    },
    {
      id: "names",
      title: "Remember Names",
      emoji: "📛",
      summary: "A person's name is their favourite sound.",
      starReward: 5,
      hook: "What's one word almost everyone loves to hear out loud?",
      story: {
        title: "The Coach Who Knew Everyone's Name",
        illustration: "⚽🏅📣",
        paragraphs: [
          "At soccer camp there were sixty kids, and it was easy to feel like just a number. But Coach Rosa was different.",
          "On day one she learned every single name. “Great shot, Daniel!” “Nice hustle, Priya!” She used names all day long.",
          "Daniel had been thinking of quitting. But when Coach Rosa cheered his name in front of everyone, he stood a little taller — and decided to stay.",
          "Years later, Daniel couldn't remember a single drill. But he never forgot how it felt when the coach said his name — like he mattered.",
        ],
        moral: "Using someone's name tells them, “I see you, and you matter.”",
      },
      bigIdea: "A person's own name is one of the sweetest sounds to them. Learning and using names shows you truly notice people.",
      reading: [
        { heading: "Why it works", body: "Hearing our name grabs our attention and makes us feel important and remembered. It turns a stranger into someone who 'knows' us." },
        { heading: "How to remember", body: "When you meet someone, say their name back (“Nice to meet you, Sam!”), picture it in your head, and use it again before you say goodbye." },
      ],
      realExamples: [
        "Saying “Thanks, Maria!” instead of just “thanks.”",
        "Greeting a classmate by name in the hallway.",
        "Remembering your friend's little brother's name.",
      ],
      tryIt: "Learn one new person's name today and use it at least twice.",
      reflect: "Whose name do you want to remember better — and what trick will you use?",
      quiz: [
        { q: "Why did Daniel decide to stay at camp?", options: ["Coach Rosa cheered him by name and he felt he mattered", "The drills were fun", "His friend made him", "He won a prize"], answer: 0 },
        { q: "You just met a kid named Sam. What's a good way to lock in the name?", options: ["Say “Nice to meet you, Sam!” and use it again", "Forget it and say “hey you”", "Avoid talking to them", "Hope you never need it"], answer: 0 },
        { q: "Why does using someone's name matter so much?", options: ["It makes them feel noticed and important", "It proves you're smart", "It ends conversations fast", "It's a magic spell"], answer: 0 },
        { q: "To most people, hearing their own name feels…", options: ["Warm and important", "Boring", "Like a secret", "Annoying"], answer: 0 },
        { q: "Which greeting feels warmest?", options: ["“Great job, Priya!”", "“Great job, you.”", "“Hey, kid.”", "“Whatever.”"], answer: 0 },
      ],
    },
    {
      id: "listen",
      title: "Be a Super Listener",
      emoji: "👂",
      summary: "Really listening makes people feel valued.",
      starReward: 5,
      hook: "Would you rather hang out with someone who really listens, or someone who only talks about themselves?",
      story: {
        title: "Two Friends and the Big News",
        illustration: "🛹👂✨",
        paragraphs: [
          "Jordan finally landed his hardest skateboard trick and couldn't wait to tell someone. He found his friend Leo first.",
          "But the second Jordan started, Leo cut in: “That's nothing — watch MY trick!” and talked about himself for ten minutes. Jordan felt invisible.",
          "Later, Jordan told his friend Aisha. She leaned in: “How long did it take? How did it feel when you landed it?” Jordan lit right up.",
          "Both friends heard the same news. But Jordan wanted to hang out with Aisha again — because she made him feel heard.",
        ],
        moral: "People feel close to those who truly listen, not those who just wait to talk.",
      },
      bigIdea: "Being a great listener — paying real attention and asking questions — makes people feel important and liked.",
      reading: [
        { heading: "Why it works", body: "When you listen, you make the other person the star. Feeling heard is something everyone craves, so good listeners are easy to love." },
        { heading: "How to listen well", body: "Look at them, don't interrupt, let them finish, and ask a question about what they said before you talk about yourself." },
      ],
      realExamples: [
        "Asking “What's your dog's name?” instead of talking about your own pet.",
        "Letting your sibling finish their story without cutting in.",
        "Asking a grandparent what they were like as a kid.",
      ],
      tryIt: "In your next chat, ask two questions before you talk about yourself.",
      reflect: "Think of a time someone really listened to you. How did it feel?",
      quiz: [
        { q: "Why did Jordan want to hang out with Aisha again?", options: ["She listened and asked about his trick", "She did a cooler trick", "She gave him a skateboard", "She talked the most"], answer: 0 },
        { q: "What was Leo's mistake when Jordan shared his news?", options: ["He interrupted to talk about himself", "He listened too closely", "He asked too many questions", "He was too quiet"], answer: 0 },
        { q: "Your friend is excited about a movie. A great listening response is…", options: ["“What was your favourite part?”", "“Mine was way better.”", "“I don't care.”", "Changing the subject"], answer: 0 },
        { q: "Good listeners make other people feel…", options: ["Important and heard", "Bored", "Rushed", "Ignored"], answer: 0 },
        { q: "A key habit of great listeners is to…", options: ["Let people finish before you talk", "Talk over them", "Look away", "Check the time"], answer: 0 },
      ],
    },
    {
      id: "compliments",
      title: "Give Real Compliments",
      emoji: "🌟",
      summary: "Honest, specific praise means the most.",
      starReward: 5,
      hook: "What's the difference between a compliment that feels great and one that feels fake?",
      story: {
        title: "The Two Notes",
        illustration: "📝🌟💌",
        paragraphs: [
          "After the class play, two kids each found a note in their bag.",
          "Ben's note said: “You're literally the BEST actor in the whole world!!!” Ben rolled his eyes — he'd forgotten half his lines. The note felt empty.",
          "Nadia's note said: “When your voice got louder in the scary scene, I actually got goosebumps. Nice work.”",
          "Nadia read it three times and kept it in her pocket. It was specific, honest, and true — so it meant everything.",
        ],
        moral: "Honest, specific praise means far more than big fake words.",
      },
      bigIdea: "Real compliments are honest and specific. They make people feel genuinely appreciated.",
      reading: [
        { heading: "Why it works", body: "Everyone wants to feel that what they do is noticed. A true, specific compliment shows you actually paid attention — so it lands deeply." },
        { heading: "Watch out", body: "Fake flattery (“you're the best ever!”) feels empty, especially when it isn't true. Say what you really mean." },
      ],
      realExamples: [
        "“Great pass!” to a teammate after a good play.",
        "“I liked how patient you were with your little brother.”",
        "“The colours in your drawing are so bright — I love it.”",
      ],
      tryIt: "Give two honest, specific compliments today — and mean them.",
      reflect: "Who did something well recently that you could honestly praise?",
      quiz: [
        { q: "Why did Nadia's note mean so much to her?", options: ["It was specific and honest", "It used the biggest words", "It had the most exclamation marks", "It was the longest"], answer: 0 },
        { q: "Why did Ben's note feel empty?", options: ["It was fake and not true", "It was too short", "It was too quiet", "It was too specific"], answer: 0 },
        { q: "Your friend played a great game. The best compliment is…", options: ["“Your defense in the last minute was amazing!”", "“You're the best ever at everything!”", "“That was okay I guess.”", "“Whatever.”"], answer: 0 },
        { q: "A real compliment is…", options: ["Honest and specific", "Big and fake", "A secret", "Mean"], answer: 0 },
        { q: "Specific compliments work because they show you…", options: ["Actually noticed what the person did", "Are smarter than them", "Want something back", "Are bored"], answer: 0 },
      ],
    },
    {
      id: "their-way",
      title: "See It Their Way",
      emoji: "🪞",
      summary: "Care about what others care about.",
      starReward: 5,
      hook: "If you want someone to help you, is it better to talk about what YOU want, or what THEY care about?",
      story: {
        title: "The Worm and the Fish",
        illustration: "🎣🐟🪱",
        paragraphs: [
          "Mia wanted her little brother Sam to help clean their shared room, but he kept saying no.",
          "She remembered something her grandpa said: “When I go fishing, I don't bait the hook with strawberries because I like them. I use what the FISH likes — worms.”",
          "So instead of “Clean up because I said so,” Mia tried: “Sam, if we tidy fast, we'll find your missing dinosaur AND have time to build that fort you wanted.”",
          "Sam jumped up and started cleaning. Mia got her tidy room — by talking about what Sam cared about.",
        ],
        moral: "To win someone over, talk about what they want, not just what you want.",
      },
      bigIdea: "People care most about their own wishes. Show how something helps them, and try to see things from their side.",
      reading: [
        { heading: "Why it works", body: "We all pay more attention to things that matter to us. When you connect your idea to what someone cares about, they actually want to say yes." },
        { heading: "How to do it", body: "Before you ask, pause and think: “How does this look from their side? What do THEY want?” Then talk about that." },
      ],
      realExamples: [
        "Getting your brother to tidy by mentioning the toy he'll find.",
        "Asking about a friend's favourite hobby before talking about yours.",
        "Showing your parents how a plan helps everyone, not just you.",
      ],
      tryIt: "Ask someone about their favourite thing today, and really listen to the answer.",
      reflect: "Next time you need help, how could you show what's in it for the other person?",
      quiz: [
        { q: "What did Grandpa's fishing tip really mean?", options: ["Offer people what THEY want, not what you want", "Strawberries are the best bait", "Fishing takes patience", "Worms are tasty"], answer: 0 },
        { q: "You want a friend to join your team. The best approach is…", options: ["Show how it'll be fun for THEM too", "Say “do it because I said so”", "Beg loudly", "Trick them into it"], answer: 0 },
        { q: "“Standing in someone's shoes” means…", options: ["Imagining how they feel", "Taking their shoes", "Being taller than them", "Copying them"], answer: 0 },
        { q: "Talking about what others care about works because people…", options: ["Pay most attention to what matters to them", "Like being bossed around", "Never listen anyway", "Hate compliments"], answer: 0 },
        { q: "Which is most likely to get a “yes”?", options: ["“If we hurry, you'll have time for your game.”", "“Clean up NOW.”", "“You never help.”", "“Because I said so.”"], answer: 0 },
      ],
    },
    {
      id: "be-kind",
      title: "Be Kind, Not Critical",
      emoji: "🕊️",
      summary: "Skip put-downs; admit mistakes; stay calm.",
      starReward: 5,
      hook: "When someone yells that you did something wrong, do you feel like listening — or arguing back?",
      story: {
        title: "The Spilled Paint",
        illustration: "🎨💙🤝",
        paragraphs: [
          "During art class, Theo bumped the table and spilled blue paint all over Lily's painting. She'd worked on it for an hour.",
          "Her first urge was to shout, “You ruined it! You're so clumsy!” She could see Theo bracing for it.",
          "Instead she took a breath and said, “It was an accident. Want to help me fix it?” Theo's shoulders dropped. “I'm really sorry — yes!”",
          "Together they turned the blue splash into a river in the picture. It ended up better than before — and they became friends.",
        ],
        moral: "Kindness turns mistakes into teamwork; criticism just starts a fight.",
      },
      bigIdea: "Criticizing and blaming make people defensive. Being kind — and admitting your own mistakes quickly — keeps friendships strong.",
      reading: [
        { heading: "Why it works", body: "When people feel attacked, they defend themselves instead of listening. Kindness lowers their guard so you can actually solve the problem together." },
        { heading: "Admit mistakes fast", body: "If you're wrong, say so quickly and kindly. It's brave, people respect it, and it ends arguments before they grow." },
      ],
      realExamples: [
        "Saying “Want to try it together?” instead of “You did it wrong!”",
        "Admitting “My bad, I forgot” instead of making excuses.",
        "Staying calm and finding what you agree on during a disagreement.",
      ],
      tryIt: "If you make a mistake today, admit it quickly and kindly.",
      reflect: "Think of a recent argument. How could kindness have changed it?",
      quiz: [
        { q: "Why did things turn out well after the paint spilled?", options: ["Lily chose kindness instead of blame", "Lily yelled louder", "Theo ran away", "They quit art"], answer: 0 },
        { q: "Criticising and blaming usually make people…", options: ["Defend themselves instead of listening", "Calm and grateful", "Agree right away", "Happy"], answer: 0 },
        { q: "A friend messes up in your group project. The best response is…", options: ["“No worries — let's fix it together.”", "“You ruined everything!”", "“You're hopeless.”", "Telling everyone they failed"], answer: 0 },
        { q: "When YOU are the one who's wrong, the brave move is to…", options: ["Admit it quickly and kindly", "Hide it", "Blame someone else", "Get angry"], answer: 0 },
        { q: "Which keeps a friendship strong during a disagreement?", options: ["Staying calm and finding common ground", "Calling names", "Storming off", "Shouting to win"], answer: 0 },
      ],
    },
  ],
};
