import type { Course } from "@/lib/courses/types";

// Original, kid-friendly lessons inspired by "The 7 Habits of Happy Kids"
// (Sean Covey). Wording is our own. Each lesson follows a learning loop:
// hook → story → big idea → why → real examples → reflect → practice quiz.

export const SEVEN_HABITS: Course = {
  id: "seven-habits",
  title: "7 Habits of Happy Kids",
  subtitle: "Seven habits to be your best",
  emoji: "🦉",
  about:
    "Seven famous habits that help kids be happy, kind, and awesome — taught with a short story each. Read, learn the idea, then pass the quiz to earn ⭐ stars!",
  passPct: 0.75,
  finalReward: 15,
  finalCount: 10,
  lessons: [
    {
      id: "be-proactive",
      title: "Be Proactive",
      emoji: "🚀",
      summary: "You're in charge of you.",
      starReward: 5,
      hook: "When something goes wrong, who decides how you react — you, or the thing that happened?",
      story: {
        title: "The Two Brothers and the Rainy Trip",
        illustration: "🌧️🛋️☕",
        paragraphs: [
          "The Kim brothers had waited weeks for the beach trip. Then they woke to grey skies and pouring rain. Cancelled.",
          "Older brother Eli flopped on the couch. “This whole day is ruined,” he grumbled, and stayed mad all morning.",
          "Younger brother Noah felt sad too — but then he chose differently. He built a giant pillow fort, made hot chocolate, and started a movie marathon.",
          "Same rain. Same cancelled trip. But Noah was “in charge of his own weather,” so his day turned out great while Eli's stayed miserable.",
        ],
        moral: "You can't always control what happens, but you're always in charge of how you respond.",
      },
      bigIdea: "Being proactive means YOU choose your response, instead of blaming your mood or what happened.",
      reading: [
        { heading: "Why it works", body: "There's a tiny gap between what happens and what you do next. Proactive people use that gap to CHOOSE a good response instead of just reacting." },
        { heading: "Watch out", body: "Blaming (“you made me angry!”) hands your power away. Reactive people let other things control their whole day." },
      ],
      realExamples: [
        "Calmly rebuilding when your block tower falls.",
        "Taking a deep breath before reacting when you're upset.",
        "Choosing to make the best of a rainy day.",
      ],
      tryIt: "Next time you feel upset, take one deep breath and choose your response before you act.",
      reflect: "When is it hardest for you to stay “in charge of you”?",
      quiz: [
        { q: "Why was Noah's rainy day better than Eli's?", options: ["He chose a good response instead of staying grumpy", "His rain was lighter", "He went to the beach anyway", "He had more toys"], answer: 0 },
        { q: "Being proactive means…", options: ["You choose how you respond", "Things control your mood", "You blame other people", "You wait for luck"], answer: 0 },
        { q: "Your game gets rained out. The proactive move is…", options: ["Find a fun indoor plan", "Sulk all day", "Blame your friend", "Yell at the sky"], answer: 0 },
        { q: "Proactive people use the gap between what happens and what they do to…", options: ["Choose a good response", "React without thinking", "Get even angrier", "Give up"], answer: 0 },
        { q: "Which sentence is REACTIVE (not proactive)?", options: ["“You made me angry — it's your fault!”", "“I'll take a breath and choose.”", "“I can handle this.”", "“What's a good response here?”"], answer: 0 },
      ],
    },
    {
      id: "end-in-mind",
      title: "Begin With the End in Mind",
      emoji: "🎯",
      summary: "Picture the finish, then plan.",
      starReward: 5,
      hook: "Would you start building something with no idea of what you're making?",
      story: {
        title: "Two Tree Houses",
        illustration: "🌳🏠📐",
        paragraphs: [
          "Cousins Ada and Ben each got wood and tools to build a tree house over summer.",
          "Ben grabbed his hammer and nailed boards wherever. By August he had a wobbly, lopsided mess with no door.",
          "Ada first drew a plan: a square floor, walls, a window, a rope ladder. Then she built toward her picture, piece by piece.",
          "Ada's tree house was sturdy and snug. Ben's fell apart. Same wood — but Ada began with the end in mind.",
        ],
        moral: "Picture the finish first, and your work has a map to follow.",
      },
      bigIdea: "Begin with the end in mind: imagine the result you want, then make a plan to get there.",
      reading: [
        { heading: "Why it works", body: "A clear goal acts like a map. Every choice gets easier because you can ask, “Does this get me closer to my picture?”" },
        { heading: "How to do it", body: "Before you start, picture how you want it to end. Say or write your goal, then list the steps to reach it." },
      ],
      realExamples: [
        "Picturing your finished sandcastle before you dig.",
        "Deciding what skill you're aiming for, then practicing it.",
        "Planning a surprise from the happy ending backward.",
      ],
      tryIt: "Pick one thing today and picture it finished before you start.",
      reflect: "What's a goal you have — and what would “finished” look like?",
      quiz: [
        { q: "Why did Ada's tree house turn out better?", options: ["She planned the end result first", "She had better wood", "She worked less", "She copied Ben"], answer: 0 },
        { q: "“Begin with the end in mind” means…", options: ["Picture the result, then plan", "Start with no plan", "Leave it to the last minute", "Copy whatever others do"], answer: 0 },
        { q: "A clear goal helps because it…", options: ["Acts like a map for your choices", "Slows you down", "Makes things random", "Doesn't really matter"], answer: 0 },
        { q: "Before a big school project, the smart first step is…", options: ["Imagine the finished project and plan steps", "Start randomly", "Wait until the night before", "Give up early"], answer: 0 },
        { q: "Which kid is using this habit?", options: ["The one who sketches a plan first", "The one nailing boards randomly", "The one who quits", "The one who copies"], answer: 0 },
      ],
    },
    {
      id: "first-things-first",
      title: "Put First Things First",
      emoji: "✅",
      summary: "Important things before fun.",
      starReward: 5,
      hook: "If you ate dessert before dinner every single night, what would happen to dinner?",
      story: {
        title: "The Big Rock Jar",
        illustration: "🫙🪨⏳",
        paragraphs: [
          "A teacher set a glass jar, some big rocks, and a pile of sand on her desk. “Watch this,” she said.",
          "First she poured in ALL the sand. Then she tried to add the big rocks on top — but they wouldn't fit, and the jar overflowed.",
          "She emptied it and started over: big rocks FIRST, then the sand, which trickled down to fill every gap. Everything fit perfectly.",
          "“The big rocks are your important things,” she said — “homework, practice, sleep. The sand is the little fun stuff. Big rocks first, or they'll never fit.”",
        ],
        moral: "Do your most important things first; the small stuff fits around them.",
      },
      bigIdea: "Put first things first: handle the important jobs before the fun, so the important things actually get done.",
      reading: [
        { heading: "Why it works", body: "You only have so much time (the jar). If little fun fills it up first, the big important things get squeezed out." },
        { heading: "Watch out", body: "Leaving important things till last creates a stressful rush — and sometimes they never get done at all." },
      ],
      realExamples: [
        "Homework before screen time.",
        "Packing your bag the night before, not in a morning panic.",
        "Practicing your instrument before video games.",
      ],
      tryIt: "Today, finish one important “big rock” before you play.",
      reflect: "What are your “big rocks” this week?",
      quiz: [
        { q: "Why did the rocks fit when the teacher added them first?", options: ["Big things must go first, then small fills the gaps", "The jar grew bigger", "She used less sand", "It was magic"], answer: 0 },
        { q: "“Put first things first” means…", options: ["Do important things before fun", "Play all day", "Do everything last", "Skip your jobs"], answer: 0 },
        { q: "If you fill your time with little fun stuff first…", options: ["Important things get squeezed out", "You feel less stressed", "Nothing changes", "You always finish early"], answer: 0 },
        { q: "It's right after school. The “big rock” move is…", options: ["Homework first, then screen time", "Hours of screens, then panic", "Skip homework entirely", "Nap until bedtime"], answer: 0 },
        { q: "Which is a “big rock” (important), not “sand”?", options: ["Studying for tomorrow's test", "Scrolling videos", "Re-watching a show", "Doodling for an hour"], answer: 0 },
      ],
    },
    {
      id: "win-win",
      title: "Think Win-Win",
      emoji: "🤝",
      summary: "Look for a way everyone wins.",
      starReward: 5,
      hook: "If two people both want the last slice, is there a way they can BOTH end up happy?",
      story: {
        title: "The Last Orange",
        illustration: "🍊🥤🧁",
        paragraphs: [
          "Twins Ravi and Anya both grabbed the last orange and started to argue. Mum was about to just cut it in half.",
          "But first she asked, “Why do you each want it?” Ravi said, “I'm thirsty — I want the juice.” Anya said, “I'm baking — I need the peel.”",
          "So Ravi squeezed the juice to drink, and Anya kept the whole peel for her cake. Each got ALL of what they needed.",
          "If they'd just split it, both would've gotten only half of what they wanted. By talking, they found a win for both.",
        ],
        moral: "When you understand what each person really wants, you can often find a way for everyone to win.",
      },
      bigIdea: "Think win-win: look for a solution where both people get what they need, instead of one winning and one losing.",
      reading: [
        { heading: "Why it works", body: "Most fights assume someone must lose. But when you ask what each person truly needs, there's often a clever answer that makes everyone happy." },
        { heading: "How to do it", body: "Ask “What do you want, and why?” Then look for a way both wishes can come true at once." },
      ],
      realExamples: [
        "Sharing chores so each person does the part they mind least.",
        "Taking turns picking the game so both friends enjoy the day.",
        "Trading snacks so you each get the one you like.",
      ],
      tryIt: "Solve one disagreement today so both people end up happy.",
      reflect: "Think of a recent argument — was there a hidden win-win you missed?",
      quiz: [
        { q: "How did the twins both win with one orange?", options: ["One used the juice, one used the peel", "They split it in half", "They threw it away", "One simply gave up"], answer: 0 },
        { q: "Win-win means…", options: ["Both people get what they need", "Only you win", "Only they win", "Everyone loses"], answer: 0 },
        { q: "You and a friend want different games. A win-win is…", options: ["Take turns so both get played", "Only ever play yours", "Argue until one quits", "Play neither and sulk"], answer: 0 },
        { q: "Asking “what do you want, and why?” helps because…", options: ["It reveals a way for both to win", "It wastes time", "It starts more fights", "It never works"], answer: 0 },
        { q: "Which one is a win-win?", options: ["Trading snacks so both get a favourite", "Grabbing both snacks for yourself", "Hiding the snacks", "Throwing them in the bin"], answer: 0 },
      ],
    },
    {
      id: "understand-first",
      title: "Listen First",
      emoji: "👂",
      summary: "Understand before you're understood.",
      starReward: 5,
      hook: "Would a good doctor hand you medicine before asking what's wrong?",
      story: {
        title: "The Wrong Medicine",
        illustration: "🩺👂💊",
        paragraphs: [
          "Imagine a doctor who walks in and, before you say a word, hands you a cast for a broken arm — but you came in with a sore throat!",
          "Silly, right? She “prescribed before she diagnosed” — gave an answer before understanding the problem.",
          "Marcus did the same with a friend. His friend said, “I'm nervous about the test,” and Marcus instantly said, “Just don't be nervous, it's easy!” His friend felt worse and went quiet.",
          "Next time, Marcus listened first: “What part worries you?” His friend opened up — and Marcus could finally help for real.",
        ],
        moral: "Understand the problem first; then your help actually fits.",
      },
      bigIdea: "Seek first to understand, then to be understood: really listen before you give your opinion or advice.",
      reading: [
        { heading: "Why it works", body: "When people feel understood, they trust you and open up. Advice given before understanding usually misses — like the wrong medicine." },
        { heading: "Watch out", body: "Jumping in with “just do this!” before listening makes people feel unheard, even when your idea is a good one." },
      ],
      realExamples: [
        "Asking a sad friend how they feel before giving advice.",
        "Letting someone fully explain before you say your side.",
        "Checking “Did I get that right?” before responding.",
      ],
      tryIt: "Before giving your idea today, listen and understand the other person first.",
      reflect: "When has someone given you advice that missed because they didn't really listen?",
      quiz: [
        { q: "What was the doctor's (and Marcus's) mistake?", options: ["Giving an answer before understanding the problem", "Listening for too long", "Asking too many questions", "Being too quiet"], answer: 0 },
        { q: "“Seek first to understand” means…", options: ["Listen before you give your view", "Always talk first", "Ignore people's feelings", "Interrupt a lot"], answer: 0 },
        { q: "When people feel understood, they…", options: ["Trust you and open up", "Walk away", "Get angrier", "Stop talking forever"], answer: 0 },
        { q: "A friend says they're nervous about a test. Best first response?", options: ["“What part worries you?”", "“Just don't be nervous!”", "“That's easy, relax.”", "“Stop complaining.”"], answer: 0 },
        { q: "Which response shows understanding first?", options: ["“Did I get that right?”", "“Here's what YOU should do, now.”", "“Boring — my turn.”", "“Whatever.”"], answer: 0 },
      ],
    },
    {
      id: "synergize",
      title: "Synergize",
      emoji: "✨",
      summary: "Together is better than alone.",
      starReward: 5,
      hook: "Can a group create something better than any one person could make alone?",
      story: {
        title: "The Comic Nobody Could Make Alone",
        illustration: "✏️🎨😂",
        paragraphs: [
          "Three friends wanted to enter the school comic contest. Alone, each was stuck. Priya could draw but not write. Sam had great stories but messy drawings. Dee couldn't do either — but was brilliant at funny jokes.",
          "Separately, their comics fell flat. Then they teamed up.",
          "Sam wrote the story, Priya drew the pictures, and Dee added jokes that made everyone laugh out loud.",
          "Their comic won first prize. None of them could have made it alone — together they were better than the sum of their parts.",
        ],
        moral: "Different strengths combined can create something amazing no one could do alone.",
      },
      bigIdea: "Synergize means teaming up so the group is stronger than any one person — by combining different strengths.",
      reading: [
        { heading: "Why it works", body: "Everyone is good at different things. When you mix those strengths and value the differences, 1 + 1 can equal 3." },
        { heading: "Watch out", body: "Synergy needs respect. If teammates put each other down or insist on doing everything alone, the magic disappears." },
      ],
      realExamples: [
        "One friend plans, one builds, one decorates.",
        "Group projects where each person does their best part.",
        "A sports team where every player has a role.",
      ],
      tryIt: "Team up with someone today and combine both of your strengths.",
      reflect: "What's something you're great at that could help a team?",
      quiz: [
        { q: "Why did the friends' comic win?", options: ["They combined their different strengths", "One person did it all", "They copied another comic", "They got lucky"], answer: 0 },
        { q: "Synergize means…", options: ["Teaming up to be better than alone", "Always working alone", "Bossing everyone around", "Quitting when it's hard"], answer: 0 },
        { q: "Teamwork creates “extra” because everyone…", options: ["Has different strengths to combine", "Is exactly the same", "Thinks they're the best", "Does nothing"], answer: 0 },
        { q: "Your group has a planner, an artist, and a joker. Best move?", options: ["Let each do the part they're best at", "Make one person do everything", "Argue over who's boss", "Each works in secret"], answer: 0 },
        { q: "What can RUIN team synergy?", options: ["Putting each other down", "Respecting differences", "Sharing the work", "Listening to ideas"], answer: 0 },
      ],
    },
    {
      id: "sharpen-the-saw",
      title: "Sharpen the Saw",
      emoji: "🌳",
      summary: "Take care of yourself to stay strong.",
      starReward: 5,
      hook: "If you never sharpened a saw, would it cut better or worse over time?",
      story: {
        title: "The Tired Woodcutter",
        illustration: "🪓🌲😴",
        paragraphs: [
          "A woodcutter worked harder every day, sawing from dawn to dark. But he cut LESS wood each week, and couldn't understand why.",
          "A friend asked, “When did you last sharpen your saw?” The woodcutter groaned, “I have no time to sharpen — I'm too busy sawing!”",
          "His saw had gone dull. All that effort was being wasted on a blunt blade.",
          "When he finally rested and sharpened it, he cut more wood in one hour than he had all day — with far less effort.",
        ],
        moral: "Taking time to care for yourself makes everything else work better.",
      },
      bigIdea: "Sharpen the saw: care for your body, brain, heart, and need for calm so you stay strong and at your best.",
      reading: [
        { heading: "Why it works", body: "You are the “saw.” If you never rest, eat well, move, or recharge, you get dull and tired — and everything becomes harder." },
        { heading: "How to do it", body: "Balance four areas: body (food, exercise, sleep), brain (learning), heart (friends and family), and calm (quiet time)." },
      ],
      realExamples: [
        "Getting good sleep before a big day.",
        "Playing outside to recharge your body and mood.",
        "Taking a quiet break when you feel overwhelmed.",
      ],
      tryIt: "Do one thing for your body and one thing for your mind today.",
      reflect: "Which part of you needs “sharpening” most right now — body, brain, heart, or calm?",
      quiz: [
        { q: "Why was the woodcutter cutting LESS wood?", options: ["His saw was dull and he wouldn't rest to sharpen it", "He was lazy", "The trees got harder", "His saw was too small"], answer: 0 },
        { q: "“Sharpen the saw” means…", options: ["Take care of yourself so you stay strong", "Work non-stop", "Never rest", "Just cut more wood"], answer: 0 },
        { q: "Skipping rest and self-care makes you…", options: ["Dull and tired, so everything's harder", "Faster forever", "Always happier", "Much stronger"], answer: 0 },
        { q: "You have a big day tomorrow. Sharpening the saw is…", options: ["Getting good sleep tonight", "Staying up all night", "Skipping meals", "Worrying till morning"], answer: 0 },
        { q: "A balanced “saw” includes caring for your…", options: ["Body, brain, heart, and calm", "Only homework", "Only games", "Only snacks"], answer: 0 },
      ],
    },
  ],
};
