// Builds Cucaino Park's 3D assets from Kenney CC0 kits (see scripts/park-assets.json).
//
//   node scripts/park-assets.mjs
//
// 1. downloads each kit zip into .park-assets-cache/ (gitignored, reused on later runs)
// 2. merges a kit's chosen models into ONE .glb (each model = a root node named by its id,
//    sharing the kit's single colormap texture), or one file per model for "separate" kits
// 3. dedupes, prunes, quantizes and meshopt-compresses -> public/park/<kit>.glb | <kit>/<id>.glb
// 4. writes lib/park/assets/manifest.gen.ts (typed model ids + file sizes)
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { NodeIO, Document } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import { dedup, prune, meshopt, mergeDocuments, unpartition } from "@gltf-transform/functions";
import { MeshoptEncoder, MeshoptDecoder } from "meshoptimizer";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cache = join(root, ".park-assets-cache");
const out = join(root, "public", "park");
const config = JSON.parse(readFileSync(join(root, "scripts", "park-assets.json"), "utf8"));

await MeshoptEncoder.ready;
await MeshoptDecoder.ready;
const io = new NodeIO()
  .registerExtensions(ALL_EXTENSIONS)
  .registerDependencies({ "meshopt.encoder": MeshoptEncoder, "meshopt.decoder": MeshoptDecoder });

function fetchKit(name, kit) {
  mkdirSync(cache, { recursive: true });
  const zip = join(cache, `${name}.zip`);
  if (!existsSync(zip)) {
    console.log(`  downloading ${name}…`);
    execFileSync("curl", ["-sL", "-o", zip, kit.zip]);
  }
  const dir = join(cache, name);
  if (!existsSync(join(dir, kit.dir))) {
    mkdirSync(dir, { recursive: true });
    execFileSync("unzip", ["-qo", zip, `${kit.dir}/*`, "License.txt", "-d", dir]);
    // unzip's wildcard doesn't descend into the Textures/ subfolder; some kits (nature) have none
    try {
      execFileSync("unzip", ["-qo", zip, `${kit.dir}/Textures/*`, "-d", dir], { stdio: "ignore" });
    } catch {
      // no textures in this kit — its models use plain material colours
    }
  }
  return join(dir, kit.dir);
}

async function compress(doc) {
  await doc.transform(
    dedup(),
    prune(),
    unpartition(),
    // meshopt() quantizes vertex data and registers EXT_meshopt_compression itself
    meshopt({ encoder: MeshoptEncoder, level: "medium" }),
  );
  return doc;
}

/** Wrap a loaded model's scene roots under one node named `id` so the kit file can be split by name. */
function wrapScene(doc, id) {
  const scene = doc.getRoot().listScenes()[0];
  const holder = doc.createNode(id);
  for (const child of scene.listChildren()) {
    scene.removeChild(child);
    holder.addChild(child);
  }
  scene.addChild(holder);
  return doc;
}

const manifest = {};
mkdirSync(out, { recursive: true });

for (const [name, kit] of Object.entries(config.kits)) {
  console.log(`▶ ${name} (${kit.models.length} models)`);
  const src = fetchKit(name, kit);
  if (kit.separate) {
    mkdirSync(join(out, name), { recursive: true });
    manifest[name] = { separate: true, models: {} };
    for (const id of kit.models) {
      const doc = await io.read(join(src, `${id}.glb`));
      await compress(doc);
      const file = join(out, name, `${id}.glb`);
      await io.write(file, doc);
      manifest[name].models[id] = statSync(file).size;
    }
  } else {
    const merged = new Document();
    merged.createBuffer();
    merged.createScene("kit");
    for (const id of kit.models) {
      const doc = wrapScene(await io.read(join(src, `${id}.glb`)), id);
      mergeDocuments(merged, doc);
    }
    // mergeDocuments appends each model's scene; fold them all into the first scene
    const [first, ...rest] = merged.getRoot().listScenes();
    for (const sc of rest) {
      for (const child of sc.listChildren()) first.addChild(child);
      sc.dispose();
    }
    await compress(merged);
    const file = join(out, `${name}.glb`);
    await io.write(file, merged);
    manifest[name] = { separate: false, bytes: statSync(file).size, models: kit.models };
  }
}

copyFileSync(join(cache, "coaster", "License.txt"), join(out, "LICENSE-kenney.txt"));

const lines = [
  "// GENERATED by scripts/park-assets.mjs — do not edit. Kenney CC0 models (public/park/LICENSE-kenney.txt).",
  `export const PARK_ASSETS = ${JSON.stringify(manifest, null, 2)} as const;`,
  "",
];
mkdirSync(join(root, "lib", "park", "assets"), { recursive: true });
writeFileSync(join(root, "lib", "park", "assets", "manifest.gen.ts"), lines.join("\n"));

let total = 0;
for (const [name, m] of Object.entries(manifest)) {
  const bytes = m.separate ? Object.values(m.models).reduce((a, b) => a + b, 0) : m.bytes;
  total += bytes;
  console.log(`  ${name.padEnd(8)} ${(bytes / 1024).toFixed(0).padStart(6)} KB`);
}
console.log(`  total    ${(total / 1024).toFixed(0).padStart(6)} KB`);
