// GENERATED by scripts/park-assets.mjs — do not edit. Kenney CC0 models (public/park/LICENSE-kenney.txt).
export const PARK_ASSETS = {
  "coaster": {
    "separate": false,
    "bytes": 153860,
    "models": [
      "park-entrance",
      "stall-food",
      "stall-drinks",
      "stall-information",
      "stall-toilets",
      "bench",
      "trash",
      "flowers",
      "grass",
      "tree",
      "tree-large",
      "path-straight",
      "path-corner",
      "path-crossing",
      "path-split",
      "path-exit",
      "path-steps",
      "station",
      "ride-entrance",
      "ride-exit",
      "coaster-train-front",
      "coaster-train"
    ]
  },
  "town": {
    "separate": false,
    "bytes": 120756,
    "models": [
      "fountain-round-detail",
      "stall",
      "stall-red",
      "stall-green",
      "stall-bench",
      "banner-red",
      "banner-green",
      "lantern",
      "hedge",
      "hedge-curved",
      "cart",
      "windmill",
      "tree-high-round",
      "fence",
      "rock-large"
    ]
  },
  "holiday": {
    "separate": false,
    "bytes": 80604,
    "models": [
      "candy-cane-red",
      "candy-cane-green",
      "present-a-cube",
      "present-a-round",
      "present-b-cube",
      "present-b-rectangle",
      "gingerbread-man",
      "gingerbread-woman",
      "lights-colored",
      "lantern-hanging"
    ]
  },
  "food": {
    "separate": false,
    "bytes": 138924,
    "models": [
      "lollypop",
      "cupcake",
      "donut-sprinkles",
      "donut-chocolate",
      "ice-cream",
      "ice-cream-cne",
      "sundae",
      "cake-birthday",
      "candy-bar",
      "cookie-chocolate",
      "popsicle",
      "strawberry",
      "cherries",
      "watermelon",
      "muffin",
      "whipped-cream"
    ]
  },
  "city": {
    "separate": false,
    "bytes": 169460,
    "models": [
      "building-a",
      "building-c",
      "building-e",
      "building-g",
      "building-k",
      "detail-awning",
      "detail-parasol-a"
    ]
  },
  "nature": {
    "separate": false,
    "bytes": 58056,
    "models": [
      "tree_default",
      "tree_oak",
      "tree_fat",
      "tree_blocks",
      "tree_cone",
      "plant_bush",
      "plant_bushLarge",
      "flower_purpleA",
      "flower_redA",
      "flower_yellowA",
      "mushroom_red",
      "mushroom_redGroup",
      "mushroom_tanTall",
      "grass_large",
      "lily_large",
      "stump_round"
    ]
  },
  "pets": {
    "separate": true,
    "models": {
      "animal-beaver": 62056,
      "animal-bee": 66436,
      "animal-bunny": 54900,
      "animal-cat": 67012,
      "animal-caterpillar": 54776,
      "animal-chick": 54244,
      "animal-cow": 54440,
      "animal-crab": 60952,
      "animal-deer": 60620,
      "animal-dog": 51436,
      "animal-elephant": 61984,
      "animal-fish": 43340,
      "animal-fox": 59908,
      "animal-giraffe": 55172,
      "animal-hog": 57932,
      "animal-koala": 55048,
      "animal-lion": 68520,
      "animal-monkey": 68936,
      "animal-panda": 54856,
      "animal-parrot": 64692,
      "animal-penguin": 54824,
      "animal-pig": 54456,
      "animal-polar": 45628,
      "animal-tiger": 68224
    }
  }
} as const;
