-- Quiz questions seed for quiz_questions2
-- 180 questions: 60 french, 60 spanish, 60 mandarin
-- 5 questions per (age_band x difficulty) = 5 x 4 x 3 = 60 per theme

-- ============================================================
-- FRENCH
-- ============================================================

-- french | 5_6 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does "bonjour" mean in English?', 'french', '5_6', 'easy', true, '[{"label":"Goodbye","isCorrect":false},{"label":"Hello","isCorrect":true},{"label":"Thank you","isCorrect":false},{"label":"Please","isCorrect":false}]'::jsonb, NULL, NULL, '"Bonjour" is the French greeting meaning "hello" or "good day".'),
(NULL, 'mc', 'What does "merci" mean in English?', 'french', '5_6', 'easy', true, '[{"label":"Sorry","isCorrect":false},{"label":"Please","isCorrect":false},{"label":"Thank you","isCorrect":true},{"label":"Hello","isCorrect":false}]'::jsonb, NULL, NULL, '"Merci" means "thank you" in French.'),
(NULL, 'mc', 'What does "au revoir" mean in English?', 'french', '5_6', 'easy', true, '[{"label":"Good morning","isCorrect":false},{"label":"See you later","isCorrect":false},{"label":"Goodbye","isCorrect":true},{"label":"Hello","isCorrect":false}]'::jsonb, NULL, NULL, '"Au revoir" is the French way of saying "goodbye".'),
(NULL, 'mc', 'How do you say the number 5 in French?', 'french', '5_6', 'easy', true, '[{"label":"trois","isCorrect":false},{"label":"sept","isCorrect":false},{"label":"cinq","isCorrect":true},{"label":"deux","isCorrect":false}]'::jsonb, NULL, NULL, '"Cinq" is the French word for the number 5.'),
(NULL, 'mc', 'What colour is "rouge" in French?', 'french', '5_6', 'easy', true, '[{"label":"Blue","isCorrect":false},{"label":"Green","isCorrect":false},{"label":"Yellow","isCorrect":false},{"label":"Red","isCorrect":true}]'::jsonb, NULL, NULL, '"Rouge" means red in French.');

-- french | 5_6 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which word is the French word for "dog"?', 'french', '5_6', 'medium', true, '[{"label":"chat","isCorrect":false},{"label":"chien","isCorrect":true},{"label":"lapin","isCorrect":false},{"label":"oiseau","isCorrect":false}]'::jsonb, NULL, NULL, '"Chien" means dog in French. "Chat" means cat.'),
(NULL, 'mc', 'What does "je m''appelle" mean?', 'french', '5_6', 'medium', true, '[{"label":"I like...","isCorrect":false},{"label":"I am...","isCorrect":false},{"label":"My name is...","isCorrect":true},{"label":"I have...","isCorrect":false}]'::jsonb, NULL, NULL, '"Je m''appelle" literally means "I call myself" — used to introduce your name.'),
(NULL, 'mc', 'How do you say "I am happy" in French?', 'french', '5_6', 'medium', true, '[{"label":"Je suis triste","isCorrect":false},{"label":"Je suis content","isCorrect":true},{"label":"Je suis fatigue","isCorrect":false},{"label":"Je suis fache","isCorrect":false}]'::jsonb, NULL, NULL, '"Je suis content(e)" means "I am happy" in French.'),
(NULL, 'mc', 'Which of these is a French animal word?', 'french', '5_6', 'medium', true, '[{"label":"perro","isCorrect":false},{"label":"Hund","isCorrect":false},{"label":"lapin","isCorrect":true},{"label":"gato","isCorrect":false}]'::jsonb, NULL, NULL, '"Lapin" is the French word for rabbit. The others are from Spanish and German.'),
(NULL, 'mc', 'What colour is "jaune" in French?', 'french', '5_6', 'medium', true, '[{"label":"Green","isCorrect":false},{"label":"Blue","isCorrect":false},{"label":"Orange","isCorrect":false},{"label":"Yellow","isCorrect":true}]'::jsonb, NULL, NULL, '"Jaune" means yellow in French.');

-- french | 5_6 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which sentence correctly uses the verb "avoir" (to have)?', 'french', '5_6', 'hard', true, '[{"label":"Je suis un chat","isCorrect":false},{"label":"J''ai un chat","isCorrect":true},{"label":"Je mange un chat","isCorrect":false},{"label":"Je vais un chat","isCorrect":false}]'::jsonb, NULL, NULL, '"J''ai" means "I have" — it comes from the verb "avoir". "Je suis" means "I am".'),
(NULL, 'mc', 'What is the French word for "school"?', 'french', '5_6', 'hard', true, '[{"label":"maison","isCorrect":false},{"label":"jardin","isCorrect":false},{"label":"ecole","isCorrect":true},{"label":"ville","isCorrect":false}]'::jsonb, NULL, NULL, '"Ecole" (école) means school in French.'),
(NULL, 'mc', 'How do you say "I eat an apple" in French?', 'french', '5_6', 'hard', true, '[{"label":"Je bois une pomme","isCorrect":false},{"label":"Je mange une pomme","isCorrect":true},{"label":"Je donne une pomme","isCorrect":false},{"label":"J''ai une pomme","isCorrect":false}]'::jsonb, NULL, NULL, '"Manger" means to eat. "Je mange" = I eat. "Pomme" = apple.'),
(NULL, 'mc', 'Which is the correct French phrase for "the big house"?', 'french', '5_6', 'hard', true, '[{"label":"la maison grande","isCorrect":false},{"label":"le grande maison","isCorrect":false},{"label":"la grande maison","isCorrect":true},{"label":"les grande maison","isCorrect":false}]'::jsonb, NULL, NULL, 'In French, adjectives like "grande" (big) come before the noun. "Maison" is feminine so the article is "la".'),
(NULL, 'mc', 'What does "Qu''est-ce que c''est?" mean?', 'french', '5_6', 'hard', true, '[{"label":"Who is that?","isCorrect":false},{"label":"How are you?","isCorrect":false},{"label":"Where is it?","isCorrect":false},{"label":"What is it?","isCorrect":true}]'::jsonb, NULL, NULL, '"Qu''est-ce que c''est?" is a common French question meaning "What is it?"');

-- french | 7_8 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does "s''il vous plait" mean?', 'french', '7_8', 'easy', true, '[{"label":"Thank you","isCorrect":false},{"label":"Excuse me","isCorrect":false},{"label":"Please","isCorrect":true},{"label":"Sorry","isCorrect":false}]'::jsonb, NULL, NULL, '"S''il vous plait" is the polite form of "please" in French.'),
(NULL, 'mc', 'Which word means "friend" in French?', 'french', '7_8', 'easy', true, '[{"label":"famille","isCorrect":false},{"label":"frere","isCorrect":false},{"label":"ami","isCorrect":true},{"label":"soeur","isCorrect":false}]'::jsonb, NULL, NULL, '"Ami" (masc.) or "amie" (fem.) means friend in French.'),
(NULL, 'mc', 'What does "je voudrais" mean?', 'french', '7_8', 'easy', true, '[{"label":"I like","isCorrect":false},{"label":"I would like","isCorrect":true},{"label":"I have","isCorrect":false},{"label":"I go","isCorrect":false}]'::jsonb, NULL, NULL, '"Je voudrais" is the conditional form of "vouloir" meaning "I would like" — very polite.'),
(NULL, 'mc', 'How do you ask "How old are you?" in French?', 'french', '7_8', 'easy', true, '[{"label":"Comment t''appelles-tu?","isCorrect":false},{"label":"Tu aimes quoi?","isCorrect":false},{"label":"Quel age as-tu?","isCorrect":true},{"label":"Tu es comment?","isCorrect":false}]'::jsonb, NULL, NULL, '"Quel age as-tu?" literally asks "What age do you have?" — French uses "avoir" (to have) for age.'),
(NULL, 'mc', 'What is "chat" in English?', 'french', '7_8', 'easy', true, '[{"label":"Dog","isCorrect":false},{"label":"Bird","isCorrect":false},{"label":"Cat","isCorrect":true},{"label":"Fish","isCorrect":false}]'::jsonb, NULL, NULL, '"Chat" means cat in French. It is pronounced roughly like "sha".');

-- french | 7_8 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which is the correct definite article for "table" in French?', 'french', '7_8', 'medium', true, '[{"label":"le","isCorrect":false},{"label":"les","isCorrect":false},{"label":"la","isCorrect":true},{"label":"un","isCorrect":false}]'::jsonb, NULL, NULL, '"Table" is feminine in French, so the definite article is "la". "Le" is masculine.'),
(NULL, 'mc', 'What does "aller" mean in English?', 'french', '7_8', 'medium', true, '[{"label":"To eat","isCorrect":false},{"label":"To have","isCorrect":false},{"label":"To go","isCorrect":true},{"label":"To be","isCorrect":false}]'::jsonb, NULL, NULL, '"Aller" is a very common irregular French verb meaning "to go".'),
(NULL, 'mc', 'Which sentence means "She is reading a book"?', 'french', '7_8', 'medium', true, '[{"label":"Elle mange un livre","isCorrect":false},{"label":"Elle lit un livre","isCorrect":true},{"label":"Elle ecrit un livre","isCorrect":false},{"label":"Elle a un livre","isCorrect":false}]'::jsonb, NULL, NULL, '"Lire" means to read. "Elle lit" = she reads/is reading. "Livre" = book.'),
(NULL, 'mc', 'How do you say "We are" in French?', 'french', '7_8', 'medium', true, '[{"label":"ils sont","isCorrect":false},{"label":"tu es","isCorrect":false},{"label":"vous etes","isCorrect":false},{"label":"nous sommes","isCorrect":true}]'::jsonb, NULL, NULL, '"Nous sommes" = we are. "Etre" (to be) is irregular: je suis, tu es, il est, nous sommes, vous etes, ils sont.'),
(NULL, 'mc', 'What does "beaucoup" mean?', 'french', '7_8', 'medium', true, '[{"label":"Beautiful","isCorrect":false},{"label":"A little","isCorrect":false},{"label":"A lot / very much","isCorrect":true},{"label":"Sometimes","isCorrect":false}]'::jsonb, NULL, NULL, '"Beaucoup" means "a lot" or "very much". "Merci beaucoup" = thank you very much.');

-- french | 7_8 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which is the correct passe compose of "manger" for "I ate"?', 'french', '7_8', 'hard', true, '[{"label":"je mange","isCorrect":false},{"label":"j''ai mange","isCorrect":true},{"label":"je mangeais","isCorrect":false},{"label":"j''allais manger","isCorrect":false}]'::jsonb, NULL, NULL, 'Passe compose = avoir/etre + past participle. "Manger" uses "avoir": j''ai mange = I ate.'),
(NULL, 'mc', 'What is the plural of "un cheval" (a horse) in French?', 'french', '7_8', 'hard', true, '[{"label":"des chevals","isCorrect":false},{"label":"des chevales","isCorrect":false},{"label":"des chevaux","isCorrect":true},{"label":"des chevales","isCorrect":false}]'::jsonb, NULL, NULL, 'Many French nouns ending in -al change to -aux in the plural. "Cheval" becomes "chevaux".'),
(NULL, 'mc', 'Which sentence uses a reflexive verb correctly?', 'french', '7_8', 'hard', true, '[{"label":"Je lave mes mains","isCorrect":false},{"label":"Je me lave les mains","isCorrect":true},{"label":"Je laver les mains","isCorrect":false},{"label":"Mes mains je lave","isCorrect":false}]'::jsonb, NULL, NULL, 'Reflexive verbs use a reflexive pronoun (me, te, se...). "Se laver" = to wash oneself; "Je me lave les mains" = I wash my hands.'),
(NULL, 'mc', 'What does "il fait beau" describe?', 'french', '7_8', 'hard', true, '[{"label":"He is handsome","isCorrect":false},{"label":"It is nice weather","isCorrect":true},{"label":"He does well","isCorrect":false},{"label":"It is hot","isCorrect":false}]'::jsonb, NULL, NULL, '"Il fait beau" is a weather expression meaning "the weather is nice / it is fine".'),
(NULL, 'mc', 'Which word is an adverb in French?', 'french', '7_8', 'hard', true, '[{"label":"rouge","isCorrect":false},{"label":"maison","isCorrect":false},{"label":"lentement","isCorrect":true},{"label":"grand","isCorrect":false}]'::jsonb, NULL, NULL, '"Lentement" means "slowly" — it is an adverb. French adverbs often end in -ment, like English -ly.');

-- french | 9_10 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What is the French word for "city"?', 'french', '9_10', 'easy', true, '[{"label":"pays","isCorrect":false},{"label":"rue","isCorrect":false},{"label":"ville","isCorrect":true},{"label":"quartier","isCorrect":false}]'::jsonb, NULL, NULL, '"Ville" means city or town in French.'),
(NULL, 'mc', 'What does "depuis" mean?', 'french', '9_10', 'easy', true, '[{"label":"because","isCorrect":false},{"label":"since / for (time)","isCorrect":true},{"label":"after","isCorrect":false},{"label":"before","isCorrect":false}]'::jsonb, NULL, NULL, '"Depuis" expresses duration or the starting point of an action still ongoing. "J''habite ici depuis 3 ans" = I have lived here for 3 years.'),
(NULL, 'mc', 'Which is the correct negation of "je parle"?', 'french', '9_10', 'easy', true, '[{"label":"je parle non","isCorrect":false},{"label":"je no parle","isCorrect":false},{"label":"je ne parle pas","isCorrect":true},{"label":"je pas parle","isCorrect":false}]'::jsonb, NULL, NULL, 'French negation wraps the verb: ne...pas. "Je ne parle pas" = I do not speak.'),
(NULL, 'mc', 'What does "apprendre" mean?', 'french', '9_10', 'easy', true, '[{"label":"To teach","isCorrect":false},{"label":"To remember","isCorrect":false},{"label":"To learn","isCorrect":true},{"label":"To read","isCorrect":false}]'::jsonb, NULL, NULL, '"Apprendre" means to learn in French. It can also mean to teach in some constructions.'),
(NULL, 'mc', 'What is "le printemps" in English?', 'french', '9_10', 'easy', true, '[{"label":"Winter","isCorrect":false},{"label":"Autumn","isCorrect":false},{"label":"Summer","isCorrect":false},{"label":"Spring","isCorrect":true}]'::jsonb, NULL, NULL, '"Le printemps" means spring. The four seasons: printemps, ete, automne, hiver.');

-- french | 9_10 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which tense is "je lisais"?', 'french', '9_10', 'medium', true, '[{"label":"Passe compose","isCorrect":false},{"label":"Futur simple","isCorrect":false},{"label":"Imparfait","isCorrect":true},{"label":"Subjonctif","isCorrect":false}]'::jsonb, NULL, NULL, '"Je lisais" is the imparfait (imperfect) tense, used for ongoing or habitual past actions.'),
(NULL, 'mc', 'What does the expression "avoir faim" mean?', 'french', '9_10', 'medium', true, '[{"label":"To be cold","isCorrect":false},{"label":"To be scared","isCorrect":false},{"label":"To be hungry","isCorrect":true},{"label":"To be tired","isCorrect":false}]'::jsonb, NULL, NULL, '"Avoir faim" literally means "to have hunger" — French uses "avoir" for many states: faim, soif, chaud, froid, peur.'),
(NULL, 'mc', 'Which pronoun replaces a direct object in "je mange la pomme"?', 'french', '9_10', 'medium', true, '[{"label":"lui","isCorrect":false},{"label":"leur","isCorrect":false},{"label":"y","isCorrect":false},{"label":"la","isCorrect":true}]'::jsonb, NULL, NULL, '"La pomme" is feminine, so the direct object pronoun is "la". "Je la mange" = I eat it.'),
(NULL, 'mc', 'What is the futur simple of "parler" for "nous"?', 'french', '9_10', 'medium', true, '[{"label":"nous parlons","isCorrect":false},{"label":"nous parlions","isCorrect":false},{"label":"nous avons parle","isCorrect":false},{"label":"nous parlerons","isCorrect":true}]'::jsonb, NULL, NULL, 'Futur simple adds endings to the infinitive: parler + ons = parlerons. "Nous parlerons" = we will speak.'),
(NULL, 'mc', 'What does "quand meme" mean in French?', 'french', '9_10', 'medium', true, '[{"label":"From time to time","isCorrect":false},{"label":"At the same time","isCorrect":false},{"label":"Even so / all the same","isCorrect":true},{"label":"Already","isCorrect":false}]'::jsonb, NULL, NULL, '"Quand meme" means "even so", "still", or "all the same" — used to show mild protest or persistence.');

-- french | 9_10 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which sentence uses the subjonctif correctly?', 'french', '9_10', 'hard', true, '[{"label":"Je veux que tu viens","isCorrect":false},{"label":"Je veux que tu viennes","isCorrect":true},{"label":"Je veux que tu venais","isCorrect":false},{"label":"Je veux que tu es venu","isCorrect":false}]'::jsonb, NULL, NULL, 'After "vouloir que", the subjonctif is required. "Venir" in the subjonctif: que tu viennes.'),
(NULL, 'mc', 'What is the correct agreement in "les filles sont arrivees"?', 'french', '9_10', 'hard', true, '[{"label":"Past participles with etre agree with the subject","isCorrect":true},{"label":"Past participles never change","isCorrect":false},{"label":"Only the subject changes form","isCorrect":false},{"label":"Agreement depends on the object","isCorrect":false}]'::jsonb, NULL, NULL, 'With "etre" verbs in passe compose, the past participle agrees with the subject in gender and number.'),
(NULL, 'mc', 'What does "au contraire" mean?', 'french', '9_10', 'hard', true, '[{"label":"On the contrary","isCorrect":true},{"label":"Of course","isCorrect":false},{"label":"In other words","isCorrect":false},{"label":"For example","isCorrect":false}]'::jsonb, NULL, NULL, '"Au contraire" is a French expression meaning "on the contrary" — also used directly in English.'),
(NULL, 'mc', 'In formal writing, which conjunction introduces a concession?', 'french', '9_10', 'hard', true, '[{"label":"parce que","isCorrect":false},{"label":"donc","isCorrect":false},{"label":"bien que","isCorrect":true},{"label":"alors","isCorrect":false}]'::jsonb, NULL, NULL, '"Bien que" (although) introduces a concession and is followed by the subjonctif. "Parce que" = because; "donc" = therefore.'),
(NULL, 'mc', 'What is the passive voice of "on a construit la maison" (the house was built)?', 'french', '9_10', 'hard', true, '[{"label":"la maison construisait","isCorrect":false},{"label":"la maison a ete construite","isCorrect":true},{"label":"la maison etait construite","isCorrect":false},{"label":"la maison construira","isCorrect":false}]'::jsonb, NULL, NULL, 'The French passive voice uses etre + past participle. "La maison a ete construite" = the house was built (passe compose passive).');

-- french | 11_12 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What literary term describes giving human qualities to non-human things?', 'french', '11_12', 'easy', true, '[{"label":"Metaphore","isCorrect":false},{"label":"Hyperbole","isCorrect":false},{"label":"Personnification","isCorrect":true},{"label":"Alliteration","isCorrect":false}]'::jsonb, NULL, NULL, '"Personnification" (personification) attributes human characteristics to objects, animals, or ideas.'),
(NULL, 'mc', 'What does "neanmoins" mean in French?', 'french', '11_12', 'easy', true, '[{"label":"Therefore","isCorrect":false},{"label":"However / nevertheless","isCorrect":true},{"label":"Because","isCorrect":false},{"label":"Although","isCorrect":false}]'::jsonb, NULL, NULL, '"Neanmoins" (néanmoins) means "nevertheless" or "however" — a formal connective.'),
(NULL, 'mc', 'Who wrote "Les Miserables"?', 'french', '11_12', 'easy', true, '[{"label":"Emile Zola","isCorrect":false},{"label":"Albert Camus","isCorrect":false},{"label":"Victor Hugo","isCorrect":true},{"label":"Gustave Flaubert","isCorrect":false}]'::jsonb, NULL, NULL, '"Les Miserables" was written by Victor Hugo, published in 1862. It follows Jean Valjean in post-revolutionary France.'),
(NULL, 'mc', 'What is the French term for "stream of consciousness" in literature?', 'french', '11_12', 'easy', true, '[{"label":"flux de pensee","isCorrect":true},{"label":"courant d''action","isCorrect":false},{"label":"recit lineaire","isCorrect":false},{"label":"style indirect","isCorrect":false}]'::jsonb, NULL, NULL, '"Flux de pensee" or "flux de conscience" refers to the literary technique where a character''s thoughts flow continuously.'),
(NULL, 'mc', 'What does the expression "avoir le cafard" mean?', 'french', '11_12', 'easy', true, '[{"label":"To be very busy","isCorrect":false},{"label":"To feel down / have the blues","isCorrect":true},{"label":"To be scared of insects","isCorrect":false},{"label":"To gossip","isCorrect":false}]'::jsonb, NULL, NULL, '"Avoir le cafard" (literally "to have the cockroach") is an idiomatic expression meaning to feel down or depressed.');

-- french | 11_12 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which tense expresses a hypothetical condition ("if I were rich, I would...")?', 'french', '11_12', 'medium', true, '[{"label":"Imparfait + conditionnel present","isCorrect":true},{"label":"Passe compose + futur simple","isCorrect":false},{"label":"Subjonctif + imparfait","isCorrect":false},{"label":"Futur simple + futur simple","isCorrect":false}]'::jsonb, NULL, NULL, 'Hypothetical conditions in French: "si" + imparfait in the "if" clause, conditionnel present in the result clause.'),
(NULL, 'mc', 'What does the "plus-que-parfait" (pluperfect) tense express?', 'french', '11_12', 'medium', true, '[{"label":"An action happening right now","isCorrect":false},{"label":"An action that had happened before another past action","isCorrect":true},{"label":"A future possibility","isCorrect":false},{"label":"A habitual past action","isCorrect":false}]'::jsonb, NULL, NULL, 'The plus-que-parfait (had done) expresses an action completed before another past action. Formed with imparfait of avoir/etre + past participle.'),
(NULL, 'mc', 'Which of these is a Francophone African country?', 'french', '11_12', 'medium', true, '[{"label":"Angola","isCorrect":false},{"label":"Kenya","isCorrect":false},{"label":"Senegal","isCorrect":true},{"label":"Tanzania","isCorrect":false}]'::jsonb, NULL, NULL, 'Senegal is a Francophone country in West Africa, with French as its official language. It was a French colony until 1960.'),
(NULL, 'mc', 'What literary movement did Emile Zola champion?', 'french', '11_12', 'medium', true, '[{"label":"Romantisme","isCorrect":false},{"label":"Surrealisme","isCorrect":false},{"label":"Naturalisme","isCorrect":true},{"label":"Classicisme","isCorrect":false}]'::jsonb, NULL, NULL, 'Emile Zola was the leading figure of Naturalism (Naturalisme), which applied scientific methods to literature to depict social reality.'),
(NULL, 'mc', 'What does "d''autant plus que" mean in formal French?', 'french', '11_12', 'medium', true, '[{"label":"As soon as","isCorrect":false},{"label":"All the more so because","isCorrect":true},{"label":"Provided that","isCorrect":false},{"label":"In spite of","isCorrect":false}]'::jsonb, NULL, NULL, '"D''autant plus que" is a formal connective meaning "all the more so because" — used in academic writing.');

-- french | 11_12 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which sentence uses the conditionnel passe correctly?', 'french', '11_12', 'hard', true, '[{"label":"Si j''avais su, je venais","isCorrect":false},{"label":"Si j''avais su, je serais venu","isCorrect":true},{"label":"Si j''aurais su, je serais venu","isCorrect":false},{"label":"Si j''ai su, j''aurais venu","isCorrect":false}]'::jsonb, NULL, NULL, 'Past hypothetical: "si" + plus-que-parfait, then conditionnel passe. "Si j''avais su, je serais venu" = If I had known, I would have come.'),
(NULL, 'mc', 'What is the rhetorical device in "la lumiere chantait" (the light sang)?', 'french', '11_12', 'hard', true, '[{"label":"Synecdoque","isCorrect":false},{"label":"Anaphore","isCorrect":false},{"label":"Synesthesie","isCorrect":true},{"label":"Euphemisme","isCorrect":false}]'::jsonb, NULL, NULL, '"Synesthesie" (synesthesia) blends senses — describing light using a sound verb. Common in Symbolist poetry.'),
(NULL, 'mc', 'What is the "these-antithese-synthese" structure used for in French essays?', 'french', '11_12', 'hard', true, '[{"label":"Comparing two poems","isCorrect":false},{"label":"Structuring a dialectical argument","isCorrect":true},{"label":"Writing a personal narrative","isCorrect":false},{"label":"Analysing grammatical structures","isCorrect":false}]'::jsonb, NULL, NULL, 'The these-antithese-synthese (TAS) plan is the standard French essay structure: present a thesis, counter it, then reconcile both positions.'),
(NULL, 'mc', 'Which French philosopher wrote "L''Etre et le Neant" (Being and Nothingness)?', 'french', '11_12', 'hard', true, '[{"label":"Albert Camus","isCorrect":false},{"label":"Simone de Beauvoir","isCorrect":false},{"label":"Jean-Paul Sartre","isCorrect":true},{"label":"Michel Foucault","isCorrect":false}]'::jsonb, NULL, NULL, '"L''Etre et le Neant" (1943) is Jean-Paul Sartre''s foundational existentialist work. Sartre coined "existence precedes essence".'),
(NULL, 'mc', 'What grammatical mood is used in "Vive la France!"?', 'french', '11_12', 'hard', true, '[{"label":"Indicatif","isCorrect":false},{"label":"Conditionnel","isCorrect":false},{"label":"Subjonctif","isCorrect":true},{"label":"Imperatif","isCorrect":false}]'::jsonb, NULL, NULL, '"Vive" is the subjonctif of "vivre". This exclamatory construction (Vive/Vivent + noun) uses the subjonctif to express a wish or acclamation.');

-- ============================================================
-- SPANISH
-- ============================================================

-- spanish | 5_6 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does "hola" mean in English?', 'spanish', '5_6', 'easy', true, '[{"label":"Goodbye","isCorrect":false},{"label":"Hello","isCorrect":true},{"label":"Thank you","isCorrect":false},{"label":"Please","isCorrect":false}]'::jsonb, NULL, NULL, '"Hola" is the Spanish greeting meaning "hello".'),
(NULL, 'mc', 'What does "gracias" mean?', 'spanish', '5_6', 'easy', true, '[{"label":"Please","isCorrect":false},{"label":"Sorry","isCorrect":false},{"label":"Thank you","isCorrect":true},{"label":"Goodbye","isCorrect":false}]'::jsonb, NULL, NULL, '"Gracias" means "thank you" in Spanish.'),
(NULL, 'mc', 'What does "adios" mean in English?', 'spanish', '5_6', 'easy', true, '[{"label":"Hello","isCorrect":false},{"label":"See you","isCorrect":false},{"label":"Goodbye","isCorrect":true},{"label":"Good night","isCorrect":false}]'::jsonb, NULL, NULL, '"Adios" is the Spanish word for "goodbye".'),
(NULL, 'mc', 'What colour is "rojo" in Spanish?', 'spanish', '5_6', 'easy', true, '[{"label":"Blue","isCorrect":false},{"label":"Green","isCorrect":false},{"label":"Red","isCorrect":true},{"label":"Yellow","isCorrect":false}]'::jsonb, NULL, NULL, '"Rojo" means red in Spanish.'),
(NULL, 'mc', 'How do you say the number 3 in Spanish?', 'spanish', '5_6', 'easy', true, '[{"label":"uno","isCorrect":false},{"label":"dos","isCorrect":false},{"label":"tres","isCorrect":true},{"label":"cuatro","isCorrect":false}]'::jsonb, NULL, NULL, '"Tres" is the Spanish word for 3. uno=1, dos=2, tres=3, cuatro=4, cinco=5.');

-- spanish | 5_6 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What is the Spanish word for "dog"?', 'spanish', '5_6', 'medium', true, '[{"label":"gato","isCorrect":false},{"label":"perro","isCorrect":true},{"label":"pajaro","isCorrect":false},{"label":"pez","isCorrect":false}]'::jsonb, NULL, NULL, '"Perro" means dog in Spanish. "Gato" means cat.'),
(NULL, 'mc', 'How do you say "My name is..." in Spanish?', 'spanish', '5_6', 'medium', true, '[{"label":"Yo soy...","isCorrect":false},{"label":"Me llamo...","isCorrect":true},{"label":"Tengo...","isCorrect":false},{"label":"Soy llamado...","isCorrect":false}]'::jsonb, NULL, NULL, '"Me llamo" literally means "I call myself" — used to state your name in Spanish.'),
(NULL, 'mc', 'What does "por favor" mean?', 'spanish', '5_6', 'medium', true, '[{"label":"Thank you","isCorrect":false},{"label":"You''re welcome","isCorrect":false},{"label":"Please","isCorrect":true},{"label":"Excuse me","isCorrect":false}]'::jsonb, NULL, NULL, '"Por favor" means "please" in Spanish.'),
(NULL, 'mc', 'What colour is "amarillo" in Spanish?', 'spanish', '5_6', 'medium', true, '[{"label":"Green","isCorrect":false},{"label":"Orange","isCorrect":false},{"label":"Blue","isCorrect":false},{"label":"Yellow","isCorrect":true}]'::jsonb, NULL, NULL, '"Amarillo" means yellow in Spanish.'),
(NULL, 'mc', 'What does "buenas noches" mean?', 'spanish', '5_6', 'medium', true, '[{"label":"Good morning","isCorrect":false},{"label":"Good afternoon","isCorrect":false},{"label":"Good night","isCorrect":true},{"label":"Hello","isCorrect":false}]'::jsonb, NULL, NULL, '"Buenas noches" means "good night" in Spanish. "Buenos dias" = good morning, "Buenas tardes" = good afternoon.');

-- spanish | 5_6 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which sentence means "I have a cat" in Spanish?', 'spanish', '5_6', 'hard', true, '[{"label":"Yo soy un gato","isCorrect":false},{"label":"Tengo un gato","isCorrect":true},{"label":"Estoy un gato","isCorrect":false},{"label":"Voy un gato","isCorrect":false}]'::jsonb, NULL, NULL, '"Tener" means to have. "Tengo" = I have. So "Tengo un gato" = I have a cat.'),
(NULL, 'mc', 'What does "cuantos anos tienes?" mean?', 'spanish', '5_6', 'hard', true, '[{"label":"What is your name?","isCorrect":false},{"label":"Where do you live?","isCorrect":false},{"label":"How old are you?","isCorrect":true},{"label":"Do you have siblings?","isCorrect":false}]'::jsonb, NULL, NULL, '"Cuantos anos tienes?" = How many years do you have? Spanish uses "tener" (to have) for age.'),
(NULL, 'mc', 'What is the Spanish word for "school"?', 'spanish', '5_6', 'hard', true, '[{"label":"casa","isCorrect":false},{"label":"tienda","isCorrect":false},{"label":"escuela","isCorrect":true},{"label":"calle","isCorrect":false}]'::jsonb, NULL, NULL, '"Escuela" means school in Spanish.'),
(NULL, 'mc', 'Which word is the Spanish indefinite article for a masculine noun?', 'spanish', '5_6', 'hard', true, '[{"label":"la","isCorrect":false},{"label":"una","isCorrect":false},{"label":"el","isCorrect":false},{"label":"un","isCorrect":true}]'::jsonb, NULL, NULL, '"Un" is the masculine indefinite article (a/an). "Una" is the feminine. "El/la" are definite articles (the).'),
(NULL, 'mc', 'What does "me gusta" mean?', 'spanish', '5_6', 'hard', true, '[{"label":"I want","isCorrect":false},{"label":"I like","isCorrect":true},{"label":"I have","isCorrect":false},{"label":"I need","isCorrect":false}]'::jsonb, NULL, NULL, '"Me gusta" literally means "it pleases me" — used to express liking something. "Me gusta el chocolate" = I like chocolate.');

-- spanish | 7_8 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What is the difference between "ser" and "estar"?', 'spanish', '7_8', 'easy', true, '[{"label":"Both mean to go","isCorrect":false},{"label":"Ser is permanent, estar is temporary/state","isCorrect":true},{"label":"Ser is formal, estar is informal","isCorrect":false},{"label":"They are exact synonyms","isCorrect":false}]'::jsonb, NULL, NULL, '"Ser" is used for permanent traits (nationality, identity); "estar" for states and locations. Both mean "to be".'),
(NULL, 'mc', 'What does "hablar" mean?', 'spanish', '7_8', 'easy', true, '[{"label":"To eat","isCorrect":false},{"label":"To live","isCorrect":false},{"label":"To speak","isCorrect":true},{"label":"To write","isCorrect":false}]'::jsonb, NULL, NULL, '"Hablar" means "to speak" in Spanish. It is a regular -ar verb.'),
(NULL, 'mc', 'How do you say "I am hungry" in Spanish?', 'spanish', '7_8', 'easy', true, '[{"label":"Estoy caliente","isCorrect":false},{"label":"Tengo hambre","isCorrect":true},{"label":"Soy hambriento","isCorrect":false},{"label":"Estoy hambre","isCorrect":false}]'::jsonb, NULL, NULL, 'Spanish uses "tener hambre" (to have hunger). "Tengo hambre" = I am hungry.'),
(NULL, 'mc', 'What is "el hermano" in English?', 'spanish', '7_8', 'easy', true, '[{"label":"The sister","isCorrect":false},{"label":"The father","isCorrect":false},{"label":"The brother","isCorrect":true},{"label":"The friend","isCorrect":false}]'::jsonb, NULL, NULL, '"El hermano" means "the brother". "La hermana" = the sister.'),
(NULL, 'mc', 'Which is the correct Spanish for "We eat dinner"?', 'spanish', '7_8', 'easy', true, '[{"label":"Nosotros almorzamos","isCorrect":false},{"label":"Nosotros cenamos","isCorrect":true},{"label":"Nosotros desayunamos","isCorrect":false},{"label":"Nosotros comemos","isCorrect":false}]'::jsonb, NULL, NULL, '"Cenar" means to eat dinner. "Almorzar" = to have lunch, "desayunar" = to have breakfast.');

-- spanish | 7_8 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which verb form correctly conjugates "vivir" for "nosotros"?', 'spanish', '7_8', 'medium', true, '[{"label":"vivemos","isCorrect":false},{"label":"vivimos","isCorrect":true},{"label":"vivamos","isCorrect":false},{"label":"vivemos","isCorrect":false}]'::jsonb, NULL, NULL, 'Regular -ir verbs: nosotros vivimos. "Vivir" = to live.'),
(NULL, 'mc', 'What does "hace calor" mean?', 'spanish', '7_8', 'medium', true, '[{"label":"He is hot","isCorrect":false},{"label":"It is hot (weather)","isCorrect":true},{"label":"I feel warm","isCorrect":false},{"label":"The sun shines","isCorrect":false}]'::jsonb, NULL, NULL, '"Hacer" is used for weather. "Hace calor" = it is hot; "hace frio" = it is cold; "hace sol" = it is sunny.'),
(NULL, 'mc', 'What is the plural of "el lapiz" (pencil)?', 'spanish', '7_8', 'medium', true, '[{"label":"los lapizes","isCorrect":false},{"label":"los lapices","isCorrect":true},{"label":"los lapizos","isCorrect":false},{"label":"los lapiz","isCorrect":false}]'::jsonb, NULL, NULL, 'Nouns ending in -z change to -c before -es in the plural: lapiz → lapices.'),
(NULL, 'mc', 'How do you form a question in Spanish?', 'spanish', '7_8', 'medium', true, '[{"label":"Put no before the verb","isCorrect":false},{"label":"Add -cion at the end","isCorrect":false},{"label":"Use inverted question marks and rising intonation","isCorrect":true},{"label":"Change the verb ending to -ar","isCorrect":false}]'::jsonb, NULL, NULL, 'Spanish questions use an inverted opening question mark (¿) and a closing one (?). Word order may invert.'),
(NULL, 'mc', 'What does "a veces" mean?', 'spanish', '7_8', 'medium', true, '[{"label":"Always","isCorrect":false},{"label":"Never","isCorrect":false},{"label":"Sometimes","isCorrect":true},{"label":"Often","isCorrect":false}]'::jsonb, NULL, NULL, '"A veces" means "sometimes". Other frequency adverbs: siempre (always), nunca (never), generalmente (generally).');

-- spanish | 7_8 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which is the correct preterite (simple past) of "hablar" for "yo"?', 'spanish', '7_8', 'hard', true, '[{"label":"yo hablaba","isCorrect":false},{"label":"yo hable","isCorrect":true},{"label":"yo hablo","isCorrect":false},{"label":"yo hablare","isCorrect":false}]'::jsonb, NULL, NULL, 'Preterite of -ar verbs: yo hable (note the accent). "Hablaba" is imperfect; "hablo" is present.'),
(NULL, 'mc', 'What is the difference between "por" and "para"?', 'spanish', '7_8', 'hard', true, '[{"label":"They are interchangeable","isCorrect":false},{"label":"Por = cause/duration, para = purpose/destination","isCorrect":true},{"label":"Por is formal, para is informal","isCorrect":false},{"label":"Por = place, para = time","isCorrect":false}]'::jsonb, NULL, NULL, '"Por" covers cause, exchange, duration, or agent. "Para" covers purpose, destination, recipient, or deadline.'),
(NULL, 'mc', 'What does the verb "poder" mean?', 'spanish', '7_8', 'hard', true, '[{"label":"To want","isCorrect":false},{"label":"To know","isCorrect":false},{"label":"To be able to / can","isCorrect":true},{"label":"To put","isCorrect":false}]'::jsonb, NULL, NULL, '"Poder" is a stem-changing modal verb meaning "to be able to" or "can". "Puedo hablar espanol" = I can speak Spanish.'),
(NULL, 'mc', 'Which reflexive verb means "to get up"?', 'spanish', '7_8', 'hard', true, '[{"label":"acostarse","isCorrect":false},{"label":"levantarse","isCorrect":true},{"label":"ducharse","isCorrect":false},{"label":"llamarse","isCorrect":false}]'::jsonb, NULL, NULL, '"Levantarse" means to get up. "Acostarse" = to go to bed; "ducharse" = to shower; "llamarse" = to be called.'),
(NULL, 'mc', 'What does "en cambio" mean?', 'spanish', '7_8', 'hard', true, '[{"label":"For example","isCorrect":false},{"label":"On the other hand","isCorrect":true},{"label":"In addition","isCorrect":false},{"label":"Therefore","isCorrect":false}]'::jsonb, NULL, NULL, '"En cambio" means "on the other hand" or "whereas" — used to contrast two ideas.');

-- spanish | 9_10 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does "sin embargo" mean?', 'spanish', '9_10', 'easy', true, '[{"label":"Therefore","isCorrect":false},{"label":"Nevertheless / however","isCorrect":true},{"label":"For example","isCorrect":false},{"label":"In addition","isCorrect":false}]'::jsonb, NULL, NULL, '"Sin embargo" means "however" or "nevertheless" — a common discourse connective.'),
(NULL, 'mc', 'What is the Spanish word for "to choose"?', 'spanish', '9_10', 'easy', true, '[{"label":"elegir","isCorrect":true},{"label":"empezar","isCorrect":false},{"label":"buscar","isCorrect":false},{"label":"conseguir","isCorrect":false}]'::jsonb, NULL, NULL, '"Elegir" means to choose or to elect. It is a stem-changing verb (e→i).'),
(NULL, 'mc', 'Which country is NOT a Spanish-speaking nation?', 'spanish', '9_10', 'easy', true, '[{"label":"Chile","isCorrect":false},{"label":"Bolivia","isCorrect":false},{"label":"Brazil","isCorrect":true},{"label":"Peru","isCorrect":false}]'::jsonb, NULL, NULL, 'Brazil''s official language is Portuguese, not Spanish. All other listed countries speak Spanish.'),
(NULL, 'mc', 'What does "el medio ambiente" mean?', 'spanish', '9_10', 'easy', true, '[{"label":"The media","isCorrect":false},{"label":"The middle of the city","isCorrect":false},{"label":"The environment","isCorrect":true},{"label":"The neighbourhood","isCorrect":false}]'::jsonb, NULL, NULL, '"El medio ambiente" means "the environment" in Spanish.'),
(NULL, 'mc', 'How do you express the future with "ir a" + infinitive?', 'spanish', '9_10', 'easy', true, '[{"label":"Voy a como","isCorrect":false},{"label":"Voy comer","isCorrect":false},{"label":"Voy a comer","isCorrect":true},{"label":"Iré comer","isCorrect":false}]'::jsonb, NULL, NULL, '"Ir a" + infinitive expresses near future: "Voy a comer" = I am going to eat.');

-- spanish | 9_10 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which tense is "habia comido" (had eaten)?', 'spanish', '9_10', 'medium', true, '[{"label":"Preterito indefinido","isCorrect":false},{"label":"Preterito imperfecto","isCorrect":false},{"label":"Preterito pluscuamperfecto","isCorrect":true},{"label":"Condicional","isCorrect":false}]'::jsonb, NULL, NULL, '"Habia comido" is the pluperfect (preterito pluscuamperfecto): habia + past participle, meaning "had eaten".'),
(NULL, 'mc', 'What is the difference between "saber" and "conocer"?', 'spanish', '9_10', 'medium', true, '[{"label":"Both mean to know equally","isCorrect":false},{"label":"Saber = to know facts/skills, conocer = to know people/places","isCorrect":true},{"label":"Saber is past, conocer is present","isCorrect":false},{"label":"Saber is informal, conocer is formal","isCorrect":false}]'::jsonb, NULL, NULL, '"Saber" is used for knowing facts, information, or how to do things. "Conocer" is for being acquainted with people or places.'),
(NULL, 'mc', 'What does the subjunctive mood express in "espero que vengas"?', 'spanish', '9_10', 'medium', true, '[{"label":"A command","isCorrect":false},{"label":"A certainty","isCorrect":false},{"label":"A wish or hope","isCorrect":true},{"label":"A past habit","isCorrect":false}]'::jsonb, NULL, NULL, '"Esperar que" triggers the subjunctive to express wishes. "Espero que vengas" = I hope you come.'),
(NULL, 'mc', 'Which pronoun is used for "you all" (plural you) in Latin America?', 'spanish', '9_10', 'medium', true, '[{"label":"vosotros","isCorrect":false},{"label":"ustedes","isCorrect":true},{"label":"ellos","isCorrect":false},{"label":"nosotros","isCorrect":false}]'::jsonb, NULL, NULL, 'In Latin America, "ustedes" is used for both formal and informal plural "you". "Vosotros" is used in Spain.'),
(NULL, 'mc', 'What does "a pesar de" mean?', 'spanish', '9_10', 'medium', true, '[{"label":"Because of","isCorrect":false},{"label":"In spite of","isCorrect":true},{"label":"In order to","isCorrect":false},{"label":"As soon as","isCorrect":false}]'::jsonb, NULL, NULL, '"A pesar de" means "in spite of" or "despite". "A pesar de la lluvia, fuimos" = In spite of the rain, we went.');

-- spanish | 9_10 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which sentence uses the imperfect subjunctive correctly?', 'spanish', '9_10', 'hard', true, '[{"label":"Queria que el viene","isCorrect":false},{"label":"Queria que el viniera","isCorrect":true},{"label":"Queria que el venia","isCorrect":false},{"label":"Queria que el vino","isCorrect":false}]'::jsonb, NULL, NULL, 'After past tense verbs of wanting/hoping, the imperfect subjunctive is required. "Venir" imperfect subj.: viniera/viniese.'),
(NULL, 'mc', 'What is the passive voice of "construyeron la iglesia" (they built the church)?', 'spanish', '9_10', 'hard', true, '[{"label":"La iglesia construyo","isCorrect":false},{"label":"La iglesia fue construida","isCorrect":true},{"label":"La iglesia era construida","isCorrect":false},{"label":"Se construyo la iglesia","isCorrect":false}]'::jsonb, NULL, NULL, 'True passive: "ser" + past participle agreeing with subject. "La iglesia fue construida" = the church was built.'),
(NULL, 'mc', 'What does "siempre y cuando" mean?', 'spanish', '9_10', 'hard', true, '[{"label":"From now on","isCorrect":false},{"label":"As long as / provided that","isCorrect":true},{"label":"Sooner or later","isCorrect":false},{"label":"Once in a while","isCorrect":false}]'::jsonb, NULL, NULL, '"Siempre y cuando" means "as long as" or "provided that" — followed by the subjunctive.'),
(NULL, 'mc', 'What rhetorical device is used in "sus lagrimas eran rios" (her tears were rivers)?', 'spanish', '9_10', 'hard', true, '[{"label":"Simil","isCorrect":false},{"label":"Personificacion","isCorrect":false},{"label":"Metafora","isCorrect":true},{"label":"Hiperbole","isCorrect":false}]'::jsonb, NULL, NULL, '"Sus lagrimas eran rios" is a metaphor (metafora) — directly equating tears with rivers without "like/as".'),
(NULL, 'mc', 'What does "haber" express in "hay mucha gente"?', 'spanish', '9_10', 'hard', true, '[{"label":"To owe","isCorrect":false},{"label":"Existence (there is/are)","isCorrect":true},{"label":"To go","isCorrect":false},{"label":"Auxiliary for past tense","isCorrect":false}]'::jsonb, NULL, NULL, '"Hay" (from haber) expresses existence: "there is/are". "Hay mucha gente" = there are many people.');

-- spanish | 11_12 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Who wrote "Don Quijote de la Mancha"?', 'spanish', '11_12', 'easy', true, '[{"label":"Federico Garcia Lorca","isCorrect":false},{"label":"Miguel de Cervantes","isCorrect":true},{"label":"Pablo Neruda","isCorrect":false},{"label":"Gabriel Garcia Marquez","isCorrect":false}]'::jsonb, NULL, NULL, '"Don Quijote" (1605) by Miguel de Cervantes is widely considered the first modern novel and a cornerstone of Spanish literature.'),
(NULL, 'mc', 'What literary movement is associated with "magical realism"?', 'spanish', '11_12', 'easy', true, '[{"label":"Romanticismo","isCorrect":false},{"label":"Vanguardismo","isCorrect":false},{"label":"Realismo magico","isCorrect":true},{"label":"Costumbrismo","isCorrect":false}]'::jsonb, NULL, NULL, 'Magical realism (realismo magico) blends realistic narrative with magical elements. Key authors: Garcia Marquez, Isabel Allende.'),
(NULL, 'mc', 'What does "no obstante" mean?', 'spanish', '11_12', 'easy', true, '[{"label":"On the other hand","isCorrect":false},{"label":"Nevertheless / notwithstanding","isCorrect":true},{"label":"For instance","isCorrect":false},{"label":"In summary","isCorrect":false}]'::jsonb, NULL, NULL, '"No obstante" means "nevertheless" or "notwithstanding" — a formal academic connective.'),
(NULL, 'mc', 'What is "el boom latinoamericano"?', 'spanish', '11_12', 'easy', true, '[{"label":"A popular dance movement","isCorrect":false},{"label":"A 1960s literary movement of Latin American novels gaining world fame","isCorrect":true},{"label":"A political revolution in the 1970s","isCorrect":false},{"label":"An economic boom in Latin America","isCorrect":false}]'::jsonb, NULL, NULL, 'El Boom was a 1960-70s surge of internationally acclaimed Latin American literature. Authors: Garcia Marquez, Cortazar, Fuentes, Vargas Llosa.'),
(NULL, 'mc', 'What does the phrase "a largo plazo" mean?', 'spanish', '11_12', 'easy', true, '[{"label":"At the same time","isCorrect":false},{"label":"In the short term","isCorrect":false},{"label":"In the long term","isCorrect":true},{"label":"As a result","isCorrect":false}]'::jsonb, NULL, NULL, '"A largo plazo" means "in the long term". "A corto plazo" = in the short term.');

-- spanish | 11_12 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which sentence correctly uses the conditional perfect?', 'spanish', '11_12', 'medium', true, '[{"label":"Si hubiera sabido, vendria","isCorrect":false},{"label":"Si hubiera sabido, habria venido","isCorrect":true},{"label":"Si sabria, habria venido","isCorrect":false},{"label":"Si supiera, venia","isCorrect":false}]'::jsonb, NULL, NULL, 'Past hypothetical: "si" + pluperfect subjunctive → conditional perfect. "Si hubiera sabido, habria venido" = If I had known, I would have come.'),
(NULL, 'mc', 'What does "asimismo" mean in formal Spanish?', 'spanish', '11_12', 'medium', true, '[{"label":"Therefore","isCorrect":false},{"label":"Likewise / also","isCorrect":true},{"label":"However","isCorrect":false},{"label":"In contrast","isCorrect":false}]'::jsonb, NULL, NULL, '"Asimismo" means "likewise" or "also" — a formal additive connective used in essays and reports.'),
(NULL, 'mc', 'What is the "voseo" form used in some Latin American countries?', 'spanish', '11_12', 'medium', true, '[{"label":"The plural you (ustedes)","isCorrect":false},{"label":"The informal singular you (vos) instead of tu","isCorrect":true},{"label":"A formal honorific","isCorrect":false},{"label":"The reflexive pronoun","isCorrect":false}]'::jsonb, NULL, NULL, '"Voseo" uses "vos" instead of "tu" for informal singular you, common in Argentina, Uruguay, and Central America.'),
(NULL, 'mc', 'What rhetorical device repeats a word at the start of successive clauses?', 'spanish', '11_12', 'medium', true, '[{"label":"Epistrofe","isCorrect":false},{"label":"Anafora","isCorrect":true},{"label":"Elipsis","isCorrect":false},{"label":"Sinecdoque","isCorrect":false}]'::jsonb, NULL, NULL, '"Anafora" (anaphora) repeats a word or phrase at the beginning of successive clauses or lines for emphasis.'),
(NULL, 'mc', 'What does "en detrimento de" mean?', 'spanish', '11_12', 'medium', true, '[{"label":"In favour of","isCorrect":false},{"label":"To the detriment of","isCorrect":true},{"label":"Instead of","isCorrect":false},{"label":"With the help of","isCorrect":false}]'::jsonb, NULL, NULL, '"En detrimento de" means "to the detriment of" — used in formal academic and argumentative writing.');

-- spanish | 11_12 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'Which grammatical construction is "al llegar a casa, me acosté"?', 'spanish', '11_12', 'hard', true, '[{"label":"Gerund clause","isCorrect":false},{"label":"Al + infinitive expressing simultaneous/immediate action","isCorrect":true},{"label":"Past subjunctive clause","isCorrect":false},{"label":"Conditional clause","isCorrect":false}]'::jsonb, NULL, NULL, '"Al" + infinitive expresses "upon doing" or "as soon as". "Al llegar" = upon arriving / as soon as I arrived.'),
(NULL, 'mc', 'What is the term for the narrative technique where the story is told by a character within it?', 'spanish', '11_12', 'hard', true, '[{"label":"Narrador omnisciente","isCorrect":false},{"label":"Narrador testigo","isCorrect":false},{"label":"Narrador protagonista","isCorrect":true},{"label":"Narrador extradiegetico","isCorrect":false}]'::jsonb, NULL, NULL, '"Narrador protagonista" (first-person narrator) tells the story as the main character. "Narrador omnisciente" knows all; "narrador testigo" is a witness narrator.'),
(NULL, 'mc', 'What does the expression "ponerse en el lugar de" mean?', 'spanish', '11_12', 'hard', true, '[{"label":"To stand in line","isCorrect":false},{"label":"To put oneself in someone else''s shoes","isCorrect":true},{"label":"To take someone''s place permanently","isCorrect":false},{"label":"To move to a new location","isCorrect":false}]'::jsonb, NULL, NULL, '"Ponerse en el lugar de alguien" means to empathise — to put yourself in someone else''s position.'),
(NULL, 'mc', 'Which feature distinguishes "ser" from "estar" in literary description?', 'spanish', '11_12', 'hard', true, '[{"label":"Ser is used for all verbs of motion","isCorrect":false},{"label":"Ser describes essential/inherent qualities; estar describes states or results","isCorrect":true},{"label":"Estar is only used in the present tense","isCorrect":false},{"label":"Ser requires a complement; estar does not","isCorrect":false}]'::jsonb, NULL, NULL, 'The ser/estar distinction is key in Spanish literature: "ser" captures identity or essence; "estar" captures conditions, mood, or change.'),
(NULL, 'mc', 'What is the name of Garcia Marquez''s most famous novel?', 'spanish', '11_12', 'hard', true, '[{"label":"El amor en los tiempos del colera","isCorrect":false},{"label":"La casa de los espiritus","isCorrect":false},{"label":"Cien anos de soledad","isCorrect":true},{"label":"Pedro Paramo","isCorrect":false}]'::jsonb, NULL, NULL, '"Cien anos de soledad" (One Hundred Years of Solitude, 1967) by Gabriel Garcia Marquez is the defining magical realist novel and won the Nobel Prize.');

-- ============================================================
-- MANDARIN
-- ============================================================

-- mandarin | 5_6 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does "ni hao" (ni3 hao3 / 你好) mean?', 'mandarin', '5_6', 'easy', true, '[{"label":"Goodbye","isCorrect":false},{"label":"Hello","isCorrect":true},{"label":"Thank you","isCorrect":false},{"label":"Please","isCorrect":false}]'::jsonb, NULL, NULL, '"Ni hao" (你好, ni3 hao3) is the standard Mandarin greeting meaning "hello".'),
(NULL, 'mc', 'What does "xie xie" (xie4 xie5 / 谢谢) mean?', 'mandarin', '5_6', 'easy', true, '[{"label":"Hello","isCorrect":false},{"label":"Goodbye","isCorrect":false},{"label":"Please","isCorrect":false},{"label":"Thank you","isCorrect":true}]'::jsonb, NULL, NULL, '"Xie xie" (谢谢, xie4 xie) means "thank you" in Mandarin.'),
(NULL, 'mc', 'How do you say "goodbye" in Mandarin?', 'mandarin', '5_6', 'easy', true, '[{"label":"ni hao","isCorrect":false},{"label":"zai jian (再见)","isCorrect":true},{"label":"xie xie","isCorrect":false},{"label":"dui bu qi","isCorrect":false}]'::jsonb, NULL, NULL, '"Zai jian" (再见, zai4 jian4) means "goodbye" — literally "see again".'),
(NULL, 'mc', 'What number is "san" (三) in Mandarin?', 'mandarin', '5_6', 'easy', true, '[{"label":"1","isCorrect":false},{"label":"2","isCorrect":false},{"label":"3","isCorrect":true},{"label":"4","isCorrect":false}]'::jsonb, NULL, NULL, '"San" (三, san1) means 3 in Mandarin. yi=1, er=2, san=3, si=4, wu=5.'),
(NULL, 'mc', 'What colour is "hong se" (红色) in Mandarin?', 'mandarin', '5_6', 'easy', true, '[{"label":"Blue","isCorrect":false},{"label":"Green","isCorrect":false},{"label":"Red","isCorrect":true},{"label":"Yellow","isCorrect":false}]'::jsonb, NULL, NULL, '"Hong se" (红色, hong2 se4) means red in Mandarin.');

-- mandarin | 5_6 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does "mama" (ma1 ma / 妈妈) mean in Mandarin?', 'mandarin', '5_6', 'medium', true, '[{"label":"Father","isCorrect":false},{"label":"Sister","isCorrect":false},{"label":"Mother","isCorrect":true},{"label":"Grandmother","isCorrect":false}]'::jsonb, NULL, NULL, '"Mama" (妈妈, ma1 ma) means "mum/mother" in Mandarin.'),
(NULL, 'mc', 'How do you say "I like" in Mandarin?', 'mandarin', '5_6', 'medium', true, '[{"label":"wo bu xi huan","isCorrect":false},{"label":"wo xi huan (我喜欢)","isCorrect":true},{"label":"wo yao","isCorrect":false},{"label":"wo shi","isCorrect":false}]'::jsonb, NULL, NULL, '"Wo xi huan" (我喜欢, wo3 xi3 huan1) means "I like". "Xi huan" = to like.'),
(NULL, 'mc', 'What does "dui bu qi" (dui4 bu qi3 / 对不起) mean?', 'mandarin', '5_6', 'medium', true, '[{"label":"You''re welcome","isCorrect":false},{"label":"Excuse me","isCorrect":false},{"label":"Sorry / I apologise","isCorrect":true},{"label":"Please","isCorrect":false}]'::jsonb, NULL, NULL, '"Dui bu qi" (对不起) means "I am sorry / I apologise" in Mandarin.'),
(NULL, 'mc', 'What does "shui" (shui3 / 水) mean in Mandarin?', 'mandarin', '5_6', 'medium', true, '[{"label":"Fire","isCorrect":false},{"label":"Earth","isCorrect":false},{"label":"Water","isCorrect":true},{"label":"Sky","isCorrect":false}]'::jsonb, NULL, NULL, '"Shui" (水, shui3) means "water" in Mandarin.'),
(NULL, 'mc', 'How many tones does Mandarin Chinese have?', 'mandarin', '5_6', 'medium', true, '[{"label":"2","isCorrect":false},{"label":"3","isCorrect":false},{"label":"4","isCorrect":true},{"label":"6","isCorrect":false}]'::jsonb, NULL, NULL, 'Mandarin has 4 tones plus a neutral tone: 1st (flat), 2nd (rising), 3rd (dipping), 4th (falling). Tones change meaning.');

-- mandarin | 5_6 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the character 大 (da4) mean?', 'mandarin', '5_6', 'hard', true, '[{"label":"Small","isCorrect":false},{"label":"Fast","isCorrect":false},{"label":"Big / large","isCorrect":true},{"label":"Good","isCorrect":false}]'::jsonb, NULL, NULL, '"Da" (大, da4) means "big" or "large" in Mandarin. The opposite is "xiao" (小) = small.'),
(NULL, 'mc', 'What does "wo yao" (wo3 yao4 / 我要) mean?', 'mandarin', '5_6', 'hard', true, '[{"label":"I have","isCorrect":false},{"label":"I am","isCorrect":false},{"label":"I want","isCorrect":true},{"label":"I go","isCorrect":false}]'::jsonb, NULL, NULL, '"Wo yao" (我要) means "I want" or "I need". "Yao" (要) can mean want, need, or going to.'),
(NULL, 'mc', 'Which of these is the Mandarin word for "eat"?', 'mandarin', '5_6', 'hard', true, '[{"label":"he (喝)","isCorrect":false},{"label":"chi (吃)","isCorrect":true},{"label":"zou (走)","isCorrect":false},{"label":"shuo (说)","isCorrect":false}]'::jsonb, NULL, NULL, '"Chi" (吃, chi1) means "to eat". "He" (喝) = to drink; "zou" (走) = to walk; "shuo" (说) = to speak.'),
(NULL, 'mc', 'What does "peng you" (peng2 you5 / 朋友) mean?', 'mandarin', '5_6', 'hard', true, '[{"label":"Family","isCorrect":false},{"label":"Teacher","isCorrect":false},{"label":"Friend","isCorrect":true},{"label":"Student","isCorrect":false}]'::jsonb, NULL, NULL, '"Peng you" (朋友) means "friend" in Mandarin.'),
(NULL, 'mc', 'What does the word "hao" (hao3 / 好) mean?', 'mandarin', '5_6', 'hard', true, '[{"label":"Bad","isCorrect":false},{"label":"Big","isCorrect":false},{"label":"Good / well","isCorrect":true},{"label":"Fast","isCorrect":false}]'::jsonb, NULL, NULL, '"Hao" (好, hao3) means "good" or "well". It appears in "ni hao" (你好) = hello, literally "you good".');

-- mandarin | 7_8 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What is the measure word for books in Mandarin?', 'mandarin', '7_8', 'easy', true, '[{"label":"ge (个)","isCorrect":false},{"label":"ben (本)","isCorrect":true},{"label":"zhang (张)","isCorrect":false},{"label":"tiao (条)","isCorrect":false}]'::jsonb, NULL, NULL, '"Ben" (本, ben3) is the measure word for books and bound volumes. "Ge" is a general measure word.'),
(NULL, 'mc', 'What does "jin tian" (jin1 tian1 / 今天) mean?', 'mandarin', '7_8', 'easy', true, '[{"label":"Yesterday","isCorrect":false},{"label":"Tomorrow","isCorrect":false},{"label":"Today","isCorrect":true},{"label":"This week","isCorrect":false}]'::jsonb, NULL, NULL, '"Jin tian" (今天) means "today". "Zuo tian" (昨天) = yesterday; "ming tian" (明天) = tomorrow.'),
(NULL, 'mc', 'How do you ask "How much does it cost?" in Mandarin?', 'mandarin', '7_8', 'easy', true, '[{"label":"Ni hao ma?","isCorrect":false},{"label":"Duo shao qian? (多少钱)","isCorrect":true},{"label":"Ni jiao shen me?","isCorrect":false},{"label":"Zai nar?","isCorrect":false}]'::jsonb, NULL, NULL, '"Duo shao qian?" (多少钱, duo1 shao3 qian2) means "How much money?" — used when asking prices.'),
(NULL, 'mc', 'What does "xue xiao" (xue2 xiao4 / 学校) mean?', 'mandarin', '7_8', 'easy', true, '[{"label":"Library","isCorrect":false},{"label":"Home","isCorrect":false},{"label":"School","isCorrect":true},{"label":"Hospital","isCorrect":false}]'::jsonb, NULL, NULL, '"Xue xiao" (学校) means "school" in Mandarin.'),
(NULL, 'mc', 'What does "tian qi" (tian1 qi4 / 天气) mean?', 'mandarin', '7_8', 'easy', true, '[{"label":"Time","isCorrect":false},{"label":"Weather","isCorrect":true},{"label":"Sky","isCorrect":false},{"label":"Season","isCorrect":false}]'::jsonb, NULL, NULL, '"Tian qi" (天气) means "weather" in Mandarin. "Tian qi zen me yang?" = What is the weather like?');

-- mandarin | 7_8 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the particle "ma" (吗) do at the end of a sentence?', 'mandarin', '7_8', 'medium', true, '[{"label":"Makes it negative","isCorrect":false},{"label":"Makes it a yes/no question","isCorrect":true},{"label":"Shows past tense","isCorrect":false},{"label":"Shows future tense","isCorrect":false}]'::jsonb, NULL, NULL, 'Adding "ma" (吗) at the end turns a statement into a yes/no question. "Ni chi fan ma?" = Have you eaten?'),
(NULL, 'mc', 'Which of the four tones is the falling tone (4th tone)?', 'mandarin', '7_8', 'medium', true, '[{"label":"ma1 (flat)","isCorrect":false},{"label":"ma2 (rising)","isCorrect":false},{"label":"ma3 (dipping)","isCorrect":false},{"label":"ma4 (falling)","isCorrect":true}]'::jsonb, NULL, NULL, 'The 4th tone falls sharply from high to low. ma4 (骂) means to scold. The tones: ma1=mother, ma2=hemp, ma3=horse, ma4=scold.'),
(NULL, 'mc', 'What does "ke yi" (ke3 yi3 / 可以) mean?', 'mandarin', '7_8', 'medium', true, '[{"label":"Must","isCorrect":false},{"label":"Cannot","isCorrect":false},{"label":"May / can (permission)","isCorrect":true},{"label":"Should","isCorrect":false}]'::jsonb, NULL, NULL, '"Ke yi" (可以) means "may" or "can" expressing permission. "Wo ke yi jin lai ma?" = May I come in?'),
(NULL, 'mc', 'What does "yi qi" (yi4 qi3 / 一起) mean?', 'mandarin', '7_8', 'medium', true, '[{"label":"One by one","isCorrect":false},{"label":"Together","isCorrect":true},{"label":"At once","isCorrect":false},{"label":"Alone","isCorrect":false}]'::jsonb, NULL, NULL, '"Yi qi" (一起) means "together". "Wo men yi qi qu ba!" = Let''s go together!'),
(NULL, 'mc', 'How do you say "I don''t understand" in Mandarin?', 'mandarin', '7_8', 'medium', true, '[{"label":"Wo bu yao","isCorrect":false},{"label":"Wo bu dong (我不懂)","isCorrect":true},{"label":"Wo bu neng","isCorrect":false},{"label":"Wo bu hao","isCorrect":false}]'::jsonb, NULL, NULL, '"Wo bu dong" (我不懂, wo3 bu4 dong3) = I don''t understand. "Bu" (不) is the negation particle.');

-- mandarin | 7_8 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the particle "le" (了) indicate at the end of a sentence?', 'mandarin', '7_8', 'hard', true, '[{"label":"A question","isCorrect":false},{"label":"A change of state or completed action","isCorrect":true},{"label":"Future intention","isCorrect":false},{"label":"Ongoing action","isCorrect":false}]'::jsonb, NULL, NULL, '"Le" (了) at sentence end signals a change of state or a new situation. "Ta zou le" (他走了) = He has left (change: he is now gone).'),
(NULL, 'mc', 'What is the difference between "hui" (会) and "neng" (能)?', 'mandarin', '7_8', 'hard', true, '[{"label":"Hui = physical ability, neng = learned skill","isCorrect":false},{"label":"Hui = learned skill/will, neng = physical/circumstantial ability","isCorrect":true},{"label":"They are interchangeable","isCorrect":false},{"label":"Hui is polite, neng is informal","isCorrect":false}]'::jsonb, NULL, NULL, '"Hui" (会) expresses learned ability or future likelihood. "Neng" (能) expresses physical or circumstantial capacity. "Wo hui you yong" = I can swim (learned); "Wo jintian bu neng qu" = I can''t go today (circumstance).'),
(NULL, 'mc', 'What does the measure word "zhang" (张) count?', 'mandarin', '7_8', 'hard', true, '[{"label":"Animals","isCorrect":false},{"label":"Flat things like paper and tables","isCorrect":true},{"label":"Long thin things","isCorrect":false},{"label":"Machines","isCorrect":false}]'::jsonb, NULL, NULL, '"Zhang" (张) is used for flat objects: paper (zhang zhi), tables (zhang zhuo zi), photos, tickets.'),
(NULL, 'mc', 'What does "you yi si" (you3 yi4 si4 / 有意思) mean?', 'mandarin', '7_8', 'hard', true, '[{"label":"Have an opinion","isCorrect":false},{"label":"Interesting","isCorrect":true},{"label":"Have a meaning","isCorrect":false},{"label":"On purpose","isCorrect":false}]'::jsonb, NULL, NULL, '"You yi si" (有意思) means "interesting". Literally "have meaning/interest". "Zhe ben shu hen you yi si" = This book is very interesting.'),
(NULL, 'mc', 'What is the radical of the character 妈 (ma, mother)?', 'mandarin', '7_8', 'hard', true, '[{"label":"Horse radical (马)","isCorrect":false},{"label":"Woman radical (女)","isCorrect":true},{"label":"Water radical (氵)","isCorrect":false},{"label":"Heart radical (心)","isCorrect":false}]'::jsonb, NULL, NULL, '"Ma" (妈) has the woman radical 女 on the left, indicating it relates to a female role. "Ma" (马) on the right gives the pronunciation.');

-- mandarin | 9_10 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the aspect particle "guo" (过) indicate?', 'mandarin', '9_10', 'easy', true, '[{"label":"Ongoing action","isCorrect":false},{"label":"Past experience","isCorrect":true},{"label":"Future plan","isCorrect":false},{"label":"Completed action","isCorrect":false}]'::jsonb, NULL, NULL, '"Guo" (过) marks past experience: "Wo qu guo Beijing" (我去过北京) = I have been to Beijing (at some point in life).'),
(NULL, 'mc', 'What does "bian hua" (bian4 hua4 / 变化) mean?', 'mandarin', '9_10', 'easy', true, '[{"label":"Weather","isCorrect":false},{"label":"Change / transformation","isCorrect":true},{"label":"Culture","isCorrect":false},{"label":"Development","isCorrect":false}]'::jsonb, NULL, NULL, '"Bian hua" (变化) means "change" or "transformation". "She hui bian hua" = social change.'),
(NULL, 'mc', 'What is the meaning of "huan jing" (huan2 jing4 / 环境)?', 'mandarin', '9_10', 'easy', true, '[{"label":"History","isCorrect":false},{"label":"Technology","isCorrect":false},{"label":"Environment","isCorrect":true},{"label":"Economy","isCorrect":false}]'::jsonb, NULL, NULL, '"Huan jing" (环境) means "environment" or "surroundings" in Mandarin.'),
(NULL, 'mc', 'What does "jiao liu" (jiao1 liu2 / 交流) mean?', 'mandarin', '9_10', 'easy', true, '[{"label":"Transport","isCorrect":false},{"label":"Exchange / communication","isCorrect":true},{"label":"Friendship","isCorrect":false},{"label":"Commerce","isCorrect":false}]'::jsonb, NULL, NULL, '"Jiao liu" (交流) means "exchange" or "communication". "Wen hua jiao liu" = cultural exchange.'),
(NULL, 'mc', 'What writing system does Mandarin use?', 'mandarin', '9_10', 'easy', true, '[{"label":"An alphabet","isCorrect":false},{"label":"Syllabic script","isCorrect":false},{"label":"Logographic characters (hanzi)","isCorrect":true},{"label":"A mixture of alphabet and syllabary","isCorrect":false}]'::jsonb, NULL, NULL, 'Mandarin uses hanzi (汉字) — logographic characters where each character represents a morpheme (meaning unit).');

-- mandarin | 9_10 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does "ba" (把) do as a grammatical particle?', 'mandarin', '9_10', 'medium', true, '[{"label":"Indicates a question","isCorrect":false},{"label":"Moves the object before the verb to show disposal","isCorrect":true},{"label":"Marks a completed action","isCorrect":false},{"label":"Introduces a subject","isCorrect":false}]'::jsonb, NULL, NULL, 'The "ba" (把) construction moves the object before the verb: "Ta ba shu na zou le" (他把书拿走了) = He took the book away.'),
(NULL, 'mc', 'What does "cheng yu" (cheng2 yu3 / 成语) refer to?', 'mandarin', '9_10', 'medium', true, '[{"label":"A type of food","isCorrect":false},{"label":"A four-character idiomatic expression","isCorrect":true},{"label":"A formal letter","isCorrect":false},{"label":"A children''s song","isCorrect":false}]'::jsonb, NULL, NULL, '"Cheng yu" (成语) are classical four-character idioms from Chinese literature and history. Each tells a story compactly.'),
(NULL, 'mc', 'What does the cheng yu "ma dao cheng gong" (马到成功) mean?', 'mandarin', '9_10', 'medium', true, '[{"label":"Work very hard","isCorrect":false},{"label":"Immediate success","isCorrect":true},{"label":"Learn from mistakes","isCorrect":false},{"label":"Brave the odds","isCorrect":false}]'::jsonb, NULL, NULL, '"Ma dao cheng gong" (马到成功) means "success comes as soon as the horse arrives" — wishing someone immediate success.'),
(NULL, 'mc', 'What does "bei dong ju" (bei4 dong4 ju4 / 被动句) mean?', 'mandarin', '9_10', 'medium', true, '[{"label":"Active sentence","isCorrect":false},{"label":"Passive sentence","isCorrect":true},{"label":"Negative sentence","isCorrect":false},{"label":"Question sentence","isCorrect":false}]'::jsonb, NULL, NULL, '"Bei dong ju" (被动句) means "passive sentence". "Bei" (被) is the passive marker: "Ta bei lao shi pi ping le" = He was criticised by the teacher.'),
(NULL, 'mc', 'What is the difference between Simplified and Traditional Chinese characters?', 'mandarin', '9_10', 'medium', true, '[{"label":"They are two different languages","isCorrect":false},{"label":"Simplified has fewer strokes, used mainly in mainland China; Traditional is used in Taiwan and Hong Kong","isCorrect":true},{"label":"Simplified is older","isCorrect":false},{"label":"Traditional is only used in calligraphy","isCorrect":false}]'::jsonb, NULL, NULL, 'Simplified characters were standardised in the 1950s in mainland China. Traditional characters are preserved in Taiwan, Hong Kong, and Macau.');

-- mandarin | 9_10 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the cheng yu "yi shi tong ren" (一视同仁) mean?', 'mandarin', '9_10', 'hard', true, '[{"label":"Work as a team","isCorrect":false},{"label":"Treat everyone equally","isCorrect":true},{"label":"See the world clearly","isCorrect":false},{"label":"One step at a time","isCorrect":false}]'::jsonb, NULL, NULL, '"Yi shi tong ren" (一视同仁) means "to treat all people equally" — literally "look at everyone with the same benevolence".'),
(NULL, 'mc', 'What does "yu fa" (yu3 fa3 / 语法) mean?', 'mandarin', '9_10', 'hard', true, '[{"label":"Vocabulary","isCorrect":false},{"label":"Pronunciation","isCorrect":false},{"label":"Grammar","isCorrect":true},{"label":"Writing","isCorrect":false}]'::jsonb, NULL, NULL, '"Yu fa" (语法) means "grammar". "Hanyu yu fa" = Chinese grammar.'),
(NULL, 'mc', 'What is the function of the complement "de liao" (得了) as in "pao de liao"?', 'mandarin', '9_10', 'hard', true, '[{"label":"Shows completion","isCorrect":false},{"label":"Shows potential ability (can manage to)","isCorrect":true},{"label":"Shows obligation","isCorrect":false},{"label":"Shows past experience","isCorrect":false}]'::jsonb, NULL, NULL, 'Potential complements use "de" (得) or "bu" (不) between verb and complement: "pao de liao" = can run (manage to); "pao bu liao" = cannot run.'),
(NULL, 'mc', 'The Tang dynasty is considered a golden age for which art form in China?', 'mandarin', '9_10', 'hard', true, '[{"label":"Calligraphy only","isCorrect":false},{"label":"Classical poetry (shi)","isCorrect":true},{"label":"Opera","isCorrect":false},{"label":"Landscape painting","isCorrect":false}]'::jsonb, NULL, NULL, 'The Tang dynasty (618-907) is celebrated as the golden age of Chinese poetry. Poets like Li Bai (李白) and Du Fu (杜甫) are iconic.'),
(NULL, 'mc', 'What does "yin wei...suo yi" (因为...所以) express?', 'mandarin', '9_10', 'hard', true, '[{"label":"Contrast: although...therefore","isCorrect":false},{"label":"Cause and effect: because...therefore","isCorrect":true},{"label":"Condition: if...then","isCorrect":false},{"label":"Concession: even if...still","isCorrect":false}]'::jsonb, NULL, NULL, '"Yin wei...suo yi" (因为...所以) expresses cause and effect: "because...therefore". Both parts are typically stated, unlike in English.');

-- mandarin | 11_12 | easy
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the cheng yu "hu tou she wei" (虎头蛇尾) mean?', 'mandarin', '11_12', 'easy', true, '[{"label":"Brave and fierce","isCorrect":false},{"label":"A strong start but weak finish","isCorrect":true},{"label":"Cunning like a fox","isCorrect":false},{"label":"Work that never ends","isCorrect":false}]'::jsonb, NULL, NULL, '"Hu tou she wei" (虎头蛇尾) literally means "tiger head, snake tail" — describing something that starts impressively but fizzles out.'),
(NULL, 'mc', 'What is "pu tong hua" (pu1 tong1 hua4 / 普通话)?', 'mandarin', '11_12', 'easy', true, '[{"label":"A Chinese dialect","isCorrect":false},{"label":"Standard Mandarin Chinese","isCorrect":true},{"label":"Classical Chinese","isCorrect":false},{"label":"Cantonese","isCorrect":false}]'::jsonb, NULL, NULL, '"Pu tong hua" (普通话) means "standard speech" — the official standardised form of Mandarin Chinese used in mainland China.'),
(NULL, 'mc', 'What does "ke chi" (ke3 chi3 / 可耻) mean?', 'mandarin', '11_12', 'easy', true, '[{"label":"Admirable","isCorrect":false},{"label":"Shameful / disgraceful","isCorrect":true},{"label":"Brave","isCorrect":false},{"label":"Generous","isCorrect":false}]'::jsonb, NULL, NULL, '"Ke chi" (可耻) means "shameful" or "disgraceful". "Chi" (耻) = shame; "ke" (可) = can/worthy of.'),
(NULL, 'mc', 'Who is the legendary philosopher associated with "ren" (仁, benevolence) in Chinese thought?', 'mandarin', '11_12', 'easy', true, '[{"label":"Laozi","isCorrect":false},{"label":"Confucius (Kong Zi)","isCorrect":true},{"label":"Mencius","isCorrect":false},{"label":"Zhuangzi","isCorrect":false}]'::jsonb, NULL, NULL, 'Confucius (孔子, Kong Zi) placed "ren" (仁, benevolence/humaneness) at the centre of his ethical philosophy.'),
(NULL, 'mc', 'What does "fu za" (fu4 za2 / 复杂) mean?', 'mandarin', '11_12', 'easy', true, '[{"label":"Simple","isCorrect":false},{"label":"Complex / complicated","isCorrect":true},{"label":"Ordinary","isCorrect":false},{"label":"Strange","isCorrect":false}]'::jsonb, NULL, NULL, '"Fu za" (复杂) means "complex" or "complicated". The opposite is "jian dan" (简单) = simple.');

-- mandarin | 11_12 | medium
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the cheng yu "ren shan ren hai" (人山人海) describe?', 'mandarin', '11_12', 'medium', true, '[{"label":"A beautiful landscape","isCorrect":false},{"label":"A massive crowd","isCorrect":true},{"label":"Teamwork","isCorrect":false},{"label":"Confusion","isCorrect":false}]'::jsonb, NULL, NULL, '"Ren shan ren hai" (人山人海) literally means "people mountains people seas" — describing an enormous crowd.'),
(NULL, 'mc', 'What is the classical Chinese concept of "he" (和)?', 'mandarin', '11_12', 'medium', true, '[{"label":"Power and authority","isCorrect":false},{"label":"Harmony and balance","isCorrect":true},{"label":"Individual achievement","isCorrect":false},{"label":"Strict rules","isCorrect":false}]'::jsonb, NULL, NULL, '"He" (和) represents harmony and balance — a central value in Chinese philosophy, politics, and aesthetics.'),
(NULL, 'mc', 'In formal Mandarin writing, what does "ci wai" (此外) mean?', 'mandarin', '11_12', 'medium', true, '[{"label":"Therefore","isCorrect":false},{"label":"However","isCorrect":false},{"label":"In addition / besides","isCorrect":true},{"label":"In conclusion","isCorrect":false}]'::jsonb, NULL, NULL, '"Ci wai" (此外) is a formal connective meaning "in addition" or "besides" — used in essays and reports.'),
(NULL, 'mc', 'What does the structure "sui ran...dan shi" (虽然...但是) express?', 'mandarin', '11_12', 'medium', true, '[{"label":"Cause and effect","isCorrect":false},{"label":"Concession: although...but","isCorrect":true},{"label":"Condition: if...then","isCorrect":false},{"label":"Sequential events","isCorrect":false}]'::jsonb, NULL, NULL, '"Sui ran...dan shi" (虽然...但是) expresses concession: "although...but/however". Both parts are needed in Chinese.'),
(NULL, 'mc', 'What is the literary device called "bi xing" (比兴) in classical Chinese poetry?', 'mandarin', '11_12', 'medium', true, '[{"label":"Repetition for emphasis","isCorrect":false},{"label":"Using natural imagery to evoke emotion or introduce a theme","isCorrect":true},{"label":"Strict tonal parallelism","isCorrect":false},{"label":"Allusion to history","isCorrect":false}]'::jsonb, NULL, NULL, '"Bi xing" (比兴) is a classical poetic technique: using comparisons (bi) and nature imagery (xing) to convey feelings indirectly.');

-- mandarin | 11_12 | hard
INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES
(NULL, 'mc', 'What does the cheng yu "wu mao dun" (无矛盾) — meaning no contradiction — contrast with in Mao Zedong''s philosophical essay?', 'mandarin', '11_12', 'hard', true, '[{"label":"He argued society has no contradictions","isCorrect":false},{"label":"He argued contradictions are universal and drive development","isCorrect":true},{"label":"He argued only economic contradictions matter","isCorrect":false},{"label":"He argued contradictions resolve without struggle","isCorrect":false}]'::jsonb, NULL, NULL, 'In "On Contradiction" (矛盾论), Mao argued contradictions are universal and the engine of change — adapting Marxist dialectics to Chinese context.'),
(NULL, 'mc', 'What does "ju ju zi jue" (据句自决) illustrate in written Chinese?', 'mandarin', '11_12', 'hard', true, '[{"label":"Each sentence must end with a question mark","isCorrect":false},{"label":"Topic-comment sentence structure where topic is stated first","isCorrect":true},{"label":"Verbs always precede subjects","isCorrect":false},{"label":"All adjectives follow nouns","isCorrect":false}]'::jsonb, NULL, NULL, 'Chinese often uses a topic-comment structure: the topic is fronted, then a comment is made about it. E.g. "Na jian shi, wo bu zhi dao" = That matter, I don''t know.'),
(NULL, 'mc', 'Which dynasty produced the "Shi Ji" (史记), the first comprehensive Chinese history?', 'mandarin', '11_12', 'hard', true, '[{"label":"Tang dynasty","isCorrect":false},{"label":"Han dynasty","isCorrect":true},{"label":"Ming dynasty","isCorrect":false},{"label":"Zhou dynasty","isCorrect":false}]'::jsonb, NULL, NULL, '"Shi Ji" (史记) was written by Sima Qian (司马迁) during the Han dynasty. It covers Chinese history from the Yellow Emperor to Emperor Wu.'),
(NULL, 'mc', 'What rhetorical technique uses repetition of a word at the end of successive phrases?', 'mandarin', '11_12', 'hard', true, '[{"label":"Pai bi (parallel structure)","isCorrect":false},{"label":"Lian zhu (anadiplosis / chain repetition)","isCorrect":false},{"label":"Dui ou (antithetical couplet)","isCorrect":false},{"label":"Di tui (epistrophe — end repetition)","isCorrect":true}]'::jsonb, NULL, NULL, '"Di tui" or epistrophe repeats a word at the end of successive clauses for rhythmic and emphatic effect — common in classical Chinese rhetoric.'),
(NULL, 'mc', 'What does the concept "mian zi" (面子) mean in Chinese culture?', 'mandarin', '11_12', 'hard', true, '[{"label":"A traditional dish","isCorrect":false},{"label":"Social face / reputation and dignity in others'' eyes","isCorrect":true},{"label":"Formal written language","isCorrect":false},{"label":"Ancestral respect","isCorrect":false}]'::jsonb, NULL, NULL, '"Mian zi" (面子, face) is a key cultural concept representing social standing, reputation, and dignity. Losing face (diu mian zi) is deeply significant.');
