INSERT INTO public.tasks (
  id, family_id, kid_ids, name, category, icon,
  schedule_type, days_of_week, time_block,
  points, family_points_contribution,
  requires_timer, requires_completion,
  active, is_builtin, rule, kid_can_add,
  cash_value_cents, description,
  created_at
) VALUES
  (gen_random_uuid(), NULL, NULL, 'Watch a TED Talk', 'activity', '🎤',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   30, 0, false, true, true, true, 'flexible', true,
   300, 'Watch any TED Talk (ted.com or YouTube). Report: the title, 2 things you learned, and 1 thing you want to try.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Listen to a Podcast', 'activity', '🎧',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   25, 0, false, true, true, true, 'flexible', true,
   250, 'Listen to a full podcast episode on any topic. Report: the topic, 2 takeaways, and 1 question it made you think about.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Read a Non-Fiction Chapter', 'activity', '📖',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   20, 0, false, true, true, true, 'flexible', true,
   200, 'Read one chapter from any non-fiction book. Write a short summary and one thing that surprised you.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Teach It Back', 'activity', '🧑‍🏫',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   30, 0, false, true, true, true, 'flexible', true,
   300, 'Learn something new about any topic. Then teach it to a family member for at least 5 minutes. Parent rates your explanation.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Budget a Dream Purchase', 'activity', '💸',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   40, 0, false, true, true, true, 'flexible', true,
   400, 'Pick something you want that costs over $50. Research the price, figure out how long it''ll take to save for it, and present your plan.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Subscription Audit', 'activity', '📋',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   50, 0, false, true, true, true, 'flexible', true,
   500, 'Find 3 subscriptions the family pays for. Write down how much each costs per year. Suggest one that could be cancelled and why.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Compound Interest Explorer', 'activity', '📈',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   30, 0, false, true, true, true, 'flexible', true,
   300, 'Use an online calculator: if you save $5 a week for 10 years at 5% interest, how much do you end up with? What about $10/week? Report your findings and what surprised you.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Research a Successful Person', 'activity', '🌟',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   30, 0, false, true, true, true, 'flexible', true,
   300, 'Pick someone successful. Research their story and share 3 decisions that helped them succeed.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Learn a New Skill (Tutorial)', 'activity', '🛠️',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   25, 0, false, true, true, true, 'flexible', true,
   250, 'Watch a how-to video and learn a new practical skill. Describe what you learned and show or demonstrate it.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Read & Summarise a News Article', 'activity', '📰',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   15, 0, false, true, true, true, 'flexible', true,
   150, 'Read a full news article (not social media). Summarise what happened, who it affects, and give your opinion.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Neighbourhood Business Idea', 'activity', '💡',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   40, 0, false, true, true, true, 'flexible', true,
   400, 'Come up with a business idea for your street or neighbourhood. Who''s the customer, what problem does it solve, and how much would you charge?',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Grocery Savings Hunt', 'activity', '🛒',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   35, 0, false, true, true, true, 'flexible', true,
   350, 'Look at the family grocery list. Find 3 items where you could save money (generic brand, different store, or coupon). Report how much you could save in total.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Career Explorer', 'activity', '👩‍💼',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   25, 0, false, true, true, true, 'flexible', true,
   250, 'Pick a job you find interesting. Research: what skills it needs, what it typically pays, and how you''d get there.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Watch a Documentary', 'activity', '🎬',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   35, 0, false, true, true, true, 'flexible', true,
   350, 'Watch any documentary (nature, history, science, technology). Report 3 things you learned and one question you now have.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Compare Before You Buy', 'activity', '🔍',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   30, 0, false, true, true, true, 'flexible', true,
   300, 'For any upcoming family purchase over $30, research at least 3 options or prices. Present your recommendation with reasons.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Interview an Adult', 'activity', '🎙️',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   40, 0, false, true, true, true, 'flexible', true,
   400, 'Interview a parent, grandparent, or family friend. Ask: what do you do for work, what''s the best money decision you ever made, and one piece of advice for kids. Report back.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Savings Goal Map', 'activity', '🗺️',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   35, 0, false, true, true, true, 'flexible', true,
   350, 'Set a savings goal for something you want to buy. Write out: how much it costs, how long it''ll take, and which gigs you''ll do to earn it.',
   now()),

  (gen_random_uuid(), NULL, NULL, '"How It''s Made" Research', 'activity', '🏭',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   25, 0, false, true, true, true, 'flexible', true,
   250, 'Pick any everyday product (phone, cereal, shoes). Research how it''s made and where the materials come from. Share 3 facts you found interesting.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Generosity Research', 'activity', '🤝',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   25, 0, false, true, true, true, 'flexible', true,
   250, 'Find 3 local or online charities or volunteer opportunities. Pick one you''d want to support and explain why giving matters to you.',
   now()),

  (gen_random_uuid(), NULL, NULL, 'Book Chapter (Rich Dad Poor Dad or similar)', 'activity', '💰',
   'daily', '{1,2,3,4,5,6,7}', 'anytime',
   30, 0, false, true, true, true, 'flexible', true,
   300, 'Read one chapter from an approved money/success book. Write a 5-sentence summary and one thing you want to apply in your life.',
   now())
;
