-- Seed quiz_questions2 with 180 built-in questions across 3 themes
-- sports (60) · music (60) · fun_facts (60)

INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES

-- ============================================================
-- THEME: sports
-- ============================================================

-- age_band: 5_6 | difficulty: easy
(NULL, 'mc', 'How many players are on a soccer team on the field at one time?', 'sports', '5_6', 'easy', true, '[{"label":"9","isCorrect":false},{"label":"11","isCorrect":true},{"label":"7","isCorrect":false},{"label":"13","isCorrect":false}]'::jsonb, NULL, NULL, 'A soccer team has 11 players on the field, including the goalkeeper.'),
(NULL, 'mc', 'Which sport uses a bat and a ball and you run around bases?', 'sports', '5_6', 'easy', true, '[{"label":"Tennis","isCorrect":false},{"label":"Golf","isCorrect":false},{"label":"Baseball","isCorrect":true},{"label":"Hockey","isCorrect":false}]'::jsonb, NULL, NULL, 'Baseball players hit a ball with a bat and run around four bases to score a run.'),
(NULL, 'mc', 'What colour is the ball used in basketball?', 'sports', '5_6', 'easy', true, '[{"label":"White","isCorrect":false},{"label":"Orange","isCorrect":true},{"label":"Blue","isCorrect":false},{"label":"Green","isCorrect":false}]'::jsonb, NULL, NULL, 'A basketball is orange, which makes it easy to see against the court.'),
(NULL, 'mc', 'In which sport do you swim in a pool and try to be the fastest?', 'sports', '5_6', 'easy', true, '[{"label":"Diving","isCorrect":false},{"label":"Water polo","isCorrect":false},{"label":"Swimming","isCorrect":true},{"label":"Surfing","isCorrect":false}]'::jsonb, NULL, NULL, 'Swimming races take place in pools and swimmers compete to touch the wall first.'),
(NULL, 'mc', 'What do you kick into to score a goal in soccer?', 'sports', '5_6', 'easy', true, '[{"label":"A basket","isCorrect":false},{"label":"A net","isCorrect":true},{"label":"A hole","isCorrect":false},{"label":"A wall","isCorrect":false}]'::jsonb, NULL, NULL, 'In soccer, players kick the ball into the opposing team''s net to score a goal.'),

-- age_band: 5_6 | difficulty: medium
(NULL, 'mc', 'How many points do you score for a basketball shot from inside the three-point line?', 'sports', '5_6', 'medium', true, '[{"label":"1","isCorrect":false},{"label":"2","isCorrect":true},{"label":"3","isCorrect":false},{"label":"4","isCorrect":false}]'::jsonb, NULL, NULL, 'A regular basket scored from inside the three-point line is worth 2 points.'),
(NULL, 'mc', 'Which animal is the mascot shape on many Australian sporting teams'' logos?', 'sports', '5_6', 'medium', true, '[{"label":"A lion","isCorrect":false},{"label":"A kangaroo","isCorrect":true},{"label":"A tiger","isCorrect":false},{"label":"An eagle","isCorrect":false}]'::jsonb, NULL, NULL, 'The kangaroo is a native Australian animal and a common symbol used by Australian sports teams.'),
(NULL, 'mc', 'In tennis, what is the name of the area you hit the ball over?', 'sports', '5_6', 'medium', true, '[{"label":"The wall","isCorrect":false},{"label":"The fence","isCorrect":false},{"label":"The net","isCorrect":true},{"label":"The line","isCorrect":false}]'::jsonb, NULL, NULL, 'In tennis, players must hit the ball over the net and into the opponent''s side of the court.'),
(NULL, 'mc', 'How many holes are there in a standard game of mini golf?', 'sports', '5_6', 'medium', true, '[{"label":"9","isCorrect":false},{"label":"12","isCorrect":false},{"label":"18","isCorrect":true},{"label":"20","isCorrect":false}]'::jsonb, NULL, NULL, 'A standard round of mini golf has 18 holes, just like regular golf.'),
(NULL, 'mc', 'What sport is played at Wimbledon?', 'sports', '5_6', 'medium', true, '[{"label":"Cricket","isCorrect":false},{"label":"Tennis","isCorrect":true},{"label":"Football","isCorrect":false},{"label":"Golf","isCorrect":false}]'::jsonb, NULL, NULL, 'Wimbledon is one of the most famous tennis tournaments in the world, held in London, England.'),

-- age_band: 5_6 | difficulty: hard
(NULL, 'mc', 'What is the name of the big trophy given to the winner of the soccer World Cup?', 'sports', '5_6', 'hard', true, '[{"label":"The Golden Boot","isCorrect":false},{"label":"The World Cup Trophy","isCorrect":true},{"label":"The Champion Shield","isCorrect":false},{"label":"The FIFA Cup","isCorrect":false}]'::jsonb, NULL, NULL, 'The FIFA World Cup Trophy is awarded to the winning nation every four years.'),
(NULL, 'mc', 'How many rings are on the Olympic flag?', 'sports', '5_6', 'hard', true, '[{"label":"4","isCorrect":false},{"label":"5","isCorrect":true},{"label":"6","isCorrect":false},{"label":"7","isCorrect":false}]'::jsonb, NULL, NULL, 'The Olympic flag has five coloured rings representing the five continents of the world.'),
(NULL, 'mc', 'In which country were the first modern Olympic Games held?', 'sports', '5_6', 'hard', true, '[{"label":"Italy","isCorrect":false},{"label":"France","isCorrect":false},{"label":"Greece","isCorrect":true},{"label":"USA","isCorrect":false}]'::jsonb, NULL, NULL, 'The first modern Olympic Games were held in Athens, Greece in 1896.'),
(NULL, 'mc', 'What sport does Serena Williams play?', 'sports', '5_6', 'hard', true, '[{"label":"Golf","isCorrect":false},{"label":"Swimming","isCorrect":false},{"label":"Tennis","isCorrect":true},{"label":"Gymnastics","isCorrect":false}]'::jsonb, NULL, NULL, 'Serena Williams is one of the greatest tennis players of all time, winning 23 Grand Slam titles.'),
(NULL, 'mc', 'What is it called when a bowler gets three strikes in a row in bowling?', 'sports', '5_6', 'hard', true, '[{"label":"A hat trick","isCorrect":false},{"label":"A triple","isCorrect":false},{"label":"A turkey","isCorrect":true},{"label":"A jackpot","isCorrect":false}]'::jsonb, NULL, NULL, 'Three strikes in a row in bowling is called a "turkey" — a fun tradition in the sport!'),

-- age_band: 7_8 | difficulty: easy
(NULL, 'mc', 'How many players are on each side in a volleyball game?', 'sports', '7_8', 'easy', true, '[{"label":"5","isCorrect":false},{"label":"6","isCorrect":true},{"label":"7","isCorrect":false},{"label":"8","isCorrect":false}]'::jsonb, NULL, NULL, 'Each volleyball team has 6 players on the court at a time.'),
(NULL, 'mc', 'In which sport would you do a "slam dunk"?', 'sports', '7_8', 'easy', true, '[{"label":"Baseball","isCorrect":false},{"label":"Soccer","isCorrect":false},{"label":"Basketball","isCorrect":true},{"label":"Rugby","isCorrect":false}]'::jsonb, NULL, NULL, 'A slam dunk is when a basketball player jumps and forcefully pushes the ball down through the hoop.'),
(NULL, 'mc', 'What country invented the sport of cricket?', 'sports', '7_8', 'easy', true, '[{"label":"Australia","isCorrect":false},{"label":"India","isCorrect":false},{"label":"England","isCorrect":true},{"label":"South Africa","isCorrect":false}]'::jsonb, NULL, NULL, 'Cricket was invented in England and has been played there since at least the 16th century.'),
(NULL, 'mc', 'In the AFL, how many points is a goal worth?', 'sports', '7_8', 'easy', true, '[{"label":"3","isCorrect":false},{"label":"4","isCorrect":false},{"label":"6","isCorrect":true},{"label":"9","isCorrect":false}]'::jsonb, NULL, NULL, 'In Australian Rules Football (AFL), a goal scored through the two tall posts is worth 6 points.'),
(NULL, 'mc', 'Which sport uses a puck instead of a ball?', 'sports', '7_8', 'easy', true, '[{"label":"Lacrosse","isCorrect":false},{"label":"Ice hockey","isCorrect":true},{"label":"Field hockey","isCorrect":false},{"label":"Polo","isCorrect":false}]'::jsonb, NULL, NULL, 'Ice hockey is played with a hard rubber disc called a puck, instead of a ball.'),

-- age_band: 7_8 | difficulty: medium
(NULL, 'mc', 'Who is famous for winning seven Tour de France cycling races?', 'sports', '7_8', 'medium', true, '[{"label":"Michael Schumacher","isCorrect":false},{"label":"Lance Armstrong","isCorrect":true},{"label":"Usain Bolt","isCorrect":false},{"label":"Roger Federer","isCorrect":false}]'::jsonb, NULL, NULL, 'Lance Armstrong won seven consecutive Tour de France titles from 1999 to 2005 (later stripped due to doping).'),
(NULL, 'mc', 'How long is a standard Olympic swimming pool?', 'sports', '7_8', 'medium', true, '[{"label":"25 metres","isCorrect":false},{"label":"50 metres","isCorrect":true},{"label":"75 metres","isCorrect":false},{"label":"100 metres","isCorrect":false}]'::jsonb, NULL, NULL, 'An Olympic swimming pool is 50 metres long. Shorter 25-metre pools are used for other competitions.'),
(NULL, 'mc', 'In cricket, what is it called when a batsman scores 100 runs in one innings?', 'sports', '7_8', 'medium', true, '[{"label":"A double","isCorrect":false},{"label":"A ton","isCorrect":false},{"label":"A century","isCorrect":true},{"label":"A perfect innings","isCorrect":false}]'::jsonb, NULL, NULL, 'Scoring 100 runs in one innings is called a "century" — one of the great achievements in cricket.'),
(NULL, 'mc', 'What sport does LeBron James play?', 'sports', '7_8', 'medium', true, '[{"label":"American Football","isCorrect":false},{"label":"Baseball","isCorrect":false},{"label":"Basketball","isCorrect":true},{"label":"Soccer","isCorrect":false}]'::jsonb, NULL, NULL, 'LeBron James is one of the greatest NBA basketball players of all time, playing for teams including the Lakers.'),
(NULL, 'mc', 'How many events make up the Olympic decathlon?', 'sports', '7_8', 'medium', true, '[{"label":"7","isCorrect":false},{"label":"8","isCorrect":false},{"label":"10","isCorrect":true},{"label":"12","isCorrect":false}]'::jsonb, NULL, NULL, 'The decathlon consists of 10 track and field events spread over two days.'),

-- age_band: 7_8 | difficulty: hard
(NULL, 'mc', 'Which country has won the most FIFA World Cup titles?', 'sports', '7_8', 'hard', true, '[{"label":"Germany","isCorrect":false},{"label":"Argentina","isCorrect":false},{"label":"Brazil","isCorrect":true},{"label":"Italy","isCorrect":false}]'::jsonb, NULL, NULL, 'Brazil has won the FIFA World Cup five times — more than any other nation.'),
(NULL, 'mc', 'What is the highest possible break in snooker?', 'sports', '7_8', 'hard', true, '[{"label":"100","isCorrect":false},{"label":"147","isCorrect":true},{"label":"155","isCorrect":false},{"label":"180","isCorrect":false}]'::jsonb, NULL, NULL, 'A maximum break of 147 in snooker involves potting all 15 reds, each followed by the black, then all colours.'),
(NULL, 'mc', 'In which year did Australia host the Summer Olympics?', 'sports', '7_8', 'hard', true, '[{"label":"1996","isCorrect":false},{"label":"2000","isCorrect":true},{"label":"2004","isCorrect":false},{"label":"2008","isCorrect":false}]'::jsonb, NULL, NULL, 'Australia hosted the Summer Olympics in Sydney in the year 2000.'),
(NULL, 'mc', 'What is the name of the fastest serve ever recorded in tennis?', 'sports', '7_8', 'hard', true, '[{"label":"The Cannonball","isCorrect":false},{"label":"The Thunderbolt","isCorrect":false},{"label":"The Ace","isCorrect":true},{"label":"The Rocket","isCorrect":false}]'::jsonb, NULL, NULL, 'An ace is a serve that the opponent cannot touch. The fastest ever recorded was over 263 km/h by Sam Groth.'),
(NULL, 'mc', 'In the Tour de France, what colour jersey does the overall leader wear?', 'sports', '7_8', 'hard', true, '[{"label":"Red","isCorrect":false},{"label":"White","isCorrect":false},{"label":"Yellow","isCorrect":true},{"label":"Blue","isCorrect":false}]'::jsonb, NULL, NULL, 'The overall leader in the Tour de France wears the famous yellow jersey, known in French as the "maillot jaune."'),

-- age_band: 9_10 | difficulty: easy
(NULL, 'mc', 'How many metres is the 100-metre sprint?', 'sports', '9_10', 'easy', true, '[{"label":"50","isCorrect":false},{"label":"100","isCorrect":true},{"label":"200","isCorrect":false},{"label":"400","isCorrect":false}]'::jsonb, NULL, NULL, 'The 100-metre sprint is one of the most famous athletics events and measures exactly 100 metres.'),
(NULL, 'mc', 'Which sport is played at the US Masters golf tournament?', 'sports', '9_10', 'easy', true, '[{"label":"Tennis","isCorrect":false},{"label":"Golf","isCorrect":true},{"label":"Cricket","isCorrect":false},{"label":"Baseball","isCorrect":false}]'::jsonb, NULL, NULL, 'The Masters is one of golf''s four major championships, held at Augusta National in Georgia, USA.'),
(NULL, 'mc', 'What are the colours of the five Olympic rings?', 'sports', '9_10', 'easy', true, '[{"label":"Red, blue, green, yellow, purple","isCorrect":false},{"label":"Blue, yellow, black, green, red","isCorrect":true},{"label":"Blue, red, white, green, orange","isCorrect":false},{"label":"Gold, silver, bronze, blue, red","isCorrect":false}]'::jsonb, NULL, NULL, 'The five Olympic rings are blue, yellow, black, green, and red — together with the white background, these colours appear on every national flag.'),
(NULL, 'mc', 'In rugby union, how many points is a try worth?', 'sports', '9_10', 'easy', true, '[{"label":"3","isCorrect":false},{"label":"4","isCorrect":false},{"label":"5","isCorrect":true},{"label":"6","isCorrect":false}]'::jsonb, NULL, NULL, 'A try in rugby union is worth 5 points. The scoring team then gets a conversion kick worth 2 more points.'),
(NULL, 'mc', 'Which country does tennis star Rafael Nadal come from?', 'sports', '9_10', 'easy', true, '[{"label":"Italy","isCorrect":false},{"label":"Portugal","isCorrect":false},{"label":"Spain","isCorrect":true},{"label":"France","isCorrect":false}]'::jsonb, NULL, NULL, 'Rafael Nadal is from Spain and is especially famous for his dominance on clay courts, winning the French Open 14 times.'),

-- age_band: 9_10 | difficulty: medium
(NULL, 'mc', 'What is the world record for the 100-metre sprint, set by Usain Bolt?', 'sports', '9_10', 'medium', true, '[{"label":"9.38 seconds","isCorrect":false},{"label":"9.58 seconds","isCorrect":true},{"label":"9.72 seconds","isCorrect":false},{"label":"9.81 seconds","isCorrect":false}]'::jsonb, NULL, NULL, 'Usain Bolt set the 100m world record of 9.58 seconds at the 2009 World Championships in Berlin.'),
(NULL, 'mc', 'How many Grand Slam tennis tournaments are there in a year?', 'sports', '9_10', 'medium', true, '[{"label":"2","isCorrect":false},{"label":"3","isCorrect":false},{"label":"4","isCorrect":true},{"label":"5","isCorrect":false}]'::jsonb, NULL, NULL, 'There are four Grand Slams: the Australian Open, French Open, Wimbledon, and the US Open.'),
(NULL, 'mc', 'What is a "hat-trick" in football (soccer)?', 'sports', '9_10', 'medium', true, '[{"label":"Three saves by the goalkeeper","isCorrect":false},{"label":"Three goals by the same player in one game","isCorrect":true},{"label":"Three yellow cards","isCorrect":false},{"label":"Scoring in three consecutive matches","isCorrect":false}]'::jsonb, NULL, NULL, 'A hat-trick is when one player scores three goals in a single match — a great individual achievement.'),
(NULL, 'mc', 'In which sport would you perform a "butterfly stroke"?', 'sports', '9_10', 'medium', true, '[{"label":"Gymnastics","isCorrect":false},{"label":"Diving","isCorrect":false},{"label":"Swimming","isCorrect":true},{"label":"Water polo","isCorrect":false}]'::jsonb, NULL, NULL, 'The butterfly stroke is one of four competitive swimming strokes, known for being the most physically demanding.'),
(NULL, 'mc', 'Which cricketer holds the record for the most Test centuries?', 'sports', '9_10', 'medium', true, '[{"label":"Brian Lara","isCorrect":false},{"label":"Ricky Ponting","isCorrect":false},{"label":"Sachin Tendulkar","isCorrect":true},{"label":"Don Bradman","isCorrect":false}]'::jsonb, NULL, NULL, 'Sachin Tendulkar of India scored 51 centuries in Test cricket — more than any other player in history.'),

-- age_band: 9_10 | difficulty: hard
(NULL, 'mc', 'What is the furthest a human has ever thrown a javelin (men''s world record, approximately)?', 'sports', '9_10', 'hard', true, '[{"label":"68 metres","isCorrect":false},{"label":"78 metres","isCorrect":false},{"label":"98 metres","isCorrect":true},{"label":"115 metres","isCorrect":false}]'::jsonb, NULL, NULL, 'Jan Železný of the Czech Republic holds the men''s javelin world record at 98.48 metres, set in 1996.'),
(NULL, 'mc', 'How many players are on the field for each team in American football?', 'sports', '9_10', 'hard', true, '[{"label":"9","isCorrect":false},{"label":"10","isCorrect":false},{"label":"11","isCorrect":true},{"label":"12","isCorrect":false}]'::jsonb, NULL, NULL, 'Like soccer, American football has 11 players per side on the field at once, but teams have large squads with specialised units.'),
(NULL, 'mc', 'In the Tour de France, approximately how many kilometres do cyclists race in total?', 'sports', '9_10', 'hard', true, '[{"label":"1,000 km","isCorrect":false},{"label":"2,000 km","isCorrect":false},{"label":"3,500 km","isCorrect":true},{"label":"5,000 km","isCorrect":false}]'::jsonb, NULL, NULL, 'The Tour de France covers roughly 3,500 kilometres over about 21 stages across three weeks.'),
(NULL, 'mc', 'Which athlete has won the most Olympic gold medals in history?', 'sports', '9_10', 'hard', true, '[{"label":"Carl Lewis","isCorrect":false},{"label":"Michael Phelps","isCorrect":true},{"label":"Usain Bolt","isCorrect":false},{"label":"Larisa Latynina","isCorrect":false}]'::jsonb, NULL, NULL, 'Michael Phelps won 23 Olympic gold medals in swimming — more than any athlete in Olympic history.'),
(NULL, 'mc', 'At what height does the high jump world record stand (men''s, approximately)?', 'sports', '9_10', 'hard', true, '[{"label":"2.05 metres","isCorrect":false},{"label":"2.25 metres","isCorrect":false},{"label":"2.45 metres","isCorrect":true},{"label":"2.65 metres","isCorrect":false}]'::jsonb, NULL, NULL, 'Javier Sotomayor of Cuba set the men''s high jump world record of 2.45 metres in 1993.'),

-- age_band: 11_12 | difficulty: easy
(NULL, 'mc', 'What is the name of the championship game in the NFL?', 'sports', '11_12', 'easy', true, '[{"label":"The World Series","isCorrect":false},{"label":"The Super Bowl","isCorrect":true},{"label":"The Stanley Cup","isCorrect":false},{"label":"The NBA Finals","isCorrect":false}]'::jsonb, NULL, NULL, 'The Super Bowl is the annual championship game of the National Football League (NFL), one of the most watched sporting events in the world.'),
(NULL, 'mc', 'Which country is considered the birthplace of the sport of rugby?', 'sports', '11_12', 'easy', true, '[{"label":"Australia","isCorrect":false},{"label":"New Zealand","isCorrect":false},{"label":"England","isCorrect":true},{"label":"South Africa","isCorrect":false}]'::jsonb, NULL, NULL, 'Rugby is said to have originated at Rugby School in England in the early 19th century.'),
(NULL, 'mc', 'What is the maximum score in a perfect game of ten-pin bowling?', 'sports', '11_12', 'easy', true, '[{"label":"200","isCorrect":false},{"label":"250","isCorrect":false},{"label":"300","isCorrect":true},{"label":"360","isCorrect":false}]'::jsonb, NULL, NULL, 'A perfect game in ten-pin bowling scores 300 points — achieved by rolling 12 strikes in a row.'),
(NULL, 'mc', 'In which sport is the "Ashes" series played between England and Australia?', 'sports', '11_12', 'easy', true, '[{"label":"Rugby","isCorrect":false},{"label":"Soccer","isCorrect":false},{"label":"Cricket","isCorrect":true},{"label":"Tennis","isCorrect":false}]'::jsonb, NULL, NULL, 'The Ashes is a famous cricket Test match series played between England and Australia, dating back to 1882.'),
(NULL, 'mc', 'What is the name of the trophy awarded to the winner of the NBA basketball championship?', 'sports', '11_12', 'easy', true, '[{"label":"The Larry O''Brien Trophy","isCorrect":true},{"label":"The Vince Lombardi Trophy","isCorrect":false},{"label":"The Commissioner''s Cup","isCorrect":false},{"label":"The NBA Shield","isCorrect":false}]'::jsonb, NULL, NULL, 'The Larry O''Brien Championship Trophy is given to the NBA Finals winner each year, named after former NBA Commissioner Larry O''Brien.'),

-- age_band: 11_12 | difficulty: medium
(NULL, 'mc', 'Who won the most Ballon d''Or awards in football history?', 'sports', '11_12', 'medium', true, '[{"label":"Cristiano Ronaldo","isCorrect":false},{"label":"Lionel Messi","isCorrect":true},{"label":"Ronaldo (R9)","isCorrect":false},{"label":"Zinedine Zidane","isCorrect":false}]'::jsonb, NULL, NULL, 'Lionel Messi has won the Ballon d''Or more than any other player, claiming the award eight times as of 2023.'),
(NULL, 'mc', 'In which year did women''s football first appear at the Olympic Games?', 'sports', '11_12', 'medium', true, '[{"label":"1984","isCorrect":false},{"label":"1992","isCorrect":false},{"label":"1996","isCorrect":true},{"label":"2000","isCorrect":false}]'::jsonb, NULL, NULL, 'Women''s football made its Olympic debut at the 1996 Atlanta Games, with the USA winning gold.'),
(NULL, 'mc', 'What does "LBW" stand for in cricket?', 'sports', '11_12', 'medium', true, '[{"label":"Left Bat Wide","isCorrect":false},{"label":"Leg Before Wicket","isCorrect":true},{"label":"Late Ball Warning","isCorrect":false},{"label":"Lower Bat Wicket","isCorrect":false}]'::jsonb, NULL, NULL, 'LBW stands for Leg Before Wicket — a batsman is out if the ball would have hit the stumps but was blocked by their leg.'),
(NULL, 'mc', 'How many players are on the court for each team in a standard game of water polo?', 'sports', '11_12', 'medium', true, '[{"label":"5","isCorrect":false},{"label":"6","isCorrect":false},{"label":"7","isCorrect":true},{"label":"8","isCorrect":false}]'::jsonb, NULL, NULL, 'Water polo teams have 7 players in the water at a time, including one goalkeeper.'),
(NULL, 'mc', 'In Formula 1, what do the letters "DRS" stand for?', 'sports', '11_12', 'medium', true, '[{"label":"Direct Racing Speed","isCorrect":false},{"label":"Drag Reduction System","isCorrect":true},{"label":"Dynamic Race Strategy","isCorrect":false},{"label":"Driver Response Signal","isCorrect":false}]'::jsonb, NULL, NULL, 'DRS (Drag Reduction System) allows drivers to open a flap in the rear wing, reducing drag and increasing straight-line speed to help overtaking.'),

-- age_band: 11_12 | difficulty: hard
(NULL, 'mc', 'What is the "Fosbury Flop" associated with in athletics?', 'sports', '11_12', 'hard', true, '[{"label":"Javelin technique","isCorrect":false},{"label":"High jump technique","isCorrect":true},{"label":"Pole vault technique","isCorrect":false},{"label":"Long jump technique","isCorrect":false}]'::jsonb, NULL, NULL, 'The Fosbury Flop is the technique of going over the high jump bar backwards, head-first, pioneered by Dick Fosbury at the 1968 Olympics.'),
(NULL, 'mc', 'Which country has won the Rugby World Cup the most times?', 'sports', '11_12', 'hard', true, '[{"label":"Australia","isCorrect":false},{"label":"South Africa","isCorrect":false},{"label":"New Zealand","isCorrect":true},{"label":"England","isCorrect":false}]'::jsonb, NULL, NULL, 'New Zealand''s All Blacks have won the Rugby World Cup three times (1987, 2011, 2015) — more than any other nation.'),
(NULL, 'mc', 'In baseball, what is a "perfect game"?', 'sports', '11_12', 'hard', true, '[{"label":"Scoring a run in every inning","isCorrect":false},{"label":"A pitcher retiring all 27 batters without any reaching base","isCorrect":true},{"label":"Winning by exactly 10 runs","isCorrect":false},{"label":"A game with no errors in the field","isCorrect":false}]'::jsonb, NULL, NULL, 'A perfect game in baseball is when a pitcher faces 27 batters and retires all of them — no hits, no walks, no errors.'),
(NULL, 'mc', 'What is the "offside rule" designed to prevent in football (soccer)?', 'sports', '11_12', 'hard', true, '[{"label":"Dangerous tackles","isCorrect":false},{"label":"Players camping near the goal to receive easy passes","isCorrect":true},{"label":"The goalkeeper leaving their area","isCorrect":false},{"label":"Players arguing with the referee","isCorrect":false}]'::jsonb, NULL, NULL, 'The offside rule prevents attackers from simply waiting near the goal for easy scoring chances; they must have at least one defender between them and the goal when the ball is played.'),
(NULL, 'mc', 'Which Formula 1 driver has won the most World Championships?', 'sports', '11_12', 'hard', true, '[{"label":"Ayrton Senna","isCorrect":false},{"label":"Michael Schumacher","isCorrect":false},{"label":"Lewis Hamilton","isCorrect":false},{"label":"Both Michael Schumacher and Lewis Hamilton (7 each)","isCorrect":true}]'::jsonb, NULL, NULL, 'Michael Schumacher and Lewis Hamilton share the record for the most Formula 1 World Championships with 7 titles each.'),

-- ============================================================
-- THEME: music
-- ============================================================

-- age_band: 5_6 | difficulty: easy
(NULL, 'mc', 'Which instrument has black and white keys that you press to make sounds?', 'music', '5_6', 'easy', true, '[{"label":"Guitar","isCorrect":false},{"label":"Drum","isCorrect":false},{"label":"Piano","isCorrect":true},{"label":"Flute","isCorrect":false}]'::jsonb, NULL, NULL, 'A piano has black and white keys. When you press them, small hammers hit strings inside to make musical sounds.'),
(NULL, 'mc', 'What do you call someone who plays music for other people to listen to?', 'music', '5_6', 'easy', true, '[{"label":"A dancer","isCorrect":false},{"label":"A musician","isCorrect":true},{"label":"A painter","isCorrect":false},{"label":"A teacher","isCorrect":false}]'::jsonb, NULL, NULL, 'A musician is a person who plays music — they can play instruments, sing, or both!'),
(NULL, 'mc', 'What body part do you mainly use to sing?', 'music', '5_6', 'easy', true, '[{"label":"Your hands","isCorrect":false},{"label":"Your feet","isCorrect":false},{"label":"Your voice","isCorrect":true},{"label":"Your eyes","isCorrect":false}]'::jsonb, NULL, NULL, 'You use your voice to sing! Air from your lungs makes your vocal cords vibrate to create sound.'),
(NULL, 'mc', 'What nursery rhyme goes "Twinkle, twinkle, little ___"?', 'music', '5_6', 'easy', true, '[{"label":"Moon","isCorrect":false},{"label":"Star","isCorrect":true},{"label":"Sun","isCorrect":false},{"label":"Cloud","isCorrect":false}]'::jsonb, NULL, NULL, '"Twinkle, Twinkle, Little Star" is one of the most famous nursery rhymes in the world.'),
(NULL, 'mc', 'Which instrument do you hit with sticks to make a beat?', 'music', '5_6', 'easy', true, '[{"label":"Violin","isCorrect":false},{"label":"Trumpet","isCorrect":false},{"label":"Drums","isCorrect":true},{"label":"Harp","isCorrect":false}]'::jsonb, NULL, NULL, 'Drums are percussion instruments that you hit with sticks or your hands to create rhythm and beat.'),

-- age_band: 5_6 | difficulty: medium
(NULL, 'mc', 'How many strings does a standard guitar have?', 'music', '5_6', 'medium', true, '[{"label":"4","isCorrect":false},{"label":"5","isCorrect":false},{"label":"6","isCorrect":true},{"label":"8","isCorrect":false}]'::jsonb, NULL, NULL, 'A standard guitar has 6 strings, usually tuned to E, A, D, G, B, and E from thickest to thinnest.'),
(NULL, 'mc', 'What is the name of the person who leads an orchestra?', 'music', '5_6', 'medium', true, '[{"label":"The director","isCorrect":false},{"label":"The conductor","isCorrect":true},{"label":"The captain","isCorrect":false},{"label":"The teacher","isCorrect":false}]'::jsonb, NULL, NULL, 'A conductor stands in front of the orchestra and uses a baton to guide the musicians in tempo and expression.'),
(NULL, 'mc', 'Which of these is a wind instrument that you blow into?', 'music', '5_6', 'medium', true, '[{"label":"Cello","isCorrect":false},{"label":"Xylophone","isCorrect":false},{"label":"Flute","isCorrect":true},{"label":"Bass guitar","isCorrect":false}]'::jsonb, NULL, NULL, 'A flute is a wind instrument — you blow across a hole to create sound, and cover different keys to change notes.'),
(NULL, 'mc', 'What song do people usually sing on someone''s birthday?', 'music', '5_6', 'medium', true, '[{"label":"Row Your Boat","isCorrect":false},{"label":"Happy Birthday to You","isCorrect":true},{"label":"Jingle Bells","isCorrect":false},{"label":"Old MacDonald","isCorrect":false}]'::jsonb, NULL, NULL, '"Happy Birthday to You" is one of the most recognised songs in the English language, sung to celebrate birthdays.'),
(NULL, 'mc', 'What is the name of the musical characters Do, Re, Mi, Fa, Sol, La, Ti?', 'music', '5_6', 'medium', true, '[{"label":"Letters","isCorrect":false},{"label":"Solfège notes","isCorrect":true},{"label":"Rhythms","isCorrect":false},{"label":"Chords","isCorrect":false}]'::jsonb, NULL, NULL, 'Do, Re, Mi are solfège notes — a system for singing musical scales made famous by the song in "The Sound of Music."'),

-- age_band: 5_6 | difficulty: hard
(NULL, 'mc', 'Which famous composer was deaf when he wrote some of his greatest music?', 'music', '5_6', 'hard', true, '[{"label":"Mozart","isCorrect":false},{"label":"Bach","isCorrect":false},{"label":"Beethoven","isCorrect":true},{"label":"Vivaldi","isCorrect":false}]'::jsonb, NULL, NULL, 'Ludwig van Beethoven composed some of his most famous works, like the Ninth Symphony, after he had become completely deaf.'),
(NULL, 'mc', 'What is the name of the large stringed instrument you sit down and pluck with both hands?', 'music', '5_6', 'hard', true, '[{"label":"Lute","isCorrect":false},{"label":"Harp","isCorrect":true},{"label":"Sitar","isCorrect":false},{"label":"Banjo","isCorrect":false}]'::jsonb, NULL, NULL, 'A harp is a large instrument with many strings. You sit next to it and pluck the strings with your fingers.'),
(NULL, 'mc', 'What does "forte" mean in music?', 'music', '5_6', 'hard', true, '[{"label":"Slow","isCorrect":false},{"label":"Fast","isCorrect":false},{"label":"Loud","isCorrect":true},{"label":"Soft","isCorrect":false}]'::jsonb, NULL, NULL, '"Forte" is an Italian musical term meaning loud. Its opposite is "piano," which means soft — that''s how the piano got its name!'),
(NULL, 'mc', 'How many notes are in a standard music scale (do re mi...)?', 'music', '5_6', 'hard', true, '[{"label":"5","isCorrect":false},{"label":"6","isCorrect":false},{"label":"7","isCorrect":true},{"label":"8","isCorrect":false}]'::jsonb, NULL, NULL, 'A standard music scale has 7 different notes (Do, Re, Mi, Fa, Sol, La, Ti) before the pattern repeats an octave higher.'),
(NULL, 'mc', 'Which instrument makes sound by vibrating a reed when you blow through it?', 'music', '5_6', 'hard', true, '[{"label":"Trumpet","isCorrect":false},{"label":"Flute","isCorrect":false},{"label":"Clarinet","isCorrect":true},{"label":"Tuba","isCorrect":false}]'::jsonb, NULL, NULL, 'A clarinet uses a thin piece of cane called a reed that vibrates when you blow through the mouthpiece to make sound.'),

-- age_band: 7_8 | difficulty: easy
(NULL, 'mc', 'What is the name of the musical symbols at the start of a piece of sheet music that tells you the key?', 'music', '7_8', 'easy', true, '[{"label":"The time signature","isCorrect":false},{"label":"The key signature","isCorrect":true},{"label":"The clef","isCorrect":false},{"label":"The tempo mark","isCorrect":false}]'::jsonb, NULL, NULL, 'The key signature appears at the start of each line of music and tells musicians which notes are sharps or flats throughout the piece.'),
(NULL, 'mc', 'Which popular band sang "Yellow Submarine" and "Let It Be"?', 'music', '7_8', 'easy', true, '[{"label":"The Rolling Stones","isCorrect":false},{"label":"The Beach Boys","isCorrect":false},{"label":"The Beatles","isCorrect":true},{"label":"ABBA","isCorrect":false}]'::jsonb, NULL, NULL, 'The Beatles are one of the most famous bands in history, from Liverpool, England, active in the 1960s.'),
(NULL, 'mc', 'What does a metronome do?', 'music', '7_8', 'easy', true, '[{"label":"It records music","isCorrect":false},{"label":"It keeps a steady beat","isCorrect":true},{"label":"It amplifies sound","isCorrect":false},{"label":"It tunes your instrument","isCorrect":false}]'::jsonb, NULL, NULL, 'A metronome clicks at a steady speed to help musicians keep the correct tempo while practising.'),
(NULL, 'mc', 'What do the letters "DJ" stand for in music?', 'music', '7_8', 'easy', true, '[{"label":"Dance Jockey","isCorrect":false},{"label":"Disc Jockey","isCorrect":true},{"label":"Digital Jammer","isCorrect":false},{"label":"Dynamic Jazz","isCorrect":false}]'::jsonb, NULL, NULL, 'DJ stands for Disc Jockey — a person who selects and plays recorded music for an audience.'),
(NULL, 'mc', 'What type of music uses the "12-bar blues" structure?', 'music', '7_8', 'easy', true, '[{"label":"Classical","isCorrect":false},{"label":"Opera","isCorrect":false},{"label":"Blues","isCorrect":true},{"label":"Country","isCorrect":false}]'::jsonb, NULL, NULL, 'The 12-bar blues is a chord progression used in blues music, and also forms the basis of many rock and jazz songs.'),

-- age_band: 7_8 | difficulty: medium
(NULL, 'mc', 'What is the name of the symbol that looks like a backwards "C" with a dot, used to indicate treble notes?', 'music', '7_8', 'medium', true, '[{"label":"The bass clef","isCorrect":false},{"label":"The treble clef","isCorrect":true},{"label":"The alto clef","isCorrect":false},{"label":"The sharp sign","isCorrect":false}]'::jsonb, NULL, NULL, 'The treble clef (also called the G clef) is used for higher-pitched instruments and voices, like the violin or flute.'),
(NULL, 'mc', 'Which Australian singer is known as the "Princess of Pop" and sang "Can''t Get You Out of My Head"?', 'music', '7_8', 'medium', true, '[{"label":"Delta Goodrem","isCorrect":false},{"label":"Natalie Imbruglia","isCorrect":false},{"label":"Kylie Minogue","isCorrect":true},{"label":"Jessica Mauboy","isCorrect":false}]'::jsonb, NULL, NULL, 'Kylie Minogue is an Australian pop icon whose song "Can''t Get You Out of My Head" was a global hit in 2001.'),
(NULL, 'mc', 'What is the name of the musical term for gradually getting louder?', 'music', '7_8', 'medium', true, '[{"label":"Decrescendo","isCorrect":false},{"label":"Forte","isCorrect":false},{"label":"Crescendo","isCorrect":true},{"label":"Legato","isCorrect":false}]'::jsonb, NULL, NULL, 'Crescendo (from Italian, meaning "growing") tells musicians to gradually increase in volume.'),
(NULL, 'mc', 'What genre of music originated in Jamaica and features a strong off-beat rhythm?', 'music', '7_8', 'medium', true, '[{"label":"Jazz","isCorrect":false},{"label":"Reggae","isCorrect":true},{"label":"Blues","isCorrect":false},{"label":"Funk","isCorrect":false}]'::jsonb, NULL, NULL, 'Reggae originated in Jamaica in the late 1960s. Bob Marley is its most famous artist.'),
(NULL, 'mc', 'What is the name of the lowest-pitched brass instrument in an orchestra?', 'music', '7_8', 'medium', true, '[{"label":"Trombone","isCorrect":false},{"label":"French horn","isCorrect":false},{"label":"Tuba","isCorrect":true},{"label":"Trumpet","isCorrect":false}]'::jsonb, NULL, NULL, 'The tuba is the largest and lowest-pitched brass instrument in the orchestra.'),

-- age_band: 7_8 | difficulty: hard
(NULL, 'mc', 'In music, what does "BPM" stand for?', 'music', '7_8', 'hard', true, '[{"label":"Beats Per Minute","isCorrect":true},{"label":"Bass Per Measure","isCorrect":false},{"label":"Bars Per Melody","isCorrect":false},{"label":"Beat Pattern Mark","isCorrect":false}]'::jsonb, NULL, NULL, 'BPM stands for Beats Per Minute — the measure of tempo or speed of a piece of music.'),
(NULL, 'mc', 'Which famous composer wrote "Eine Kleine Nachtmusik"?', 'music', '7_8', 'hard', true, '[{"label":"Beethoven","isCorrect":false},{"label":"Bach","isCorrect":false},{"label":"Mozart","isCorrect":true},{"label":"Handel","isCorrect":false}]'::jsonb, NULL, NULL, 'Wolfgang Amadeus Mozart composed "Eine Kleine Nachtmusik" (A Little Night Music) in 1787 — one of his most famous pieces.'),
(NULL, 'mc', 'What are the four main sections of an orchestra?', 'music', '7_8', 'hard', true, '[{"label":"Strings, brass, woodwind, percussion","isCorrect":true},{"label":"Strings, piano, brass, voice","isCorrect":false},{"label":"Woodwind, bass, drums, horns","isCorrect":false},{"label":"Violins, trumpets, flutes, cymbals","isCorrect":false}]'::jsonb, NULL, NULL, 'An orchestra is divided into four main sections: strings (violins, cellos), brass (trumpets, trombones), woodwind (flutes, oboes), and percussion (drums, timpani).'),
(NULL, 'mc', 'What is a "chord" in music?', 'music', '7_8', 'hard', true, '[{"label":"A single note played very long","isCorrect":false},{"label":"Two or more notes played together","isCorrect":true},{"label":"The highest note in a melody","isCorrect":false},{"label":"A rest between two phrases","isCorrect":false}]'::jsonb, NULL, NULL, 'A chord is when two or more notes are played at the same time, creating harmony.'),
(NULL, 'mc', 'What is the term for the speed at which a piece of music is played?', 'music', '7_8', 'hard', true, '[{"label":"Dynamics","isCorrect":false},{"label":"Tempo","isCorrect":true},{"label":"Timbre","isCorrect":false},{"label":"Harmony","isCorrect":false}]'::jsonb, NULL, NULL, 'Tempo (from Italian, meaning "time") refers to the speed of the music. It is often indicated by words like "Allegro" (fast) or "Adagio" (slow).'),

-- age_band: 9_10 | difficulty: easy
(NULL, 'mc', 'What music genre features "call and response" vocals and originated among African Americans in the US South?', 'music', '9_10', 'easy', true, '[{"label":"Classical","isCorrect":false},{"label":"Country","isCorrect":false},{"label":"Blues","isCorrect":true},{"label":"Pop","isCorrect":false}]'::jsonb, NULL, NULL, 'Blues music originated in the Deep South of the United States among African Americans and features "call and response" singing patterns.'),
(NULL, 'mc', 'What instrument did Jimi Hendrix famously play?', 'music', '9_10', 'easy', true, '[{"label":"Piano","isCorrect":false},{"label":"Electric guitar","isCorrect":true},{"label":"Bass guitar","isCorrect":false},{"label":"Drums","isCorrect":false}]'::jsonb, NULL, NULL, 'Jimi Hendrix is considered one of the greatest electric guitarists of all time, famous for his innovative style in the 1960s.'),
(NULL, 'mc', 'What is the name of the world''s most famous music streaming service, launched in 2008?', 'music', '9_10', 'easy', true, '[{"label":"Apple Music","isCorrect":false},{"label":"Spotify","isCorrect":true},{"label":"Tidal","isCorrect":false},{"label":"Pandora","isCorrect":false}]'::jsonb, NULL, NULL, 'Spotify was launched in 2008 in Sweden and quickly became the world''s most popular music streaming service.'),
(NULL, 'mc', 'Which musical term means to play notes smoothly and connected?', 'music', '9_10', 'easy', true, '[{"label":"Staccato","isCorrect":false},{"label":"Forte","isCorrect":false},{"label":"Legato","isCorrect":true},{"label":"Pizzicato","isCorrect":false}]'::jsonb, NULL, NULL, 'Legato (Italian for "tied together") means to play notes smoothly with no gaps between them.'),
(NULL, 'mc', 'What is the name for the distance between two musical notes of the same name (e.g. C to the next C)?', 'music', '9_10', 'easy', true, '[{"label":"A step","isCorrect":false},{"label":"An octave","isCorrect":true},{"label":"A scale","isCorrect":false},{"label":"A third","isCorrect":false}]'::jsonb, NULL, NULL, 'An octave is the interval between one musical pitch and another with double its frequency — from C to the next C, for example.'),

-- age_band: 9_10 | difficulty: medium
(NULL, 'mc', 'Which city is considered the birthplace of jazz music?', 'music', '9_10', 'medium', true, '[{"label":"Chicago","isCorrect":false},{"label":"New York","isCorrect":false},{"label":"New Orleans","isCorrect":true},{"label":"Memphis","isCorrect":false}]'::jsonb, NULL, NULL, 'Jazz music originated in New Orleans, Louisiana in the late 19th and early 20th centuries, blending African rhythms with European musical traditions.'),
(NULL, 'mc', 'What does a time signature of 4/4 mean in music?', 'music', '9_10', 'medium', true, '[{"label":"There are 4 notes in each piece","isCorrect":false},{"label":"There are 4 beats per bar and a quarter note gets one beat","isCorrect":true},{"label":"The music plays at 4 BPM","isCorrect":false},{"label":"There are 4 sharps in the key","isCorrect":false}]'::jsonb, NULL, NULL, 'In a 4/4 time signature, the top number means 4 beats per bar, and the bottom number means a quarter note (crotchet) gets one beat.'),
(NULL, 'mc', 'Which famous singer is known as the "King of Pop"?', 'music', '9_10', 'medium', true, '[{"label":"Elvis Presley","isCorrect":false},{"label":"Prince","isCorrect":false},{"label":"Michael Jackson","isCorrect":true},{"label":"David Bowie","isCorrect":false}]'::jsonb, NULL, NULL, 'Michael Jackson earned the title "King of Pop" due to his groundbreaking music, videos, and dance moves throughout the 1980s and 1990s.'),
(NULL, 'mc', 'In music, what is an "arpeggio"?', 'music', '9_10', 'medium', true, '[{"label":"A fast drum rhythm","isCorrect":false},{"label":"A chord played one note at a time in sequence","isCorrect":true},{"label":"A sudden change in volume","isCorrect":false},{"label":"A melody sung by two people","isCorrect":false}]'::jsonb, NULL, NULL, 'An arpeggio is when the notes of a chord are played in sequence rather than simultaneously — like "broken chords."'),
(NULL, 'mc', 'What is the name of Beethoven''s famous fifth symphony''s opening theme (da-da-da-DUM)?', 'music', '9_10', 'medium', true, '[{"label":"The Fate motif","isCorrect":true},{"label":"The Victory theme","isCorrect":false},{"label":"The Storm opening","isCorrect":false},{"label":"The Destiny chord","isCorrect":false}]'::jsonb, NULL, NULL, 'Beethoven''s four-note opening of Symphony No. 5 is known as the "Fate motif" — one of the most recognisable musical phrases ever written.'),

-- age_band: 9_10 | difficulty: hard
(NULL, 'mc', 'How many keys does a standard full-size piano have?', 'music', '9_10', 'hard', true, '[{"label":"72","isCorrect":false},{"label":"76","isCorrect":false},{"label":"88","isCorrect":true},{"label":"96","isCorrect":false}]'::jsonb, NULL, NULL, 'A full-size piano has 88 keys: 52 white keys and 36 black keys, spanning over 7 octaves.'),
(NULL, 'mc', 'What is the name of the music genre that blends jazz and classical music with improvisation, developed in the US in the early 20th century?', 'music', '9_10', 'hard', true, '[{"label":"Ragtime","isCorrect":false},{"label":"Swing","isCorrect":false},{"label":"Bebop","isCorrect":true},{"label":"Soul","isCorrect":false}]'::jsonb, NULL, NULL, 'Bebop developed in the early 1940s as a complex jazz style featuring fast tempos and intricate improvisation, with Charlie Parker as one of its key figures.'),
(NULL, 'mc', 'What is the "pentatonic scale" made up of?', 'music', '9_10', 'hard', true, '[{"label":"Three notes","isCorrect":false},{"label":"Four notes","isCorrect":false},{"label":"Five notes","isCorrect":true},{"label":"Six notes","isCorrect":false}]'::jsonb, NULL, NULL, 'A pentatonic scale uses five notes per octave (penta = five). It is used widely in blues, rock, and folk music around the world.'),
(NULL, 'mc', 'Which Italian composer wrote "The Four Seasons"?', 'music', '9_10', 'hard', true, '[{"label":"Verdi","isCorrect":false},{"label":"Vivaldi","isCorrect":true},{"label":"Puccini","isCorrect":false},{"label":"Corelli","isCorrect":false}]'::jsonb, NULL, NULL, 'Antonio Vivaldi composed "The Four Seasons" around 1720 — four violin concertos representing spring, summer, autumn, and winter.'),
(NULL, 'mc', 'What is the term for music written for a solo instrument accompanied by an orchestra?', 'music', '9_10', 'hard', true, '[{"label":"Symphony","isCorrect":false},{"label":"Sonata","isCorrect":false},{"label":"Concerto","isCorrect":true},{"label":"Overture","isCorrect":false}]'::jsonb, NULL, NULL, 'A concerto is a composition for a solo instrument (like piano or violin) that performs alongside and contrasts with a full orchestra.'),

-- age_band: 11_12 | difficulty: easy
(NULL, 'mc', 'What is the name of the music chart that ranks the most popular songs in the UK each week?', 'music', '11_12', 'easy', true, '[{"label":"The Hot 100","isCorrect":false},{"label":"The UK Singles Chart","isCorrect":true},{"label":"The ARIA Chart","isCorrect":false},{"label":"The Top 40","isCorrect":false}]'::jsonb, NULL, NULL, 'The UK Singles Chart, published weekly since 1952, ranks the best-selling singles in the United Kingdom.'),
(NULL, 'mc', 'What is the name of the award given for excellence in the music industry in the US?', 'music', '11_12', 'easy', true, '[{"label":"The BRIT Award","isCorrect":false},{"label":"The Grammy","isCorrect":true},{"label":"The ARIA Award","isCorrect":false},{"label":"The MTV Award","isCorrect":false}]'::jsonb, NULL, NULL, 'The Grammy Awards are given by the Recording Academy in the USA and are the most prestigious awards in the music industry.'),
(NULL, 'mc', 'Which singer released the albums "Fearless" and "1989"?', 'music', '11_12', 'easy', true, '[{"label":"Katy Perry","isCorrect":false},{"label":"Ariana Grande","isCorrect":false},{"label":"Taylor Swift","isCorrect":true},{"label":"Beyoncé","isCorrect":false}]'::jsonb, NULL, NULL, '"Fearless" (2008) and "1989" (2014) are both by Taylor Swift and won Album of the Year at the Grammy Awards.'),
(NULL, 'mc', 'What is the name of the lower set of lines in a musical score, used for instruments like the cello and bass?', 'music', '11_12', 'easy', true, '[{"label":"Alto clef","isCorrect":false},{"label":"Bass clef","isCorrect":true},{"label":"Tenor clef","isCorrect":false},{"label":"Baritone clef","isCorrect":false}]'::jsonb, NULL, NULL, 'The bass clef is used for lower-pitched instruments and voices, such as the cello, double bass, trombone, and bass guitar.'),
(NULL, 'mc', 'What does "a cappella" mean?', 'music', '11_12', 'easy', true, '[{"label":"Very fast and lively","isCorrect":false},{"label":"Singing without instrumental accompaniment","isCorrect":true},{"label":"A slow and sad style of singing","isCorrect":false},{"label":"Using electronic effects on a voice","isCorrect":false}]'::jsonb, NULL, NULL, '"A cappella" is an Italian phrase meaning "in the chapel style" — singing performed without any instrumental backing.'),

-- age_band: 11_12 | difficulty: medium
(NULL, 'mc', 'What is the term for the unique quality of a sound that lets you tell the difference between a violin and a flute playing the same note?', 'music', '11_12', 'medium', true, '[{"label":"Pitch","isCorrect":false},{"label":"Dynamics","isCorrect":false},{"label":"Timbre","isCorrect":true},{"label":"Tempo","isCorrect":false}]'::jsonb, NULL, NULL, 'Timbre (pronounced "tam-ber") is the tone colour or quality of a sound that makes instruments sound different from each other, even at the same pitch.'),
(NULL, 'mc', 'Which musical period came before the Classical period?', 'music', '11_12', 'medium', true, '[{"label":"Romantic","isCorrect":false},{"label":"Modern","isCorrect":false},{"label":"Baroque","isCorrect":true},{"label":"Renaissance","isCorrect":false}]'::jsonb, NULL, NULL, 'The Baroque period (roughly 1600–1750) preceded the Classical period (1750–1820). Composers like Bach and Handel worked in the Baroque era.'),
(NULL, 'mc', 'What is "syncopation" in music?', 'music', '11_12', 'medium', true, '[{"label":"Playing all notes at the same volume","isCorrect":false},{"label":"Emphasising the off-beats or weak beats","isCorrect":true},{"label":"Slowing down at the end of a phrase","isCorrect":false},{"label":"Repeating the same chord throughout","isCorrect":false}]'::jsonb, NULL, NULL, 'Syncopation is a rhythmic technique where the accent is placed on beats that are normally unaccented, creating a bouncy or unexpected feel — common in jazz, funk, and pop.'),
(NULL, 'mc', 'What term describes two notes played together that sound pleasant and resolved?', 'music', '11_12', 'medium', true, '[{"label":"Dissonance","isCorrect":false},{"label":"Consonance","isCorrect":true},{"label":"Resonance","isCorrect":false},{"label":"Cadence","isCorrect":false}]'::jsonb, NULL, NULL, 'Consonance describes notes or chords that sound stable and pleasing when played together. Its opposite, dissonance, sounds tense or unresolved.'),
(NULL, 'mc', 'How many movements does Beethoven''s Ninth Symphony have?', 'music', '11_12', 'medium', true, '[{"label":"2","isCorrect":false},{"label":"3","isCorrect":false},{"label":"4","isCorrect":true},{"label":"5","isCorrect":false}]'::jsonb, NULL, NULL, 'Beethoven''s Ninth Symphony has four movements. The final movement famously includes the choral setting of Schiller''s "Ode to Joy."'),

-- age_band: 11_12 | difficulty: hard
(NULL, 'mc', 'What is a "Picardy third"?', 'music', '11_12', 'hard', true, '[{"label":"A chord that uses three trumpets","isCorrect":false},{"label":"Ending a piece in a minor key with a major chord","isCorrect":true},{"label":"A rhythm with three beats per bar","isCorrect":false},{"label":"A scale from northern France","isCorrect":false}]'::jsonb, NULL, NULL, 'A Picardy third is when a piece written in a minor key unexpectedly ends on a major chord, creating a brightening effect at the conclusion.'),
(NULL, 'mc', 'What is the name of the technique where a violinist plucks the strings instead of using a bow?', 'music', '11_12', 'hard', true, '[{"label":"Glissando","isCorrect":false},{"label":"Tremolo","isCorrect":false},{"label":"Pizzicato","isCorrect":true},{"label":"Vibrato","isCorrect":false}]'::jsonb, NULL, NULL, 'Pizzicato (Italian for "pinched") is the technique of plucking the strings of a bowed string instrument with the fingers.'),
(NULL, 'mc', 'In music theory, what is a "tritone"?', 'music', '11_12', 'hard', true, '[{"label":"A chord with three notes","isCorrect":false},{"label":"An interval spanning three whole tones (an augmented fourth)","isCorrect":true},{"label":"A time signature with three beats","isCorrect":false},{"label":"A three-part vocal harmony","isCorrect":false}]'::jsonb, NULL, NULL, 'A tritone is an interval of three whole tones (an augmented fourth or diminished fifth). It was once called "diabolus in musica" (the devil in music) for its dissonant sound.'),
(NULL, 'mc', 'What is the name of Schubert''s unfinished symphony?', 'music', '11_12', 'hard', true, '[{"label":"Symphony No. 7","isCorrect":false},{"label":"Symphony No. 8 in B minor","isCorrect":true},{"label":"Symphony No. 9 in C major","isCorrect":false},{"label":"Symphony No. 6 in C major","isCorrect":false}]'::jsonb, NULL, NULL, 'Schubert''s "Unfinished Symphony" is Symphony No. 8 in B minor. He only completed two of its movements before his death in 1828.'),
(NULL, 'mc', 'What is "counterpoint" in music composition?', 'music', '11_12', 'hard', true, '[{"label":"A note that cancels out a previous note","isCorrect":false},{"label":"Two or more independent melodic lines played simultaneously","isCorrect":true},{"label":"Writing music in the opposite key","isCorrect":false},{"label":"Playing a melody backwards","isCorrect":false}]'::jsonb, NULL, NULL, 'Counterpoint is the technique of combining two or more independent melodic lines that harmonise while maintaining their own identity. Bach was the master of counterpoint.'),

-- ============================================================
-- THEME: fun_facts
-- ============================================================

-- age_band: 5_6 | difficulty: easy
(NULL, 'mc', 'How many legs does a spider have?', 'fun_facts', '5_6', 'easy', true, '[{"label":"4","isCorrect":false},{"label":"6","isCorrect":false},{"label":"8","isCorrect":true},{"label":"10","isCorrect":false}]'::jsonb, NULL, NULL, 'All spiders have exactly 8 legs. This is one of the features that makes them arachnids, not insects.'),
(NULL, 'mc', 'What colour is a flamingo?', 'fun_facts', '5_6', 'easy', true, '[{"label":"Blue","isCorrect":false},{"label":"Pink","isCorrect":true},{"label":"Yellow","isCorrect":false},{"label":"Green","isCorrect":false}]'::jsonb, NULL, NULL, 'Flamingos are pink! Their colour comes from the pink pigments in the shrimp and algae they eat.'),
(NULL, 'mc', 'Which is the biggest animal on Earth?', 'fun_facts', '5_6', 'easy', true, '[{"label":"Elephant","isCorrect":false},{"label":"Giraffe","isCorrect":false},{"label":"Blue whale","isCorrect":true},{"label":"Great white shark","isCorrect":false}]'::jsonb, NULL, NULL, 'The blue whale is the largest animal ever known to have lived on Earth, reaching up to 30 metres long.'),
(NULL, 'mc', 'How many sides does a triangle have?', 'fun_facts', '5_6', 'easy', true, '[{"label":"2","isCorrect":false},{"label":"3","isCorrect":true},{"label":"4","isCorrect":false},{"label":"5","isCorrect":false}]'::jsonb, NULL, NULL, 'A triangle has 3 sides and 3 corners (vertices). The word "tri" means three.'),
(NULL, 'mc', 'What do caterpillars turn into?', 'fun_facts', '5_6', 'easy', true, '[{"label":"Bees","isCorrect":false},{"label":"Moths or butterflies","isCorrect":true},{"label":"Beetles","isCorrect":false},{"label":"Dragonflies","isCorrect":false}]'::jsonb, NULL, NULL, 'Caterpillars go through metamorphosis — they form a cocoon and emerge as either a butterfly or a moth.'),

-- age_band: 5_6 | difficulty: medium
(NULL, 'mc', 'How many colours are in a rainbow?', 'fun_facts', '5_6', 'medium', true, '[{"label":"5","isCorrect":false},{"label":"6","isCorrect":false},{"label":"7","isCorrect":true},{"label":"8","isCorrect":false}]'::jsonb, NULL, NULL, 'A rainbow has 7 colours: red, orange, yellow, green, blue, indigo, and violet.'),
(NULL, 'mc', 'Which planet do we live on?', 'fun_facts', '5_6', 'medium', true, '[{"label":"Mars","isCorrect":false},{"label":"Venus","isCorrect":false},{"label":"Earth","isCorrect":true},{"label":"Jupiter","isCorrect":false}]'::jsonb, NULL, NULL, 'We live on planet Earth, the third planet from the Sun and the only known planet with life.'),
(NULL, 'mc', 'What do bees make that we can eat?', 'fun_facts', '5_6', 'medium', true, '[{"label":"Milk","isCorrect":false},{"label":"Honey","isCorrect":true},{"label":"Sugar","isCorrect":false},{"label":"Bread","isCorrect":false}]'::jsonb, NULL, NULL, 'Bees collect nectar from flowers and turn it into honey, which they store in their hives as food.'),
(NULL, 'mc', 'Which is the tallest land animal?', 'fun_facts', '5_6', 'medium', true, '[{"label":"Elephant","isCorrect":false},{"label":"Horse","isCorrect":false},{"label":"Giraffe","isCorrect":true},{"label":"Camel","isCorrect":false}]'::jsonb, NULL, NULL, 'Giraffes are the tallest land animals on Earth, reaching heights of up to 6 metres!'),
(NULL, 'mc', 'What do plants need from the sun to grow?', 'fun_facts', '5_6', 'medium', true, '[{"label":"Warmth only","isCorrect":false},{"label":"Light for photosynthesis","isCorrect":true},{"label":"Darkness","isCorrect":false},{"label":"Rain from clouds","isCorrect":false}]'::jsonb, NULL, NULL, 'Plants use sunlight to make their own food through photosynthesis — turning light, water, and carbon dioxide into sugar.'),

-- age_band: 5_6 | difficulty: hard
(NULL, 'mc', 'Which country has the most wild kangaroos?', 'fun_facts', '5_6', 'hard', true, '[{"label":"New Zealand","isCorrect":false},{"label":"South Africa","isCorrect":false},{"label":"Australia","isCorrect":true},{"label":"Brazil","isCorrect":false}]'::jsonb, NULL, NULL, 'Kangaroos are native to Australia. There are actually more kangaroos in Australia than people!'),
(NULL, 'mc', 'What is the hardest natural material on Earth?', 'fun_facts', '5_6', 'hard', true, '[{"label":"Gold","isCorrect":false},{"label":"Iron","isCorrect":false},{"label":"Diamond","isCorrect":true},{"label":"Rock","isCorrect":false}]'::jsonb, NULL, NULL, 'Diamonds are the hardest natural material known — they are formed deep underground from carbon under extreme pressure.'),
(NULL, 'mc', 'How many bones does an adult human body have?', 'fun_facts', '5_6', 'hard', true, '[{"label":"106","isCorrect":false},{"label":"156","isCorrect":false},{"label":"206","isCorrect":true},{"label":"256","isCorrect":false}]'::jsonb, NULL, NULL, 'The adult human body has 206 bones. Babies are born with about 270 bones, but many fuse together as they grow.'),
(NULL, 'mc', 'What is the name of the largest ocean on Earth?', 'fun_facts', '5_6', 'hard', true, '[{"label":"Atlantic Ocean","isCorrect":false},{"label":"Indian Ocean","isCorrect":false},{"label":"Pacific Ocean","isCorrect":true},{"label":"Arctic Ocean","isCorrect":false}]'::jsonb, NULL, NULL, 'The Pacific Ocean is the largest and deepest ocean, covering more than 30% of Earth''s surface.'),
(NULL, 'mc', 'What makes the sky appear blue during the day?', 'fun_facts', '5_6', 'hard', true, '[{"label":"The ocean reflecting up","isCorrect":false},{"label":"Sunlight scattering off air molecules","isCorrect":true},{"label":"Blue paint in the clouds","isCorrect":false},{"label":"The sun is blue inside","isCorrect":false}]'::jsonb, NULL, NULL, 'Sunlight contains all colours. When it hits the atmosphere, air molecules scatter blue light more than other colours, making the sky appear blue.'),

-- age_band: 7_8 | difficulty: easy
(NULL, 'mc', 'What gas do humans breathe in to survive?', 'fun_facts', '7_8', 'easy', true, '[{"label":"Carbon dioxide","isCorrect":false},{"label":"Nitrogen","isCorrect":false},{"label":"Oxygen","isCorrect":true},{"label":"Hydrogen","isCorrect":false}]'::jsonb, NULL, NULL, 'Humans need oxygen to survive. We breathe in air, which is about 21% oxygen, and breathe out carbon dioxide.'),
(NULL, 'mc', 'Which planet is known as the Red Planet?', 'fun_facts', '7_8', 'easy', true, '[{"label":"Jupiter","isCorrect":false},{"label":"Venus","isCorrect":false},{"label":"Mars","isCorrect":true},{"label":"Saturn","isCorrect":false}]'::jsonb, NULL, NULL, 'Mars is called the Red Planet because its surface is covered in iron oxide (rust), giving it a reddish appearance.'),
(NULL, 'mc', 'What is the fastest land animal?', 'fun_facts', '7_8', 'easy', true, '[{"label":"Lion","isCorrect":false},{"label":"Cheetah","isCorrect":true},{"label":"Horse","isCorrect":false},{"label":"Greyhound","isCorrect":false}]'::jsonb, NULL, NULL, 'The cheetah is the fastest land animal, capable of reaching speeds of up to 112 km/h in short sprints.'),
(NULL, 'mc', 'What is the main ingredient in glass?', 'fun_facts', '7_8', 'easy', true, '[{"label":"Clay","isCorrect":false},{"label":"Sand","isCorrect":true},{"label":"Water","isCorrect":false},{"label":"Salt","isCorrect":false}]'::jsonb, NULL, NULL, 'Glass is made primarily from silica sand, which is melted at very high temperatures and then cooled quickly.'),
(NULL, 'mc', 'How long does it take for Earth to orbit the Sun once?', 'fun_facts', '7_8', 'easy', true, '[{"label":"One month","isCorrect":false},{"label":"Six months","isCorrect":false},{"label":"One year","isCorrect":true},{"label":"Two years","isCorrect":false}]'::jsonb, NULL, NULL, 'Earth takes approximately 365.25 days — one year — to complete one orbit around the Sun. The extra quarter day is why we have leap years.'),

-- age_band: 7_8 | difficulty: medium
(NULL, 'mc', 'Which animal has the longest lifespan of any vertebrate on Earth?', 'fun_facts', '7_8', 'medium', true, '[{"label":"Giant tortoise","isCorrect":false},{"label":"Greenland shark","isCorrect":true},{"label":"Bowhead whale","isCorrect":false},{"label":"Koi fish","isCorrect":false}]'::jsonb, NULL, NULL, 'The Greenland shark can live for over 400 years, making it the longest-lived vertebrate animal known to science.'),
(NULL, 'mc', 'What is the only mammal that can truly fly?', 'fun_facts', '7_8', 'medium', true, '[{"label":"Flying squirrel","isCorrect":false},{"label":"Sugar glider","isCorrect":false},{"label":"Bat","isCorrect":true},{"label":"Flying lemur","isCorrect":false}]'::jsonb, NULL, NULL, 'Bats are the only mammals capable of true, sustained flight. Other "flying" mammals like sugar gliders can only glide.'),
(NULL, 'mc', 'What percentage of the human body is water?', 'fun_facts', '7_8', 'medium', true, '[{"label":"Around 30%","isCorrect":false},{"label":"Around 45%","isCorrect":false},{"label":"Around 60%","isCorrect":true},{"label":"Around 80%","isCorrect":false}]'::jsonb, NULL, NULL, 'About 60% of the human body is made up of water. It is essential for nearly every function in our bodies.'),
(NULL, 'mc', 'What causes thunder during a storm?', 'fun_facts', '7_8', 'medium', true, '[{"label":"Clouds colliding together","isCorrect":false},{"label":"The rapid expansion of air heated by lightning","isCorrect":true},{"label":"Rain hitting the ground hard","isCorrect":false},{"label":"Wind bouncing between clouds","isCorrect":false}]'::jsonb, NULL, NULL, 'Lightning superheats the surrounding air, causing it to rapidly expand and create a shockwave — that''s the sound of thunder.'),
(NULL, 'mc', 'What is the name of the force that keeps us on the ground?', 'fun_facts', '7_8', 'medium', true, '[{"label":"Magnetism","isCorrect":false},{"label":"Friction","isCorrect":false},{"label":"Gravity","isCorrect":true},{"label":"Pressure","isCorrect":false}]'::jsonb, NULL, NULL, 'Gravity is the force that attracts objects with mass toward each other. Earth''s gravity keeps us on the ground and the Moon in orbit.'),

-- age_band: 7_8 | difficulty: hard
(NULL, 'mc', 'What is the name of the deepest ocean trench on Earth?', 'fun_facts', '7_8', 'hard', true, '[{"label":"Java Trench","isCorrect":false},{"label":"Puerto Rico Trench","isCorrect":false},{"label":"Mariana Trench","isCorrect":true},{"label":"Tonga Trench","isCorrect":false}]'::jsonb, NULL, NULL, 'The Mariana Trench in the Pacific Ocean is the deepest point on Earth, reaching about 11,000 metres below sea level.'),
(NULL, 'mc', 'Roughly how far away is the Moon from Earth?', 'fun_facts', '7_8', 'hard', true, '[{"label":"38,000 km","isCorrect":false},{"label":"384,000 km","isCorrect":true},{"label":"3,840,000 km","isCorrect":false},{"label":"38,000,000 km","isCorrect":false}]'::jsonb, NULL, NULL, 'The Moon is on average about 384,000 kilometres from Earth. It takes light about 1.3 seconds to travel that distance.'),
(NULL, 'mc', 'What is the chemical symbol for gold?', 'fun_facts', '7_8', 'hard', true, '[{"label":"Go","isCorrect":false},{"label":"Gd","isCorrect":false},{"label":"Au","isCorrect":true},{"label":"Gl","isCorrect":false}]'::jsonb, NULL, NULL, 'Gold''s chemical symbol is "Au," from the Latin word "aurum," meaning gold. It has been prized by humans for thousands of years.'),
(NULL, 'mc', 'Which country has the most wild tigers?', 'fun_facts', '7_8', 'hard', true, '[{"label":"China","isCorrect":false},{"label":"Russia","isCorrect":false},{"label":"India","isCorrect":true},{"label":"Indonesia","isCorrect":false}]'::jsonb, NULL, NULL, 'India is home to more than 70% of the world''s wild tiger population, thanks in part to its conservation programmes.'),
(NULL, 'mc', 'How long is a light year?', 'fun_facts', '7_8', 'hard', true, '[{"label":"The distance light travels in one hour","isCorrect":false},{"label":"The distance light travels in one year","isCorrect":true},{"label":"One thousand kilometres","isCorrect":false},{"label":"The age of the universe","isCorrect":false}]'::jsonb, NULL, NULL, 'A light year is the distance that light travels in one year — approximately 9.46 trillion kilometres!'),

-- age_band: 9_10 | difficulty: easy
(NULL, 'mc', 'What is the name of the tallest mountain on Earth?', 'fun_facts', '9_10', 'easy', true, '[{"label":"K2","isCorrect":false},{"label":"Kilimanjaro","isCorrect":false},{"label":"Mount Everest","isCorrect":true},{"label":"Mont Blanc","isCorrect":false}]'::jsonb, NULL, NULL, 'Mount Everest, on the border of Nepal and Tibet, is the world''s highest mountain at 8,849 metres above sea level.'),
(NULL, 'mc', 'How many continents are there on Earth?', 'fun_facts', '9_10', 'easy', true, '[{"label":"5","isCorrect":false},{"label":"6","isCorrect":false},{"label":"7","isCorrect":true},{"label":"8","isCorrect":false}]'::jsonb, NULL, NULL, 'Earth has seven continents: Africa, Antarctica, Asia, Australia (Oceania), Europe, North America, and South America.'),
(NULL, 'mc', 'What is the largest country by land area?', 'fun_facts', '9_10', 'easy', true, '[{"label":"Canada","isCorrect":false},{"label":"China","isCorrect":false},{"label":"Russia","isCorrect":true},{"label":"USA","isCorrect":false}]'::jsonb, NULL, NULL, 'Russia is the largest country on Earth, covering about 17.1 million square kilometres — about twice the size of the next largest country.'),
(NULL, 'mc', 'Approximately how many species of birds exist on Earth?', 'fun_facts', '9_10', 'easy', true, '[{"label":"About 1,000","isCorrect":false},{"label":"About 5,000","isCorrect":false},{"label":"About 10,000","isCorrect":true},{"label":"About 50,000","isCorrect":false}]'::jsonb, NULL, NULL, 'Scientists have identified approximately 10,000 species of birds on Earth, ranging from tiny hummingbirds to large ostriches.'),
(NULL, 'mc', 'Which element is the most abundant in the Earth''s atmosphere?', 'fun_facts', '9_10', 'easy', true, '[{"label":"Oxygen","isCorrect":false},{"label":"Carbon dioxide","isCorrect":false},{"label":"Nitrogen","isCorrect":true},{"label":"Argon","isCorrect":false}]'::jsonb, NULL, NULL, 'Nitrogen makes up about 78% of Earth''s atmosphere. Oxygen is second at about 21%.'),

-- age_band: 9_10 | difficulty: medium
(NULL, 'mc', 'What is the speed of light (approximately) in a vacuum?', 'fun_facts', '9_10', 'medium', true, '[{"label":"300,000 km/s","isCorrect":true},{"label":"30,000 km/s","isCorrect":false},{"label":"3,000,000 km/s","isCorrect":false},{"label":"3,000 km/s","isCorrect":false}]'::jsonb, NULL, NULL, 'Light travels at approximately 300,000 kilometres per second in a vacuum. It takes about 8 minutes for light to travel from the Sun to Earth.'),
(NULL, 'mc', 'What is the name of the process by which rocks are formed from cooling lava?', 'fun_facts', '9_10', 'medium', true, '[{"label":"Sedimentary formation","isCorrect":false},{"label":"Metamorphic change","isCorrect":false},{"label":"Igneous formation","isCorrect":true},{"label":"Erosion","isCorrect":false}]'::jsonb, NULL, NULL, 'Igneous rocks are formed when magma (underground lava) cools and solidifies. Examples include basalt and granite.'),
(NULL, 'mc', 'What is the name of the world''s longest river?', 'fun_facts', '9_10', 'medium', true, '[{"label":"The Amazon","isCorrect":false},{"label":"The Nile","isCorrect":true},{"label":"The Yangtze","isCorrect":false},{"label":"The Mississippi","isCorrect":false}]'::jsonb, NULL, NULL, 'The Nile River in northeastern Africa is generally considered the world''s longest river at about 6,650 kilometres.'),
(NULL, 'mc', 'Which organ in the human body pumps blood around the body?', 'fun_facts', '9_10', 'medium', true, '[{"label":"The lungs","isCorrect":false},{"label":"The kidneys","isCorrect":false},{"label":"The heart","isCorrect":true},{"label":"The liver","isCorrect":false}]'::jsonb, NULL, NULL, 'The heart is a muscular organ that pumps blood around the body. In an average lifetime, it beats about 2.5 billion times!'),
(NULL, 'mc', 'What natural phenomenon is measured on the Richter scale?', 'fun_facts', '9_10', 'medium', true, '[{"label":"Hurricanes","isCorrect":false},{"label":"Earthquakes","isCorrect":true},{"label":"Tornadoes","isCorrect":false},{"label":"Volcanic eruptions","isCorrect":false}]'::jsonb, NULL, NULL, 'The Richter scale (now superseded by the Moment Magnitude scale) measures the strength of earthquakes.'),

-- age_band: 9_10 | difficulty: hard
(NULL, 'mc', 'What is the world record for the longest time a human has held their breath underwater (approximately)?', 'fun_facts', '9_10', 'hard', true, '[{"label":"8 minutes","isCorrect":false},{"label":"16 minutes","isCorrect":false},{"label":"24 minutes","isCorrect":true},{"label":"32 minutes","isCorrect":false}]'::jsonb, NULL, NULL, 'The static apnea world record is held by Budimir Šobat who held his breath for 24 minutes and 37 seconds in 2021.'),
(NULL, 'mc', 'How many times does the human heart beat per minute on average?', 'fun_facts', '9_10', 'hard', true, '[{"label":"40-50 bpm","isCorrect":false},{"label":"60-100 bpm","isCorrect":true},{"label":"110-130 bpm","isCorrect":false},{"label":"150-200 bpm","isCorrect":false}]'::jsonb, NULL, NULL, 'The average adult heart beats between 60 and 100 times per minute. Athletes often have lower resting heart rates due to their fitness.'),
(NULL, 'mc', 'What percentage of Earth''s water is fresh water (not salt water)?', 'fun_facts', '9_10', 'hard', true, '[{"label":"Less than 3%","isCorrect":true},{"label":"About 15%","isCorrect":false},{"label":"About 30%","isCorrect":false},{"label":"About 50%","isCorrect":false}]'::jsonb, NULL, NULL, 'Only about 2.5–3% of Earth''s water is fresh water, and most of that is locked in glaciers and ice caps, leaving very little accessible for humans.'),
(NULL, 'mc', 'What is the name of the phenomenon where a species gradually changes over generations to suit its environment?', 'fun_facts', '9_10', 'hard', true, '[{"label":"Mutation","isCorrect":false},{"label":"Evolution","isCorrect":true},{"label":"Adaptation","isCorrect":false},{"label":"Natural variation","isCorrect":false}]'::jsonb, NULL, NULL, 'Evolution is the process by which species change over many generations through natural selection — first described by Charles Darwin.'),
(NULL, 'mc', 'How many atoms are roughly in a grain of sand?', 'fun_facts', '9_10', 'hard', true, '[{"label":"About 100","isCorrect":false},{"label":"About 1,000","isCorrect":false},{"label":"About 1 million","isCorrect":false},{"label":"About 2 quintillion (2 × 10¹⁸)","isCorrect":true}]'::jsonb, NULL, NULL, 'A single grain of sand contains roughly 2 quintillion (2,000,000,000,000,000,000) atoms — a mind-boggling number that shows how incredibly small atoms are!'),

-- age_band: 11_12 | difficulty: easy
(NULL, 'mc', 'What is the name of the galaxy we live in?', 'fun_facts', '11_12', 'easy', true, '[{"label":"Andromeda","isCorrect":false},{"label":"Triangulum","isCorrect":false},{"label":"The Milky Way","isCorrect":true},{"label":"The Whirlpool","isCorrect":false}]'::jsonb, NULL, NULL, 'We live in the Milky Way galaxy, a barred spiral galaxy containing between 100 and 400 billion stars.'),
(NULL, 'mc', 'What is the name of the table that organises all known chemical elements?', 'fun_facts', '11_12', 'easy', true, '[{"label":"The Element Chart","isCorrect":false},{"label":"The Periodic Table","isCorrect":true},{"label":"The Chemical Index","isCorrect":false},{"label":"The Atomic Grid","isCorrect":false}]'::jsonb, NULL, NULL, 'The Periodic Table of Elements, arranged by atomic number, was first created by Dmitri Mendeleev in 1869.'),
(NULL, 'mc', 'What is the name of the closest star to our solar system?', 'fun_facts', '11_12', 'easy', true, '[{"label":"Sirius","isCorrect":false},{"label":"Proxima Centauri","isCorrect":true},{"label":"Betelgeuse","isCorrect":false},{"label":"Alpha Centauri A","isCorrect":false}]'::jsonb, NULL, NULL, 'Proxima Centauri is the closest known star to our Sun, about 4.24 light years away.'),
(NULL, 'mc', 'What type of energy comes from the Sun?', 'fun_facts', '11_12', 'easy', true, '[{"label":"Nuclear fission energy","isCorrect":false},{"label":"Solar (radiant) energy","isCorrect":true},{"label":"Geothermal energy","isCorrect":false},{"label":"Chemical energy","isCorrect":false}]'::jsonb, NULL, NULL, 'The Sun produces solar (radiant) energy through nuclear fusion — fusing hydrogen atoms into helium and releasing enormous amounts of light and heat.'),
(NULL, 'mc', 'What is the most widely spoken language in the world by total speakers?', 'fun_facts', '11_12', 'easy', true, '[{"label":"Spanish","isCorrect":false},{"label":"Hindi","isCorrect":false},{"label":"English","isCorrect":true},{"label":"Mandarin Chinese","isCorrect":false}]'::jsonb, NULL, NULL, 'English is the most widely spoken language in the world when counting total speakers (native + second language learners), with about 1.5 billion speakers.'),

-- age_band: 11_12 | difficulty: medium
(NULL, 'mc', 'What is the name of the process by which plants convert sunlight into food?', 'fun_facts', '11_12', 'medium', true, '[{"label":"Respiration","isCorrect":false},{"label":"Photosynthesis","isCorrect":true},{"label":"Transpiration","isCorrect":false},{"label":"Germination","isCorrect":false}]'::jsonb, NULL, NULL, 'Photosynthesis is the process by which plants use sunlight, water, and carbon dioxide to produce glucose and oxygen.'),
(NULL, 'mc', 'What is the name of the force that resists relative motion between two surfaces in contact?', 'fun_facts', '11_12', 'medium', true, '[{"label":"Gravity","isCorrect":false},{"label":"Inertia","isCorrect":false},{"label":"Friction","isCorrect":true},{"label":"Tension","isCorrect":false}]'::jsonb, NULL, NULL, 'Friction is the force that opposes motion between surfaces in contact. It can generate heat and is what lets tyres grip roads.'),
(NULL, 'mc', 'Which scientist formulated the three laws of motion?', 'fun_facts', '11_12', 'medium', true, '[{"label":"Albert Einstein","isCorrect":false},{"label":"Galileo Galilei","isCorrect":false},{"label":"Isaac Newton","isCorrect":true},{"label":"Stephen Hawking","isCorrect":false}]'::jsonb, NULL, NULL, 'Isaac Newton published his three laws of motion in 1687 in his landmark work "Principia Mathematica," laying the foundation for classical mechanics.'),
(NULL, 'mc', 'What is the world''s most populated country as of 2024?', 'fun_facts', '11_12', 'medium', true, '[{"label":"China","isCorrect":false},{"label":"India","isCorrect":true},{"label":"USA","isCorrect":false},{"label":"Indonesia","isCorrect":false}]'::jsonb, NULL, NULL, 'India surpassed China in 2023 to become the world''s most populated country, with over 1.4 billion people.'),
(NULL, 'mc', 'What is the name of the layer of gas that surrounds Earth and protects it from ultraviolet radiation?', 'fun_facts', '11_12', 'medium', true, '[{"label":"The ionosphere","isCorrect":false},{"label":"The ozone layer","isCorrect":true},{"label":"The troposphere","isCorrect":false},{"label":"The magnetosphere","isCorrect":false}]'::jsonb, NULL, NULL, 'The ozone layer in the stratosphere absorbs the majority of the Sun''s harmful ultraviolet radiation, protecting life on Earth.'),

-- age_band: 11_12 | difficulty: hard
(NULL, 'mc', 'What is the name of the scientific theory that describes the origin of the universe from an extremely hot, dense state?', 'fun_facts', '11_12', 'hard', true, '[{"label":"The Steady State Theory","isCorrect":false},{"label":"The Big Bang Theory","isCorrect":true},{"label":"The Inflationary Model","isCorrect":false},{"label":"The Cosmic Web Theory","isCorrect":false}]'::jsonb, NULL, NULL, 'The Big Bang Theory proposes that the universe began about 13.8 billion years ago from an extremely hot, dense single point and has been expanding ever since.'),
(NULL, 'mc', 'What is the name of the subatomic particles found in the nucleus of an atom (not electrons)?', 'fun_facts', '11_12', 'hard', true, '[{"label":"Electrons and protons","isCorrect":false},{"label":"Protons and neutrons","isCorrect":true},{"label":"Neutrons and quarks","isCorrect":false},{"label":"Photons and protons","isCorrect":false}]'::jsonb, NULL, NULL, 'The nucleus of an atom contains protons (positively charged) and neutrons (no charge). Electrons orbit the nucleus in shells.'),
(NULL, 'mc', 'What is the name of the genetic molecule that carries instructions for building and running living organisms?', 'fun_facts', '11_12', 'hard', true, '[{"label":"RNA","isCorrect":false},{"label":"ATP","isCorrect":false},{"label":"DNA","isCorrect":true},{"label":"mRNA","isCorrect":false}]'::jsonb, NULL, NULL, 'DNA (deoxyribonucleic acid) is the molecule that contains the genetic instructions for the development, function, and reproduction of all living organisms.'),
(NULL, 'mc', 'Approximately how old is planet Earth?', 'fun_facts', '11_12', 'hard', true, '[{"label":"1 billion years","isCorrect":false},{"label":"2.5 billion years","isCorrect":false},{"label":"4.5 billion years","isCorrect":true},{"label":"10 billion years","isCorrect":false}]'::jsonb, NULL, NULL, 'Earth is approximately 4.5 billion years old, formed from a cloud of gas and dust around our young Sun.'),
(NULL, 'mc', 'What is the term for an animal that eats both plants and other animals?', 'fun_facts', '11_12', 'hard', true, '[{"label":"Carnivore","isCorrect":false},{"label":"Herbivore","isCorrect":false},{"label":"Omnivore","isCorrect":true},{"label":"Detritivore","isCorrect":false}]'::jsonb, NULL, NULL, 'An omnivore eats both plant and animal matter. Humans are omnivores, as are bears, pigs, and many other animals.');
