-- Seed quiz_questions2 with 180 built-in questions across 3 themes
-- pop_culture (60) · technology (60) · food_culture (60)

INSERT INTO quiz_questions2 (family_id, type, question_text, theme, age_band, difficulty, is_builtin, choices, sentence_template, accepted_answers, explanation) VALUES

-- ============================================================
-- THEME: pop_culture
-- ============================================================

-- age_band: 5_6 | difficulty: easy
(NULL, 'mc', 'What is the name of the little pig who wears a red dress on TV?', 'pop_culture', '5_6', 'easy', true, '[{"label":"Peppa Pig","isCorrect":true},{"label":"George Pig","isCorrect":false},{"label":"Daddy Pig","isCorrect":false},{"label":"Suzy Sheep","isCorrect":false}]'::jsonb, NULL, NULL, 'Peppa Pig is the star of the popular children''s TV show Peppa Pig, and she wears a red dress.'),
(NULL, 'mc', 'In the movie "Finding Nemo," what kind of fish is Nemo?', 'pop_culture', '5_6', 'easy', true, '[{"label":"Shark","isCorrect":false},{"label":"Clownfish","isCorrect":true},{"label":"Goldfish","isCorrect":false},{"label":"Starfish","isCorrect":false}]'::jsonb, NULL, NULL, 'Nemo is a clownfish — the orange-and-white striped fish also called an anemonefish.'),
(NULL, 'mc', 'What colour is Elmo from Sesame Street?', 'pop_culture', '5_6', 'easy', true, '[{"label":"Blue","isCorrect":false},{"label":"Yellow","isCorrect":false},{"label":"Red","isCorrect":true},{"label":"Green","isCorrect":false}]'::jsonb, NULL, NULL, 'Elmo is a furry red monster on Sesame Street who loves to laugh and learn.'),
(NULL, 'mc', 'In "Frozen," what is Elsa''s magical power?', 'pop_culture', '5_6', 'easy', true, '[{"label":"Fire","isCorrect":false},{"label":"Flying","isCorrect":false},{"label":"Ice and snow","isCorrect":true},{"label":"Super speed","isCorrect":false}]'::jsonb, NULL, NULL, 'Elsa can create ice and snow with her hands. She even builds a giant ice castle!'),
(NULL, 'mc', 'What animal is Simba in "The Lion King"?', 'pop_culture', '5_6', 'easy', true, '[{"label":"Tiger","isCorrect":false},{"label":"Lion","isCorrect":true},{"label":"Cheetah","isCorrect":false},{"label":"Leopard","isCorrect":false}]'::jsonb, NULL, NULL, 'Simba is a lion cub who grows up to become the king of the Pride Lands in "The Lion King."'),

-- age_band: 5_6 | difficulty: medium
(NULL, 'mc', 'What is the name of Peppa Pig''s little brother?', 'pop_culture', '5_6', 'medium', true, '[{"label":"Danny Dog","isCorrect":false},{"label":"Pedro Pony","isCorrect":false},{"label":"George Pig","isCorrect":true},{"label":"Zoe Zebra","isCorrect":false}]'::jsonb, NULL, NULL, 'George Pig is Peppa''s younger brother. He loves his toy dinosaur and says "Dine-saw! Grr!"'),
(NULL, 'mc', 'In "Toy Story," what is the name of the cowboy doll?', 'pop_culture', '5_6', 'medium', true, '[{"label":"Buzz","isCorrect":false},{"label":"Woody","isCorrect":true},{"label":"Rex","isCorrect":false},{"label":"Hamm","isCorrect":false}]'::jsonb, NULL, NULL, 'Woody is the cowboy doll and the leader of the toys in Andy''s room in "Toy Story."'),
(NULL, 'mc', 'What colour spots does the character Bluey have?', 'pop_culture', '5_6', 'medium', true, '[{"label":"Bluey has no spots","isCorrect":true},{"label":"White spots","isCorrect":false},{"label":"Red spots","isCorrect":false},{"label":"Yellow spots","isCorrect":false}]'::jsonb, NULL, NULL, 'Bluey is a blue heeler puppy — blue heelers have a speckled coat, but Bluey herself is a solid blue colour with no spots in the cartoon.'),
(NULL, 'mc', 'In "Cars," what is Lightning McQueen''s racing number?', 'pop_culture', '5_6', 'medium', true, '[{"label":"86","isCorrect":false},{"label":"95","isCorrect":true},{"label":"12","isCorrect":false},{"label":"7","isCorrect":false}]'::jsonb, NULL, NULL, 'Lightning McQueen races with the number 95 on his side in the Pixar movie "Cars."'),
(NULL, 'mc', 'Which Disney princess has very long magical hair?', 'pop_culture', '5_6', 'medium', true, '[{"label":"Cinderella","isCorrect":false},{"label":"Moana","isCorrect":false},{"label":"Rapunzel","isCorrect":true},{"label":"Aurora","isCorrect":false}]'::jsonb, NULL, NULL, 'Rapunzel from "Tangled" has incredibly long magical golden hair — about 70 feet long!'),

-- age_band: 5_6 | difficulty: hard
(NULL, 'mc', 'What is the name of the fairy who helps Peter Pan fly?', 'pop_culture', '5_6', 'hard', true, '[{"label":"Silvermist","isCorrect":false},{"label":"Tinker Bell","isCorrect":true},{"label":"Rosetta","isCorrect":false},{"label":"Iridessa","isCorrect":false}]'::jsonb, NULL, NULL, 'Tinker Bell is the tiny fairy who sprinkles pixie dust so that Peter Pan and the children can fly to Neverland.'),
(NULL, 'mc', 'In "Dumbo," what is special about the elephant that lets him fly?', 'pop_culture', '5_6', 'hard', true, '[{"label":"His tail","isCorrect":false},{"label":"His trunk","isCorrect":false},{"label":"His big ears","isCorrect":true},{"label":"His hat","isCorrect":false}]'::jsonb, NULL, NULL, 'Dumbo uses his oversized ears like wings to fly — they act as a pair of sails that lift him into the air.'),
(NULL, 'mc', 'What colour is the Ugly Duckling at the start of his story?', 'pop_culture', '5_6', 'hard', true, '[{"label":"White","isCorrect":false},{"label":"Yellow","isCorrect":false},{"label":"Grey","isCorrect":true},{"label":"Black","isCorrect":false}]'::jsonb, NULL, NULL, 'The Ugly Duckling is grey and plain-looking compared to the yellow ducklings, but later grows into a beautiful white swan.'),
(NULL, 'mc', 'In the nursery rhyme, what did Jack and Jill go up the hill to fetch?', 'pop_culture', '5_6', 'hard', true, '[{"label":"Apples","isCorrect":false},{"label":"A pail of water","isCorrect":true},{"label":"Some flowers","isCorrect":false},{"label":"A lost kitten","isCorrect":false}]'::jsonb, NULL, NULL, '"Jack and Jill went up the hill to fetch a pail of water" — it''s one of the oldest English nursery rhymes.'),
(NULL, 'mc', 'In "Snow White," how many dwarfs are there?', 'pop_culture', '5_6', 'hard', true, '[{"label":"Five","isCorrect":false},{"label":"Six","isCorrect":false},{"label":"Seven","isCorrect":true},{"label":"Eight","isCorrect":false}]'::jsonb, NULL, NULL, 'Snow White lives with seven dwarfs: Doc, Grumpy, Happy, Sleepy, Bashful, Sneezy, and Dopey.'),

-- age_band: 7_8 | difficulty: easy
(NULL, 'mc', 'What school does Harry Potter attend?', 'pop_culture', '7_8', 'easy', true, '[{"label":"Narnia Academy","isCorrect":false},{"label":"Hogwarts","isCorrect":true},{"label":"Beauxbatons","isCorrect":false},{"label":"Xavier''s School","isCorrect":false}]'::jsonb, NULL, NULL, 'Harry Potter attends Hogwarts School of Witchcraft and Wizardry, where he learns to cast spells and makes lifelong friends.'),
(NULL, 'mc', 'What type of creature is Pikachu in Pokémon?', 'pop_culture', '7_8', 'easy', true, '[{"label":"Fire-type","isCorrect":false},{"label":"Water-type","isCorrect":false},{"label":"Electric-type","isCorrect":true},{"label":"Grass-type","isCorrect":false}]'::jsonb, NULL, NULL, 'Pikachu is an Electric-type Pokémon known for its thunderbolt attack and its friendship with Ash Ketchum.'),
(NULL, 'mc', 'In Minecraft, what do you need to destroy to win the game?', 'pop_culture', '7_8', 'easy', true, '[{"label":"The Wither","isCorrect":false},{"label":"The Ender Dragon","isCorrect":true},{"label":"A Creeper","isCorrect":false},{"label":"The Elder Guardian","isCorrect":false}]'::jsonb, NULL, NULL, 'The Ender Dragon is the final boss of Minecraft. Defeating it triggers the end credits and counts as completing the main game.'),
(NULL, 'mc', 'Which Avenger is known as the "Genius, Billionaire, Playboy, Philanthropist"?', 'pop_culture', '7_8', 'easy', true, '[{"label":"Captain America","isCorrect":false},{"label":"Thor","isCorrect":false},{"label":"Iron Man","isCorrect":true},{"label":"Hulk","isCorrect":false}]'::jsonb, NULL, NULL, 'Tony Stark (Iron Man) describes himself as a "genius, billionaire, playboy, philanthropist" in the first Avengers movie.'),
(NULL, 'mc', 'What is the name of the friendly ghost in the classic cartoon?', 'pop_culture', '7_8', 'easy', true, '[{"label":"Slimer","isCorrect":false},{"label":"Casper","isCorrect":true},{"label":"Boo","isCorrect":false},{"label":"Ghostly","isCorrect":false}]'::jsonb, NULL, NULL, 'Casper the Friendly Ghost is a classic cartoon character who just wants to make friends despite being a ghost.'),

-- age_band: 7_8 | difficulty: medium
(NULL, 'mc', 'In Harry Potter, what house is Harry sorted into?', 'pop_culture', '7_8', 'medium', true, '[{"label":"Slytherin","isCorrect":false},{"label":"Ravenclaw","isCorrect":false},{"label":"Hufflepuff","isCorrect":false},{"label":"Gryffindor","isCorrect":true}]'::jsonb, NULL, NULL, 'Harry Potter is sorted into Gryffindor, the house known for bravery and courage, by the magical Sorting Hat.'),
(NULL, 'mc', 'What are the three starter Pokémon types in the original Pokémon games?', 'pop_culture', '7_8', 'medium', true, '[{"label":"Fire, Water, Electric","isCorrect":false},{"label":"Grass, Fire, Water","isCorrect":true},{"label":"Normal, Fire, Grass","isCorrect":false},{"label":"Psychic, Water, Fire","isCorrect":false}]'::jsonb, NULL, NULL, 'In the original Pokémon Red and Blue games, you choose between Bulbasaur (Grass), Charmander (Fire), and Squirtle (Water).'),
(NULL, 'mc', 'In Minecraft, which material is the strongest for tools and armour?', 'pop_culture', '7_8', 'medium', true, '[{"label":"Gold","isCorrect":false},{"label":"Iron","isCorrect":false},{"label":"Diamond","isCorrect":true},{"label":"Stone","isCorrect":false}]'::jsonb, NULL, NULL, 'Diamond tools and armour are the strongest in vanilla Minecraft — though Netherite can upgrade them further in newer versions.'),
(NULL, 'mc', 'What is the name of Spider-Man''s alter ego?', 'pop_culture', '7_8', 'medium', true, '[{"label":"Bruce Banner","isCorrect":false},{"label":"Peter Parker","isCorrect":true},{"label":"Steve Rogers","isCorrect":false},{"label":"Tony Stark","isCorrect":false}]'::jsonb, NULL, NULL, 'Spider-Man''s real name is Peter Parker. He got his powers after being bitten by a radioactive spider.'),
(NULL, 'mc', 'In "The Lion, the Witch and the Wardrobe," what world do the children enter through the wardrobe?', 'pop_culture', '7_8', 'medium', true, '[{"label":"Middle-earth","isCorrect":false},{"label":"Neverland","isCorrect":false},{"label":"Narnia","isCorrect":true},{"label":"Wonderland","isCorrect":false}]'::jsonb, NULL, NULL, 'The four Pevensie children step through a magical wardrobe and discover the land of Narnia in C.S. Lewis''s classic story.'),

-- age_band: 7_8 | difficulty: hard
(NULL, 'mc', 'What is the name of the invisibility cloak''s original owner before Harry Potter?', 'pop_culture', '7_8', 'hard', true, '[{"label":"Albus Dumbledore","isCorrect":false},{"label":"Ignotus Peverell","isCorrect":true},{"label":"Godric Gryffindor","isCorrect":false},{"label":"James Potter","isCorrect":false}]'::jsonb, NULL, NULL, 'The cloak originally belonged to Ignotus Peverell, one of the three brothers in the "Tale of the Three Brothers." It passed down through his family to Harry.'),
(NULL, 'mc', 'How many Gym Badges must a trainer collect before challenging the Pokémon League in Kanto?', 'pop_culture', '7_8', 'hard', true, '[{"label":"6","isCorrect":false},{"label":"10","isCorrect":false},{"label":"8","isCorrect":true},{"label":"4","isCorrect":false}]'::jsonb, NULL, NULL, 'Trainers must collect all 8 Gym Badges in the Kanto region to qualify for the Pokémon League at Indigo Plateau.'),
(NULL, 'mc', 'In "Diary of a Wimpy Kid," what is Greg Heffley''s older brother''s name?', 'pop_culture', '7_8', 'hard', true, '[{"label":"Manny","isCorrect":false},{"label":"Rowley","isCorrect":false},{"label":"Rodrick","isCorrect":true},{"label":"Fregley","isCorrect":false}]'::jsonb, NULL, NULL, 'Rodrick is Greg''s older brother who plays in a band called Löded Diper and loves to tease Greg.'),
(NULL, 'mc', 'In the Marvel universe, what stone does Thanos put in the middle of the Infinity Gauntlet?', 'pop_culture', '7_8', 'hard', true, '[{"label":"Space Stone","isCorrect":false},{"label":"Time Stone","isCorrect":false},{"label":"Reality Stone","isCorrect":false},{"label":"Mind Stone","isCorrect":true}]'::jsonb, NULL, NULL, 'The Mind Stone (yellow) sits in the centre of the Gauntlet. It was originally embedded in Vision''s forehead before Thanos took it.'),
(NULL, 'mc', 'In "Matilda" by Roald Dahl, what special power does Matilda develop?', 'pop_culture', '7_8', 'hard', true, '[{"label":"Invisibility","isCorrect":false},{"label":"Flying","isCorrect":false},{"label":"Telekinesis","isCorrect":true},{"label":"Mind reading","isCorrect":false}]'::jsonb, NULL, NULL, 'Matilda develops telekinesis — the ability to move objects with her mind — as a result of her extraordinary intelligence being left untapped.'),

-- age_band: 9_10 | difficulty: easy
(NULL, 'mc', 'Which book series features a girl named Katniss Everdeen?', 'pop_culture', '9_10', 'easy', true, '[{"label":"Divergent","isCorrect":false},{"label":"The Hunger Games","isCorrect":true},{"label":"The Maze Runner","isCorrect":false},{"label":"Percy Jackson","isCorrect":false}]'::jsonb, NULL, NULL, '"The Hunger Games" by Suzanne Collins follows Katniss Everdeen, a teenage girl who volunteers to compete in a deadly televised competition.'),
(NULL, 'mc', 'What is the name of the main character in "Percy Jackson and the Olympians"?', 'pop_culture', '9_10', 'easy', true, '[{"label":"Jason Grace","isCorrect":false},{"label":"Nico di Angelo","isCorrect":false},{"label":"Percy Jackson","isCorrect":true},{"label":"Grover Underwood","isCorrect":false}]'::jsonb, NULL, NULL, 'Percy Jackson is the 12-year-old son of Poseidon who discovers he is a demigod and goes on quests in Rick Riordan''s series.'),
(NULL, 'mc', 'In "Minecraft," what dimension do you travel to using a Nether Portal?', 'pop_culture', '9_10', 'easy', true, '[{"label":"The End","isCorrect":false},{"label":"The Nether","isCorrect":true},{"label":"The Aether","isCorrect":false},{"label":"The Deep Dark","isCorrect":false}]'::jsonb, NULL, NULL, 'A Nether Portal (made of obsidian) transports players to the Nether, a dangerous fiery dimension filled with unique mobs and resources.'),
(NULL, 'mc', 'Which film franchise features the character Hermione Granger?', 'pop_culture', '9_10', 'easy', true, '[{"label":"The Chronicles of Narnia","isCorrect":false},{"label":"Harry Potter","isCorrect":true},{"label":"Lord of the Rings","isCorrect":false},{"label":"Fantastic Beasts","isCorrect":false}]'::jsonb, NULL, NULL, 'Hermione Granger is one of Harry Potter''s best friends, known for her intelligence and magical skill throughout the Harry Potter series.'),
(NULL, 'mc', 'In the game "Among Us," what is the goal of the Impostors?', 'pop_culture', '9_10', 'easy', true, '[{"label":"Complete tasks faster than Crewmates","isCorrect":false},{"label":"Sabotage and eliminate Crewmates","isCorrect":true},{"label":"Collect all coloured gems","isCorrect":false},{"label":"Win mini-games","isCorrect":false}]'::jsonb, NULL, NULL, 'Impostors in Among Us must sabotage the ship and secretly eliminate Crewmates without being caught and voted off.'),

-- age_band: 9_10 | difficulty: medium
(NULL, 'mc', 'In "The Hunger Games," what district is Katniss from?', 'pop_culture', '9_10', 'medium', true, '[{"label":"District 1","isCorrect":false},{"label":"District 4","isCorrect":false},{"label":"District 12","isCorrect":true},{"label":"District 7","isCorrect":false}]'::jsonb, NULL, NULL, 'Katniss Everdeen is from District 12, the coal-mining district of Panem, which is one of the poorest districts.'),
(NULL, 'mc', 'Which Greek god is Percy Jackson''s father?', 'pop_culture', '9_10', 'medium', true, '[{"label":"Zeus","isCorrect":false},{"label":"Hades","isCorrect":false},{"label":"Poseidon","isCorrect":true},{"label":"Ares","isCorrect":false}]'::jsonb, NULL, NULL, 'Percy Jackson is the son of Poseidon, the Greek god of the sea, which gives Percy the ability to control water and breathe underwater.'),
(NULL, 'mc', 'In "Stranger Things," what is the name of the parallel dimension?', 'pop_culture', '9_10', 'medium', true, '[{"label":"The Shadow Realm","isCorrect":false},{"label":"The Upside Down","isCorrect":true},{"label":"The Dark Side","isCorrect":false},{"label":"The Mirror World","isCorrect":false}]'::jsonb, NULL, NULL, 'The Upside Down is a dark, dangerous parallel dimension that mirrors the real world and is home to terrifying creatures in "Stranger Things."'),
(NULL, 'mc', 'What is the name of the virtual world in the book and film "Ready Player One"?', 'pop_culture', '9_10', 'medium', true, '[{"label":"The Grid","isCorrect":false},{"label":"The Matrix","isCorrect":false},{"label":"The OASIS","isCorrect":true},{"label":"The Metaverse","isCorrect":false}]'::jsonb, NULL, NULL, 'The OASIS is a massive virtual reality world in "Ready Player One" where people spend most of their lives. Players search it for Easter eggs left by its creator.'),
(NULL, 'mc', 'In "Roblox," what is the in-game currency called?', 'pop_culture', '9_10', 'medium', true, '[{"label":"Gems","isCorrect":false},{"label":"Robux","isCorrect":true},{"label":"Coins","isCorrect":false},{"label":"Credits","isCorrect":false}]'::jsonb, NULL, NULL, 'Robux is the virtual currency used on the Roblox platform to buy avatar items, game passes, and access premium games.'),

-- age_band: 9_10 | difficulty: hard
(NULL, 'mc', 'In "The Hobbit" by J.R.R. Tolkien, what is the name of the dragon who guards the treasure?', 'pop_culture', '9_10', 'hard', true, '[{"label":"Ancalagon","isCorrect":false},{"label":"Glaurung","isCorrect":false},{"label":"Smaug","isCorrect":true},{"label":"Vermithrax","isCorrect":false}]'::jsonb, NULL, NULL, 'Smaug is the enormous, greedy dragon who took over the Lonely Mountain and hoards the dwarves'' treasure. Bilbo must outsmart him.'),
(NULL, 'mc', 'Which author wrote "The Maze Runner" series?', 'pop_culture', '9_10', 'hard', true, '[{"label":"Suzanne Collins","isCorrect":false},{"label":"James Dashner","isCorrect":true},{"label":"Veronica Roth","isCorrect":false},{"label":"Rick Riordan","isCorrect":false}]'::jsonb, NULL, NULL, 'James Dashner wrote "The Maze Runner" series, which follows Thomas and a group of teenagers trapped in a mysterious maze.'),
(NULL, 'mc', 'In the video game "Zelda: Breath of the Wild," what is the name of the ancient evil that Link must defeat?', 'pop_culture', '9_10', 'hard', true, '[{"label":"Ganon","isCorrect":false},{"label":"Calamity Ganon","isCorrect":true},{"label":"Demise","isCorrect":false},{"label":"Majora","isCorrect":false}]'::jsonb, NULL, NULL, 'Calamity Ganon is the main antagonist in "Breath of the Wild." It has taken over Hyrule Castle and Link must defeat it to free Princess Zelda.'),
(NULL, 'mc', 'In "Star Wars," what order did Emperor Palpatine give to destroy the Jedi?', 'pop_culture', '9_10', 'hard', true, '[{"label":"Order 65","isCorrect":false},{"label":"Order 37","isCorrect":false},{"label":"Order 66","isCorrect":true},{"label":"Order 99","isCorrect":false}]'::jsonb, NULL, NULL, 'Order 66 was the secret command that turned the clone troopers against the Jedi, nearly wiping out the entire Jedi Order.'),
(NULL, 'mc', 'In "Fortnite," what is the name of the storm that shrinks the play area?', 'pop_culture', '9_10', 'hard', true, '[{"label":"The Blizzard","isCorrect":false},{"label":"The Storm","isCorrect":true},{"label":"The Eye","isCorrect":false},{"label":"The Surge","isCorrect":false}]'::jsonb, NULL, NULL, 'In Fortnite, "The Storm" is the circle that gradually shrinks the safe zone, forcing all players together and eliminating anyone caught outside it.'),

-- age_band: 11_12 | difficulty: easy
(NULL, 'mc', 'Which novel begins with the line "It was the best of times, it was the worst of times"?', 'pop_culture', '11_12', 'easy', true, '[{"label":"Great Expectations","isCorrect":false},{"label":"Oliver Twist","isCorrect":false},{"label":"A Tale of Two Cities","isCorrect":true},{"label":"David Copperfield","isCorrect":false}]'::jsonb, NULL, NULL, '"A Tale of Two Cities" by Charles Dickens opens with this famous line contrasting the French Revolution''s hope and terror.'),
(NULL, 'mc', 'What is the highest-grossing film franchise of all time?', 'pop_culture', '11_12', 'easy', true, '[{"label":"Harry Potter","isCorrect":false},{"label":"Star Wars","isCorrect":false},{"label":"Marvel Cinematic Universe","isCorrect":true},{"label":"James Bond","isCorrect":false}]'::jsonb, NULL, NULL, 'The Marvel Cinematic Universe (MCU) is the highest-grossing film franchise globally, with Avengers: Endgame being one of the top-earning films ever.'),
(NULL, 'mc', 'In competitive gaming (esports), what does "FPS" stand for?', 'pop_culture', '11_12', 'easy', true, '[{"label":"Final Player Score","isCorrect":false},{"label":"First Person Shooter","isCorrect":true},{"label":"Fast Play Strategy","isCorrect":false},{"label":"Full Pixel Screen","isCorrect":false}]'::jsonb, NULL, NULL, 'FPS stands for First Person Shooter — a genre of game where you see through the character''s eyes, like Call of Duty or Valorant.'),
(NULL, 'mc', 'Who wrote the dystopian novel "1984"?', 'pop_culture', '11_12', 'easy', true, '[{"label":"Aldous Huxley","isCorrect":false},{"label":"Ray Bradbury","isCorrect":false},{"label":"George Orwell","isCorrect":true},{"label":"H.G. Wells","isCorrect":false}]'::jsonb, NULL, NULL, 'George Orwell wrote "1984" in 1949. It depicts a totalitarian society ruled by "Big Brother" and introduced terms like "doublethink" and "Newspeak."'),
(NULL, 'mc', 'In film, what does CGI stand for?', 'pop_culture', '11_12', 'easy', true, '[{"label":"Colour Grading Interface","isCorrect":false},{"label":"Computer Generated Imagery","isCorrect":true},{"label":"Cinema Graphics Integration","isCorrect":false},{"label":"Creative Graphics Input","isCorrect":false}]'::jsonb, NULL, NULL, 'CGI stands for Computer Generated Imagery — the digital visual effects technology used to create creatures, environments, and action sequences in modern films.'),

-- age_band: 11_12 | difficulty: medium
(NULL, 'mc', 'In "Lord of the Flies," why do the boys end up on the island?', 'pop_culture', '11_12', 'medium', true, '[{"label":"They were on a school camping trip","isCorrect":false},{"label":"Their plane was shot down during wartime","isCorrect":true},{"label":"They were shipwrecked at sea","isCorrect":false},{"label":"They ran away from home together","isCorrect":false}]'::jsonb, NULL, NULL, 'In William Golding''s "Lord of the Flies," a group of British boys are stranded on an island after their evacuation plane is shot down during a wartime conflict.'),
(NULL, 'mc', 'What storytelling technique is used when the story reveals events that happened before the current timeline?', 'pop_culture', '11_12', 'medium', true, '[{"label":"Foreshadowing","isCorrect":false},{"label":"Flashback","isCorrect":true},{"label":"Cliffhanger","isCorrect":false},{"label":"In media res","isCorrect":false}]'::jsonb, NULL, NULL, 'A flashback is a narrative device that interrupts the present story to show earlier events. Films like "The Godfather Part II" use it extensively.'),
(NULL, 'mc', 'The first modern Olympic Games were held in which city?', 'pop_culture', '11_12', 'medium', true, '[{"label":"Paris","isCorrect":false},{"label":"London","isCorrect":false},{"label":"Athens","isCorrect":true},{"label":"Rome","isCorrect":false}]'::jsonb, NULL, NULL, 'The first modern Olympic Games were held in Athens, Greece in 1896. The ancient Olympics were also held in Greece, at Olympia.'),
(NULL, 'mc', 'In gaming, what does "RPG" stand for?', 'pop_culture', '11_12', 'medium', true, '[{"label":"Rapid Play Game","isCorrect":false},{"label":"Role Playing Game","isCorrect":true},{"label":"Real Player Gaming","isCorrect":false},{"label":"Ranked Position Game","isCorrect":false}]'::jsonb, NULL, NULL, 'RPG stands for Role Playing Game — a genre where players take on the role of a character and make choices that affect the story, like Final Fantasy or Skyrim.'),
(NULL, 'mc', 'Which author created the fictional detective Sherlock Holmes?', 'pop_culture', '11_12', 'medium', true, '[{"label":"Agatha Christie","isCorrect":false},{"label":"Edgar Allan Poe","isCorrect":false},{"label":"Arthur Conan Doyle","isCorrect":true},{"label":"G.K. Chesterton","isCorrect":false}]'::jsonb, NULL, NULL, 'Sir Arthur Conan Doyle created Sherlock Holmes in 1887. Holmes first appeared in "A Study in Scarlet" and became one of fiction''s most famous detectives.'),

-- age_band: 11_12 | difficulty: hard
(NULL, 'mc', 'What literary device is used when an author gives hints about what will happen later in the story?', 'pop_culture', '11_12', 'hard', true, '[{"label":"Allegory","isCorrect":false},{"label":"Irony","isCorrect":false},{"label":"Foreshadowing","isCorrect":true},{"label":"Anachronism","isCorrect":false}]'::jsonb, NULL, NULL, 'Foreshadowing is when an author plants subtle clues about future events. Shakespeare used it constantly — for example, when the witches hint at Macbeth''s fate early on.'),
(NULL, 'mc', 'The film "2001: A Space Odyssey" was directed by which filmmaker?', 'pop_culture', '11_12', 'hard', true, '[{"label":"Steven Spielberg","isCorrect":false},{"label":"Stanley Kubrick","isCorrect":true},{"label":"Ridley Scott","isCorrect":false},{"label":"George Lucas","isCorrect":false}]'::jsonb, NULL, NULL, 'Stanley Kubrick directed "2001: A Space Odyssey" (1968), a groundbreaking sci-fi film renowned for its realistic depiction of space and its mysterious ending.'),
(NULL, 'mc', 'In speedrunning, what does "any%" mean?', 'pop_culture', '11_12', 'hard', true, '[{"label":"Completing the game with 100% of items","isCorrect":false},{"label":"Finishing the game as fast as possible using any means","isCorrect":true},{"label":"Winning without taking any damage","isCorrect":false},{"label":"Collecting any percentage of collectibles","isCorrect":false}]'::jsonb, NULL, NULL, '"Any%" speedruns mean finishing the game as fast as possible using any glitches or shortcuts available — the goal is simply to reach the credits in the shortest time.'),
(NULL, 'mc', 'In "Animal Farm" by George Orwell, the pigs taking control of the farm is an allegory for what real historical event?', 'pop_culture', '11_12', 'hard', true, '[{"label":"World War I","isCorrect":false},{"label":"The French Revolution","isCorrect":false},{"label":"The Russian Revolution","isCorrect":true},{"label":"The American Civil War","isCorrect":false}]'::jsonb, NULL, NULL, '"Animal Farm" is an allegory for the Russian Revolution and the rise of Stalinism. Napoleon the pig represents Joseph Stalin, and the farm represents Soviet Russia.'),
(NULL, 'mc', 'What is the term for when a film breaks the fourth wall and a character speaks directly to the audience?', 'pop_culture', '11_12', 'hard', true, '[{"label":"Soliloquy","isCorrect":false},{"label":"Direct address","isCorrect":true},{"label":"Aside","isCorrect":false},{"label":"Monologue","isCorrect":false}]'::jsonb, NULL, NULL, 'Direct address (also called breaking the fourth wall) is when a character looks at the camera and speaks to the audience — used memorably in "Ferris Bueller''s Day Off" and "Deadpool."'),

-- ============================================================
-- THEME: technology
-- ============================================================

-- age_band: 5_6 | difficulty: easy
(NULL, 'mc', 'What do you use to talk to someone far away on a phone?', 'technology', '5_6', 'easy', true, '[{"label":"The screen","isCorrect":false},{"label":"Your voice","isCorrect":true},{"label":"The camera","isCorrect":false},{"label":"The battery","isCorrect":false}]'::jsonb, NULL, NULL, 'You speak into the microphone on a phone and your voice travels as a signal so the other person can hear you, no matter how far away they are.'),
(NULL, 'mc', 'What is a tablet used for?', 'technology', '5_6', 'easy', true, '[{"label":"Eating meals","isCorrect":false},{"label":"Playing games, watching videos, and learning","isCorrect":true},{"label":"Keeping food cold","isCorrect":false},{"label":"Making toast","isCorrect":false}]'::jsonb, NULL, NULL, 'A tablet is a portable touchscreen computer you can use to play games, watch videos, read books, and learn new things.'),
(NULL, 'mc', 'What does a camera do?', 'technology', '5_6', 'easy', true, '[{"label":"Plays music","isCorrect":false},{"label":"Takes pictures","isCorrect":true},{"label":"Sends emails","isCorrect":false},{"label":"Charges your phone","isCorrect":false}]'::jsonb, NULL, NULL, 'A camera captures light to take photos or record videos so you can remember special moments.'),
(NULL, 'mc', 'What does a television do?', 'technology', '5_6', 'easy', true, '[{"label":"Washes your clothes","isCorrect":false},{"label":"Shows pictures and sound so you can watch shows","isCorrect":true},{"label":"Cooks your dinner","isCorrect":false},{"label":"Charges your toys","isCorrect":false}]'::jsonb, NULL, NULL, 'A television displays moving pictures and sound, allowing you to watch cartoons, movies, and educational programmes.'),
(NULL, 'mc', 'Which of these is a device you can use to listen to music?', 'technology', '5_6', 'easy', true, '[{"label":"A refrigerator","isCorrect":false},{"label":"Headphones","isCorrect":true},{"label":"A lamp","isCorrect":false},{"label":"A clock","isCorrect":false}]'::jsonb, NULL, NULL, 'Headphones go over or in your ears and let you listen to music, podcasts, or audio from a phone or tablet.'),

-- age_band: 5_6 | difficulty: medium
(NULL, 'mc', 'What do you press on a keyboard to start a new line when typing?', 'technology', '5_6', 'medium', true, '[{"label":"Space bar","isCorrect":false},{"label":"Enter key","isCorrect":true},{"label":"Delete key","isCorrect":false},{"label":"Shift key","isCorrect":false}]'::jsonb, NULL, NULL, 'Pressing the Enter key (also called Return) moves the cursor to a new line when you are typing on a keyboard.'),
(NULL, 'mc', 'What is the internet?', 'technology', '5_6', 'medium', true, '[{"label":"A giant library of information and connections around the world","isCorrect":true},{"label":"A type of TV remote","isCorrect":false},{"label":"The back of a computer","isCorrect":false},{"label":"A game you play outside","isCorrect":false}]'::jsonb, NULL, NULL, 'The internet is a huge network that connects computers all around the world, letting people share information, videos, and messages.'),
(NULL, 'mc', 'What does a printer do?', 'technology', '5_6', 'medium', true, '[{"label":"Takes pictures","isCorrect":false},{"label":"Puts words and pictures from a computer onto paper","isCorrect":true},{"label":"Stores your files","isCorrect":false},{"label":"Plays videos","isCorrect":false}]'::jsonb, NULL, NULL, 'A printer receives information from a computer and uses ink to put words and images onto paper, creating a physical copy.'),
(NULL, 'mc', 'What is a password used for?', 'technology', '5_6', 'medium', true, '[{"label":"Making your screen brighter","isCorrect":false},{"label":"Keeping your accounts safe so only you can log in","isCorrect":true},{"label":"Charging the battery faster","isCorrect":false},{"label":"Connecting to Wi-Fi","isCorrect":false}]'::jsonb, NULL, NULL, 'A password is a secret word or set of characters that protects your accounts. Only people who know the password can log in.'),
(NULL, 'mc', 'What does "Wi-Fi" let your device do?', 'technology', '5_6', 'medium', true, '[{"label":"Play music louder","isCorrect":false},{"label":"Connect to the internet without wires","isCorrect":true},{"label":"Save battery power","isCorrect":false},{"label":"Turn on the screen","isCorrect":false}]'::jsonb, NULL, NULL, 'Wi-Fi is a wireless signal that lets your phone, tablet, or computer connect to the internet without needing any cables.'),

-- age_band: 5_6 | difficulty: hard
(NULL, 'mc', 'What is a computer mouse used for?', 'technology', '5_6', 'hard', true, '[{"label":"To move the cursor and click on things on the screen","isCorrect":true},{"label":"To type letters","isCorrect":false},{"label":"To print documents","isCorrect":false},{"label":"To store photos","isCorrect":false}]'::jsonb, NULL, NULL, 'A computer mouse is a pointing device you move on a surface to control the cursor on the screen. You click its buttons to select or open things.'),
(NULL, 'mc', 'Which of these is NOT a type of computer?', 'technology', '5_6', 'hard', true, '[{"label":"Laptop","isCorrect":false},{"label":"Desktop","isCorrect":false},{"label":"Tablet","isCorrect":false},{"label":"Toaster","isCorrect":true}]'::jsonb, NULL, NULL, 'A toaster is a kitchen appliance — it is not a computer! Laptops, desktops, and tablets are all types of computers.'),
(NULL, 'mc', 'What does a robot do that makes it different from a regular toy?', 'technology', '5_6', 'hard', true, '[{"label":"It is made of plastic","isCorrect":false},{"label":"It can follow instructions and move on its own","isCorrect":true},{"label":"It needs batteries","isCorrect":false},{"label":"It makes noise","isCorrect":false}]'::jsonb, NULL, NULL, 'Robots are machines that can be programmed to follow instructions and perform tasks automatically — they can sense their environment and respond to it.'),
(NULL, 'mc', 'What is the name for the small pictures on a phone or tablet screen that open apps?', 'technology', '5_6', 'hard', true, '[{"label":"Pixels","isCorrect":false},{"label":"Icons","isCorrect":true},{"label":"Buttons","isCorrect":false},{"label":"Tabs","isCorrect":false}]'::jsonb, NULL, NULL, 'Icons are small images on a touchscreen or computer desktop that represent apps or files. You tap or click them to open the app.'),
(NULL, 'mc', 'What powers most portable devices like phones and tablets?', 'technology', '5_6', 'hard', true, '[{"label":"Solar panels","isCorrect":false},{"label":"A rechargeable battery","isCorrect":true},{"label":"Petrol","isCorrect":false},{"label":"Water","isCorrect":false}]'::jsonb, NULL, NULL, 'Phones and tablets use rechargeable batteries that store electrical energy. When the battery runs low, you plug the device into a charger to refill it.'),

-- age_band: 7_8 | difficulty: easy
(NULL, 'mc', 'What does "www" stand for at the start of a website address?', 'technology', '7_8', 'easy', true, '[{"label":"World Wide Web","isCorrect":true},{"label":"Worldwide Wireless Web","isCorrect":false},{"label":"Web With Wires","isCorrect":false},{"label":"Working Wide Web","isCorrect":false}]'::jsonb, NULL, NULL, 'WWW stands for World Wide Web — the global system of linked web pages and websites that you access through the internet.'),
(NULL, 'mc', 'What does a search engine like Google do?', 'technology', '7_8', 'easy', true, '[{"label":"Sends your emails","isCorrect":false},{"label":"Finds websites and information based on what you type","isCorrect":true},{"label":"Builds websites for you","isCorrect":false},{"label":"Stores your photos online","isCorrect":false}]'::jsonb, NULL, NULL, 'A search engine like Google crawls and indexes billions of web pages so that when you type a query, it can show you the most relevant results.'),
(NULL, 'mc', 'What is a "username"?', 'technology', '7_8', 'easy', true, '[{"label":"Your real name written backwards","isCorrect":false},{"label":"A name you choose to identify yourself online","isCorrect":true},{"label":"A secret code to unlock your phone","isCorrect":false},{"label":"The name of your Wi-Fi network","isCorrect":false}]'::jsonb, NULL, NULL, 'A username is the name you pick when you create an account. It identifies you online and can be different from your real name.'),
(NULL, 'mc', 'Which company made the iPhone?', 'technology', '7_8', 'easy', true, '[{"label":"Samsung","isCorrect":false},{"label":"Google","isCorrect":false},{"label":"Apple","isCorrect":true},{"label":"Microsoft","isCorrect":false}]'::jsonb, NULL, NULL, 'Apple Inc. created the iPhone, first released in 2007. Steve Jobs famously announced it as "an iPod, a phone, and an internet communicator."'),
(NULL, 'mc', 'What does "download" mean?', 'technology', '7_8', 'easy', true, '[{"label":"Deleting a file from your device","isCorrect":false},{"label":"Copying a file from the internet to your device","isCorrect":true},{"label":"Sending a file to someone else","isCorrect":false},{"label":"Printing a document","isCorrect":false}]'::jsonb, NULL, NULL, 'Downloading means copying data from the internet or another device onto your own device so you can use it offline or later.'),

-- age_band: 7_8 | difficulty: medium
(NULL, 'mc', 'What is an "app" short for?', 'technology', '7_8', 'medium', true, '[{"label":"Application","isCorrect":true},{"label":"Apparatus","isCorrect":false},{"label":"Appendix","isCorrect":false},{"label":"Appreciation","isCorrect":false}]'::jsonb, NULL, NULL, '"App" is short for "application" — a software program designed to perform a specific function on your phone, tablet, or computer.'),
(NULL, 'mc', 'What does "Bluetooth" technology allow devices to do?', 'technology', '7_8', 'medium', true, '[{"label":"Connect to the internet faster","isCorrect":false},{"label":"Communicate wirelessly over short distances","isCorrect":true},{"label":"Take better photos","isCorrect":false},{"label":"Charge without a cable","isCorrect":false}]'::jsonb, NULL, NULL, 'Bluetooth is a short-range wireless technology that lets devices like phones, speakers, and headphones connect and share data without cables.'),
(NULL, 'mc', 'What is the "cloud" in technology?', 'technology', '7_8', 'medium', true, '[{"label":"A type of computer screen","isCorrect":false},{"label":"Storage and services accessed over the internet, not on your device","isCorrect":true},{"label":"The Wi-Fi signal from your router","isCorrect":false},{"label":"The cooling fan inside a computer","isCorrect":false}]'::jsonb, NULL, NULL, 'The "cloud" refers to servers accessed via the internet where you can store files, run apps, and access services from any device, anywhere.'),
(NULL, 'mc', 'What does a QR code do when you scan it with a phone?', 'technology', '7_8', 'medium', true, '[{"label":"Takes a photo of your face","isCorrect":false},{"label":"Takes you to a website or shows information","isCorrect":true},{"label":"Charges your phone wirelessly","isCorrect":false},{"label":"Sends a text message","isCorrect":false}]'::jsonb, NULL, NULL, 'A QR code is a square barcode that stores information. When you scan it with your phone''s camera, it typically opens a website or displays a message.'),
(NULL, 'mc', 'In computing, what does "hardware" refer to?', 'technology', '7_8', 'medium', true, '[{"label":"The programs and apps on a computer","isCorrect":false},{"label":"The physical parts of a computer you can touch","isCorrect":true},{"label":"The internet connection","isCorrect":false},{"label":"The files stored on a device","isCorrect":false}]'::jsonb, NULL, NULL, 'Hardware refers to the physical components of a computer — things you can see and touch, like the screen, keyboard, mouse, and circuit board inside.'),

-- age_band: 7_8 | difficulty: hard
(NULL, 'mc', 'What is a "bug" in a computer program?', 'technology', '7_8', 'hard', true, '[{"label":"A virus that damages your files","isCorrect":false},{"label":"An error or mistake in the code that causes problems","isCorrect":true},{"label":"A type of computer game","isCorrect":false},{"label":"Extra storage space","isCorrect":false}]'::jsonb, NULL, NULL, 'A bug is an error in software code that causes the program to behave unexpectedly. The term originated from a real moth found in an early computer in 1947!'),
(NULL, 'mc', 'What is the main job of a computer''s CPU?', 'technology', '7_8', 'hard', true, '[{"label":"Store long-term data like photos and files","isCorrect":false},{"label":"Process instructions and carry out calculations","isCorrect":true},{"label":"Display images on the screen","isCorrect":false},{"label":"Connect to the internet","isCorrect":false}]'::jsonb, NULL, NULL, 'The CPU (Central Processing Unit) is the "brain" of the computer. It processes instructions from programs and carries out the calculations needed to run everything.'),
(NULL, 'mc', 'Which programming language uses blocks you snap together, designed for beginners?', 'technology', '7_8', 'hard', true, '[{"label":"Python","isCorrect":false},{"label":"Scratch","isCorrect":true},{"label":"JavaScript","isCorrect":false},{"label":"HTML","isCorrect":false}]'::jsonb, NULL, NULL, 'Scratch is a visual programming language developed at MIT where you drag and snap coloured code blocks together — perfect for beginners learning programming concepts.'),
(NULL, 'mc', 'What does GPS stand for?', 'technology', '7_8', 'hard', true, '[{"label":"Global Phone System","isCorrect":false},{"label":"General Positioning Satellite","isCorrect":false},{"label":"Global Positioning System","isCorrect":true},{"label":"Geographic Position Sensor","isCorrect":false}]'::jsonb, NULL, NULL, 'GPS stands for Global Positioning System — a network of satellites that sends signals to devices to pinpoint their exact location on Earth.'),
(NULL, 'mc', 'What does "software" mean in computing?', 'technology', '7_8', 'hard', true, '[{"label":"The outer case of a computer","isCorrect":false},{"label":"Programs and apps that tell the hardware what to do","isCorrect":true},{"label":"The screen and keyboard","isCorrect":false},{"label":"The internet connection","isCorrect":false}]'::jsonb, NULL, NULL, 'Software is the collection of programs, operating systems, and apps that run on hardware. Unlike hardware, you can''t physically touch software.'),

-- age_band: 9_10 | difficulty: easy
(NULL, 'mc', 'What language is primarily used to create the structure of web pages?', 'technology', '9_10', 'easy', true, '[{"label":"Python","isCorrect":false},{"label":"HTML","isCorrect":true},{"label":"Java","isCorrect":false},{"label":"CSS","isCorrect":false}]'::jsonb, NULL, NULL, 'HTML (HyperText Markup Language) is the standard language used to structure and organise the content of web pages, like headings, paragraphs, and images.'),
(NULL, 'mc', 'What does an algorithm do?', 'technology', '9_10', 'easy', true, '[{"label":"Stores data permanently","isCorrect":false},{"label":"Provides a set of step-by-step instructions to solve a problem","isCorrect":true},{"label":"Connects devices to the internet","isCorrect":false},{"label":"Displays graphics on screen","isCorrect":false}]'::jsonb, NULL, NULL, 'An algorithm is a set of step-by-step instructions for solving a problem or completing a task. Recipes and directions are everyday examples of algorithms.'),
(NULL, 'mc', 'What does RAM stand for in a computer?', 'technology', '9_10', 'easy', true, '[{"label":"Random Access Memory","isCorrect":true},{"label":"Rapid Application Mode","isCorrect":false},{"label":"Read And Modify","isCorrect":false},{"label":"Retained Audio Memory","isCorrect":false}]'::jsonb, NULL, NULL, 'RAM stands for Random Access Memory — it''s the short-term memory your computer uses to run programs. More RAM means your computer can handle more tasks at once.'),
(NULL, 'mc', 'What is the name for a series of instructions that a computer follows, written in a programming language?', 'technology', '9_10', 'easy', true, '[{"label":"Document","isCorrect":false},{"label":"Program","isCorrect":true},{"label":"Network","isCorrect":false},{"label":"Database","isCorrect":false}]'::jsonb, NULL, NULL, 'A program (also called software or code) is a set of instructions written in a programming language that tells a computer exactly what to do.'),
(NULL, 'mc', 'What is "open source" software?', 'technology', '9_10', 'easy', true, '[{"label":"Software that costs money to use","isCorrect":false},{"label":"Software whose source code anyone can view, modify, and share","isCorrect":true},{"label":"Software only for smartphones","isCorrect":false},{"label":"Software made by the government","isCorrect":false}]'::jsonb, NULL, NULL, 'Open source software has publicly available code that anyone can inspect, modify, and distribute. Examples include Linux, Firefox, and VLC media player.'),

-- age_band: 9_10 | difficulty: medium
(NULL, 'mc', 'In coding, what is a "loop"?', 'technology', '9_10', 'medium', true, '[{"label":"A type of wireless connection","isCorrect":false},{"label":"A section of code that repeats until a condition is met","isCorrect":true},{"label":"A way to store data in a list","isCorrect":false},{"label":"A tool to find bugs in code","isCorrect":false}]'::jsonb, NULL, NULL, 'A loop is a programming construct that repeats a block of code multiple times — either a set number of times (for loop) or until a condition is no longer true (while loop).'),
(NULL, 'mc', 'What is the difference between the internet and the World Wide Web?', 'technology', '9_10', 'medium', true, '[{"label":"They are exactly the same thing","isCorrect":false},{"label":"The internet is the network of computers; the Web is the websites on it","isCorrect":true},{"label":"The Web is the network; the internet is the collection of websites","isCorrect":false},{"label":"The internet is only for email; the Web is for websites","isCorrect":false}]'::jsonb, NULL, NULL, 'The internet is the global network of connected computers. The World Wide Web is just one service that runs on it — the system of interlinked web pages you browse.'),
(NULL, 'mc', 'What is a "variable" in programming?', 'technology', '9_10', 'medium', true, '[{"label":"A type of computer virus","isCorrect":false},{"label":"A named storage location that holds a value","isCorrect":true},{"label":"A network connection","isCorrect":false},{"label":"A bug in the code","isCorrect":false}]'::jsonb, NULL, NULL, 'A variable is like a labelled box in your program that stores a value (like a number or word). The value can change as the program runs — hence "variable."'),
(NULL, 'mc', 'What does a firewall do?', 'technology', '9_10', 'medium', true, '[{"label":"Speeds up your internet connection","isCorrect":false},{"label":"Monitors and controls incoming and outgoing network traffic for security","isCorrect":true},{"label":"Backs up your files","isCorrect":false},{"label":"Compresses video files","isCorrect":false}]'::jsonb, NULL, NULL, 'A firewall is a security system that monitors network traffic and blocks unauthorised or suspicious connections, protecting your device from hackers and malware.'),
(NULL, 'mc', 'What is "phishing"?', 'technology', '9_10', 'medium', true, '[{"label":"A way to speed up downloads","isCorrect":false},{"label":"A scam where criminals trick people into revealing personal information","isCorrect":true},{"label":"A type of computer game","isCorrect":false},{"label":"A method for compressing files","isCorrect":false}]'::jsonb, NULL, NULL, 'Phishing is when cybercriminals send fake emails or messages that look legitimate to trick people into sharing passwords, credit card numbers, or other private details.'),

-- age_band: 9_10 | difficulty: hard
(NULL, 'mc', 'In programming, what is a "function"?', 'technology', '9_10', 'hard', true, '[{"label":"A type of error in code","isCorrect":false},{"label":"A reusable block of code that performs a specific task","isCorrect":true},{"label":"A way to display images","isCorrect":false},{"label":"A connection between two computers","isCorrect":false}]'::jsonb, NULL, NULL, 'A function is a named, reusable block of code that performs a specific task. You can call a function as many times as you need rather than writing the same code repeatedly.'),
(NULL, 'mc', 'What does "binary" mean in computing?', 'technology', '9_10', 'hard', true, '[{"label":"Two computers connected together","isCorrect":false},{"label":"A number system using only 0s and 1s","isCorrect":true},{"label":"A type of data storage","isCorrect":false},{"label":"A programming language for beginners","isCorrect":false}]'::jsonb, NULL, NULL, 'Binary is a base-2 number system that uses only two digits: 0 and 1. All computer data — text, images, sound — is ultimately stored and processed as binary.'),
(NULL, 'mc', 'What is "encryption" used for?', 'technology', '9_10', 'hard', true, '[{"label":"Making files smaller","isCorrect":false},{"label":"Scrambling data so only authorised people can read it","isCorrect":true},{"label":"Speeding up a computer","isCorrect":false},{"label":"Finding errors in code","isCorrect":false}]'::jsonb, NULL, NULL, 'Encryption converts readable data into a scrambled format using a mathematical key. Only someone with the correct key can decrypt and read the original information.'),
(NULL, 'mc', 'What is the purpose of an "if statement" in programming?', 'technology', '9_10', 'hard', true, '[{"label":"To repeat a block of code","isCorrect":false},{"label":"To execute code only when a certain condition is true","isCorrect":true},{"label":"To define a new variable","isCorrect":false},{"label":"To display output on screen","isCorrect":false}]'::jsonb, NULL, NULL, 'An if statement checks whether a condition is true and only runs the code inside it when that condition is met — it gives programs the ability to make decisions.'),
(NULL, 'mc', 'What is the difference between a compiled and an interpreted programming language?', 'technology', '9_10', 'hard', true, '[{"label":"Compiled languages are slower; interpreted are faster","isCorrect":false},{"label":"Compiled languages are translated all at once; interpreted languages are translated line by line","isCorrect":true},{"label":"Compiled languages are older; interpreted languages are newer","isCorrect":false},{"label":"There is no meaningful difference","isCorrect":false}]'::jsonb, NULL, NULL, 'Compiled languages (like C) convert all code into machine code before running. Interpreted languages (like Python) translate and run code line by line as it executes.'),

-- age_band: 11_12 | difficulty: easy
(NULL, 'mc', 'Who is widely credited with inventing the World Wide Web?', 'technology', '11_12', 'easy', true, '[{"label":"Bill Gates","isCorrect":false},{"label":"Steve Jobs","isCorrect":false},{"label":"Tim Berners-Lee","isCorrect":true},{"label":"Mark Zuckerberg","isCorrect":false}]'::jsonb, NULL, NULL, 'Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN. He also created the first web browser and web server.'),
(NULL, 'mc', 'What programming language is most commonly used for data science and machine learning?', 'technology', '11_12', 'easy', true, '[{"label":"Java","isCorrect":false},{"label":"Python","isCorrect":true},{"label":"Swift","isCorrect":false},{"label":"Ruby","isCorrect":false}]'::jsonb, NULL, NULL, 'Python is the most popular language for data science and machine learning due to its simple syntax and powerful libraries like NumPy, Pandas, and TensorFlow.'),
(NULL, 'mc', 'What does "AI" stand for in technology?', 'technology', '11_12', 'easy', true, '[{"label":"Automated Interface","isCorrect":false},{"label":"Artificial Intelligence","isCorrect":true},{"label":"Advanced Internet","isCorrect":false},{"label":"Automatic Integration","isCorrect":false}]'::jsonb, NULL, NULL, 'AI stands for Artificial Intelligence — the simulation of human-like thinking and learning by computer systems, used in voice assistants, recommendation engines, and more.'),
(NULL, 'mc', 'What is "Moore''s Law"?', 'technology', '11_12', 'easy', true, '[{"label":"The rule that internet speeds double every year","isCorrect":false},{"label":"The observation that the number of transistors in chips doubles roughly every two years","isCorrect":true},{"label":"The law governing data privacy online","isCorrect":false},{"label":"The principle that all software has bugs","isCorrect":false}]'::jsonb, NULL, NULL, 'Moore''s Law, named after Intel co-founder Gordon Moore, observed that the number of transistors on a chip doubles roughly every two years, driving exponential growth in computing power.'),
(NULL, 'mc', 'What is a "database"?', 'technology', '11_12', 'easy', true, '[{"label":"A type of computer virus","isCorrect":false},{"label":"An organised collection of structured data stored electronically","isCorrect":true},{"label":"A wireless network protocol","isCorrect":false},{"label":"The physical memory inside a computer","isCorrect":false}]'::jsonb, NULL, NULL, 'A database is an organised collection of structured data, typically stored and accessed electronically. SQL databases like PostgreSQL and MySQL are widely used in websites and apps.'),

-- age_band: 11_12 | difficulty: medium
(NULL, 'mc', 'What is the difference between HTTP and HTTPS?', 'technology', '11_12', 'medium', true, '[{"label":"HTTPS is faster than HTTP","isCorrect":false},{"label":"HTTPS encrypts the connection for security; HTTP does not","isCorrect":true},{"label":"HTTP is for mobile; HTTPS is for desktop","isCorrect":false},{"label":"HTTPS is the older version of HTTP","isCorrect":false}]'::jsonb, NULL, NULL, 'HTTPS (HyperText Transfer Protocol Secure) adds SSL/TLS encryption to HTTP, meaning data between your browser and the server is scrambled and secure from eavesdroppers.'),
(NULL, 'mc', 'In computing, what is an "operating system"?', 'technology', '11_12', 'medium', true, '[{"label":"A program for editing documents","isCorrect":false},{"label":"The core software that manages computer hardware and runs other programs","isCorrect":true},{"label":"A type of database","isCorrect":false},{"label":"The physical processor inside a computer","isCorrect":false}]'::jsonb, NULL, NULL, 'An operating system (OS) is the fundamental software that manages computer hardware and provides a platform for other software. Examples include Windows, macOS, Linux, iOS, and Android.'),
(NULL, 'mc', 'What does "bandwidth" refer to in networking?', 'technology', '11_12', 'medium', true, '[{"label":"The physical width of a network cable","isCorrect":false},{"label":"The maximum amount of data that can be transmitted per second","isCorrect":true},{"label":"The number of devices on a network","isCorrect":false},{"label":"The distance a Wi-Fi signal can travel","isCorrect":false}]'::jsonb, NULL, NULL, 'Bandwidth is the maximum rate of data transfer across a network connection, usually measured in megabits per second (Mbps) or gigabits per second (Gbps).'),
(NULL, 'mc', 'What is "machine learning"?', 'technology', '11_12', 'medium', true, '[{"label":"Programming a robot to move","isCorrect":false},{"label":"Training computers to learn patterns from data and improve without explicit programming","isCorrect":true},{"label":"Building computer hardware","isCorrect":false},{"label":"Automating factory production","isCorrect":false}]'::jsonb, NULL, NULL, 'Machine learning is a branch of AI where algorithms learn from large datasets to make predictions or decisions. It powers things like spam filters, Netflix recommendations, and facial recognition.'),
(NULL, 'mc', 'What is the purpose of a "version control system" like Git?', 'technology', '11_12', 'medium', true, '[{"label":"To speed up code compilation","isCorrect":false},{"label":"To track changes to code over time and allow collaboration","isCorrect":true},{"label":"To protect code from viruses","isCorrect":false},{"label":"To convert code to binary","isCorrect":false}]'::jsonb, NULL, NULL, 'Git is a version control system that tracks every change made to code. It lets multiple developers collaborate, revert to earlier versions, and manage different branches of a project.'),

-- age_band: 11_12 | difficulty: hard
(NULL, 'mc', 'What is "Big O notation" used for in computer science?', 'technology', '11_12', 'hard', true, '[{"label":"Describing how much memory an algorithm uses","isCorrect":false},{"label":"Describing how an algorithm''s time or space requirements grow as input size increases","isCorrect":true},{"label":"Naming different types of programming languages","isCorrect":false},{"label":"Measuring internet bandwidth","isCorrect":false}]'::jsonb, NULL, NULL, 'Big O notation describes the efficiency of an algorithm — specifically how its time or memory requirements scale as the input grows. O(n) means linear growth; O(n²) means quadratic growth.'),
(NULL, 'mc', 'What is the main difference between TCP and UDP?', 'technology', '11_12', 'hard', true, '[{"label":"TCP is wireless; UDP uses cables","isCorrect":false},{"label":"TCP guarantees delivery and order; UDP is faster but does not guarantee delivery","isCorrect":true},{"label":"UDP is more secure than TCP","isCorrect":false},{"label":"TCP is for video; UDP is for text","isCorrect":false}]'::jsonb, NULL, NULL, 'TCP (Transmission Control Protocol) ensures data arrives correctly and in order — used for web browsing and email. UDP (User Datagram Protocol) is faster but less reliable — used for video streaming and gaming.'),
(NULL, 'mc', 'In cryptography, what is a "public key"?', 'technology', '11_12', 'hard', true, '[{"label":"The password you use to log in to a website","isCorrect":false},{"label":"A shareable key used to encrypt messages that only the private key can decrypt","isCorrect":true},{"label":"The encryption key stored inside a chip card","isCorrect":false},{"label":"A key that unlocks all encrypted files","isCorrect":false}]'::jsonb, NULL, NULL, 'In public-key cryptography, a public key can be shared with anyone. People use it to encrypt messages for you, but only your private key can decrypt them — keeping communications secure.'),
(NULL, 'mc', 'What does "recursion" mean in programming?', 'technology', '11_12', 'hard', true, '[{"label":"Running code in parallel on multiple processors","isCorrect":false},{"label":"A function that calls itself as part of its own definition","isCorrect":true},{"label":"Repeating code using a for loop","isCorrect":false},{"label":"Converting code from one language to another","isCorrect":false}]'::jsonb, NULL, NULL, 'Recursion is when a function calls itself to solve a smaller version of the same problem. Classic examples include calculating factorials and traversing tree data structures.'),
(NULL, 'mc', 'Which computer scientist is considered the founder of theoretical computer science and formulated the concept of the "universal computing machine"?', 'technology', '11_12', 'hard', true, '[{"label":"John von Neumann","isCorrect":false},{"label":"Claude Shannon","isCorrect":false},{"label":"Alan Turing","isCorrect":true},{"label":"Ada Lovelace","isCorrect":false}]'::jsonb, NULL, NULL, 'Alan Turing (1912–1954) described the theoretical "Turing machine," the foundation of modern computing. He also cracked the Enigma code during WWII and pioneered early AI concepts.'),

-- ============================================================
-- THEME: food_culture
-- ============================================================

-- age_band: 5_6 | difficulty: easy
(NULL, 'mc', 'Which of these is a fruit?', 'food_culture', '5_6', 'easy', true, '[{"label":"Carrot","isCorrect":false},{"label":"Apple","isCorrect":true},{"label":"Broccoli","isCorrect":false},{"label":"Potato","isCorrect":false}]'::jsonb, NULL, NULL, 'An apple is a fruit — it grows on a tree and contains seeds inside. Fruits are the sweet, seed-containing part of a plant.'),
(NULL, 'mc', 'What colour is a ripe banana?', 'food_culture', '5_6', 'easy', true, '[{"label":"Red","isCorrect":false},{"label":"Green","isCorrect":false},{"label":"Yellow","isCorrect":true},{"label":"Purple","isCorrect":false}]'::jsonb, NULL, NULL, 'Ripe bananas are yellow! They start out green and turn yellow as they ripen, becoming sweeter as they change colour.'),
(NULL, 'mc', 'Which food group gives us energy and includes bread, rice, and pasta?', 'food_culture', '5_6', 'easy', true, '[{"label":"Dairy","isCorrect":false},{"label":"Vegetables","isCorrect":false},{"label":"Carbohydrates","isCorrect":true},{"label":"Protein","isCorrect":false}]'::jsonb, NULL, NULL, 'Carbohydrates (also called carbs) are found in bread, rice, pasta, and cereals. They are the body''s main source of energy.'),
(NULL, 'mc', 'Where does milk come from?', 'food_culture', '5_6', 'easy', true, '[{"label":"Trees","isCorrect":false},{"label":"Cows","isCorrect":true},{"label":"Fish","isCorrect":false},{"label":"Underground","isCorrect":false}]'::jsonb, NULL, NULL, 'Milk that we drink usually comes from cows. It can also come from goats, sheep, and other animals. Milk is full of calcium which helps build strong bones.'),
(NULL, 'mc', 'Which vegetable is orange and grows underground?', 'food_culture', '5_6', 'easy', true, '[{"label":"Broccoli","isCorrect":false},{"label":"Carrot","isCorrect":true},{"label":"Pea","isCorrect":false},{"label":"Corn","isCorrect":false}]'::jsonb, NULL, NULL, 'Carrots are orange root vegetables that grow underground. They are sweet, crunchy, and packed with vitamin A, which is good for your eyes!'),

-- age_band: 5_6 | difficulty: medium
(NULL, 'mc', 'What do we call a meal eaten in the morning?', 'food_culture', '5_6', 'medium', true, '[{"label":"Lunch","isCorrect":false},{"label":"Dinner","isCorrect":false},{"label":"Breakfast","isCorrect":true},{"label":"Supper","isCorrect":false}]'::jsonb, NULL, NULL, 'Breakfast is the first meal of the day, eaten in the morning. The word comes from "breaking the fast" — you haven''t eaten while you slept!'),
(NULL, 'mc', 'Which food is made by bees?', 'food_culture', '5_6', 'medium', true, '[{"label":"Jam","isCorrect":false},{"label":"Honey","isCorrect":true},{"label":"Butter","isCorrect":false},{"label":"Maple syrup","isCorrect":false}]'::jsonb, NULL, NULL, 'Honey is made by bees from the nectar of flowers. Bees store it in honeycombs inside their hives. It has been used as a natural sweetener for thousands of years.'),
(NULL, 'mc', 'What shape is a typical pizza?', 'food_culture', '5_6', 'medium', true, '[{"label":"Square","isCorrect":false},{"label":"Triangle","isCorrect":false},{"label":"Round","isCorrect":true},{"label":"Rectangle","isCorrect":false}]'::jsonb, NULL, NULL, 'A traditional pizza is round — though the slices are triangular! Pizza originated in Italy and is now eaten all over the world with many different toppings.'),
(NULL, 'mc', 'Which of these foods contains the most protein to help muscles grow?', 'food_culture', '5_6', 'medium', true, '[{"label":"Lollies","isCorrect":false},{"label":"Chicken","isCorrect":true},{"label":"Chips","isCorrect":false},{"label":"Biscuits","isCorrect":false}]'::jsonb, NULL, NULL, 'Chicken is an excellent source of protein, which your body uses to build and repair muscles. Eggs, fish, meat, and beans are also high in protein.'),
(NULL, 'mc', 'What liquid is inside a coconut?', 'food_culture', '5_6', 'medium', true, '[{"label":"Orange juice","isCorrect":false},{"label":"Milk","isCorrect":false},{"label":"Coconut water","isCorrect":true},{"label":"Apple juice","isCorrect":false}]'::jsonb, NULL, NULL, 'Inside a fresh coconut is coconut water — a clear, refreshing liquid that is naturally sweet. It is different from coconut milk, which is made from the white coconut flesh.'),

-- age_band: 5_6 | difficulty: hard
(NULL, 'mc', 'From which country does spaghetti originally come?', 'food_culture', '5_6', 'hard', true, '[{"label":"France","isCorrect":false},{"label":"Spain","isCorrect":false},{"label":"Italy","isCorrect":true},{"label":"Greece","isCorrect":false}]'::jsonb, NULL, NULL, 'Spaghetti is a type of pasta that originates from Italy. Pasta has been part of Italian cuisine for hundreds of years and comes in many shapes and sizes.'),
(NULL, 'mc', 'What is the main ingredient in bread?', 'food_culture', '5_6', 'hard', true, '[{"label":"Sugar","isCorrect":false},{"label":"Flour","isCorrect":true},{"label":"Salt","isCorrect":false},{"label":"Butter","isCorrect":false}]'::jsonb, NULL, NULL, 'Flour is the main ingredient in bread. It is mixed with water, yeast, and salt. The yeast makes the dough rise, and baking in an oven turns it into bread.'),
(NULL, 'mc', 'Which of these fruits grows on a tall tropical tree and has a spiky brown shell?', 'food_culture', '5_6', 'hard', true, '[{"label":"Strawberry","isCorrect":false},{"label":"Coconut","isCorrect":true},{"label":"Grape","isCorrect":false},{"label":"Blueberry","isCorrect":false}]'::jsonb, NULL, NULL, 'Coconuts grow on tall palm trees in tropical places. They have a hard, hairy brown outer shell, white flesh inside, and delicious coconut water.'),
(NULL, 'mc', 'Chocolate is made from which plant?', 'food_culture', '5_6', 'hard', true, '[{"label":"Coffee plant","isCorrect":false},{"label":"Vanilla plant","isCorrect":false},{"label":"Cacao tree","isCorrect":true},{"label":"Sugar cane","isCorrect":false}]'::jsonb, NULL, NULL, 'Chocolate comes from the seeds (called cacao beans) of the cacao tree, which grows in tropical regions. The beans are fermented, dried, roasted, and processed to make chocolate.'),
(NULL, 'mc', 'What gives carrots their orange colour?', 'food_culture', '5_6', 'hard', true, '[{"label":"Iron","isCorrect":false},{"label":"Beta-carotene","isCorrect":true},{"label":"Vitamin C","isCorrect":false},{"label":"Calcium","isCorrect":false}]'::jsonb, NULL, NULL, 'Beta-carotene is the pigment that makes carrots orange. Your body converts it into vitamin A, which is important for healthy eyesight.'),

-- age_band: 7_8 | difficulty: easy
(NULL, 'mc', 'From which country does sushi originally come?', 'food_culture', '7_8', 'easy', true, '[{"label":"China","isCorrect":false},{"label":"South Korea","isCorrect":false},{"label":"Japan","isCorrect":true},{"label":"Thailand","isCorrect":false}]'::jsonb, NULL, NULL, 'Sushi originated in Japan. It typically consists of vinegared rice combined with ingredients like raw fish, seafood, and vegetables. It''s now enjoyed worldwide.'),
(NULL, 'mc', 'What is a taco?', 'food_culture', '7_8', 'easy', true, '[{"label":"A type of Italian pasta","isCorrect":false},{"label":"A Mexican dish with a folded tortilla and fillings","isCorrect":true},{"label":"A Japanese rice dish","isCorrect":false},{"label":"An Indian flatbread","isCorrect":false}]'::jsonb, NULL, NULL, 'A taco is a traditional Mexican dish made with a folded or rolled tortilla (corn or flour flatbread) filled with meat, cheese, salsa, and other toppings.'),
(NULL, 'mc', 'Which vitamin do we mostly get from sunshine?', 'food_culture', '7_8', 'easy', true, '[{"label":"Vitamin A","isCorrect":false},{"label":"Vitamin C","isCorrect":false},{"label":"Vitamin D","isCorrect":true},{"label":"Vitamin B12","isCorrect":false}]'::jsonb, NULL, NULL, 'Vitamin D is produced in your skin when it''s exposed to sunlight. It''s essential for strong bones and a healthy immune system. It''s sometimes called the "sunshine vitamin."'),
(NULL, 'mc', 'What kind of food is naan?', 'food_culture', '7_8', 'easy', true, '[{"label":"A type of Indian flatbread","isCorrect":true},{"label":"A Chinese dumpling","isCorrect":false},{"label":"A French pastry","isCorrect":false},{"label":"A Mexican soup","isCorrect":false}]'::jsonb, NULL, NULL, 'Naan is a soft, leavened flatbread from South Asia (India, Pakistan). It is traditionally baked in a tandoor (clay oven) and often served with curries and dips.'),
(NULL, 'mc', 'What are the three primary colours that mixing food dye uses to create other colours?', 'food_culture', '7_8', 'easy', true, '[{"label":"Orange, green, purple","isCorrect":false},{"label":"Red, yellow, blue","isCorrect":true},{"label":"Red, white, black","isCorrect":false},{"label":"Pink, teal, gold","isCorrect":false}]'::jsonb, NULL, NULL, 'Red, yellow, and blue are the primary colours. Mixing them creates secondary colours — red + yellow = orange, yellow + blue = green, red + blue = purple.'),

-- age_band: 7_8 | difficulty: medium
(NULL, 'mc', 'What is the main ingredient in guacamole?', 'food_culture', '7_8', 'medium', true, '[{"label":"Tomato","isCorrect":false},{"label":"Avocado","isCorrect":true},{"label":"Jalapeño","isCorrect":false},{"label":"Corn","isCorrect":false}]'::jsonb, NULL, NULL, 'Guacamole is a dip made mainly from mashed avocado, mixed with lime juice, salt, and often tomato, onion, and coriander. It originated in Mexico with the Aztecs.'),
(NULL, 'mc', 'Which country is famous for inventing pizza?', 'food_culture', '7_8', 'medium', true, '[{"label":"USA","isCorrect":false},{"label":"Greece","isCorrect":false},{"label":"Italy","isCorrect":true},{"label":"France","isCorrect":false}]'::jsonb, NULL, NULL, 'Pizza was invented in Naples, Italy. The classic Margherita pizza — with tomato, mozzarella, and basil — was reportedly created in 1889 and named after Queen Margherita of Italy.'),
(NULL, 'mc', 'What is the process called when yeast makes bread dough rise?', 'food_culture', '7_8', 'medium', true, '[{"label":"Evaporation","isCorrect":false},{"label":"Fermentation","isCorrect":true},{"label":"Oxidation","isCorrect":false},{"label":"Condensation","isCorrect":false}]'::jsonb, NULL, NULL, 'Fermentation is the process where yeast eats sugars in the dough and produces carbon dioxide gas, which forms bubbles that make the dough rise and become light and fluffy.'),
(NULL, 'mc', 'What food tradition involves eating mooncakes?', 'food_culture', '7_8', 'medium', true, '[{"label":"Diwali in India","isCorrect":false},{"label":"Chinese Mid-Autumn Festival","isCorrect":true},{"label":"Eid al-Fitr in the Middle East","isCorrect":false},{"label":"Christmas in Europe","isCorrect":false}]'::jsonb, NULL, NULL, 'Mooncakes are a traditional Chinese pastry eaten during the Mid-Autumn Festival (also called the Moon Festival), which celebrates the harvest and the full moon.'),
(NULL, 'mc', 'Which nutrient found in fish is important for brain health?', 'food_culture', '7_8', 'medium', true, '[{"label":"Calcium","isCorrect":false},{"label":"Iron","isCorrect":false},{"label":"Omega-3 fatty acids","isCorrect":true},{"label":"Vitamin C","isCorrect":false}]'::jsonb, NULL, NULL, 'Omega-3 fatty acids, found in oily fish like salmon and sardines, are essential for brain development and function, as well as heart health.'),

-- age_band: 7_8 | difficulty: hard
(NULL, 'mc', 'Which ancient civilisation invented chocolate by processing cacao beans?', 'food_culture', '7_8', 'hard', true, '[{"label":"Ancient Egyptians","isCorrect":false},{"label":"Ancient Romans","isCorrect":false},{"label":"The Mayans and Aztecs","isCorrect":true},{"label":"Ancient Chinese","isCorrect":false}]'::jsonb, NULL, NULL, 'The Mayans and Aztecs of Mesoamerica first cultivated cacao and made a bitter chocolate drink thousands of years ago. Europeans later sweetened it with sugar after encountering it in the 1500s.'),
(NULL, 'mc', 'What is "umami"?', 'food_culture', '7_8', 'hard', true, '[{"label":"A type of Japanese noodle","isCorrect":false},{"label":"The fifth basic taste, described as savoury and meaty","isCorrect":true},{"label":"A cooking technique using steam","isCorrect":false},{"label":"A type of Japanese tea ceremony","isCorrect":false}]'::jsonb, NULL, NULL, 'Umami is the fifth basic taste alongside sweet, sour, salty, and bitter. It is described as a deep, savoury, meaty flavour found in foods like mushrooms, soy sauce, and parmesan cheese.'),
(NULL, 'mc', 'What country produces about one-third of the world''s olive oil?', 'food_culture', '7_8', 'hard', true, '[{"label":"France","isCorrect":false},{"label":"Greece","isCorrect":false},{"label":"Spain","isCorrect":true},{"label":"Italy","isCorrect":false}]'::jsonb, NULL, NULL, 'Spain is the world''s largest producer of olive oil, accounting for about one-third of global production. Olive oil has been central to Mediterranean cooking for thousands of years.'),
(NULL, 'mc', 'What is the traditional Japanese cooking technique "tempura"?', 'food_culture', '7_8', 'hard', true, '[{"label":"Grilling food over charcoal","isCorrect":false},{"label":"Fermenting vegetables in salt","isCorrect":false},{"label":"Lightly battering and deep-frying seafood or vegetables","isCorrect":true},{"label":"Steaming food in bamboo baskets","isCorrect":false}]'::jsonb, NULL, NULL, 'Tempura is a Japanese cooking technique where seafood and vegetables are coated in a light batter and deep-fried until crispy. It was introduced to Japan by Portuguese missionaries in the 1500s.'),
(NULL, 'mc', 'Which spice, once worth more than gold, was at the centre of the "Spice Trade" between Europe and Asia?', 'food_culture', '7_8', 'hard', true, '[{"label":"Cinnamon","isCorrect":false},{"label":"Black pepper","isCorrect":true},{"label":"Paprika","isCorrect":false},{"label":"Turmeric","isCorrect":false}]'::jsonb, NULL, NULL, 'Black pepper was one of the most sought-after spices in medieval Europe and was so valuable it was used as currency. The desire for spices drove European exploration of sea routes to Asia.'),

-- age_band: 9_10 | difficulty: easy
(NULL, 'mc', 'What is the main ingredient in hummus?', 'food_culture', '9_10', 'easy', true, '[{"label":"Lentils","isCorrect":false},{"label":"Chickpeas","isCorrect":true},{"label":"Black beans","isCorrect":false},{"label":"Peas","isCorrect":false}]'::jsonb, NULL, NULL, 'Hummus is a dip originating in the Middle East made primarily from blended chickpeas, tahini (sesame paste), lemon juice, and garlic.'),
(NULL, 'mc', 'Which vitamin is abundant in citrus fruits like oranges and lemons?', 'food_culture', '9_10', 'easy', true, '[{"label":"Vitamin A","isCorrect":false},{"label":"Vitamin D","isCorrect":false},{"label":"Vitamin C","isCorrect":true},{"label":"Vitamin K","isCorrect":false}]'::jsonb, NULL, NULL, 'Citrus fruits are rich in Vitamin C (ascorbic acid), which supports the immune system, helps the body absorb iron, and aids in healing wounds.'),
(NULL, 'mc', 'What is fermentation in food production?', 'food_culture', '9_10', 'easy', true, '[{"label":"Cooking food at very high temperatures","isCorrect":false},{"label":"Using microorganisms to convert sugars into acids, alcohol, or gases","isCorrect":true},{"label":"Removing water from food to preserve it","isCorrect":false},{"label":"Adding preservatives to prevent spoiling","isCorrect":false}]'::jsonb, NULL, NULL, 'Fermentation uses bacteria, yeast, or other microorganisms to transform food. It''s how bread rises, yoghurt is made, cheese is aged, beer is brewed, and kimchi is prepared.'),
(NULL, 'mc', 'Which country is the world''s largest producer of rice?', 'food_culture', '9_10', 'easy', true, '[{"label":"Japan","isCorrect":false},{"label":"India","isCorrect":false},{"label":"China","isCorrect":true},{"label":"Thailand","isCorrect":false}]'::jsonb, NULL, NULL, 'China is the world''s largest producer of rice, accounting for about 30% of global production. Rice is the dietary staple for more than half the world''s population.'),
(NULL, 'mc', 'What is a "staple food"?', 'food_culture', '9_10', 'easy', true, '[{"label":"A food eaten only on special occasions","isCorrect":false},{"label":"A food that forms the basis of a diet and is eaten regularly","isCorrect":true},{"label":"A food that is imported from other countries","isCorrect":false},{"label":"A food that must be cooked before eating","isCorrect":false}]'::jsonb, NULL, NULL, 'A staple food is one that makes up the dominant part of a population''s diet. Common staples include rice, wheat, corn, potatoes, and cassava across different cultures.'),

-- age_band: 9_10 | difficulty: medium
(NULL, 'mc', 'What causes bread to go stale?', 'food_culture', '9_10', 'medium', true, '[{"label":"The bread dries out and loses all its water","isCorrect":false},{"label":"Starch molecules in bread recrystallise and become firm over time","isCorrect":true},{"label":"Bacteria grow and harden the bread","isCorrect":false},{"label":"Yeast continues working after baking","isCorrect":false}]'::jsonb, NULL, NULL, 'Staling is caused by retrogradation — starch molecules slowly reorganise into a more rigid crystal structure as the bread cools and ages, making it hard and crumbly even if it''s not dry.'),
(NULL, 'mc', 'What is the Maillard reaction in cooking?', 'food_culture', '9_10', 'medium', true, '[{"label":"The process of food absorbing oil when fried","isCorrect":false},{"label":"A chemical reaction between amino acids and sugars that causes browning and new flavours","isCorrect":true},{"label":"The way salt draws moisture out of food","isCorrect":false},{"label":"The reaction that makes egg whites foam","isCorrect":false}]'::jsonb, NULL, NULL, 'The Maillard reaction happens when amino acids and sugars react under heat, creating hundreds of new flavour compounds and the brown colour on grilled meat, toast, and baked goods.'),
(NULL, 'mc', 'Which country did the croissant actually originate in (despite being associated with France)?', 'food_culture', '9_10', 'medium', true, '[{"label":"Germany","isCorrect":false},{"label":"Switzerland","isCorrect":false},{"label":"Austria","isCorrect":true},{"label":"Belgium","isCorrect":false}]'::jsonb, NULL, NULL, 'The croissant evolved from the Austrian "kipferl," a crescent-shaped pastry. Austrian Marie Antoinette is said to have introduced it to France, where bakers added the flaky, buttery layers.'),
(NULL, 'mc', 'What is the "food pyramid" or "healthy plate" designed to show?', 'food_culture', '9_10', 'medium', true, '[{"label":"Which foods are most expensive","isCorrect":false},{"label":"The recommended proportions of different food groups in a healthy diet","isCorrect":true},{"label":"How many calories are in different foods","isCorrect":false},{"label":"Which foods come from plants versus animals","isCorrect":false}]'::jsonb, NULL, NULL, 'The food pyramid and healthy plate guides show the recommended proportions of food groups (grains, vegetables, fruits, proteins, dairy) to eat for a balanced, nutritious diet.'),
(NULL, 'mc', 'Where did the potato originally come from before spreading to the rest of the world?', 'food_culture', '9_10', 'medium', true, '[{"label":"Ireland","isCorrect":false},{"label":"Russia","isCorrect":false},{"label":"South America","isCorrect":true},{"label":"India","isCorrect":false}]'::jsonb, NULL, NULL, 'Potatoes were first cultivated in the Andes mountains of South America (present-day Peru and Bolivia) by Indigenous peoples thousands of years ago. Spanish explorers brought them to Europe in the 1500s.'),

-- age_band: 9_10 | difficulty: hard
(NULL, 'mc', 'What is "pasteurisation" in food production?', 'food_culture', '9_10', 'hard', true, '[{"label":"Adding vitamins and minerals to food","isCorrect":false},{"label":"Heating food to kill harmful microorganisms without fully cooking it","isCorrect":true},{"label":"Freezing food rapidly to lock in nutrients","isCorrect":false},{"label":"Removing fat from dairy products","isCorrect":false}]'::jsonb, NULL, NULL, 'Pasteurisation, developed by Louis Pasteur in the 1860s, heats liquids like milk and juice to a specific temperature to kill harmful bacteria, extending shelf life without changing taste much.'),
(NULL, 'mc', 'What is the difference between a fruit and a vegetable, scientifically speaking?', 'food_culture', '9_10', 'hard', true, '[{"label":"Fruits are sweet and vegetables are savoury","isCorrect":false},{"label":"A fruit develops from a flower''s ovary and contains seeds; vegetables are other plant parts","isCorrect":true},{"label":"Fruits grow above ground; vegetables grow below ground","isCorrect":false},{"label":"Fruits must be eaten raw; vegetables must be cooked","isCorrect":false}]'::jsonb, NULL, NULL, 'Botanically, a fruit is the seed-containing structure that develops from a plant''s flower (so tomatoes, cucumbers, and peppers are fruits). Vegetables are other edible plant parts like roots, leaves, and stems.'),
(NULL, 'mc', 'Which nutrient deficiency historically caused the disease scurvy among sailors?', 'food_culture', '9_10', 'hard', true, '[{"label":"Vitamin A","isCorrect":false},{"label":"Iron","isCorrect":false},{"label":"Vitamin C","isCorrect":true},{"label":"Calcium","isCorrect":false}]'::jsonb, NULL, NULL, 'Scurvy was caused by a lack of Vitamin C during long sea voyages when sailors ate no fresh fruits or vegetables. British ships began carrying limes to prevent it — hence the nickname "limeys."'),
(NULL, 'mc', 'What is "food miles"?', 'food_culture', '9_10', 'hard', true, '[{"label":"The distance a chef has walked in a kitchen","isCorrect":false},{"label":"The distance food travels from where it is produced to where it is eaten","isCorrect":true},{"label":"The number of calories burned cooking a meal","isCorrect":false},{"label":"The measurement of food portion sizes","isCorrect":false}]'::jsonb, NULL, NULL, 'Food miles refers to how far food has travelled from farm to consumer. High food miles mean more transport emissions and environmental impact, which is why local and seasonal food is often promoted.'),
(NULL, 'mc', 'What makes chilli peppers taste hot?', 'food_culture', '9_10', 'hard', true, '[{"label":"Citric acid","isCorrect":false},{"label":"Capsaicin","isCorrect":true},{"label":"Tannins","isCorrect":false},{"label":"Allicin","isCorrect":false}]'::jsonb, NULL, NULL, 'Capsaicin is the chemical compound in chilli peppers that triggers heat receptors in your mouth. The Scoville scale measures the capsaicin concentration — and therefore the "hotness" — of peppers.'),

-- age_band: 11_12 | difficulty: easy
(NULL, 'mc', 'What is the "Mediterranean diet" primarily based on?', 'food_culture', '11_12', 'easy', true, '[{"label":"Meat, dairy, and processed foods","isCorrect":false},{"label":"Plant foods, olive oil, fish, and moderate dairy and meat","isCorrect":true},{"label":"Raw foods only","isCorrect":false},{"label":"High protein, low carbohydrate foods","isCorrect":false}]'::jsonb, NULL, NULL, 'The Mediterranean diet emphasises vegetables, fruits, wholegrains, legumes, nuts, olive oil, and fish — with limited red meat and dairy. It is widely associated with longevity and heart health.'),
(NULL, 'mc', 'What is "food sovereignty"?', 'food_culture', '11_12', 'easy', true, '[{"label":"A country''s ability to export its food","isCorrect":false},{"label":"The right of peoples to define their own food systems and agricultural policies","isCorrect":true},{"label":"Laws governing food labelling","isCorrect":false},{"label":"A type of international food aid programme","isCorrect":false}]'::jsonb, NULL, NULL, 'Food sovereignty is the principle that people have the right to control their own food systems — including land, seeds, water, and agricultural methods — rather than having these dictated by global markets.'),
(NULL, 'mc', 'What does "GMO" stand for in food production?', 'food_culture', '11_12', 'easy', true, '[{"label":"Globally Managed Output","isCorrect":false},{"label":"Genetically Modified Organism","isCorrect":true},{"label":"Growth Maximised Organic","isCorrect":false},{"label":"Government Monitored Output","isCorrect":false}]'::jsonb, NULL, NULL, 'GMO stands for Genetically Modified Organism — a plant, animal, or microorganism whose genetic material has been altered using biotechnology to add desirable traits like pest resistance or higher yield.'),
(NULL, 'mc', 'In which country did the practice of tea drinking originate?', 'food_culture', '11_12', 'easy', true, '[{"label":"India","isCorrect":false},{"label":"Japan","isCorrect":false},{"label":"China","isCorrect":true},{"label":"England","isCorrect":false}]'::jsonb, NULL, NULL, 'Tea drinking originated in China thousands of years ago. Legend says Emperor Shen Nong discovered tea in 2737 BCE when leaves fell into his boiling water. China remains a top tea producer.'),
(NULL, 'mc', 'What is the "slow food" movement?', 'food_culture', '11_12', 'easy', true, '[{"label":"A diet that restricts how fast you eat","isCorrect":false},{"label":"A movement promoting local, traditional, and sustainable food culture over fast food","isCorrect":true},{"label":"A cooking method that uses low temperatures for a long time","isCorrect":false},{"label":"A charity that delivers food to remote communities","isCorrect":false}]'::jsonb, NULL, NULL, 'The Slow Food movement was founded in Italy in 1989 as a response to fast food culture. It promotes traditional recipes, local food producers, sustainable farming, and taking time to enjoy food.'),

-- age_band: 11_12 | difficulty: medium
(NULL, 'mc', 'What role do probiotics play in the human body?', 'food_culture', '11_12', 'medium', true, '[{"label":"They provide a quick source of energy","isCorrect":false},{"label":"They support healthy gut bacteria and digestion","isCorrect":true},{"label":"They speed up metabolism","isCorrect":false},{"label":"They help the body absorb fat-soluble vitamins","isCorrect":false}]'::jsonb, NULL, NULL, 'Probiotics are live beneficial bacteria found in fermented foods like yoghurt, kefir, and kimchi. They help maintain a healthy gut microbiome, which supports digestion and immune function.'),
(NULL, 'mc', 'What is the "Green Revolution" in the context of global food history?', 'food_culture', '11_12', 'medium', true, '[{"label":"The shift to organic farming in the 1990s","isCorrect":false},{"label":"A mid-20th-century period of agricultural innovation that dramatically increased crop yields","isCorrect":true},{"label":"An international agreement to reduce food waste","isCorrect":false},{"label":"A movement to plant more urban gardens","isCorrect":false}]'::jsonb, NULL, NULL, 'The Green Revolution (1940s–1970s) introduced high-yield crop varieties, irrigation, and synthetic fertilisers, massively boosting food production in developing countries — but also raising environmental concerns.'),
(NULL, 'mc', 'What is "food insecurity"?', 'food_culture', '11_12', 'medium', true, '[{"label":"When food is stored improperly and becomes unsafe to eat","isCorrect":false},{"label":"When people lack reliable access to sufficient, affordable, nutritious food","isCorrect":true},{"label":"When a country cannot export its food surpluses","isCorrect":false},{"label":"When food labels are unclear or misleading","isCorrect":false}]'::jsonb, NULL, NULL, 'Food insecurity exists when people do not have consistent access to enough food for an active, healthy life. It can result from poverty, conflict, climate change, or disrupted food supply chains.'),
(NULL, 'mc', 'What is the significance of the "Maillard reaction" to professional chefs?', 'food_culture', '11_12', 'medium', true, '[{"label":"It explains why food shrinks when cooked","isCorrect":false},{"label":"It creates the complex flavours and brown crust in grilled, roasted, and fried foods","isCorrect":true},{"label":"It determines how long food can be stored safely","isCorrect":false},{"label":"It describes how fats become liquid when heated","isCorrect":false}]'::jsonb, NULL, NULL, 'Chefs deliberately trigger the Maillard reaction by applying high heat to create the brown, flavourful crust on a seared steak, a toasted bun, or roasted coffee — it''s fundamental to flavour development.'),
(NULL, 'mc', 'What does "terroir" mean in the context of food and wine?', 'food_culture', '11_12', 'medium', true, '[{"label":"A French word for traditional recipes","isCorrect":false},{"label":"The environmental conditions (soil, climate, geography) that affect a food''s characteristics","isCorrect":true},{"label":"The technique of fermenting wine in oak barrels","isCorrect":false},{"label":"A classification system for French restaurants","isCorrect":false}]'::jsonb, NULL, NULL, 'Terroir (French for "land") describes how the geography, geology, and climate of a place affect the taste of agricultural products. It''s why wine from Bordeaux tastes different from wine from the same grape grown elsewhere.'),

-- age_band: 11_12 | difficulty: hard
(NULL, 'mc', 'What is the environmental concern with the global meat industry?', 'food_culture', '11_12', 'hard', true, '[{"label":"Meat production uses too much electricity","isCorrect":false},{"label":"Livestock farming contributes significantly to greenhouse gas emissions, deforestation, and water use","isCorrect":true},{"label":"Meat packaging creates most of the world''s plastic waste","isCorrect":false},{"label":"Overfishing is reducing global meat supplies","isCorrect":false}]'::jsonb, NULL, NULL, 'The global meat industry generates significant greenhouse gases (especially methane from cattle), requires vast land cleared from forests, and uses enormous amounts of water — making it a major contributor to climate change.'),
(NULL, 'mc', 'What economic concept describes the difference between the price farmers receive for food and the price consumers pay at a shop?', 'food_culture', '11_12', 'hard', true, '[{"label":"Food inflation","isCorrect":false},{"label":"The farm-to-retail price spread","isCorrect":true},{"label":"Agricultural subsidy gap","isCorrect":false},{"label":"Supply chain markup","isCorrect":false}]'::jsonb, NULL, NULL, 'The farm-to-retail price spread measures the difference between what producers earn and what consumers pay. It includes processing, packaging, transport, and retail costs — and often farmers receive only a small fraction of the final price.'),
(NULL, 'mc', 'What is "food anthropology"?', 'food_culture', '11_12', 'hard', true, '[{"label":"The science of measuring calorie content in food","isCorrect":false},{"label":"The study of how food shapes and reflects human culture, identity, and social relationships","isCorrect":true},{"label":"The analysis of ancient food remains from archaeological sites","isCorrect":false},{"label":"The study of how the human digestive system evolved","isCorrect":false}]'::jsonb, NULL, NULL, 'Food anthropology examines how food practices, rituals, and systems reflect cultural values, social hierarchies, and identity. What we eat, how we cook it, and who we eat with all carry deep cultural meaning.'),
(NULL, 'mc', 'What is "vertical farming" and why is it considered sustainable?', 'food_culture', '11_12', 'hard', true, '[{"label":"Growing crops on hillsides to reduce erosion","isCorrect":false},{"label":"Growing crops in stacked indoor layers using artificial light, using less water and no pesticides","isCorrect":true},{"label":"Farming by rotating crops each season in tall silos","isCorrect":false},{"label":"Using tall greenhouses to extend growing seasons","isCorrect":false}]'::jsonb, NULL, NULL, 'Vertical farming grows crops in stacked indoor layers under LED lighting. It uses up to 95% less water than traditional farming, needs no pesticides, and can operate year-round close to cities — reducing food miles.'),
(NULL, 'mc', 'Which major historical event was significantly worsened by relying on a single crop variety, demonstrating the danger of low agricultural biodiversity?', 'food_culture', '11_12', 'hard', true, '[{"label":"The Dust Bowl in the United States","isCorrect":false},{"label":"The Irish Potato Famine","isCorrect":true},{"label":"The Great Leap Forward in China","isCorrect":false},{"label":"The Bengal Famine","isCorrect":false}]'::jsonb, NULL, NULL, 'The Irish Potato Famine (1845–1852) devastated Ireland because nearly all potatoes grown were of a single variety (the Lumper), which was wiped out by the blight Phytophthora infestans. Over one million people died and another million emigrated.');
